### ISSUE TITLE
opencv completions fail

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#10]
@simonhaenisch reported this:
>This is what I get now when trying to trigger a completion for a Mat variable or doing cv:: (I shortened the full paths for the -I arguments). Somehow it can't get any completions for OpenCV (maybe I use the wrong include dir?)... I use another framework and for that most completions work.

Tracking this issue here.

**Comment by niosus** [comment]
@simonhaenisch can you tell me which framework are you using? Can you also post full line with all -I includes? It seems to be just that. I will eventually add error output too.

**Comment by simonhaenisch** [comment]
```
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 15
DEBUG:EasyClangComplete.EasyClangComplete:init completer for view id: 15
DEBUG:EasyClangComplete.plugin.plugin_settings: populating include dirs with current variables:
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_name = 
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_folder = C:\MinGW\msys\1.0\home\shaenisc\ocv-test
DEBUG:EasyClangComplete.plugin.plugin_settings: file_parent_folder = C:\MinGW\msys\1.0\home\shaenisc
DEBUG:EasyClangComplete.plugin.plugin_settings: include_dirs = ['C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include', 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.1A\\Include', 'C:\\Program Files\\LLVM\\lib\\clang\\3.8.0\\include', 'C:\\OpenCV\\opencv_3_1_0\\build\\include\\opencv2', 'C:\\MinGW\\msys\\1.0\\home\\shaenisc\\ocv-test']
DEBUG:EasyClangComplete.plugin.clang_bin_complete: searching for .clang_complete in C:\MinGW\msys\1.0\home\shaenisc\ocv-test up to C:\MinGW\msys\1.0\home\shaenisc\ocv-test
DEBUG:EasyClangComplete.plugin.clang_bin_complete: clang flags are: ['-IC:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include', '-IC:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.1A\\Include', '-IC:\\Program Files\\LLVM\\lib\\clang\\3.8.0\\include', '-IC:\\OpenCV\\opencv_3_1_0\\build\\include\\opencv2', '-IC:\\MinGW\\msys\\1.0\\home\\shaenisc\\ocv-test']
```

when triggering a completion:
```
DEBUG:EasyClangComplete.plugin.clang_bin_complete: clang command: 
clang++ -cc1 -fsyntax-only -x c++ -std=c++11 -code-completion-at c:\users\shaenisc\appdata\local\temp\test.cpp:7:9 c:\users\shaenisc\appdata\local\temp\test.cpp -IC:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include -IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include -IC:\Program Files\LLVM\lib\clang\3.8.0\include -IC:\OpenCV\opencv_3_1_0\build\include\opencv2 -IC:\MinGW\msys\1.0\home\shaenisc\ocv-test
DEBUG:EasyClangComplete.plugin.clang_bin_complete: started code complete for view 15
CRITICAL:EasyClangComplete.plugin.clang_bin_complete: 
DEBUG:EasyClangComplete.plugin.clang_bin_complete: code complete done in 0.1380140781402588 seconds
DEBUG:EasyClangComplete.plugin.clang_bin_complete: completions: []
DEBUG:EasyClangComplete.plugin.clang_bin_complete: reload completion tooltip
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 15
```

**Comment by niosus** [comment]
@simonhaenisch you can also try to run the command from command line. Just copy the line after `clang command:` to your command line and run right after trying to complete from sublime. It will probably show you some errors.

**Comment by niosus** [comment]
Also, can you please tell me which other framework are you using that you said works? I will look what can be adopted from them to make setup as simple as possible. And thanks for your help! :+1:

**Comment by simonhaenisch** [comment]
the framework is commercial, so I don't think it will help you... its called ADTF.

**Comment by simonhaenisch** [comment]
Ok I figured it out when trying the command in the cmd: I had \include\opencv2 as include dir instead of \include, so it couldn't find the `opencv2/opencv.hpp` header... my mistake. Works now.

**Comment by niosus** [comment]
Great. Then I am closing this issue. 

One more question to you just to be sure. You did see the output of an error in cmd (not in sublime) when running the clang command? I just want to be sure it is the same on Windows as I see in on my machine. :)

**Comment by simonhaenisch** [comment]
yes I saw the error output in cmd (`fatal error: 'opencv2/opencv.hpp' file not found`)

**Comment by niosus** [comment]
Awesome! then I will implement issue #11 to help reducing confusion.
