### ISSUE TITLE
Set cmake options

### ISSUE THREAD

**Issue by Zouch** [niosus/EasyClangComplete#100]
Hi,

In my CMakeLists.txt I use `find_package(Qt5 SomeQtPackages)`. On Windows I have to tell CMake where to look for it by setting `CMAKE_PREFIX_PATH`. This leads to errors when using `EasyClangComplete` because it cannot find Qt. 

My question is how can I tell `EasyClangComplete` that it should add a `-DCMAKE_PREFIX_PATH=Path/To/Qt` to be able to create the database files by itself ?

Thanks

**Comment by niosus** [comment]
There is a setting in the plugin preferences where you can set any `CMAKE_PREFIX_PATH`. See [here](https://github.com/niosus/EasyClangComplete/blob/master/EasyClangComplete.sublime-settings#L34)

**Comment by Zouch** [comment]
Oh missed it ! Thanks :)

**Comment by niosus** [comment]
No problem! Happy to help :)
