### ISSUE TITLE
Wildcards in include_dirs?

### ISSUE THREAD

**Issue by tastytea** [niosus/EasyClangComplete#101]
If I set `use_libclang` to `true`, I get errors, like _»field has incomplete type 'const std::string'«_. After I add `/usr/lib/clang/3.8.1/include` to `include_dirs`, these errors disappear.
However, if I set  `use_libclang` to `false`, adding the clang include path is not necessary.
Could it be changed so that adding the path is not necessary with libclang? Or could you add wildcard (like `/usr/lib/clang/*/include`) support?
That way, we would not have to change the path on every clang update.

**Comment by niosus** [comment]
That is a good idea. It will take some time as there is a number of bugs I need to fix first and the time is really a big issue now. I will gladly accept a pull request on this if you would be willing to contribute.

**Comment by tastytea** [comment]
Okay, I'm working on it.

**Comment by niosus** [comment]
Thanks for a pull request! I have some ideas and suggestions about it. Let's discuss it there!
