### ISSUE TITLE
Improving CMake support

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#104]
This is a discussion for improving CMake support with EasyClangComplete, and in particular the possibility to load a `compile_commands.json` database directly. A first discussion is already provided in #19, but I think now this can be taken a bit further.

Currently, when a `compile_commands.json` is generated with CMake, flags are merged into a single `.clang_complete` file in the project directory. This is not ideal because we lose the possibility to have different flags for different files, and for large projects this is important. However, if the `compile_commands.json` file can be loaded directly, then there is no need to load flags from the `.clang_complete` file anymore.

The way I see it, the idea is to have different "backends" that can generate flags for a given file. Backends  can be queried following a preference list in the plugin settings:

```
"backend_order": ["cmake", "simple"],
```

That way, you leave open the possibility to add other backends later on (a custom script, other build systems such as `qmake`, `scons`, etc.). The `cmake` backends corresponds to a `CMakeLists.txt` that has successfully generated a `compile_commands.json` file, and the `simple` backend corresponds to the `.clang_complete` currently used. Using the priority list above, if the flags for a file can be generated using the `cmake` backend, then there is nothing more to do. If not, then try to generate default flags via the `simple` backend. Of course, you would need to regenerate the the `compile_commands.json` as necessacy when the `CMakeLists.txt` has changed.

My second suggestion would be to allow for a custom build path for cmake. I am not sure exactly what would be the best practice here, but you could have a setting with something like:

```
"cmake_build_dir": "<<temp>>",
```

And then the user can customize it. `<<temp>>` would be the unique id in `/tmp` currently generated. You can have other special variables, such as `<<home>>`, `<<project>>` or `<<cmakelist>>`, corresponding respectively to the home folder, the project root folder (well, there can be several roots in a project so I don't know), and the path to the `CMakeLists.txt` used to generate the build (so if you specify `<<cmakelist>>/build/` you can imagine where this will be built).

The problem when you do that is that the build directory can already exist. So if the build has not been generated by the plugin (which you can mark by placing a `.easy_clang_complete` in the build directory for example), then you should ask the user what to do (clean dir / use as is). You can set the default behavior in a plugin setting, but I would be careful to always ask the use before deleting a directory =)

The advantage of having a build dir in the currenty project tree, is that you can search any generated file via the standard sublime commands. This is not super indispensable though, so I don't think it should be high-priority. Also, it allows you to use the generated build dir as your normal build directory for your project.

Last point, more minor, is that right no you don't seem to be passing the flags `-DCMAKE_C_COMPILER=`which clang` -DCMAKE_CXX_COMPILER=`which clang++`` to the cmake build command. Correct me if a wrong though, I may have missed something in your code. Since some flags are specific to clang and not gcc, this can have some importance.

Let me know if any of these ideas make sense.

**Comment by niosus** [comment]
Ok, let's discuss a bit more.

Let's start with the start :)
> load a compile_commands.json database directly

What exactly do you mean by this?

As for another thing you mentioned such as running cmake not in temp folder - this comes hand in hand with using exactly correct parameters as used by user. We could add those settings and use them, but I would love to postpone this until there is actual need for that by somebody. Do you lack this functionality? Can you describe a real use case? 

>Last point, more minor, is that right no you don't seem to be passing the flags -DCMAKE_C_COMPILER=`which clang` -DCMAKE_CXX_COMPILER=`which clang++`

Indeed, I don't and probably should. But my projects were for now always properly built. I will probably add these flags soon.

**Comment by jdumas** [comment]
> What exactly do you mean by this?

Right now, the way flags are loaded is via the `.clang_complete` file if it exists. If it doesn't, or if the project has a `CMakeLists.txt`, then a `.clang_complete` file is generated and/or merged/overwritten. To me it seems the biggest drawback of doing this is that you cannot have different `.c`/`.cpp` with different flags passed. Imagine a simple project with two subfolders `a/` and `b/`, and all the `.cpp` files in `a/` are compiled with a `-DFOO=1`, but the files in `b/` should be compiled with `-DFOO=0`. Another typical use case is when you build a project with some libraries bundled in them. Each library is in its own subfolder of a certain `third_party/` folder, and should be compiled with their own flags. This is easily done in CMake by creating different target for each library with their respective compilation flags.

>  running cmake not in temp folder

On large projects running even the cmake command can take forever. Try to generate the `compile_commands.json` for [libarchive](https://github.com/libarchive/libarchive) for example. Even on small projects, it can make the plugin more responsive after a reboot I think, to save running the cmake command from scratch. I wouldn't put it high on the priority list, but I wouldn't rule it out either.
The other use case I had in mind is when there are header files generated by a script run by cmake (to preprocess certain files, e.g. gathering glsl shader files into a .cpp file with proper strings). I think if the flags passed to clang point to files that are not in the temp folder anymore (because the system has rebooted), then it might be a problem. However, since you are using a unique temp folder id base on the absolute path of the `CMakeLists.txt` file, this second scenario is probably a non-issue.

> Indeed, I don't and probably should. But my projects were for now always properly built. I will probably add these flags soon.

For most projects the resulting flags should be pretty similar anyway, given that clang and gcc are designed to be mostly compatible. However there are a few warning flags e.g. that are present in one compiler and not the other, and vice-versa. Not critical but it doesn't hurt to pass the option properly.

**Comment by niosus** [comment]
So I've been trying to think about the changes I could make. More or less, the idea is the following. I would introduce another level of abstraction over `FlagsManager` that will handle flags from different build systems. See it in green here: https://sketchboard.me/rAbnwhdbIjGX#/

One of these abstractions will be a wrapper around `CMake` build system. The general idea would be the following:
- store a list of flags generated from `compile_commands.json` with `shlex` for each view file name.
- get these flags for a given view with function `flags_for_view(view)` or alike.
- if `compile_commands.json` has been updated we generate new flags from it when calling the above defined function.
- additionally if we are allowed to run cmake by ourselves, we also regenerate compilation database if needed

This way we avoid generating an unnecessary `.clang_complete`, which can be handled in another instantiation of `BuildSystemWrapper`.

The main problem I don't have a good solution to is the fact, that we can only have compilation flags for `*.cpp` files that represent some target for cmake. While it is possible to get flags for accompanying `*.h` files, it is hard to get those for standalone headers. A fallback solution would be to just use all flags merged together in this case, but it is not ideal. Anyway, I see no better way here.

The other slight problem is the amount of settings we need to add. We need to specify the preferred order of build systems + some arguments for each supported build system, which can be really a lot. this will clutter the settings.

**Comment by jdumas** [comment]
Hmm good point for the standalone header files. There can also be a problem if the same `.cpp` gets compiled twice with different options as part of different libraries in the same project. But then, if you have a project like that you're just asking for troubles.

No, instead of merging all possible compilation flags passed for all files, I would just pick up the first line I find and use it. The flags are likely to be correct anyway. There could be a fancy way of detecting which `.cpp` file include which header, and pick the flags accordingly. Or having a setting to specify which `.cpp` is your "main" one and use its flags to compile headers. But that's just heuristics and workaround, I don't know if there's a universal solution here.

Concerning the explosions of settings, well they can always be nested to keep them organized ... but at some point I don't think you can avoid adding them.

**Comment by niosus** [comment]
> instead of merging all possible compilation flags passed for all files, I would just pick up the first line I find and use it.

I think I don't quite understand you here. We are also talking about the include files, and they are likely to be wrong if I pick some target at random. While it will probably work if I use all unique flags together. I could also exclude any non-include flags when compiling headers.

**Comment by jdumas** [comment]
I don't know, it's just that I don't like the idea of mixing flags together in a heuristic manner. [CLion](https://blog.jetbrains.com/clion/2014/09/clion-answers-frequently-asked-questions/), which is a CMake-based IDE, seems to have some [discussions](https://youtrack.jetbrains.com/issue/CPP-270) on the matter. The approach that they seem to be using so far is that if you have a header file which does not corresponds to any `.cpp`, you need to include it explicitly in your CMake's source list. That way CMake will still generate compilation flags for this file (need to double-check it though).
