### ISSUE TITLE
Why does pselect can't autocomplete

### ISSUE THREAD

**Issue by voidprotossarthas** [niosus/EasyClangComplete#107]
```
#include <sys/select.h>

int main ( int argc, char const *argv[] )
{
        //"select" can autocomplete, "pselect" can't
    return 0;
}
```

ST3 3126
linuxmint 17.3

**Comment by voidprotossarthas** [comment]
the first line is "#include <sys/select.h>"

**Comment by niosus** [comment]
Edited for clarity. Please specify more details. What are you trying to do and what are you getting?

**Comment by voidprotossarthas** [comment]
I had solved this problem with adding "-std=gnu99" in config

**Comment by niosus** [comment]
Great, happy you have solved it.
