### ISSUE TITLE
"clang_flags" setting removed

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#113]
Seems like with rewrite of settings handling, you've removed `clang_flags` setting.

You can prove me wrong, but I believe it was the only way of specifying custom compiler flags. For my project I need to add a lot of defines and various other compiler arguments to make most of the code compile. Is there no way to do it now?

BTW. Removing support for "clang_flags" setting is backwards incompatible change. I think it's good that "clang_flags" was removed as it had too generic name to be in shared settings, but "easy_clang_complete_clang_flags" should still be supported IMO (without "use_project_settings" of course).
And it would probably be best to mention this change in release notes in BIG letters.

But then maybe more thought has to be given to this because now there are separate settings for various compiler arguments (std_flag_cpp, std_flag_c, include_dirs) and maybe that all should be consolidated in some smart way.

**Comment by rchl** [comment]
Of course I know about clang_complete_file but I don't want to use as then I would need to ignore that file in git and I don't want to do that in shared repo.

**Comment by rchl** [comment]
Also Readme.md should be updated as it still mentions setting project specific clang_flags.

**Comment by niosus** [comment]
Yes, this is exactly the reason why there is no release yet :)

You are right about `clang_flags`. I was not aware of this as I don't use it personally, but I understand the importance, so sorry for this. 

I think it would be better, to just have `flags` setting. There seems to be no need whatsoever to have it separated. The only thing that I need to take care of are local paths in includes, should the user define any.

Although, I see the problem using plugin for different languages. There have to be separate flags for separate languages and here it becomes slightly painful. Do I then have some generic flags, e.g. `common_flags` and add to them `c_flags` or `cpp_flags` depending on the context? I am still thinking about it. What would your opinion be?

I don't think this plugin is heavily used yet, so I am not too afraid to do breaking changes. But yes, all the breaking changes will be written out upfront in update notes.
