### ISSUE TITLE
Project specific overrides are initialized from first opened project

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#119]
The Settings object is initialized once which means that project overrides will be read only once and from the first project that is opened. If having a couple of projects open at the same time, or switching between them, all will share settings of that first project.

**Comment by niosus** [comment]
I think we can update these in `on_activated_async` right before initializing a completer. We just need to call one function, like `settings.update_settings_from_project_if_needed`. The only thing missing here is that we also need to reinitialize settings from the settings file to avoid old settings propagating to new project

**Comment by rchl** [comment]
So update global settings on each view activation? That sounds quite hacky. And it could lead to problems fairly easily. Imagine some script changing a tab that is not active and triggering some ECC action in it. It would use settings of active view instead.
Maybe it wouldn't be a major problem in practice but you never know with those hacks. I think the proper solution would be to store project specific settings per view. Or even all settings.

**Comment by niosus** [comment]
While merging #140 I have bumped into an issue that we cannot have fully independent settings until we allow multiple completers. So this issue is blocked by #141.
