### ISSUE TITLE
FlagsManager created once per view, overwriting previously created one

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#120]
Creation of FlagsManager overwrites previously created FlagsManager in base_complete.py `init()`.
It needs to make up its mind if it's a singleton or created per-view. :)

This can lead to problem with wrong flags being used for views, I think. And even if not, it's conceptually a bug.

With #117 integrated, FlagsManager will have even bigger ties to view instance, so could potentially cause more issues.

**Comment by rchl** [comment]
Actually self.flags_manager seems to be only used during `init()` (`init_for_view()` in #117) so this shouldn't cause any problems.
But it's still weird and error prone to store it as a member of Completer if it only can be used safely from `init()`.

**Comment by niosus** [comment]
I do not see the problem, but I have to leave it for another day, as today I can only do this much. I will come back to this issue in a couple of days.

**Comment by rchl** [comment]
One concrete example where it actually can return wrong results:

`BaseCompleter.needs_init()` checks if view needs to be re-initialized by calling `self.flags_manager.any_file_modified()`. When coming back to previously initialized view, this will return state for a different view (the one that was initialized later) because self.flags_manager is overwritten for each newly activated view. This can potentially cause erratic behavior if those two files use different cmake projects.
