### ISSUE TITLE
User specified compilation flags order gets shuffled

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#122]
The order of flags specified in "common_flags" is randomly changed. I suppose due to using sets and not lists. That can break compilation as some arguments need to be in specific order, for example:

```
'-Xclang', '-add-plugin', '-Xclang', 'find-bad-constructs',
```

**Comment by niosus** [comment]
I don't know if we need to fix this actually. Why can't we specify flags together? like in one line (hope I write the command correct):
```json
"common_flags": [
    "-Xclang -add-plugin -Xclang find-bad-constructs"
]
```

**Comment by rchl** [comment]
Because if you pass such list item to subprocess, it will treat that as one argument and that is not how clang expects it and will fail.

**Comment by niosus** [comment]
Ah, you're right. Ok. Then we do need to fix this :)
