### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#124]
It would be great to be able to jump to object's definition or declaration using a shortcut. It's possible to do as SublimeClang plugin is/was supporting that and that is pretty much the only thing from that plugin that I'm missing in EasyClangComplete currently.

That also could be made to work with #include directives to quickly jump to a header file (as proved to be possible by that other plugin).

(Often sublime's ctrl+shift+r does a good job of finding declarations/definitions but it's not ideal)

**Comment by niosus** [comment]
Yes, I have been thinking about it.

The problem for me here is that this requires fixing all the design issues and I would need at least a week of full time work on this plugin for this. Unfortunately, I do not have the time. Maybe when we fix all the other issues, we could really work on this.

Also, I am quite happy with how ctrl+shift+r and F12 work, so this is for now quite low priority for me. But i am open to pull requests on this.

**Comment by cidadao** [comment]
+1 for this! I understand the priorities though. In any case, any pointers on how to get started implementing this feature for anyone willing to try? (maybe me if I'm up for the task)

**Comment by niosus** [comment]
I really didn't look into this, but it seems that one could start along the lines of this blog post: http://eli.thegreenplace.net/2011/07/03/parsing-c-in-python-with-clang/

I will be willing to accept a pull request on this if someone implements this :)

**Comment by simia** [comment]
This seems to be quite easy to implement. I'll have a try with this one.
Btw. what's your opinion on implementing functionality like "Implement function" where plugin inserts definition into source file based on header contents?

**Comment by niosus** [comment]
@simia great to hear that :+1: 

As for the functionality - it is a complicated question. I think I like the idea, but it has to be working properly most of the times so that it does not annoy users. So, bottom line, if it is well implemented, why not? :)

But please, separate these things in multiple PRs should you consider to actually implement this.

**Comment by simia** [comment]
Ok. After a brief reading I have some initial thoughts. 
Implementing goto definition/declaration requires knowledge from multiple translation units.
To achieve this we would need to preparse whole project and gather all TUs. This would be quite a huge change in terms of how plugin works and I don't if @niosus want's to go that way.
On the upside:
- This would enable implementation of fairly large amount of features - goto definition/declaration, show usages, peek definition, implement methods/virtual methods, fix includes(?). Those are just few that come to my head right away.
- This could be separated from current functionality and be by default disabled.

There are lots of possible obstacles on the way but I think this would be cool to have such a rich functionality within one plugin. 
What are your thoughts @niosus ?

**Comment by niosus** [comment]
Keeping all things compiled is a no go. It will grow out of hands really quickly. I think we should separate the functionality even more and address this really granularly. So I would not implement it project wide, but rather view dependent. 
- goto definition/declaration - we actually don't need more information than we already have. The declaration is going to be in the ast tree of the translation unit already if I understand it correctly. Definition is a bit trickier, but we can guess it is in a corresponding source file.
- implement methods - again, we don't need more information then we have. Having a header opened we have all the information we need. The user then can specify which file to add the definitions to. What seems to be difficult to me is to keep track of which ones have already been defined, etc.


And yes, it should be separated from current functionality. I also see a lot of obstacles on the way to actually have this working reliably. If there is something that is working we could roll it out as a beta experience if it does not interfere with the completion functionalities of the plugin.

**Comment by maddanio** [comment]
Yes, going to declaration would be a huge win! especially when jumping to headers of depended upon libraries. Often there is documentation in those headers, or related functions (like the constructor set of a class), and this would make my workflow so much quicker. I tried looking at the ecc source, but got lost :). If I ever grok it properly I am open to helping :).

**Comment by simia** [comment]
There is 'go to declaration' functionality on the popup that is displayed when hovering over function/variable etc.

**Comment by maddanio** [comment]
but is that ecc powered? because
a) it is unprecise (it seems to look just for the method name anywhere, instead of knowing the right class)
b) it does not jump outside of the project, i.e. to system headers

**Comment by simia** [comment]
There is one provided by Sublime but it gets suppressed when you enable:
"show_type_info": true, in your ECC settings.
It should always point you to the correct class and it supports system headers without problems (if ECC is correctly configured).

**Comment by maddanio** [comment]
hmm, I use cmake, so I assumed it configures itself correctly. show_type_info is on. yet nothing on system headers (actually it seems to think a lot of those things, like std::cerr, are of type int...) and the mentioned many imprecise options on methods...

**Comment by simia** [comment]
Simple example:
![image](https://user-images.githubusercontent.com/7147203/28163839-a604f93c-67c4-11e7-8dfd-626a364592e1.png)

And cliclikng blue links leads to "thread" and "iosfwd" files located in /usr/include/c++/... as expected

**Comment by maddanio** [comment]
hmm, then it seems to be wrongly configured...is there a way to debug that?

**Comment by simia** [comment]
Well, let's start from the beginning :)
What os are you using? Which version of libclang etc.
Does auto completion work for you?
Are there any ECC related logs in Sublime console?

**Comment by niosus** [comment]
@maddanio this is definitely an issue with your configs. Please a new issue with your question. The issue template will guide you about the information we might need to help you.

**Comment by niosus** [comment]
Ok, so one of the sleepless nights I've been thinking about it. @simia is totally right that we need the knowledge from multiple translation units to navigate to definition. Even more importantly, we need the knowledge of *from which files* these translation units need to be generated.

IDEs indeed index the whole project and as a result of this, rely heavily on their own project definition. I would really like to keep the way this plugin allows any build system and is not too heavy on plugin-specific configuration files. But even if the knew which files to parse, we would still need a way to reuse parts of this huge translation unit (or keep multiple of those).

I do not really see any way to provide this functionality in any meaningful way. I encourage somebody else to write a plugin that would mimic an IDE within sublime text. I believe it is realistic to do if some constraints on the build system or on the project structure are enforced. I see no way of implementing this within the framework of this plugin for now. All the implementations that I can think of have one or another flaw that I see no way of overcoming. 

As a result, I guess I will keep this issue open here for other people to find, but I do not intend to work on it mainly because I do not see how. I will be happy if anybody actually proves me wrong.

**Comment by niosus** [comment]
@maddanio I am removing your comments which are off topic to streamline this whole conversation to ease things up for future readers. Sorry for that.

**Comment by maddanio** [comment]
as a small note: I would like "whole project indexing" at least to be switchable. this kind of indexing tends to lead to massive cpu hunger of modern IDEs, and more often than not massive lags and other problems when trying to use it while changing lots of files.

**Comment by maddanio** [comment]
This problem is one of the reasons I like to use sublime instead, so I would not like it to resurface in my new home :).

**Comment by niosus** [comment]
Probably I have written too much text above :laughing: 

To have a shorter statement and to avoid confusion: **there is no plan to implement `go_to_definition`** as it would require full project indexing which does not fit with the core idea and architecture of the plugin and is overall just infeasible at this point.

**Comment by dibalavs** [comment]
It is possible to use some "tricks" to get symbol definition. 
we already know header file, where function is declared, So we can switch to source file (like Alt+O hotkey) and index only this source, where function is defined.
It will not work in all cases, but it is better than nothing.

**Comment by niosus** [comment]
Yeah, the issue with "tricks" is that everybody will want their own. Arguably, <kbd>F12</kbd> works decently well in simple cases and we will not be able to cover complicated ones with this solution.

**Comment by maddanio** [comment]
Well, then "opt-in" to this feature would be an option? :)
Is there a kind of index cache right now? Or are they recomputed all the time?

**Comment by niosus** [comment]
@maddanio there is no index right now as I explicitly wanted to avoid that. Every translation unit is completely independent from another. Whenever you open a file a new translation unit is generated. The existing ones for open files are stored in cache for some time and then discarded. They are also removed if the view is closed.

**Comment by niosus** [comment]
I will close this issue as I see no way of fixing it. Therefore the `wontfix` label.
