### ISSUE TITLE
How to add some EasyClangComplete settings to project settings?

### ISSUE THREAD

**Issue by r44083** [niosus/EasyClangComplete#13]
Hi, 
I am very grateful to you for this plugin. I have the next question: how to add some include_dirs into *.sublime-project file? It is important because the folder structures with .h files are different from project to project.

For example, I recently create plugin which uses Cling binary for linting C, C++. So, in my *.sublime-project file the settings for plugin looks like this:
```
{
	"folders":
	[
		{
			"follow_symlinks": true,
			"path": ".",
			"file_exclude_patterns": [".tags", ".tags_sorted_by_file", ".gemtags"],
		}
	],
	"settings":
	{
		"clanglinter_cmd_options":
		[
			"-I${project_path}/source",
			"-I${project_path}/source/Common",
			"-I${project_path}/source/DL",
			"-I${project_path}/source/BL",
			"-I${project_path}/source/HAL",
			"-I${project_path}/source/HAL/src-STM32F3xx",
			"-I${project_path}/source/HAL/src-STM32F3xx/PLib/CMSIS/CoreSupport",
			"-I${project_path}/source/ThirdParty",
			"-I${project_path}/source/UL",
			"-DSTM32F334x8",
			"-DUSE_STDPERIPH_DRIVER",
			"-DARM_MATH_CM4",
			"-DHSE_VALUE=8000000",
			"-std=c99",
			"-Wall",
			"-IE:/soft/1-ready/sublimetext/GNU Tools ARM Embedded/arm-none-eabi/include",
		]
	}
}
```

**Comment by niosus** [comment]
Hey @r44083 thanks for your interest!

For now the plugin will not search for settings key in the `.sublime-project` file. Current available way is to have a `.clang_complete` file in the root of your project and to put all relative -I paths and -D macroses there. For example, this is the content of such a file for one of my projects:
```
-Isrc/
-I/opt/ros/jade/include/
-I/opt/ros/indigo/include
-I/usr/include/eigen3
-I/usr/include/pcl-1.7
```

There is currently no way of adding specific flags like `-Wall` or `-std=c99` there. But I guess it would be cool to add it, so I will work on it as soon as I have time. 

My current idea would be to check if there is "settings" key in `.sublime-project` file and if yes, ignore all the general settings in favor of the ones in the settings. Tell me if you think about it. Would that work for you?

**Comment by r44083** [comment]
I did it using this way:

```
	def __get_project_settings(self):
		# try if any project is open, except - no project is open
		try:
			project_data = sublime.active_window().project_data()
			project_file_name = sublime.active_window().project_file_name()
			
			project_settings = (
					project_data['settings']['clanglinter_cmd_options'])
			
			project_path = os.path.dirname(project_file_name)
			
			for i in range(len(project_settings)):
				project_settings[i] = project_settings[i].replace(
					'${project_path}', project_path)
				# project_settings[i] = project_settings[i].replace("\\", "/")
		except:
			project_settings = []
		
		return project_settings
```

This works for the example which I write in the first message.

**Comment by niosus** [comment]
Thanks for the snippet. I am now at the conference for work and will be home only in the middle of this week. So I will not be able to do this until the next weekend or so. If you want, you can try to open a pull request and this will speed up the process :)

**Comment by niosus** [comment]
It is now possible to set flags for clang. Example project file:
```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"clang_flags": ["-std=c++11", "-I/usr/include"]
	}
}
```

These settings will override all other settings.
Please reopen the issue if anything is still wrong.

**Comment by r44083** [comment]
Thx!
Is this settings support ${project_path} identifier?

Can I write like this?
```
"-I${project_path}/source/UL/ulCRC",
```

**Comment by niosus** [comment]
Nope, but you can use relative paths, e.g. `-Isrc/` for a project - local folder src. Just be sure not to put a slash before it. :)

**Comment by r44083** [comment]
Ok. I just use this code in my plugin for replacing ${project_path} token.
```
			for i in range(len(project_settings)):
				project_settings[i] = project_settings[i].replace(
					'${project_path}', project_path)
```
But it is also good,

**Comment by niosus** [comment]
@r44083 I didn't quite get you. Why would you need to replace anything? The `*.sublime-project` should already lie inside of your project, so relative paths should be enough. Am I missing anything?
