### ISSUE TITLE
Design of the software architecture

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#130]
Having issues like #129 #122 #124 #123 #120 #119 #104 I feel like it is not enough to have an implicit notion of the architecture of this plugin and I believe the time has come to actually have it at least sketched out. For now the idea would be to create a diagram at: https://sketchboard.me/rAbnwhdbIjGX#/

- [x] sketch what the design is now
- [x] update the design to fit the needs of the above mentioned issues

Anyone is free to participate. Input is as always welcome.

**Comment by rchl** [comment]
I don't have much experience in designing this way but if you kickstart something then I might contribute. Maybe I'll learn something myself this way. :)

**Comment by niosus** [comment]
Sure, I will sketch out the way it is built now and then will invite you to the board. :)

**Comment by niosus** [comment]
Ok, so I have sketched current state approximately without going into all the details. I already see, that `FlagsManager` should probably be separated into two classes, that would represent build systems as also suggested in #104 

This way, we can have the CMakeBuildSystem that would store a dictionary of flags for a view name and would only rebuild this when CMakeLists.txt has been changed. This way we also won't need to update `.clang_complete` file by ourselves as the flags will come directly from cmake. Other build systems may function in a similar way. 

I will also give it another look in the upcoming days to find if I have any flaws in sketching out the design and finding out how to simplify the dependencies because currently we have a web of interconnected classes and I feel there is not always the need for the present dependencies.

**Comment by rchl** [comment]
Should also take redesign of settings into account to fix #119.
I suppose it will have to store settings per-view.

**Comment by niosus** [comment]
Maybe there is some way to use `sublime.View.settings()`. Not sure about it yet, though.

**Comment by niosus** [comment]
Although, we could just store some settings containers in plugin settings in a dict with view id as a key. As any setting can be overridden at any point of time.

**Comment by niosus** [comment]
New settings are now in the pull request #140. Feel free to comment on possible issue there.

**Comment by niosus** [comment]
I've been trying to gradually rewrite the plugin to match the structure, but cognitive load it too much for me to handle at once. The changes to per-view ideology has many changes and it seems it is easier to rethink the way everything is connected from scratch than to do gradual improvements. 

For now, the most viable idea to me seems to be to have a class `ViewConfiguration` that would be smth along the lines:
```
ViewConfiguration:
    - view
    - build system
    - completer
```
It would also store the settings it was previously run with. We would then need to get a `ViewConfiguration` from some manager object for a view (and settings). The flow is approximately sketched out here: https://sketchboard.me/FAb9Y9l1UFoh#/

It is hard to keep in mind what needs to be stored and how things should be shared. For example, how should the build system know that the file (say, `.clang_complete`, `CMakeLists.txt` or `compile_database.json`) above current view has been changed? Should we store this info for every view? For every build system? Lazy generation or pre-generate everything? Too many questions and I am struggling a bit to separate unnecessary details without sacrificing useful part of the design.

Please comment if you have ideas or see flaws in my logic anywhere.
