### ISSUE TITLE
Add specific readme for package control

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#131]
Readme on package control is lagging behind. Create a special smaller readme that would point to the github one.

Relevant: https://github.com/wbond/package_control/blob/2bcface6c34544eb5b0258984f2803b7a3c98ffc/example-repository.json#L113-L134

**Comment by rchl** [comment]
Doesn't Package Control just show the README.md from the repository?
I guess it might be delayed a little with updating its copy, but is it really a problem if it's outdated by 1 or 2 days?

**Comment by niosus** [comment]
Yes it does, but it also caches the build status, which annoys me to the extreme. 
They have a way of specifying a custom readme as I have recently found out: https://github.com/wbond/package_control/blob/2bcface6c34544eb5b0258984f2803b7a3c98ffc/example-repository.json#L113-L134

I think a short version of the full readme would be nicer there. The problem is then to support two readmes, but I really like it better than having a failing build always showing under the package name for no reason.

**Comment by niosus** [comment]
Added in pull request wbond/package_control_channel#5929
