### ISSUE TITLE
cmake generated flags order shuffled

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#139]
The flags generated by cmake have their order shuffled.

**Comment by rchl** [comment]
Any high-level idea how this should be fixed?

Would we stop merging flags from different compilation units together? If so, then I think we might still need to create some "fallback" set of flags in case user opens a header file or some other file not listed as a compilation unit.

**Comment by niosus** [comment]
Yeah, after sketching a bit yesterday it is clear that FlagsManager has to be divided into parts that are build-system related. For cmake we could have a dictionary that uses file name (we can get it from command) as a key and stores all the flags for this view. Then we just query the flags for a view, while this class is persistent and has the control over cmake, i.e. doesn't rebuild for every view or can even skip builds as a whole if needed. This way there is also no need to generate `.clang_complete` file.

The same can be done for other build systems. The old FlagsManager then becomes just a layer that manages `.clang_complete` file if other systems have failed or are unspecified.

At least that is very coarsely the ideas that I have right now. But I haven't yet spent any significant time at trying to simplify the diagram in #130. Maybe I will have more ideas from that.

Feel free to throw in ideas and comments as usual :)

**Comment by niosus** [comment]
Missed part of your comment:
> in case user opens a header file or some other file not listed as a compilation unit

I think I have seen that YouCompleteMe actually gets the flags of the corresponding cpp file. And this makes sense to some degree as I think clang allows to compile "incomplete" files. At least there is a constant in `TranslationUnit` class: `PARSE_INCOMPLETE`

**Comment by niosus** [comment]
On the other hand it is unclear on what to do about headers that have no cpp counterpart
