### ISSUE TITLE
Completers have to be generated per view

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#141]
While merging #140 we have found out that not all settings can be easily merged because there is only one Completer object that is used to generate completions in every view. Therefore it uses settings like `clang_binary` or `use_libclang` only once. We cannot make settings fully independent unless we allow many completers and picking one for each view.

For this, I think that the best way would be to have some `CompletionFactory` class that would test the availability of `libclang` once and when asked will return a specific completer based on the given settings and particular completer availability. So I expect it to have a function like `completer_for_view(view, settings)` that will return a completer object.

This is work in progress. Comments are welcome.

**Comment by rchl** [comment]
Sounds good.

**Comment by niosus** [comment]
Now I don't think a single completer is enough. See the flow I imagine here: https://sketchboard.me/FAb9Y9l1UFoh#/
