### ISSUE TITLE
CMake - search for root CMakeLists.txt

### ISSUE THREAD

**Issue by Xecutor** [niosus/EasyClangComplete#142]
I have a project where each directory contains CMakeLists.txt and parent adds subdirectories with add_subdirectory command. CMakeLists.txt files in subdirectories depend on root CMakeLists.txt. They cannot be used independently.

Also, ideally it should be possible to specify/guess build directory to reuse CMakeCache.txt.

**Comment by niosus** [comment]
The plugin currently searches up the directories until the project root for `CMakeLists.txt` files that have `project` macros specified in them. It then runs cmake on this `CMakeLists.txt` file, so it should work just fine in your case, unless every small CMakeLists.txt defines a `project` macros, while still not being a standalone cmake project.

The second part of your question is in progress and is partially discussed in #104

**Comment by Xecutor** [comment]
Whole 'solution' consists of many libraries and binaries. So, actually yes, many CMakeLists.txt have project macro, if it's independent library or binary...

**Comment by niosus** [comment]
so if it is independent it should be able to build on its own, right? Otherwise it should not be a standalone cmake project, or am I getting it wrong?

**Comment by Xecutor** [comment]
Root CMakeLists.txt defines a lot of common stuff for other subprojects, so they aren't standalone in this sense. Valid build configuration can only be generated from root CMakeLists.txt.

**Comment by niosus** [comment]
But what is the reason of them having `project` macro then?

**Comment by Xecutor** [comment]
For some reason I thought that project() generates visual studio project... But apparently that's not the case. Project was generated long time ago... Ok, never mind than about root :)

**Comment by niosus** [comment]
Oh, no it does not :) Anyway, that is only my understanding that the project kinda marks whatever is below it as "independent" from everything above it.

**Comment by leolchat** [comment]
It would still be very useful to have an easy way to tell which cmakelists to use. I am in a big project with exactly the problem indicated above (project which are not "independents") and changing all the cmake files is not really in scope.

Any quick hack to achieve that at least ?
