### ISSUE TITLE
Cannot complete C code (-x c++)

### ISSUE THREAD

**Issue by FHTheron** [niosus/EasyClangComplete#150]
Create a test.c file with:
```
struct qqqq {
	int qwe;
};
void main()
{
    qqqq aa;
    aa.
}
```

Trying to autocomplete on `aa.` produces:
```
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C`
DEBUG:EasyClangComplete.plugin.completion.base_complete: view 28, already has a completer
DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang command: 
['clang++', '-c', '-fsyntax-only', '-x', 'c++', '-std=c11', '-isystem/usr/include', '-I/src', '-I/workspace/src', '-I/usr/lib/clang/3.8.0/include', '-I/home/testuser', '-I/home', '-Xclang', '-code-completion-at=/tmp/EasyClangComplete/test2.c:8:8', '/tmp/EasyClangComplete/test2.c']
DEBUG:EasyClangComplete.plugin.tools: command: 
clang++ -c -fsyntax-only -x c++ -std=c11 -isystem/usr/include -I/src -I/workspace/src -I/usr/lib/clang/3.8.0/include -I/home/testuser -I/home -Xclang -code-completion-at=/tmp/EasyClangComplete/test2.c:8:8 /tmp/EasyClangComplete/test2.c
DEBUG:EasyClangComplete.plugin.tools: clang process finished with code: 1
DEBUG:EasyClangComplete.plugin.tools: clang process output: 
error: invalid argument '-std=c11' not allowed with 'C++/ObjC++'

DEBUG:EasyClangComplete.plugin.completion.bin_complete: code complete done in 0.04167652130126953 seconds
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'error: invalid argument '-std=c11' not allowed with 'C++/ObjC++'' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
```

I tested this using a new user, getting a new sublimetext tarball (build 3125), installing package control and then EasyClangComplete. Then set these settings to get debug output:
"use_libclang" : false,
"verbose" : true,

With this clean environment, it still happens.

**Comment by niosus** [comment]
Sorry for that :) Can you tell me what settings do you have in `cpp_flags`? It should be smth like:
```
"cpp_flags" : [
		"-std=c++11"
	],
``` 

Also, it seems that your code is detected as `C` instead of `C++`. What is stated in the bottom right corner of the editor? Which syntax does sublime text guess?

**Comment by FHTheron** [comment]
SublimeText and EasyClangComplete both see the file as "C" (which is correct).

```
$ cat /home/testuser/.config/sublime-text-3/Packages/User/EasyClangComplete.sublime-settings
{
    "use_libclang": false,
    "verbose" : true,
}
$ grep -A2 "c_flags\|cpp_flags" /home/testuser/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.sublime-settings 
    "c_flags" : [
        "-std=c11"
    ],
--
    "cpp_flags" : [
        "-std=c++11"
    ],
```

EasyClangComplete also passes the correct -std flag, but it seems clang wants `-x c` in this case (I haven't tested this yet).

The following change seems to fix the C case:
```
--- a/EasyClangComplete/plugin/completion/compiler_variant.py
+++ b/EasyClangComplete/plugin/completion/compiler_variant.py (Unsaved)
@@ -36,7 +36,7 @@
         init_flags (list): flags that every command needs
         error_regex (re): regex to find contents of an error
     """
-    init_flags = ["-c", "-fsyntax-only", "-x", "c++"]
+    init_flags = ["-c", "-fsyntax-only", "-x", "c"]
     include_prefixes = ["-isystem", "-I", "-isysroot"]
     error_regex = re.compile("(?P<file>.*)" +
                              ":(?P<row>\d+):(?P<col>\d+)" +
```

But the -x switch should instead be syntax aware then I suppose.

**Comment by niosus** [comment]
Ok, yes, now I understand. This is a bug, we should not set `-x` flag in a compiler variant. It should be done elsewhere once we have detected the language. Will most likely fix this this weekend. Thanks for reporting.

**Comment by niosus** [comment]
I have pushed the change to master. Now the `-x` flag should be specified in the user preferences of the plugin and is not hardcoded. I hope to make this change live in a release today or tomorrow.

**Comment by niosus** [comment]
Sorry for the delay, but I was not able to push a release on the weekend. I will make it as soon as possible. Quite a busy week. :(
