### ISSUE TITLE
gl.h header breaking up autocompletion

### ISSUE THREAD

**Issue by brupelo** [niosus/EasyClangComplete#157]
This is a continuation from the other issue, here's a little [video](https://dl.dropboxusercontent.com/u/21334722/ShareX/2016/12/2016-12-01_16-08-01.gif) showing up the current status of the plugin.

As you can see, there isn't any problem with some custom classes/structs... at the moment I try std::vector completion the package won't work.

Could you suggest how we can start narrowing down this issue?

Thanks in advance

**Comment by rchl** [comment]
You are missing `#include <vector>` line. It can't know what std::vector is if you don't include the header.

And I don't know if it makes a difference but I would suggest to point to MS header files using `-imsvc` flag:
```
"-imsvcC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE",
```
(escaped backslashes should work too)

**Comment by brupelo** [comment]
@rchl Thanks for your answer. Mmm, your suggestions seemed like would be the solution to my problem but unfortunately they weren't, please take a look to all my attempts [here](https://dl.dropboxusercontent.com/u/21334722/Uploads/2016/12/2016-12-01_16-56-27.mp4) . As you can see I've tried all your suggestions, am I missing something here?

Also, worth mentioning the autocomplete works with std somehow, take a look to [this](https://dl.dropboxusercontent.com/u/21334722/Uploads/2016/12/2016-12-01_17-01-21.mp4)

**Comment by rchl** [comment]
Try `"use_libclang": false,` . Binary completer has more verbose output when some header files it's looking for are missing. If you fix the problem based on its output then it should also work with libclang then.

BTW. My advice about using `-imsvc` might not be valid for clang++. I was thinking of clang-cl as that is what I'm normally using.

**Comment by rchl** [comment]
It works with those for me:
```
"-IC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE",
"-IC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/ATLMFC/INCLUDE",
"-IC:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/ucrt",
"-IC:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/shared",
"-IC:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/um",
"-IC:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/winrt",
```

**Comment by brupelo** [comment]
@rchl Mmm, thanks to your suggestion of using `use_libclang:false`, thanks to that I've been able to revel the real bug. It seems the problem wasn't related with std/vector include paths at all, minimum required is `"-IC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE",` . The real problem, which I wasn't showing on the previous videos was the fact of including `#include <gl\gl.h>` header. Try that on your tests and you'll see how that header will mess up... That's the real issue here I guess.

**Comment by brupelo** [comment]
There isn't any bug at all, I just needed to `#include <windows.h>` before `#include <gl\gl.h>` , this package rocks too much. Don't need VS anymore \o/
