### ISSUE TITLE
Duplicate flags removed on parsing

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#161]
I'm trying out `compile_commands.json` support and noticed that some flags are dropped. Probably because ECC thinks they are duplicates but they are not.

Example:
```
/MD -Xclang -add-plugin -Xclang find-bad-constructs 
```

becomes:
```
'/MD', '-Xclang', '-add-plugin', 'find-bad-constructs',
```

Notice how second `-Xclang` was dropped.
I suppose this is due to using UniqueList which assumes that there can be no two identical flags in the command? In this case there must be.

This is probably not specific to `flags_sources`.

**Comment by niosus** [comment]
This should be easy to fix. We just need to add those to `separable_prefixes` [here](https://github.com/niosus/EasyClangComplete/blob/master/plugin/utils/flag.py#L67). This way, these flags will not be discarded. Actually, I was thinking of running a command `clang -h` with a simple regex to determine which flags consist of two parts.

**Comment by niosus** [comment]
I have pushed a quick fix for this. Does this work for you?

**Comment by rchl** [comment]
Yes, that appears to solve this problem.

**Comment by niosus** [comment]
Ok, I will release it as a small bug fix now, with all the flags that need two parameters.
