### ISSUE TITLE
No support for @foo.rsp command line option

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#163]
So rsp files basically contain compiler commands. They are most often used on Windows due to biggest limitation on the command line length, but I think they are also used on other platforms sometimes. Or at least they are supported on non-Windows systems also.

I've done a small hack to support @rsp files. When I encounter a `@path.rsp` flag, I open the file at path.rsp, read the content, process it like other flags are processed (relative paths converted to absolute), and append those flags. Quickly realized that this is not a way to go. Apart from being very slow when there are 30 000+ entries in compiler_commands.json, that also triggers an error that rsp files were made to fix - command line length gets too long and fails when passed to clang binary.

_Question 1: Does command line length matter for libclang? I think it shouldn't be a problem for libclang at least._

So given that problem, I think we would need to pass the rsp file to the compiler rather than extracting flags from it. But that means that relative paths would not be converted to absolute so we would need to make sure that working directory is correct when running clang.

_Question 2: Does libclang handle passing @path.rsp file? If yes than fine, if not then we would need to extract flags from rsp file only for it._

**Comment by niosus** [comment]
Q1: I don't think it does, because it does not call the binary. It is an actual lib that feeds the data to c++ code. 

Q2 : don't know yet. As a side note, can you omit creating rsp files?

**Comment by niosus** [comment]
Also, I think we should really discuss it in #115

**Comment by niosus** [comment]
I will close this issue in favor of #115

**Comment by rchl** [comment]
> Q2 : don't know yet. As a side note, can you omit creating rsp files?

No, you can't omit them. The point of them is to not have too many compile flags on the command line as that would exceed command line length limit easily. Especially on Windows.

**Comment by niosus** [comment]
yes, but if you're using libclang that should not be the issue after all right?

**Comment by rchl** [comment]
Yes, I assume that libclang wouldn't have a problem with very long compile options as it doesn't go through the command line limitations. But ideally both libclang and clangbinary would be handled the same for code simplicity.
