### ISSUE TITLE
Incorrect auto completion.

### ISSUE THREAD

**Issue by david9991** [niosus/EasyClangComplete#164]
<img width="710" alt="screen shot 2016-12-09 at 3 01 57 pm" src="https://cloud.githubusercontent.com/assets/123219/21040538/93426076-be20-11e6-8f58-a9759dd31411.png">

This image show that we have grpc::ClientContext class under grpc namespace, but it not presented in the completion list. 

<img width="365" alt="screen shot 2016-12-09 at 3 06 02 pm" src="https://cloud.githubusercontent.com/assets/123219/21040617/0d5e258e-be21-11e6-8c8e-45f5217469bc.png">

And this image means we ONLY has MSVGReply class in GS namespace but many classes which defined in other namespaces was auto completed.

That's happened after I moved to v3.0.2.

**Comment by niosus** [comment]
Ok, we did slightly changed the way completions are shown. I will try to plays around with this and will try to reproduce this behavior.

**Comment by simia** [comment]
That would be me who broke it:(
Fortunately it's easy to fix.

**Comment by niosus** [comment]
@simia do you know what exactly is broken? Then just PR the fix and I will quickly merge it :)

**Comment by simia** [comment]
CursorKind CLASS_DECL is excluded for double colons. 
Fix would be replacing:
excluded = self.ignore_list[:-1]
with:
excluded = self.ignore_list[:-2]

I can't PR at work so either you make change or wait until I get back home :(

**Comment by niosus** [comment]
I will change it. Thanks. :)

**Comment by niosus** [comment]
The fix will be live soon in version 3.0.3. Have just submitted a new release.
