### ISSUE TITLE
db['all'] entry can be very wrong

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#166]
If there is no entry for given file in the DB, plugin chooses to return db['all'] entry which is created like this:
```
parsed_db['all'] = unique_list_of_flags.as_list()
```
But in my case this entry is very wrong as it contains around 30000 @rsp entries for all the compilation units (compile_commands.json is around 16MB in this project):
```
['d:\\workspace\\work\\chromium\\src\\third_party\\llvm-build\\Release+Asserts\\bin\\clang-cl.exe', '-c', '-fsyntax-only', '-I\\usr\\include', '-ID:\\workspace\\work\\chromium\\src\\third_party\\branding\\src', '-I\\usr\\lib\\clang\\4.0.0\\include', '/nologo', '/FC', '@obj/apps/apps/app_lifetime_monitor.obj.rsp', '@obj/apps/apps/app_lifetime_monitor_factory.obj.rsp', '@obj/apps/apps/app_load_service.obj.rsp', '@obj/apps/apps/app_load_service_factory.obj.rsp', ..., 'file_to_compile.cc']
```

**Comment by niosus** [comment]
Is there really anything we can do about it? I think this is the best solution we have. Another solutions could be:
- return nothing (I don't like it)
- return flags of the closest present file (shorter, but still very wrong)

**Comment by rchl** [comment]
I'm not sure of better solution but passing 30000 rsp files on the command line will:
a) exceed command line limit when using clang binary
b) will take a lot of time for clang to read all of those files.

**Comment by niosus** [comment]
What would you suggest to do instead?

**Comment by niosus** [comment]
I will close it I guess as there is no good solution that I see, so we probably cannot really fix this. It also doesn't occur for me in my day-to-day use.
