### ISSUE TITLE
"file" path property from compile_commands.json not converted to absolute path

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#167]
An entry like:
```
  {
    "directory": "D:\\workspace\\work\\chromium\\src\\out\\clang",
    "command": "../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/unit_tests/SelectionControllerTest.obj.rsp /c ../../third_party/WebKit/Source/core/editing/SelectionControllerTest.cpp /Foobj/third_party/WebKit/Source/core/unit_tests/SelectionControllerTest.obj /Fd\"obj/third_party/WebKit/Source/core/unit_tests_cc.pdb\"",
    "file": "../../third_party/WebKit/Source/core/editing/SelectionControllerTest.cpp"
  },
```
Will end up in internal database map as `"../../third_party/WebKit/Source/core/editing/SelectionControllerTest" = [...]` and thus will later not be matched to the actual SelectionControllerTest.cpp file which will have absolute path.

**Comment by rchl** [comment]
After fixing this with something like:
```
entry_path = entry['file']
if path.isabs(entry_path):
  entry_path = path.normpath(entry_path)
else:
  path.normpath(path.join(database_file.folder(), entry_path))
```
I've noticed that there can still be discrepancies in the path's case.
In database:
  `d:\\workspace\\work\\chromium\\src\\third_party\\WebKit\\Source\\core\\editing\\SelectionController`
In view.file_name():
  `D:\\workspace\\work\\chromium\\src\\third_party\\WebKit\\Source\\core\\editing\\SelectionController`

Notice uppercase drive letter in second case

**Comment by rchl** [comment]
We could probably use os.path.normcase to fix that problem. We would need to apply it consistently both to database and view.file_name() then.

**Comment by niosus** [comment]
yes, thanks. That is a bug and I will fix it hopefully on this weekend.

**Comment by niosus** [comment]
I have created a PR for this. Please check if it works for you.
