### ISSUE TITLE
reloading cmake only if top level one changed

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#169]
If we have a hierarchy of `CMakeLists.txt` files and get flags from cmake, the cmake will only be run if the top-most CMakeLists.txt has changed. This is not enough. If we change something in the lower one we still want to regenerate new flags.

**Comment by jdumas** [comment]
Have a look at the file `CMakeFiles/Makefile.cmake` that is generated in the build directory. You should be able to parse it and extract the content of the variable `CMAKE_MAKEFILE_DEPENDS`, which contains the dependencies you are looking for. Of course this is specific to the `Makefile` generator ... I don't know how it goes for the Ninja or Visual Studio generators.

**Comment by niosus** [comment]
Yeah, I know about that one. However, I don't think I need this as I always search for a `CMakeLists.txt` up the tree and ignore those that don't contain `project` in them. I can as well test if they have changed since the last access to them. This should be easy. I hope to find some time to implement this over the weekend.

**Comment by jdumas** [comment]
I am not sure I follow. The `CMakeLists.txt` of the project can depend on *a lot* of files. For example all the custom `FindModule.cmake` that are searched by `find_package` (and can be located anywhere), as well as all the files that are directly `included()`. Do you intend to parse the `CMakeLists.txt` yourself and find all of them? Why bother if CMake is doing this job for you?

**Comment by niosus** [comment]
You're right. I only bumped into a situation when I changed a `CMakeLists.txt` file that it lower in the tree. I didn't think, that someone may change some other file CMake depends on which of course can happen. So then I think the only way is to proceed is to actually parse `Makefile.cmake` and remember the change data of those files.

**Comment by niosus** [comment]
The change is in `dev`. I will merge it to `master` and release it tomorrow.
