### ISSUE TITLE
Does EasyClangComplete copy file to user folder?

### ISSUE THREAD

**Issue by r44083** [niosus/EasyClangComplete#17]
Hi, I just noticed that sometimes I get warning like this:
```
WARNING:EasyClangComplete.plugin.completion.bin_complete: completion c:\users\user\appdata\local\temp\bl.c:3:10: fatal error: 'string.h' file not found did not match pattern <_sre.SRE_Pattern object at 0x03C65578>
```

So, I'm just interested in. Is EasyClangComplete really create copy of edited file into the user folder?

**Comment by niosus** [comment]
Yep, it does, when you use binary for completion. It is needed to account for unsaved changes in the file being edited and to allow changing this file, while the autocompletion thread is already working. Therefore whenever you trigger autocompletion, the current file contents are copied to the system temp folder (`c:\users\user\appdata\local\temp` on Windows, `/tmp` on Linux and OSX) and the autocompletion is triggered on the copy.

**Comment by niosus** [comment]
I will close this isssue for now as the only question you asked has been answered and there has been no follow up.
