### ISSUE TITLE
Async CMake run

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#170]
Hi,

Right now, every time I open Sublime with EasyClangComplete enabled, Sublime appears to freeze when the plugin is running the `cmake` command necessary to produce the necessary completion flags for the project.

CMake project generation can take some time for large project, so ideally this step should be done in a separate thread so as not to freeze the UI. This doesn't seem to be the case at the moment, but correct me if I am wrong.

Finally, every time I restart Sublime the plugin rerun cmake again, even though the files in the output build folder should be up to date already. It should be possible to save some time by running it only when necessary.

**Comment by niosus** [comment]
First part - everything is going in asynchronously. There is no blocking function that takes any considerable amount of time. At least there should be none :)

Second part. Yes, this should be the case, but we don't know if those files are up to date. So when you start plugin it will run cmake. It will not run it anymore unless you change the `CMakeLists.txt` files as everything is cached.

If you don't want to run cmake you can always just use the compilation database that would be produced manually on every manual build.

**Comment by jdumas** [comment]
Then I don't understand why Sublime is freezing on startup (seemingly when it runs the CMake command). Can you point me to the part of the code that should spawn the thread running the `cmake` command? I'd like to understand what is going on.

For the second point, `cmake` is run again everytime on startup because you are using:

    shutil.rmtree(tempdir, ignore_errors=True)

In the file [cmake_file.py](https://github.com/niosus/EasyClangComplete/blob/94cd6a23714801cb7180630b02e81abe50490509/plugin/flags_sources/cmake_file.py#L133). I think you should leave it to the user to clean the build tree, or at least provide a quick command (Ctrl+Shift+P) "Invalidate CMake Cache" that `rm` the build tree and let CMake generate a clean project (e.g., useful when you change cached variable in the CMake script).

**Comment by niosus** [comment]
It starts from `EasyClangComplete.py`. The only method of `ViewConfigManager` that can trigger a run of cmake is `load_for_view`. This one is only called from `on_post_save_async` and `on_activated_async`. These are managed by sublime itself. So, it should not freeze the gui, but it may delay the other plugins that rely on async functionality as there is only one working thread in sublime text.

**Comment by jdumas** [comment]
Ok, how about this call to [`__generate_essentials`](https://github.com/niosus/EasyClangComplete/blob/bf323bbf8f8e6844eab2ef0cd59c5f9c05eda223/plugin/view_config.py#L58) in the `__init__` method of `ViewConfig`? This seems to call `__load_source_flags` and later `flag_source.get_flags(...)`.

**Comment by niosus** [comment]
Yes, but you never call `__init__` of `ViewConfig` in a non-async context

**Comment by jdumas** [comment]
Printing the traceback before [the call](https://github.com/niosus/EasyClangComplete/blob/94cd6a23714801cb7180630b02e81abe50490509/plugin/flags_sources/cmake_file.py#L148) to CMake, I can see that indeed this comes from a call to `on_activated_async`. However, it still freezes my UI. If you put a `time.sleep(60)` at this moment, you should see the effect as well. This may be a bug in sublime text? Can you confirm?

**Comment by niosus** [comment]
No it does not happen on my side. My ui is still as responsive as ever.

**Comment by jdumas** [comment]
Ok. then I'd be interested to see if anyone else has a frozen ui when puttin a `time.sleep(60)`. For the record I am using Build 3126 + Python 3.5.2 (Archlinux).

**Comment by rchl** [comment]
It does seem like ECC is actually blocking some functionality of Sublime. Loading of 15MB compile_commands.json file does block the whole UI for 30 seconds or so. Maybe we shouldn't be doing extensive work on sublime's async thread as it's probably shared by plugins.

**Comment by niosus** [comment]
Ok, then we should just use the thread pool that is already used for completions also for initial loading.
