### ISSUE TITLE
Only hide default completions if no EasyClangComplete completions are available

### ISSUE THREAD

**Issue by SpeCter** [niosus/EasyClangComplete#173]
Is it possible to only hide the default completitions if ecc has none?
Right now I have the problem that the completion list defaults to the middle(?) and I have to scroll up to get to the beginning to see the entries added by ecc if I don't hide the default ones.
In general I prefer the ecc suggestions but if there are no suggestions I would like to see the fuzzy ones from sublime text.

For the time being it would be enough if someone knows how to stop sublime from scrolling the suggestion list on its own.

**Comment by niosus** [comment]
If you use `hide_default_completions` it will only hide those after some trigger like `'.', '->', '::'` and will not touch them otherwise. Is this not the behavior you need?

**Comment by SpeCter** [comment]
This is exactly what I need, but this is not the behaviour I'm experiencing though :)
When I turn on `hide_default_completions` I don't get _any_ completions outside of `'.', '->', '::'` completions. Right now I use `hide_default_completions` with CTags, to get completions on Space+Enter which works as you described minus the fuzzy suggestions.

**Comment by niosus** [comment]
This is strange to me. With `disable_default_completions` set to true, I type in a cpp file and get completions generated by sublime text. As soon as I hit, say `->` I get only the ones from my plugin.

**Comment by niosus** [comment]
As a side note - what are you using CTags for that this plugin cannot do?

**Comment by SpeCter** [comment]
CTags is only used to help me with suggestion weird long variable/macro names(which the default completion of ST would be more than enough for).
So I use CTags if I don't want to access member variables(/functions).
Maybe it is important to note here that I'm using it for a pure C project atm not C++ eventhough I think the behaviour should be the same?

**Comment by niosus** [comment]
yep, should behave the same. For now I don't have an idea why this is happening, but maybe I will get an idea about this.

**Comment by niosus** [comment]
Maybe ctags messes with default sublime completions? Can you disable all packages but ECC and still reproduce this?

**Comment by SpeCter** [comment]
Maybe you are right. On my home pc there is no ctags installed and the completion list starts at the first entry even with sublime completions. Will try on monday if removing ctags will do the trick.

**Comment by niosus** [comment]
Great. Please close the issue if everything is ok or provide more details to nail it down. Thanks.

**Comment by SpeCter** [comment]
I can't seem to get it to work as expected on my C-Project at work, but since it only happens with sublime completions I'll guess the problem is not due to ecc but a combination of sublime and my project. 
I'll close this for now, thanks for your help.

**Comment by niosus** [comment]
This is strange. You can try to create a minimal verifiable example for me to check out. Anyway, feel free to reopen the issue if you find more details or what causes the behavior.
