### ISSUE TITLE
AttributeError: 'SettingsStorage' object has no attribute 'clang_binary'

### ISSUE THREAD

**Issue by fuzzyBatman** [niosus/EasyClangComplete#174]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 480, in on_post_save_async
    callback.on_post_save_async(v)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 182, in on_post_save_async
    self.view_config_manager.load_for_view(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 344, in load_for_view
    config = ViewConfig(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 58, in __init__
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 163, in __generate_essentials
    completer = ViewConfig.__init_completer(settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 254, in __init_completer
    completer = lib_complete.Completer(settings.clang_binary,
AttributeError: 'SettingsStorage' object has no attribute 'clang_binary'
```

**Comment by niosus** [comment]
This is strange. When does this happen?

**Comment by fuzzyBatman** [comment]
I installed the plugin and added this to my ".sublime-settings-User" file

{  
	"common_flags": [
		"c:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include\\c++"
	],
  "use_libclang" : true,

  "verbose" : true,
  "clang_binary" : "clang++",

  // hide the completions generated by other plugins
  "hide_default_completions": true,
}

don't even know if I'm doing this right. I added Clang headers in the default settings file by replacing the headers for clang provided for linux.

when I test it on a random c++ file no autocomplete suggestions are shown and whenever I hit save, that error message pops up

**Comment by niosus** [comment]
Ok. We should really invest some time into specifying the startup procedure for those using gcc on Windows. Unfortunately I don't know about this myself, but maybe other windows people may be of help. Anyway. That is a completely unrelated topic.

As for now, please set `"verbose"` setting to true, restart Sublime Text and copy the full console output here. Then I will probably be able to tell you more about what could go wrong and we can think on how to fix this.

**Comment by rchl** [comment]
At least the entry in `common_flags` is wrong. I guess you meant to make it an include dir in which case you need to prefix the path with `-I`.

**Comment by fuzzyBatman** [comment]
Hey, I was able to fix it. Specifying the headers seemed to be the problem. Now the error is gone.
And yeah, I missed out the '-I' there.

This is the final "common_flags" setting I used:

"common_flags" : [
    // MinGW includes
    "-Ic:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include\\c++",
    "-I$project_base_pat\\src",
    // this is needed to include the correct headers for clang
    "-Ic:\\Program Files\\LLVM\\lib\\clang\\$clang_version\\include"
  ]

**Comment by niosus** [comment]
I will close this issue, but I still don't understand why it crashed with the original error. We should probably catch when something is wrong with flags...
