### ISSUE TITLE
Document setup procedure for using MinGW on Windows 

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#175]
People who have a setup like this seem to struggle setting the plugin up. 

I know a couple of you guys use Windows and probably also MinGW. Could you tell me about the caveats? Or even better update the readme to reflect this?

**Comment by SpeCter** [comment]
Could you elaborate what GCC/MinGW does have to do with a plugin which utilizes clang?
I'm willing to help since I also use MinGW but right now I'm clearly missing the point.
(Or does gcc finally allow to use it for code completion?)

**Comment by niosus** [comment]
No, sorry, my bad. I just use gcc myself and clang inside of the plugin and have too many things happening at the same moment. :) I meant, that people that use MinGW have to configure their default include paths (to find stl for example) and I have no idea how these include paths generally look.

**Comment by SpeCter** [comment]
You mean include paths like this:
```
C:\mingw530_32\i686-w64-mingw32\include\c+
C:\mingw530_32\i686-w64-mingw32\include\c++\bits
```
?

**Comment by niosus** [comment]
I guess so. Maybe it is worth adding those as default examples? (wrong includes don't break `clang`)

**Comment by SpeCter** [comment]
I'll try to get it properly working with gcc headers and will report later, should not be to hard I hope

**Comment by SpeCter** [comment]
Ok so I pretty much only added these to my .clang_complete file:
```
-ID:\Qt\Qt5.8.0\Tools\mingw530_32\i686-w64-mingw32\include
-ID:\Qt\Qt5.8.0\Tools\mingw530_32\i686-w64-mingw32\include\c++
-ID:\Qt\Qt5.8.0\Tools\mingw530_32\i686-w64-mingw32\include\c++\bits
-ID:\Qt\Qt5.8.0\Tools\mingw530_32\i686-w64-mingw32\include\c++\i686-w64-mingw32
-ID:\Qt\Qt5.8.0\Tools\mingw530_32\i686-w64-mingw32\include\c++\backward
```
to my project and it pretty much seemed to work out of the box.
Clang is the official precompiled binary from LLVM version 3.9.
MinGW is the one shipped with Qt 5.8 version 5.3.0 but it should work with any other version too just adjust the path to the mingw folder accordingly like so:
`C:\MinGW\i686-w64-mingw32\include\...`

**Comment by niosus** [comment]
Is this a minimal setup? Can you still work having, say, no `backward` entry?

**Comment by SpeCter** [comment]
As far as I remember I just compiled a minimal project with gcc and used the -v option to see which headers are included by gcc and used these just with absolute paths.

**Comment by niosus** [comment]
Makes sense :) Thanks. I will include them as soon as I do proper documentation.

**Comment by SpeCter** [comment]
I took another look at it, it seems that the official clang packages were compiled with visual studio since 3.8.
This seems to break compatibility with mingw.
If you use the packages from msys2 and use clang from there, the target is still `i686-w64-windows-gnu` and it really works out of the box, without any includes.
The `i686-w64-windows-msvc` doesn't integrate with mingw and doesn't like the mingw header files that much.

**Comment by niosus** [comment]
So does anybody successfully use MinGW with the plugin? What settings are being used?

**Comment by Dimenus** [comment]
Mine is mostly working. It's not picking up a few functions in nested folders though. For example:
`#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtx/quaternion.hpp>`

But it does pick up everything in :
`#include <glm/glm.hpp>`

Here is my settings file:
`{
	// hide the completions generated by other plugins
	"hide_default_completions": false,
	"common_flags" : [
    // some example includes
    "-I$project_base_path/include",
    "-IC:/msys64/mingw64/include"
	],
	// C++ specific flags. Prepend common_flags for C++ files.
	"cpp_flags" : [
    "-std=c++11"
  ],
}`
