### ISSUE TITLE
Error message is too long to be displayed

### ISSUE THREAD

**Issue by david9991** [niosus/EasyClangComplete#177]
Error message is too long to be displayed when mouse-over inside error area. Could it be split to multiple lines?

![untitled](https://cloud.githubusercontent.com/assets/123219/21211095/9012e796-c2bb-11e6-819b-49df43e81d8d.png)

**Comment by niosus** [comment]
If we think about a nice rule to divide an error message into lines, I am happy to introduce this. Otherwise, this windows should be scrollable with a mouse.

**Comment by niosus** [comment]
This issue will go away as soon as I merge #185

**Comment by niosus** [comment]
After some consideration, I decided to close this issue for now. I will keep the backlog label to return to it if the demand will be overwhelming.
