### ISSUE TITLE
Parameters representation wrong with binary completion

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#178]
Hi,

I just tried EasyClangCompletion on a `std::vector<Stuff> t`, and when I type `t.emplace_ba<tab>` it produces the following:

    t.emplace_back(<#_Args &&__args...#>)

I think this is a bit "noisy". We could do without the `<#_Args &&__args...#>` part (that I need to remove manually ... more typing). To be fair, a "tooltip" showing us the function prototype when the mouse is hovering the function would be nice. It can be achieved with the *[on_hover](http://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener)* API introduced in build 3124.

**Comment by niosus** [comment]
First part: I strongly disagree. I think having berbose parameters in place is a very good thing as it helps a lot when having more than one parameter. Also, you can navigate them with <kbd>Tab</kbd> and just start typing to replace them. If this is not the behavior you are seeing, this is a bug.

Second part. Yes, we should. I will move it to a separate issue. However, I won't have much time in the coming month because of a couple of deadlines and an important interview. But I would be happy to merge a PR on that.

**Comment by rchl** [comment]
I think the issue is still valid. The representation of the arguments in this case is some internal clang form that I think you filter out (or process) in the plugin normally, but it doesn't seem to work in this case.

And tabbing to the argument doesn't work in that case either. Or rather, given that there is only one argument, there is nothing to tab to but the argument is in this case not selected which is a bug.
1. `vector.empl|`
2. press tab
3 `vector.emplace_back(<#_Valty &&_Val...#>)|`

Check where the caret ends up after completing this method.

**Comment by niosus** [comment]
Ok, I got this. It only happens if we are using binary completion and this is because of an error in regex that parses completions.

I remember you guys having issues with libclang, are they still valid?

**Comment by rchl** [comment]
> I remember you guys having issues with libclang, are they still valid?

I'm not using libclang because I can't get the @rsp files to work in it (even with `-working-directory` argument). But I don't really have any fundamental problems with libclang. It generally works well.

**Comment by rsp** [comment]
@rchl Every time you write `@username` in the comment on GitHub the user gets a notification - see:
* https://github.com/blog/821-mention-somebody-they-re-notified
Specifically, when you write @rsp then I get an email. If you want to `@rsp` without sending me a notification then you can use the backticks in markdown - see Inline code in https://guides.github.com/features/mastering-markdown/

**Comment by niosus** [comment]
@rsp sorry. We will try to avoid it and write it properly. `@rsp` it is from now on.

**Comment by rsp** [comment]
@niosus No problem. I didn't know you were aware of the notifications. You know, it's kind of scary to see a notification about somone trying to "get the @rsp files" ;)

**Comment by niosus** [comment]
Please do open a separate issue. You don't see the command, but the flags should be there anyway.

**Comment by jdumas** [comment]
So, I the expected behavior is to have the default argument prototype selected when the function is autocompleted (which is nice indeed, and not a pain to remove), it still leave me with a problems for functions with multiple arguments. Consider typing this:

```cpp
std::vector<int> foo;
foo.assi|
```

When you press <tab>, I still need to manually erase the second argument prototype `, const value_type &__val`, which sounds like a lot of unnecessary work to me at least (compared to the benefits of having the prototype displayed).

**Comment by niosus** [comment]
Nope, if there is a second parameter you will be able to <kbd>Tab</kbd> your way to it. I think it is a really nice feature. The plugin currently drops all the optional parameters.

**Comment by jdumas** [comment]
Imho this is a fragile construct. If I inadvertently type "right", and the cursor ends up after the comma, I am screwed, I cannot `tab` my way to the second argument, and I have to erase it manually to enter mine. It would be nice if at least keyboard navigation could select the whole argument, to make it easy to "erase". I think this is important, because it is very easy to "lose" focus of a windows, or go check some other file to find out something before coming back to writing down the arguments, etc.

Another problem I have noticed (which might be related to a bug in Sublime itself), is that if you have the carret as follows

```cpp
	std::vector<int> foo;
	foo.assi|gn(10, 24);
```

And press `tab` again (e.g. to "navigate" the arguments), then I ended up with the following redundant completion

```cpp
	foo.assign(size_type __n, const value_type &__val)gn(10, 24);
```

**Comment by niosus** [comment]
It's not sublime text. If you start completion at some point there is no way to know if what you have after it is correct. Also, I definitely don't want to delete anything from a buffer.

Anyway. We probably can add this as an option. This is easy to do. So you will be able to disable the parameter suggestions.

**Comment by jdumas** [comment]
I mentioned it might have been a bug in Sublime text, because I was experiencing similar issues with the LaTeXTools completion feature (see [here](https://github.com/SublimeText/LaTeXTools/issues/867) and [there](https://github.com/SublimeTextIssues/Core/issues/1281) for the related threads).

Also, I didn't know about the <kbd>Ctrl + Shift + m</kbd> shortcut, this is a neat one! I guess I'm learning something new about Sublime every day =)
