### ISSUE TITLE
How to predefine macros in common_flags?

### ISSUE THREAD

**Issue by canfoderiskii** [niosus/EasyClangComplete#179]
Firstly, I just want to say thanks for the great plugin.

Maybe my question is silly, but I truly cannot find how to add user-defined macros to clang, like the `-DMACRO=value` in GCC.

Any help?

**Comment by niosus** [comment]
Just the same way you do it in GCC. So adding it to common flags should work as you expect.
```
"common_flags" : [
    // some example includes
    "-I/usr/include",
    "-I$project_base_path/src",
    // this is needed to include the correct headers for clang
    "-I/usr/lib/clang/$clang_version/include",
    // your macro
    "-DMACRO=value",
  ],
```

**Comment by canfoderiskii** [comment]
@niosus Hi, thanks for the timely reply. I searched the documentation of clang, but I did not find anything about the command line argument "-D". Also can't find it in the output of `clang --help`.

I'm just so curious, am I missing something? or am I reading the documentation in a wrong way?

**Comment by niosus** [comment]
Yeah, it's not showing up but works. Clang is built to be compatible with gcc.
I've tested this with a small test:
```cpp
#include <stdio.h>
int main(int argc, char const *argv[]) {
  #ifdef hello
  printf("DEFINED hello");
  #endif
  return 0;
}
```
And building and running it with 
```
clang -Dhello=1 test_a.cpp
./a.out
```
This gives the expected output.

**Comment by niosus** [comment]
I will close this issue for now, but feel free to reopen if this doesn't work for you.

**Comment by canfoderiskii** [comment]
@niosus Thank you for the detailed reply.
