### ISSUE TITLE
Show tooltip with function docs

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#180]
From @jdumas
> a "tooltip" showing us the function prototype when the mouse is hovering the function would be nice. It can be achieved with the on_hover API introduced in build 3124.

**Comment by niosus** [comment]
I probably won't have much time in the coming month to implement this. PRs welcome.

**Comment by simia** [comment]
I've tried doing something similar (displaying variable type on hover). It interferes with sublime "Goto" popup. It might be better option to add shortcut/command to display such an information rather then using on_hover. I plan to spend few days next week to work on some enhancements so maybe I'll look more into this.

**Comment by niosus** [comment]
Very welcome :) I know that Anaconda does it in two ways:
- you can enable showing the description of a function upon completion
- you can call it from a submenu with a mouse

Additionaly, a shortcut seems to be appropriate. I don't know if `on_hover` is a good idea as it would trigger too often (not sure???).

**Comment by jdumas** [comment]
I don't think `on_hover` would trigger too often. If you show the tooltip with a function prototype only when the mouse hovers the function + when the carret is currently on the function as well. At least consider making the apparition delay a setting, e.g. in CLion function prototypes are popping up all the time and this has annoyed the hell out of me.

**Comment by niosus** [comment]
@jdumas I'm sorry, I am missing your point. Are you for `on_hover` or against? Or is it about the delay? I am confused :)

**Comment by jdumas** [comment]
I am for `on_hover`! As long as we can configure its delay/disable it if we find it annoying =)

**Comment by simia** [comment]
Hi Guys,
I've started playing with this today. I've got on_hover displaying declaration of function/member.
What do you think about this? This hides popup with sublime default "goto definition" so it's not perfect.
I'll work tomorrow on adding command to display this instead but that will probably require some architecture rework.

![screenshot from 2016-12-19 16-07-58](https://cloud.githubusercontent.com/assets/7147203/21319546/8e35b7c6-c605-11e6-8199-fa76b3aa3611.png)
![screenshot from 2016-12-19 16-08-06](https://cloud.githubusercontent.com/assets/7147203/21319547/8e3af1be-c605-11e6-9d71-f815dcab94b8.png)
![screenshot from 2016-12-19 16-08-11](https://cloud.githubusercontent.com/assets/7147203/21319548/8e3bd886-c605-11e6-99fe-b194b5b928cb.png)
![screenshot from 2016-12-19 16-08-20](https://cloud.githubusercontent.com/assets/7147203/21319549/8e3be510-c605-11e6-92f1-3416fde2d1f9.png)

**Comment by niosus** [comment]
Overall nice. At least I like this one. Also, documentation would be also cool to show with some setting enabled.

**Comment by simia** [comment]
By documentation you mean doxygen etc. comments? That shouldn't be a problem.

**Comment by niosus** [comment]
Yep, exactly. Actually, I think I would love an option for using your popups *instead* the sublime ones as I find those quite useless, so please don't completely remove this. It is not a bug, it's a feature :)

**Comment by simia** [comment]
Yeah. I was also thinking about replacing sublime autocomplete list with custom made popup but that's a different story :)

**Comment by SpeCter** [comment]
Would this make it possible to show values of lets say definitions?Right now Sublime Text only shows where defines are located but it would be nice if the value(or possible values) are shown in the tooltip as well.

**Comment by simia** [comment]
Yes it's possible... but:
While I understand that it's better to be able to navigate to a definition I don't see a good solution for now. I am not a big fan of approach: "find header file and then go to corresponding cpp file", as it wouldn't work on most projects that I work on. 
So I'll aim for go to declaration in first step and then we'll see :)

**Comment by simia** [comment]
What do you mean by "value of definition"? I understand it for a variable but for function? Would you expect function body?

**Comment by SpeCter** [comment]
Lets say you have `#define Foo 1` somewhere in a header file. And now I have another file which has something like `#ifdef Foo etc.`. Now if I hover over Foo I would like to see `Foo = 1` in a Tooltip with every (possible) define.
It doesn't have anything to do with functions, but I was hoping that whatever is used here could be used for this as well.

**Comment by simia** [comment]
Ah sorry I misunderstood. I had a quick look and I think it's completely possible to have this.
