### ISSUE TITLE
Phantom for errors

### ISSUE THREAD

**Issue by simia** [niosus/EasyClangComplete#182]
Hi,
What do you think about adding option to display compilation errors of TU as phantoms instead of popup on row click?

**Comment by niosus** [comment]
Yeah, I was thinking about it for a while. I think this is a good idea. this way we will be consistent with sublime text.

**Comment by simia** [comment]
No worries you are not alone :)

**Comment by niosus** [comment]
If you will implement this, I am more than willing to provide my help. :) Just open a work in progress PR and we can chat about it there. And thanks for contributing! :+1:

**Comment by niosus** [comment]
Closing this with #185
