### ISSUE TITLE
AttributeError: no 'settings_manager'

### ISSUE THREAD

**Issue by mvoidex** [niosus/EasyClangComplete#186]
I get this on any action:

```
File "C:\Users\voidex\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 135, in on_activated_async
    settings = self.settings_manager.settings_for_view(view)
AttributeError: 'EasyClangComplete' object has no attribute 'settings_manager'
```

Sublime Text 3, Windows x64

**Comment by niosus** [comment]
Does it still happen after you restart sublime text? This looks very strange.
Can you tell me what exactly you are doing before this happens?

**Comment by mvoidex** [comment]
Thanks for fast response. I've reinstalled it one more time and error is gone. I've also cleaned up my settings (as long as they they contained some strange settings, maybe for olrder version of plugin).

**Comment by bangnoise** [comment]
Just to note this also happened for me immediately after installation, and likewise hasn't been an issue since restarting. Sublime Text 3, Ubuntu, EasyClangComplete 3.3.2. It was a clean installation, so no existing settings.
