### ISSUE TITLE
error while compiling: Error parsing translation unit

### ISSUE THREAD

**Issue by fuzzyBatman** [niosus/EasyClangComplete#192]
This shows up only on Windows, anytime I save the file or activate the current buffer. I've tried it on a running Linux system and it works fine.

```
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
ERROR:EasyClangComplete.plugin.completion.lib_complete: error while compiling: Error parsing translation unit.
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 137, in on_activated_async
    self.view_config_manager.load_for_view(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 344, in load_for_view
    config = ViewConfig(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 66, in __init__
    self.completer.update(view, settings.errors_on_save)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\lib_complete.py", line 213, in update
    self.tu.reparse()
AttributeError: 'NoneType' object has no attribute 'reparse'
```

**Comment by niosus** [comment]
There seems to be a problem before this somewhere. Can you enable `verbose` and copy full log from the moment you start sublime text to the moment it crashes?

**Comment by fuzzyBatman** [comment]
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Satyajith/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Satyajith/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Satyajith/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.135842
startup time: 0.151842
first paint time: 0.166842
first paint time: 0.166842
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin C++NamespaceTool.C++NamespaceTool
reloading plugin Clang Format.clang_format
reloading plugin DocBlockr.jsdocs
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_gutter_jump_to_changes
reloading plugin GitGutter.git_gutter_popup
reloading plugin GitGutter.git_gutter_settings
reloading plugin GitGutter.git_gutter_show_diff
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.promise
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-clang.linter
SublimeLinter: clang linter loaded 
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin Terminal.Terminal
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: clang activated: C:\Program Files\LLVM\bin\clang.exe 
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  autocomplete_all           <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  c_flags                    <-- '['-std=c11']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  clang_binary               <-- 'clang++'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  common_flags               <-- '['C:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include', 'C:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include\\C++', 'C:\\Program Files\\LLVM\\lib\\clang\\$clang_version\\include']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  cpp_flags                  <-- '['-std=c++11']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  errors_on_save             <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  flags_sources              <-- '[{'file': 'CMakeLists.txt'}, {'file': 'compile_commands.json'}, {'file': '.clang_complete'}]'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  hide_default_completions   <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  include_file_folder        <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  include_file_parent_folder <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  max_cache_age              <-- '00:30:00'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  triggers                   <-- '['.', '->', '::']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  use_libclang               <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  verbose                    <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 29
DEBUG:EasyClangComplete.plugin.settings.settings_manager: no settings for view 29. Reinitializing.
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Overriding settings by project ones if needed:
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Valid prefixes: ['ecc_', 'easy_clang_complete_']
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 3.9.0
DEBUG:EasyClangComplete.plugin.settings.settings_storage: populating common_flags with current variables.
DEBUG:EasyClangComplete.plugin.settings.settings_storage: populated 'C:\Program Files\LLVM\lib\clang\$clang_version\include' to 'C:\Program Files\LLVM\lib\clang\3.9.0\include'
DEBUG:EasyClangComplete.plugin.settings.settings_manager: settings initialized for view: 29
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.view_config: generate new config for path: 29
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
DEBUG:EasyClangComplete.plugin.completion.lib_complete: using bundled cindex: EasyClangComplete.clang.cindex39
DEBUG:EasyClangComplete.clang.utils: platform: ('64bit', 'WindowsPE')
DEBUG:EasyClangComplete.clang.utils: python version: 3.3.6
INFO:EasyClangComplete.clang.utils: we are on 'Windows'
INFO:EasyClangComplete.clang.utils: searching for: 'libclang.dll'
INFO:EasyClangComplete.clang.utils: libclang search output = 'C:\Program Files\LLVM\bin\'
DEBUG:EasyClangComplete.clang.utils: real output: C:\Program Files\LLVM\bin\
DEBUG:EasyClangComplete.clang.utils: architecture: ('64bit', 'WindowsPE')
INFO:EasyClangComplete.clang.utils: found libclang dir: 'C:\Program Files\LLVM\bin'
INFO:EasyClangComplete.clang.utils: found library file: 'libclang.dll'
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[get]: for file C:\Users\Satyajith\Documents\github\algorithms\sorting\bucket-sort.cpp
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[cached]: 'None'
DEBUG:EasyClangComplete.plugin.tools: searching 'CMakeLists.txt' from 'C:\Users\Satyajith\Documents\github\algorithms\sorting' to 'C:\\Users\\Satyajith\\Documents\\github\\algorithms'
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[current]: 'None'
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[generate new db]
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[get]: for file c:\users\satyajith\documents\github\algorithms\sorting\bucket-sort
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[cached]: 'None'
DEBUG:EasyClangComplete.plugin.tools: searching 'compile_commands.json' from 'C:\Users\Satyajith\Documents\github\algorithms\sorting' to 'C:\\Users\\Satyajith\\Documents\\github\\algorithms'
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[current]: 'None'
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[load new]
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[no new]: return None
DEBUG:EasyClangComplete.plugin.flags_sources.flags_file: [clang_complete_file]:[get]: for file C:\Users\Satyajith\Documents\github\algorithms\sorting\bucket-sort.cpp
DEBUG:EasyClangComplete.plugin.flags_sources.flags_file: [clang_complete_file]:[cached]: 'None'
DEBUG:EasyClangComplete.plugin.tools: searching '.clang_complete' from 'C:\Users\Satyajith\Documents\github\algorithms\sorting' to 'C:\\Users\\Satyajith\\Documents\\github\\algorithms'
DEBUG:EasyClangComplete.plugin.flags_sources.flags_file: [clang_complete_file]:[current]: 'None'
DEBUG:EasyClangComplete.plugin.completion.lib_complete: view is 29
DEBUG:EasyClangComplete.plugin.completion.lib_complete: translation unit does not exist. Creating.
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.lib_complete: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', 'C:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include', 'C:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include\\C++', 'C:\\Program Files\\LLVM\\lib\\clang\\3.9.0\\include', '-IC:\\Users\\Satyajith\\Documents\\github\\algorithms\\sorting', '-IC:\\Users\\Satyajith\\Documents\\github\\algorithms']
DEBUG:EasyClangComplete.plugin.completion.lib_complete: compilation started for view id: 29
ERROR:EasyClangComplete.plugin.completion.lib_complete: error while compiling: Error parsing translation unit.
DEBUG:EasyClangComplete.plugin.completion.lib_complete: reparsing translation_unit for view 29
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 55, in plugin_loaded
    handle_plugin_loaded_function()
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 113, in on_plugin_loaded
    self.on_activated_async(sublime.active_window().active_view())
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 137, in on_activated_async
    self.view_config_manager.load_for_view(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 344, in load_for_view
    config = ViewConfig(view, settings)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 66, in __init__
    self.completer.update(view, settings.errors_on_save)
  File "C:\Users\Satyajith\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\lib_complete.py", line 213, in update
    self.tu.reparse()
AttributeError: 'NoneType' object has no attribute 'reparse'

**Comment by niosus** [comment]
Ok, so the reason is that your flags are wrong.  Consider this line.
```
DEBUG:EasyClangComplete.plugin.completion.lib_complete: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', 'C:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include', 'C:\\TDM-GCC-64\\lib\\gcc\\x86_64-w64-mingw32\\5.1.0\\include\\C++', 'C:\\Program Files\\LLVM\\lib\\clang\\3.9.0\\include', '-IC:\\Users\\Satyajith\\Documents\\github\\algorithms\\sorting', '-IC:\\Users\\Satyajith\\Documents\\github\\algorithms']
```

There is a number of includes that have to start with `-I` like the last two flags, but start with `C:\\`. Change them to `-IC:\\` and the problem should be gone.

But I agree, that the error message could be better. I will target this as soon as I have time.

**Comment by fuzzyBatman** [comment]
damn! I can't believe I missed that. Thanks a lot :)

**Comment by niosus** [comment]
Don't worry. Good software should be able to tell you there is something wrong BEFORE you encounter a cryptic error. I am going to target the usability at some point soon probably. I want this plugin to be as failsafe as possible.
