### ISSUE TITLE
MSYS2 libclang.dll missing

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#194]
As reported by @DJviolin:
> I found the following files in these locations:
> ```
> C:\msys64\mingw64\lib\libclang.a
> C:\msys64\mingw64\lib\libclang.dll.a
> ```
> At C:\msys64\mingw64\bin\ location libclang.dll file is not presented in MSYS2.

**Comment by niosus** [comment]
I will ask you to change this [line](https://github.com/niosus/EasyClangComplete/blob/master/clang/utils.py#L29) to read like:
```
windows_suffixes = ['.dll', '.lib', '.a']
```

**Comment by DJviolin** [comment]
Just to clear the package versions in use, these are installed under `MSYS2` with `pacman` package manager. All of them are the latest available `clang` packages that you can install within `MSYS2`:

```sh
mingw64/mingw-w64-x86_64-clang 3.9.0-2 [installed]
    C language family frontend for LLVM (mingw-w64)
mingw64/mingw-w64-x86_64-clang-analyzer 3.9.0-2 [installed]
    A source code analysis framework (mingw-w64)
mingw64/mingw-w64-x86_64-clang-tools-extra 3.9.0-2 [installed]
    Extra tools built using Clang's tooling APIs (mingw-w64)
```

**Comment by DJviolin** [comment]
I changed the line to this one:

```py
windows_suffixes = ['.dll', '.lib', '.a']
```

But it's not enough, because `EasyClangComplete` still looking at `C:\msys64\mingw64\bin\` location for this file, but actually is presented in `C:\msys64\mingw64\lib\` folder (which I added to the PATH too). Maybe an option to set `libclang`'s location in `EasyClangComplete.sublime-settings - User`?

**Comment by DJviolin** [comment]
Copying `libclang.a` and `libclang.dll.a` into `C:\msys64\mingw64\bin\` also not solving the issue (maybe missing dependencies this way?). It gives me the following error message after starting Sublime Text 3:

![vagolap02](https://cloud.githubusercontent.com/assets/5021728/21963343/6fbecb18-db39-11e6-9795-ef0b1add0792.png)

**Comment by DJviolin** [comment]
Looks like I found the solution. In `C:\msys64\mingw64\bin` folder there is a file named `clang.dll` next to `clang.exe`. I renamed this file to `libclang.dll` and suddenly it's working:

```sh
INFO:EasyClangComplete.clang.utils: searching for: 'libclang.dll'
INFO:EasyClangComplete.clang.utils: libclang search output = 'C:\msys64\mingw64\bin\'
INFO:EasyClangComplete.clang.utils: found libclang dir: 'C:\msys64\mingw64\bin'
INFO:EasyClangComplete.clang.utils: found library file: 'libclang.dll'
```

I think renaming this file not the best practice (no you have a copy of the same file, one is used by clang and the other is used by EasyClangComplete), so it would be nice to have an option to set this .dll's location and filename, or better, if it's detecting msys, automatically search this file.

**Comment by DJviolin** [comment]
In [utils.py](https://github.com/niosus/EasyClangComplete/blob/master/clang/utils.py) at line 82:

```py
#file = "libclang{}".format(suffix)
file = "clang{}".format(suffix)
```

This is a monkey patch for `MSYS2`, dirty, non-future proof.

**Comment by niosus** [comment]
Ok, I will think how to include it nicely in the coming days. Thanks!

**Comment by niosus** [comment]
I have introduced the fix, but haven't really tested it. Please try this out and reopen in case this is not fixed.

**Comment by DJviolin** [comment]
Thank You! It's working:

```sh
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 3.9.0
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
WARNING:EasyClangComplete.clang.utils: clang could not find 'libclang.dll'
INFO:EasyClangComplete.clang.utils: found libclang library file: 'C:\msys64\mingw64\bin\clang.dll'
```

**Comment by niosus** [comment]
Great! Happy to hear that and thanks for the hints. I will introduce it in a new version some time today.
