### ISSUE TITLE
Picking up wrong project base path

### ISSUE THREAD

**Issue by smfelsher** [niosus/EasyClangComplete#201]
Platform: Ubuntu 16.04 64-bit LTS, clang 3.8.0, ST3

I have a source project with multiple levels of hierarchy:
```
isi-refactor/
   -apps.sublime-project
   apps/
         -> isi2/
               -> src/
         -> debug/
               -> src/
   tests/
         -> cpputest/
         -> mocks/
         -> module_test/
               - module_test.sublime-project
               ->SerialPort/
               ->AnotherModule/
```

I am putting some project-specific EasyClangComplete settings in the **module_test.sublime-project** file:
```
"settings":
   {
      "easy_clang_complete_common_flags":
      [
         "-I/usr/include",
         "-I/usr/lib/clang/$clang_version/include",
         "-I$project_base_path/../../apps/isi2/src",
         "-I$project_base_path/../cpputest/include"
      ],
}
```
However, EasyClangComplete is populating with the wrong project base:
```
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  common_flags               <-- '['-I/usr/include', '-I/usr/lib/clang/$clang_version/include', '-I$project_base_path/../../apps/isi2/src', '-I$project_base_path/../cpputest/include']'
...
DEBUG:EasyClangComplete.plugin.settings.settings_storage: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/3.8.0/include'
DEBUG:EasyClangComplete.plugin.settings.settings_storage: populated '-I$project_base_path/../../apps/isi2/src' to '-I/home/developer/sandbox/isi-refactor/../../apps/isi2/src'
DEBUG:EasyClangComplete.plugin.settings.settings_storage: populated '-I$project_base_path/../cpputest/include' to '-I/home/developer/sandbox/isi-refactor/../cpputest/include'
```
It appears that EasyClangComplete is picking up on _apps.sublime-project_ instead of **module_test.sublime-project**, which is where the EasyClangComplete customization is defined.

**Comment by smfelsher** [comment]
PS: I just deleted the apps.sublime-project and the population did not change, so it must be failing on something else.

**Comment by smfelsher** [comment]
Another bit of information. My module_test.sublime-project "folders" settings references the top-level. Maybe this is influencing the population?

```
   "folders":
   [
      {
         // "name": "Top-level",
         "path": "../../",
         "folder_exclude_patterns": ["*"],
         "file_include_patterns": ["Makefile", "common.mk"]
      },
      {
         // "name": "Prodcution Code",
         "path": "../../apps/isi2/src",
      },
      {
         // "name": "Module Tests",
         "path": "."
      },
      {
         // "name": "Mocks",
         "path": "../mocks"
      },
      {
         // "name": "Framework",
         "path": "../cpputest",
         "folder_exclude_patterns": [".settings"]
      },
   ],
```

**Comment by smfelsher** [comment]
OK, moving the "Module Tests" folders setting to the top of the list seems to make things work.

**Comment by niosus** [comment]
I guess instead of `"-I$project_base_path/../../apps/isi2/src",` you actually wanted smth like this: `"-I$project_base_path/apps/isi2/src",`

**Comment by smfelsher** [comment]
Yes, that would be valid with my original "folders" settings, but why is the population being influenced by how I have my folders settings listed?

**Comment by niosus** [comment]
Ah, sorry, misunderstood the question I guess. I don't really know by which mechanism sublime text detects the root of the project. I never actually changed those settings, so I will have to look into this during the weekend. For now I just assumed that whatever project is opened as active is the one, that sublime text will use to populate the base path.

**Comment by smfelsher** [comment]
Yes, that was my assumption as well and is why I was forming my absolute paths that way. Thank you very much for your time, and I really love the tool!

**Comment by niosus** [comment]
So. Can you formulate a question that I need to answer here? I feel it is still vague. When I have a question to answer, I will be able to look into it during the weekend :) And thanks for the kind words. Means a lot to me. Consider telling more people about it if you like it or support it otherwise :)

**Comment by smfelsher** [comment]
Not sure how to word one precisely. 

Now that we've figured out a "work-around", I'll just take that into consideration. You can close this issue and I will reopen another one if I figure out a more precise question to ask.

I am also having some issues with the CscopeSublime plug-in that may cause me to rethink my projects, so my EasyClangComplete problem may become a non-issue.

Thanks again.

**Comment by niosus** [comment]
Sure! Feel free to come back should something stop working again :laughing:
