### ISSUE TITLE
Logging conflicts with other plugins that use logging module.

### ISSUE THREAD

**Issue by drammelt** [niosus/EasyClangComplete#205]
No logging is working apart from ERROR/WARNING messages. No INFO or DEBUG messages are logged to the console.
Setting the verbose flag does not change the output, these are my settings. 

```
{
	"verbose" : true,
	"errors_on_save" : false,
    "flags_sources": [
    	{"file": "compile_commands.json"},
    	{"file": "CMakeLists.txt"},
    	{"file": ".clang_complete"},
    ],
  	"common_flags" : [
			"-I/Library/Frameworks/SDL2.framework/Headers",
			"-I/Library/Frameworks/SDL2_ttf.framework/Headers",
			"-I/Library/Frameworks/SDL2_image.framework/Headers",
			"-I/Library/Frameworks/SDL2_mixer.framework/Headers",
			"-I/Library/Frameworks/SDL2_net.framework/Headers",
	],
}
```
I had to change the flags_sources since I was getting ERROR about CMAKE not creating the database (but I can do it manually just fine). Which was when I tried to enable the verbose setting which did nothing. So. I checked the python code in ECC and it looks like it should output INFO message even when verbose is false.

Removing ECC and my settings and then reinstalling does not help. This is the entire output from the plugin after loading a C file with default settings and fresh plugin.

```
[2017-02-07 15:51:04,158 - WARNING  - EasyClangComplete.plugin.tools]  OSX version 8.0 reported. Reducing it to 3.8. Info: {'platform': 'Darwin'}
[2017-02-07 15:51:04,367 - ERROR    - EasyClangComplete.plugin.flags_sources.cmake_file]  cmake has finished, but no compilation database.
```

Switching back to my settings above just removes the ERROR message, there is still no other logging from ECC.

I also tried forcing the log level for the logging.disable(level=logging.NOTSET) which did nothing either.

Last thing to note, this is an entirely fresh install of sublime text 3 on a new computer.

Sublime Text 3: build 3126
EasyClangComplete: 3.3.2
OSX: 10.12.3
Apple LLVM version 8.0.0 (clang-800.0.42.1)

**Comment by drammelt** [comment]
Ok if I wipe my "~/Library/Application Support/Sublime Text 3" dir and only install Easy Clang complete from package manager it works fine.

I must assume then that some other plugin is interfering somehow?

**Comment by drammelt** [comment]
Plugin that breaks EasyClangComplete logging...

SublimeGit
https://github.com/SublimeGit/SublimeGit

As soon as I uninstall this plugin the logging works fine.

**Comment by niosus** [comment]
I can suggest you GitSavvy as a replacement :) I will have a look on what can cause this issue in the meantime. Thanks.

**Comment by niosus** [comment]
I had a brief look into that plugin and the reason we interfere is this [line](https://github.com/SublimeGit/SublimeGit/blob/master/SublimeGit.py#L8). It configures logging globally and we do it the same way in the plugin. I will think of an alternative for us as for now the only one I see is to configure every logger on its own, which is a hassle in the long run as we have to remember about it for every new class. I will think how to solve it best.
