### ISSUE TITLE
Allow to configure search path for libclang.so

### ISSUE THREAD

**Issue by mhoeher** [niosus/EasyClangComplete#206]
I am using CentOS 7. This distribution provides a package containing libclang.so (via EPEL), however, the library gets installed into `/usr/lib64/llvm/` by default, where EasyClangComplete does not find it out of the box.

I could fix this by adding a symlink to the file in `/usr/lib64`. However, this means manipulating system directories and there are use cases, where a user is not able to so. Hence, it would be nice if there would be an option that enables us to tell the plugin where to search for libclang.

Thanks for considering :-)

PS: I already tried setting LD_LIBRARY_PATH before starting ST as well as [this plugin](https://packagecontrol.io/packages/LD%20library%20Path), however, both did not help :-(

**Comment by niosus** [comment]
This should be possible, however, it is strange, that this happens as I get the library path from `clang -print-file-name=""` call and it should find libclang wherever it is. I wonder why this does not happen.

**Comment by mhoeher** [comment]
That commands yields the following path on my system: `/usr/bin/../lib/clang/3.4.2`. This directory in turn contains two sub-directories `lib` and `include`. Here are the contents of the former one:

```
libclang_rt.asan-x86_64.a   libclang_rt.full-x86_64.a  libclang_rt.msan-x86_64.a     libclang_rt.san-x86_64.a   libclang_rt.ubsan_cxx-x86_64.a
libclang_rt.dfsan-x86_64.a  libclang_rt.lsan-x86_64.a  libclang_rt.profile-x86_64.a  libclang_rt.tsan-x86_64.a  libclang_rt.ubsan-x86_64.a
```

No trace of libclang.so there :( Do you need some more information to understand that issue better?

**Comment by niosus** [comment]
Really strange. I wonder what the suffixes mean. Also why are these libraries static? I have to this point have only seen dynamic clang libraries. I will think what to make out of this. Anyway, adding a parameter to settings would fix this of course, but I feel that we are scratching a bigger issue here.

**Comment by mhoeher** [comment]
I agree, probably this is somehow specific to the RHEL/EPEL packaging of clang. I will check my setup at home (there I am running Fedora) this evening if it uses a similar approach or behaves more like other distributions. Will update you on my findings.

**Comment by niosus** [comment]
Thanks! And thanks for reporting.

**Comment by mhoeher** [comment]
Okay, just checked: On Fedora, libclang.so is found in `/usr/lib64`. However, using `clang` to obtain the path I get the following:

```
clang -print-file-name=""
/usr/bin/../lib64/clang/3.8.1

ls /usr/bin/../lib64/clang/3.8.1/
asan_blacklist.txt  cfi_blacklist.txt  dfsan_abilist.txt  include  lib  msan_blacklist.txt

ls /usr/bin/../lib64/clang/3.8.1/lib/
libclang_rt.asan_cxx-x86_64.a       libclang_rt.cfi-x86_64.a            libclang_rt.msan-x86_64.a           libclang_rt.ubsan_standalone_cxx-x86_64.a
libclang_rt.asan_cxx-x86_64.a.syms  libclang_rt.dd-x86_64.a             libclang_rt.msan-x86_64.a.syms      libclang_rt.ubsan_standalone_cxx-x86_64.a.syms
libclang_rt.asan-preinit-x86_64.a   libclang_rt.dfsan-x86_64.a          libclang_rt.profile-x86_64.a        libclang_rt.ubsan_standalone-x86_64.a
libclang_rt.asan-x86_64.a           libclang_rt.dfsan-x86_64.a.syms     libclang_rt.safestack-x86_64.a      libclang_rt.ubsan_standalone-x86_64.a.syms
libclang_rt.asan-x86_64.a.syms      libclang_rt.dyndd-x86_64.so         libclang_rt.tsan_cxx-x86_64.a       linux
libclang_rt.asan-x86_64.so          libclang_rt.lsan-x86_64.a           libclang_rt.tsan_cxx-x86_64.a.syms
libclang_rt.builtins-x86_64.a       libclang_rt.msan_cxx-x86_64.a       libclang_rt.tsan-x86_64.a
libclang_rt.cfi_diag-x86_64.a       libclang_rt.msan_cxx-x86_64.a.syms  libclang_rt.tsan-x86_64.a.syms
```

**Comment by niosus** [comment]
So, on Fedora, does the plugin work? Also, I lied to you before :) Sorry. On Linux it runs this command to find the proper libclang: `clang -print-file-name=libclang.so.1`. (or a version without the `.1`). What does this one say on Fedora and on CentOS?

**Comment by mhoeher** [comment]
Yes, on Fedora it works as expected.

On CentOS the command reports the following:

```
clang -print-file-name=libclang.so.1
libclang.so.1

clang -print-file-name=libclang.so
libclang.so
```

After creating a symlink to libclang in /usr/lib64, it produces the following output:

```
clang -print-file-name=libclang.so.1
libclang.so.1

clang -print-file-name=libclang.so
/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libclang.so
```

Which looks strange but in fact is the correct path:

```
file /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libclang.so                                                                                                                                                                            
/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libclang.so: symbolic link to `llvm/libclang.so'
```

For Fedora, I'll test it this evening when I'm back home.

**Comment by niosus** [comment]
Thanks! So it seems that it's clang's fault that it does not search in `lib64` folder. So I guess there is no better fix than to actually add a setting for the folder to give the plugin a hint on where to search for libclang if clang fails to provide such details.

**Comment by mhoeher** [comment]
Just for the sake of completeness, here's the output of clang on Fedora:

```
clang -print-file-name=libclang.so
/usr/bin/../lib/gcc/x86_64-redhat-linux/6.3.1/../../../../lib64/libclang.so
```

Which is the expected output since on Fedora the library can be found where it actually shall be. Guess the issue in CentOS is due to the special packaging of EPEL.

Anyway, thanks for considering making the search path configurable! This will definitely benefit those who cannot simply hack their system folders. ;-)

**Comment by niosus** [comment]
Yeah, it shouldn't be a big change. But it probably won't happen fast. There is a deadline approaching. :)

**Comment by carlos-stellar** [comment]
On my system, it does not print a path for libclang:

[carlos@dhcp94 ~]$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 
[carlos@dhcp94 ~]$ clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
[carlos@dhcp94 ~]$ clang -print-file-name=libclang.so
libclang.so
