### ISSUE TITLE
Keyboard command as trigger

### ISSUE THREAD

**Issue by Pehoh** [niosus/EasyClangComplete#208]
Hello,
My completion works fine for std and structs but when I type a function already defined in a *.h file, it is not autocompleted. I have to set `  "autocomplete_all" : true,` to have propositions of functions.

I would like to know if we can use a keyboard command ( such Ctrl+Space) to trigger the autocompletion_all when I want to.

Thanks for the help.

**Comment by niosus** [comment]
We can, just not <kbd>Ctrl</kbd>+<kbd>Space</kbd>. It depends on the system and on Sublime Text itself. On my Linux machine it is <kbd>Alt</kbd>+<kbd>/</kbd>. It will only work, when there is a trigger (like `::` for example) before the cursor. 

There seems to be no way to know if the completion was triggered automatically or by calling the window manually, so I don't think we can do much more here.

**Comment by niosus** [comment]
You can search for `"command": "auto_complete"` in your `*.sublime-keymap` file to see which trigger there is for you.

**Comment by vanbwodonk** [comment]
@niosus 
I Already did <kbd>ALT</kbd>+<kbd>/</kbd> but sublime say "No available completion". I need this keybind too. 
I used sublime to ARM embedded in 'C', is rarely trigger with this `[ ".", "->", "::"]`.

**Comment by niosus** [comment]
I believe, you can now easily have this functionality by changing `[ ".", "->", "::"]` to `[ ".", "->", "::", " "]` in the plugin settings. We may additionally need to modify the sublime triggers for that, but that is a different story.
