### ISSUE TITLE
Plugin is not using the include directories provided in .clang-complete

### ISSUE THREAD

**Issue by cpagravel** [niosus/EasyClangComplete#211]
I recently made a fresh Ubuntu 14.04 install and after following steps which I previously followed to get Easy Clang working, I find that the plugin is not using my include directory. Is there an easy way to determine if the locations in my .clang-complete file are being checked?

I notice that Sublime is scanning only a handful of folders from the directory (see console [picture).]

![1](https://cloud.githubusercontent.com/assets/9516565/23050123/604ccab8-f48e-11e6-8fe2-f829d99c94d1.png)

**Comment by cpagravel** [comment]
The behaviour is that I am not able to get any code completion, but it will detect what it thinks are errors because it hasn't processed the header files. 
![2](https://cloud.githubusercontent.com/assets/9516565/23050190/be083e58-f48e-11e6-82b7-268c2914f336.png)

**Comment by cpagravel** [comment]
Update: I am able to get this to work if I put all of my include directories in the settings file under common_flags. So it seems that the problem is strictly that the .clang-complete file is either not being found or not being read. 


![3](https://cloud.githubusercontent.com/assets/9516565/23052033/f0df97b0-f49b-11e6-8ac6-fb279d5649a2.png)

**Comment by simia** [comment]
I would say that there is a typo in your .clang_complete filename and you are using "-" instead of "_".
But I won't say that :(

**Comment by cpagravel** [comment]
Simia, thank you. I've been spending too much time in front of the computer I think. This is not an issue then, perhaps a feature request to prompt that the file has been found or not (like what's done for the library). Though, maybe I'm the only person that this has happened to.
