### ISSUE TITLE
Could there be a setting to disable cmake compile_commands?

### ISSUE THREAD

**Issue by assumptionsoup** [niosus/EasyClangComplete#212]
I would absolutely love to use cmake's compile_commands.json.  But I'm on windows.  And my project is compiled using Visual Studio.  (Clang and EasyClangComplete, btw, works great autocompleting on windows after you get the include paths squared away).  Cmake doesn't support compile_commands.json with visual studio generators.  For reference, cmake issues this warning on first time you try to configure against Visual Studio (but not on later attempts):
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_COMPILE_COMMANDS
```
And EasyClangComplete will subsequently complain:
```
ERROR:EasyClangComplete.plugin.flags_sources.cmake_file: cmake has finished, but no compilation database.
```
So I'd really like a flag to disable cmake compilation when I know it will *never* produce a useful result.  It's mildly irksom to see EasyClangComplete trying to compile `compile_commands.json` every few seconds (and chewing on my SSD).  I can probably make the change myself if you're open to a pull request.

**Comment by niosus** [comment]
You already have that. Just replace this [line](https://github.com/niosus/EasyClangComplete/blob/master/easy_clang_complete.sublime-project#L27) in project settings with the way you provide flags to the plugin or leave blank if you only use the `common_flags` in settings.

**Comment by assumptionsoup** [comment]
Oh, I must have missed that when I was looking through the settings last time.  Thanks!
