### ISSUE TITLE
QT macro 'SIGNAL' is not recognized

### ISSUE THREAD

**Issue by tdok** [niosus/EasyClangComplete#213]
When using QT, the macro 'SIGNAL' is not recognized and is shown as an error.  For example, the following line of code will have SIGNAL highlighted as an error but SLOT is okay:

connect(&m_buffer, SIGNAL(readyRead()), this, SLOT(readyRead()));

When hovering the mouse over SIGNAL, the following error is shown:
"no matching literal operator for call to 'operator "" __FILE__' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template"

**Comment by niosus** [comment]
It is probably something wrong with your config. It works for me. Are you using cmake as a build system? The setup with QT is not as simple as without it unfortunately.

**Comment by tdok** [comment]
Thanks niosus.  Unfortunately, I am not using cmake.  I simply added each of the top level QT include directories to the "common_flags" ("-I/usr/include/Qt", "-I/usr/include/QtCore", ...).

Do you have any pointer on how to set it up manually through the settings file?

Thanks.

**Comment by niosus** [comment]
The things you have added should be enough. But if you are using gui, then you probably need to include the dynamically generated headers.

Anyway, I have a really important deadline on Thursday, but I will look into this after that. Probably next weekend or near that. Feel free to ping me should I forget :)

**Comment by tdok** [comment]
Thanks. There's absolutely no rush on this whatsoever, so please don't worry about it.

I'll try including all of the generated files.
Thanks.

**Comment by niosus** [comment]
Sure! Sorry, that I can't be more helpful. :) If you think of a way to read the includes from some other place or build system - tell me.
