### ISSUE TITLE
Settings for objective c?

### ISSUE THREAD

**Issue by johnofcamas** [niosus/EasyClangComplete#215]
What are the settings necessary to get this to work with objective C?

**Comment by niosus** [comment]
I don't really know, but would be happy to find out. I never worked with Objective C and have no time or desire to start now. But I will be happy to add it to the readme should anyone try it out.

**Comment by niosus** [comment]
There is not a pull request that adds the support for this. I believe I will merge it pretty soon.

**Comment by niosus** [comment]
Ok, closing this with #219
