### ISSUE TITLE
Can not complete with EasyClangComplete

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#217]
EasyClangComplete 3.3.2 work very well for me, but after upgrade to 3.3.3 I've got  these errors:

```
ERROR    - EasyClangComplete.plugin.completion.lib_complete]  error: dlsym(0x7fcfa6fec5b0, clang_CXXConstructor_isConvertingConstructor): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
ERROR    - EasyClangComplete.plugin.view_config]  cannot initialize completer with libclang.
```

My English isn't very good, please don't mind.

**Comment by kjteske** [comment]
Ran into the same issue here on OS X, can provide a workaround and few more details.

**Workaround**
Edit ~/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/tools.py
Change OSX_CLANG_VERSION_DICT so nothing points to newer than 3.8:
    '8.0': '3.8',
    '8.1': '3.8',
    '8.2': '3.8'

**A few more details**
With EasyClangComplete in verbose mode, got these messages:

> WARNING:EasyClangComplete.plugin.tools: OSX version 8.0 reported. Reducing it to 3.9. Info: {'platform': 'Darwin'}
> INFO:EasyClangComplete.plugin.tools: Found clang version: 3.9
> DEBUG:EasyClangComplete.plugin.settings.settings_storage: populating common_flags with current variables.
> DEBUG:EasyClangComplete.plugin.settings.settings_storage: populated '-I$project_base_path' to '-I/Users/username/test'
> DEBUG:EasyClangComplete.plugin.settings.settings_storage: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/3.9/include'
> DEBUG:EasyClangComplete.plugin.settings.settings_manager: settings initialized for view: 65
> DEBUG:EasyClangComplete.plugin.utils.thread_pool:submitting job: job: 'update', args: ([<sublime.View object at 0x111bf1790>, <EasyClangComplete.plugin.settings.settings_storage.SettingsStorage object at 0x11266d510>])
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
> DEBUG:EasyClangComplete.plugin.view_config: generate new config for path: 65
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
> 
> INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
> DEBUG:EasyClangComplete.plugin.completion.lib_complete: using bundled cindex: EasyClangComplete.plugin.clang.cindex39
> DEBUG:EasyClangComplete.plugin.clang.utils: platform: ('64bit', '')
> DEBUG:EasyClangComplete.plugin.clang.utils: python version: 3.3.6
> DEBUG:EasyClangComplete.plugin.clang.utils: we are on 'Darwin'
> DEBUG:EasyClangComplete.plugin.clang.utils: searching for: 'libclang.dylib'
> DEBUG:EasyClangComplete.plugin.clang.utils: libclang search output = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0'
> DEBUG:EasyClangComplete.plugin.clang.utils: real output: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0
> DEBUG:EasyClangComplete.plugin.clang.utils: folder to search: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/../..
> INFO:EasyClangComplete.plugin.clang.utils: found libclang library file: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/../../libclang.dylib'
> ERROR:EasyClangComplete.plugin.completion.lib_complete: error: dlsym(0x7fc30e8e7b20, clang_CXXConstructor_isConvertingConstructor): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
> ERROR:EasyClangComplete.plugin.view_config: cannot initialize completer with libclang.
> INFO:EasyClangComplete.plugin.view_config: falling back to using clang in a subprocess.
> INFO:EasyClangComplete.plugin.view_config: init completer based on clang from cmd

$ clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ooJerryLeeoo** [comment]
Change OSX_CLANG_VERSION_DICT solved my problem!!
Thanks!!

**Comment by niosus** [comment]
Ok, this is clearly a bug in the plugin. So, the bindings from clang 3.9 are incompatible with apple-clang 8.0.0. This is really strange. I will revert it back to 3.8 in the dict then. I will reopen this issue to track it. Thanks for help!

**Comment by ooJerryLeeoo** [comment]
I've upgrade Xcode from version 8.2 to 8.3-beta, 3.9  is work very well for me now!!

$ clang++ --version
Apple LLVM version 8.1.0 (clang-802.0.35)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by niosus** [comment]
So, then I guess only 8.0.0 -> 3.8, but all the above -> 3.9, right? Will fix it either today or tomorrow.

**Comment by niosus** [comment]
Should be up in half an hour or so. Thanks again for reporting!
