### ISSUE TITLE
Add an option to change or custom the status indicator style.

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#224]
@niosus Could you please add an option to change or custom the status indicator style, because I kinda more like the old "⣾⣽⣻⢿⡿⣟⣯⣷" status indicator style.

Example:
``` json
"status_indicator_style": "ColorSublime"
```
or some thing like
``` json
"custom_status_indicator": "⣾⣽⣻⢿⡿⣟⣯⣷"
```

**Comment by niosus** [comment]
Ok, makes sense. I was undecided which one I like more. Will happen in the next days.

**Comment by niosus** [comment]
I have added an option to the settings to set the style of the indicator. I will create a release soon.
