### ISSUE TITLE
New status indicator is going kinda crazy

### ISSUE THREAD

**Issue by SDEagle** [niosus/EasyClangComplete#225]
The new status indicator seems to be going a bit crazy on my system... This is pretty distracting and as far as I can tell it doesn't stop.

![ecc_going_crazy](https://cloud.githubusercontent.com/assets/867049/24033803/faf4777a-0aee-11e7-84eb-f11d6a4b0da1.gif)

This is ST3 on latest OS X

**Comment by niosus** [comment]
Oh wow. Did you just update? Try to restart sublime text if you haven't already. It seems that both indicators are there now...

**Comment by SDEagle** [comment]
I did get an update after a restart and that caused the bug, so I assuemed the state was somewhat consistent... But appearently it wasn't - restarting again fixed it...

**Comment by niosus** [comment]
Yeah, sorry for that. I should probably invest some time into making the plugin stable on update. But this is not fun and hard to do after a full day of work :) Anyway, glad it works now.
