### ISSUE TITLE
[Bug] Completions loaded from cache after file save.

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#228]
I have this problem since I installed EasyClangComplete.
Here's an example:

![problem](https://cloud.githubusercontent.com/assets/20783502/24130641/c9a30662-0e24-11e7-869c-538f32f07f4d.gif)

the weird thing is that after change `test` to `::test` the completion is work very well

![weird](https://cloud.githubusercontent.com/assets/20783502/24130646/d22b60cc-0e24-11e7-9334-a3031a262e4f.gif)

**Comment by niosus** [comment]
Ok, I know the reason. It should be easy to fix too. We cache the completions in a specific position of the document. We just need to invalidate this cache on file save.

**Comment by ooJerryLeeoo** [comment]
To make sure you understand my problem, here's Xcode version of first gif:
![2017-03-20 21_15_36](https://cloud.githubusercontent.com/assets/20783502/24101234/752f8abe-0db2-11e7-8da8-82e778b1440f.gif)

**Comment by niosus** [comment]
Yep, I totally understand the issue. I hope I will have the time to fix this during this week. It should not be too hard.

**Comment by niosus** [comment]
Ugh. It appeared to be harder than I expected. I have changed what I assumed was the error, but it seems that in case of the completion being triggered by `" "` or in case of `"autocomplete_all": true` libclang does not do a proper job at completing.

I invalidate the cache on file save just to be sure, but libclang generates the completions with old function nevertheless. The strange part is that it generates correct completions if I trigger them with `"."` or `"->"`.

I have no idea why this happens for now... :confused:

**Comment by niosus** [comment]
The only way I see to fix this is to invalidate the whole translation unit, forcing it to be parsed as opposed to being reparsed only. The problem with this is that it takes twice the time and as it only happens when there is no trigger before the input, I would just leave this as it is now.

**Comment by ooJerryLeeoo** [comment]
So the problem fixed??

**Comment by niosus** [comment]
Nope. Unfortunetely not. But it is unfixable at this point as it comes from libclang itself and not from the plugin.

**Comment by ooJerryLeeoo** [comment]
But why some IDE like `Xcode` doesn't have this problem ?

**Comment by niosus** [comment]
I don't really know. I should probably keep this issue open though. 

What I am sure of is that the completions come from libclang itself. Just the way they do when I complete with a dot, but they don't get updated properly.

**Comment by ooJerryLeeoo** [comment]
[autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) from atom doesn't have this problem, maybe you can take a look.

**Comment by ooJerryLeeoo** [comment]
![2017-03-21 09_11_23](https://cloud.githubusercontent.com/assets/20783502/24128369/63564738-0e16-11e7-822d-969fb15d55df.gif)

**Comment by ooJerryLeeoo** [comment]
I have an idea, maybe you can just add an command to tell `ECC` check every function, if have any function modified, then reload the completion of that function.

**Comment by ooJerryLeeoo** [comment]
or reload all completion when file save.

**Comment by niosus** [comment]
I will look into the atom's plugin, thanks for reference. As for your suggestions that is essentially what I thought. I thought, that we skip interfacing with libclang at all when this happens, so I thought that reloading all completions would help. It doesn't as it is libclang that gives us the wrong completions. I have one more idea on what we can do, but I don't expect too much as it should work as it is.

**Comment by niosus** [comment]
The plugin you refer to in Atom does not use libclang. It uses clang and parses the output from it. The bug seems to be related to the upstream of libclang. I will try to create a minimal example to submit a bug report there. There is really nothing else I can do now.

**Comment by ooJerryLeeoo** [comment]
Yes.

**Comment by niosus** [comment]
Ok, will happen soon.

**Comment by ooJerryLeeoo** [comment]
So It's an alternatives, right?

**Comment by ooJerryLeeoo** [comment]
So It could be twice slower, right?

**Comment by niosus** [comment]
I will add an option that will be callable through <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> called smth like "Hard Reparse". It will essentially delete current translation unit and will recreate it. This way you will get the proper completions when completing after a space. It will take twice the time of an ordinary reparse that is currently done on file save.

**Comment by ooJerryLeeoo** [comment]
Okay, I get it.

**Comment by ooJerryLeeoo** [comment]
Here's more example:

![2017-03-21 22_47_28](https://cloud.githubusercontent.com/assets/20783502/24153072/6cfc018e-0e88-11e7-86b5-ac7a2afd6e38.gif)
![2017-03-21 22_47_03](https://cloud.githubusercontent.com/assets/20783502/24153071/6ccbfb1a-0e88-11e7-8912-18774ceefe1d.gif)
![2017-03-21 22_45_53](https://cloud.githubusercontent.com/assets/20783502/24153073/6d682d0a-0e88-11e7-8115-f8d3f12a3461.gif)

**Comment by simia** [comment]
Hmm not sure how this works performance wise but removing TU.PARSE_CACHE_COMPLETION_RESULTS  flag from initial parsing does the job.

**Comment by ooJerryLeeoo** [comment]
Wow, it work very well after removing TU.PARSE_CACHE_COMPLETION_RESULTS, thank a lot!!!!

**Comment by ooJerryLeeoo** [comment]
But, after removing `TU.PARSE_CACHE_COMPLETION_RESULTS`, `ECC` does not complete C/C++ macros, like `INT_MAX`, `NULL`, `EXIT_SUCCESS`.

**Comment by niosus** [comment]
@simia great find. It does look like a bug to me in libclang then though. It should not fetch completions from cache in this case.

**Comment by simia** [comment]
Yeah, libclang is buggy. As @ooJerryLeeoo mentioned removing caching breaks macros :D

**Comment by ooJerryLeeoo** [comment]
Is possible to fix the new `macros` problem??

**Comment by niosus** [comment]
@ooJerryLeeoo probably not unless we miss some small flag in libclang. We can only get as good as libclang gets. But the fact that Xcode can manage this hints that there is something we could be missing here.

**Comment by ooJerryLeeoo** [comment]
That, okay. at least this problem is smaller than previous problem. :D

**Comment by niosus** [comment]
Ok, we can add a setting to disable the libclang caching. the performance will drop though.

**Comment by simia** [comment]
include_macros=False option needs to be added to the tu.codeComplete() call parameter list.

**Comment by ooJerryLeeoo** [comment]
@simia Thanks a lot again!!!

**Comment by niosus** [comment]
Damn, I so want to have more time for this. I will add it and push a new version. Thanks a lot @simia

**Comment by ooJerryLeeoo** [comment]
I'm wondering when to post a new release ?

**Comment by niosus** [comment]
Sorry, no estimate when I will have the time. It will happen, but there is no proper timing on when.

**Comment by ooJerryLeeoo** [comment]
Okay, I get it.

**Comment by niosus** [comment]
Closed with 8b578bbfbe1c9d39126f053c19744c438898f6c9
Will be out in a new version in a couple of hours.

@ooJerryLeeoo please do not modify the name of the issue after me, this way I get lost in them. I have labels to mark something as a bug. Thanks.
