### ISSUE TITLE
Doesn't seem to work under Arch Linux

### ISSUE THREAD

**Issue by alberto2000** [niosus/EasyClangComplete#229]
I'm using project settings file in root of my project (openFrameworks) myProject.sublime-project

```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {  
		"ecc_use_libclang": true,
		"ecc_verbose": true,
		"ecc_common_flags": [
			"-Isrc", 
			"-I/usr/include",
			"-I/home/thinkpad2000/Code/openFrameworks/addons/**",
			"-I/home/thinkpad2000/Code/openFrameworks/libs/**"
		]
	}
}
```

But EasyClangComplete doesn't seem to read the header includes, it will always complain about files it cannot find, but they are in those folders I specified.

Is this Arch Linux specific or am I doing something wrong still?

![Errors](http://i.imgur.com/86Hb18I.png)
It says "ofMain.h file not found" although that lies in /home/thinkpad2000/Code/openFrameworks/libs/openFrameworks/app/ofMain.h so should be found as I specified that folder in settings, no?

Any help is greatly appreciated :)

**Comment by niosus** [comment]
Hm, I guess it is because of the stars in the end of the paths here `-I/home/thinkpad2000/Code/openFrameworks/libs/**`. We do not recursively read the folders.

**Comment by alberto2000** [comment]
@niosus thanks. Is there no way of recursively reading folders then? Could this be a potential new feature? It's a bit difficult to name each and every folder with the headers you need no? Sorry if I misunderstand anything, I'm quite new to C++

**Comment by niosus** [comment]
You can do pretty much anything in C++. Therefore, people generally follow some style guide to avoid misunderstandings and ambiguities. I personally prefer Google's style sheet. Here is a part on [includes](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) from it. The important part from it here is this:

> All of a project's header files should be listed as descendants of the project's source directory without use of UNIX directory shortcuts . (the current directory) or .. (the parent directory)

So you see, that following this style sheet you would avoid having includes in the way you do, i.e. `"ofMain.h"` would turn into `"app/ofMain.h"`. This way there is no need to recursively traverse the includes folder.

Generally, I would suggest to adopt a style like this as this is less error prone and disambiguates your includes. Also, if you are new to C++, I would suggest to start using CMake straight away. This makes setting up the project so much easier and you won't have to think about the includes to use this plugin.

I will close this issue for now.
