### ISSUE TITLE
Library mode support for OS X.

### ISSUE THREAD

**Issue by Ventero** [niosus/EasyClangComplete#23]
I've been looking into getting library mode working on OS X - and it actually seems to be working just fine almost out of the box!

I had to make one small change, as I'm not using the default clang/LLVM installation that ships with Xcode, but a Homebrew installation instead. The code for that can be found in https://github.com/Ventero/EasyClangComplete/commit/e79556c6d9dc9c7ba98ce22da3fbbe675d480922 - from what I can tell, that snippet should work for all clang installations on OS X - including the default Xcode installation.

After applying that change, autocompletion and error highlighting worked just fine with most clang versions tested - only 3.8 segfaults somewhere inside libclang, so I guess there's some kind of mismatch between that version of cindex.py and the native library.

If you think the commit above makes sense, feel free to apply it.

**Comment by niosus** [comment]
Oh wow! This is awesome! Thanks for the input! I will check the commit as soon as possible. From the way it sounds, it must be working. May I ask you to do a pull request? That would help me checking. Again, thanks for the contribution!

**Comment by niosus** [comment]
Thanks! I will close this issue for now and will continue discussion in the pull request if needed :) Thanks again, if only every issue were like this one :+1:
