### ISSUE TITLE
Code map?

### ISSUE THREAD

**Issue by simia** [niosus/EasyClangComplete#234]
I saw recently this: https://github.com/oleg-shilo/sublime-codemap
Would adding something similar be a benefit to ECC? It looks cool and can be potentially useful but I am not 100% sure. What are your thoughts?

**Comment by ooJerryLeeoo** [comment]
I think `goto everything` is same as `sublime-codemap`.

**Comment by niosus** [comment]
While I like the looks of it, I don't really think it belongs to this plugin. Also, while undeniably being a pretty cool feature I don't really see the benefit in this at least for myself.

**Comment by niosus** [comment]
I have decided that I will not implement this. It is hard enough to find time now to maintain everything :)

I might review some PR on this, but it is going to be a lot of work both for the one who will implement this and for me to review this, as it must not be a hassle to use.

I will close this now. If anyone creates a PR for this, we can reopen this.
