### ISSUE TITLE
Show icon in auto_complete menu like Xcode.

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#237]
Pretty cool feature to help people recognize `macros`, `function`, `keyword` and `other` with the icon.
But I don't know is it possible ?

![image](https://cloud.githubusercontent.com/assets/20783502/24320127/e6e8fdc4-1169-11e7-9571-8ecb80006116.png)

**Comment by niosus** [comment]
So, as sublime text api tells us:

> A 2-element tuple with the first element being the list format documented above, and the second element being bit flags from the following list:
> - sublime.INHIBIT_WORD_COMPLETIONS: prevent Sublime Text from showing completions based on the contents of the view
> - sublime.INHIBIT_EXPLICIT_COMPLETIONS: prevent Sublime Text from showing completions based on .sublime-completions files

So I believe this is not possible to do in sublime text.

**Comment by simia** [comment]
We could prep-end trigger with something like [F/V/pV] etc. based on token kind. 
Please have a look at the screenshot. 
![image](https://cloud.githubusercontent.com/assets/7147203/24795609/cc474dc8-1b81-11e7-8e5d-a421e4121f4b.png)

**Comment by niosus** [comment]
I like it. We can definitely add it as an option.

**Comment by niosus** [comment]
I don't think I will have the time to implement it currently. I will put it into the backlog for now. Maybe somebody will pick it up from there.
