### ISSUE TITLE
Scope is not checked when using autocomplete_all

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#239]
![2017-03-30 13_32_32](https://cloud.githubusercontent.com/assets/20783502/24489035/7cb7891a-154d-11e7-9b5e-7b36b52fc660.gif)

**Comment by niosus** [comment]
Ok, got it. We should filter by the scope in which we are. I believe this only happens when autocomplete_all is on.

**Comment by niosus** [comment]
Hmmm. I finally got the time to try this out and I cannot reproduce this. What are your settings for completion triggers?

**Comment by ooJerryLeeoo** [comment]
``` json
	"auto_complete_triggers":
	[
		{
			"characters": "",
			"selector": "source.c++ - string - comment - constant.numeric"
		},
		{
			"characters": "",
			"selector": "source.c - string - comment - constant.numeric"
		}
	]
```

**Comment by niosus** [comment]
Well, these are the ones that go with this plugin, but it seems that there are some other ones that interfere. Can you still reproduce this if ECC is the only plugin installed?

**Comment by ooJerryLeeoo** [comment]
Umm... I just realized that the problem is fixed by some unknown reason... :stuck_out_tongue_winking_eye:, I think I can close this issue now.

**Comment by niosus** [comment]
Cool. Great that it works now :)
