### ISSUE TITLE
Autocompletion is painfully slow compared to VS

### ISSUE THREAD

**Issue by mvacha** [niosus/EasyClangComplete#241]
I'm working on an R package, so my .clang_complete contains includes from R and Rcpp (maybe 200 header files) plus std lib. But every time I want autocompletion for something new (and not cached) it tooks maybe 5-10s to show up. The same project has no perf issues with Visual Studio's IntelliSense. It seems to me, that VS loads all the included header files in the beginning and then just shows the suggestions without any additional calls to the compiler, but EasyClangComplete always calls the compiler if it's not in cache (and no preloading happens after start).

**Comment by niosus** [comment]
It might be true. However, I don't have a good way of addressing this. I don't know what Visual Studio guys do to make IntelliSense that fast. As far as I know clang uses the notion of a translation unit, which is basically spawned from a source file. I don't have a good strategy on how to know before-wise which of the translation units will be used by the user and therefore should be pre-cached.

For now, I would say, that we have reached approximately the maximum speed of which this plugin is capable of. It lacks a feature here or there and has some bugs, which are my current priority. I am a single person and I code this on my spare time, so it is unrealistically to believe, that I can compete with a product like Visual Studio that has a dedicated team of engineers that have more experience in this field than I do. Originally, the plugin was written just out of the frustration, that there is nothing available to complete the code on Linux and the Windows and OSX support are just a lucky by-product of the development :)

Anyway, I do appreciate your input, but being reasonable, I don't expect I will ever have the time to make the plugin work much faster. 

Also, a more correct comparison would be with CLion as they also are CMake based and use libclang as the backend.

**Comment by niosus** [comment]
I will close this issue, but feel free to continue discussing it here if you have new input.
