### ISSUE TITLE
Show more from Doxygen comments in a hover popup

### ISSUE THREAD

**Issue by ThunderSmotch** [niosus/EasyClangComplete#244]
Is this intended behaviour? If so, can we have an option to have it show all the tags like input parameters and return tags?

**Comment by niosus** [comment]
Yes, this is the intended behavior as we are just a medium between a user and libclang. Libclang using a flag `PARSE_INCLUDE_BRIEF_COMMENTS_IN_CODE_COMPLETION` returns the brief documentation of the function. It is probably possible to show more, but it will take a lot of effort as we will need to manually parse Doxygen comments. I would like to avoid that. 

I will probably think about it for some time. Maybe I am missing something now.

**Comment by simia** [comment]
It is possible to get "raw comment" from cursor so we could add option to get more on demand. We are limited to what clang recognizes as comments, though.

**Comment by simia** [comment]
Ok... good news is that full comments are available effortlessly. Bad news is that they are not formatted anyhow so this must be done by the plugin (including stripping of comment characters). Maybe there is already a python lib that provides such functionality.

**Comment by simia** [comment]
I've noticed that "static" qualifier for methods is wrongly displayed before "Definition:".
Additionally I think that "Declaration:" would be more appropriate.
Doxygen parsing does not support "\brfief" tag and maybe support for other commands like @param etc. should be added?

**Comment by niosus** [comment]
I was thinking which one to use and went for the one used by Sublime Text. But "Declaration" makes sense.

I will fix static appearance and will add "`\brief`" tag. The intention was not to parse full Doxygen comments. The intention was not to duplicate brief description.
