### ISSUE TITLE
Show deduced type when hovering over "auto"

### ISSUE THREAD

**Issue by Pbdas** [niosus/EasyClangComplete#246]
When hovering the cursor above the `auto` keyword in variable declarations, it would be great to display (an abbreviated!) deduced type.

Would this entail a straight forward call to libclang, or am I being naiive?

**Comment by niosus** [comment]
I would expect it to be possible. Will probably look into this during the week.

I feel this should be possible. Is probably relying on [this line](https://github.com/niosus/EasyClangComplete/blob/master/plugin/completion/lib_complete.py#L270) of code.

**Comment by Pbdas** [comment]
That's great to hear! Scott Meyers actually dedicates an entire item in his famous book "Effective Modern C++" to viewing deduced types, and he explicitly mentions IDEs as a viable solution.

This would certainly contribute toward making your plugin essential for C++ programmers using sublimetext (which in my opinion it already is).

**Comment by niosus** [comment]
Thanks a lot for the kind words :) I'm really happy to hear it!

I will be 3 hours on a train on Friday and plan to check it out then.

**Comment by niosus** [comment]
Ok, that was easy :) I will release the version that supports it in a couple of hours.
