### ISSUE TITLE
Filter out operator overloads from suggestions

### ISSUE THREAD

**Issue by MattDiesel** [niosus/EasyClangComplete#247]
This doesn't seem to be listed as a specific cursor type (being a function I guess) so I don't think it's possible using the ignore_lists currently in the plugin. However, I know very little about how clang and the plugin works so I could well be mistaken.

As an alternative, it would be sufficient to blacklist function names containing non-alphanumerics.

**Comment by niosus** [comment]
I'm not sure this is a good idea. I have seen a decent amount of code that uses operators explicitly when working with, say, pointers. I don't argue this is good style, but as public members they are expected in the output from the plugin. I will leave it open for some discussion for now, but my feeling is towards not changing the current behavior.

**Comment by MattDiesel** [comment]
I implemented for myself by a regex check in lib_complete.py. I had a brief look as to how to add a setting to the package but it seems that the completion parts of the package are several steps removed from where the settings are used at the moment. It was the work of a couple of minutes to do so I'm quite happy working with that as a solution.

For me, I see completion as being more of a hint rather than a technically correct reference. Normally I only use it if I can't quite remember the name of a method.

**Comment by niosus** [comment]
I understand why that can be important, but we enter the realm of preferences. I would like the plugin to show correct reference.

**Comment by niosus** [comment]
I have though about it for some more time and I think, I will close it for now. I still want all the completions to be correct and I see no way of introducing this without causing confusion and I would really like to avoid it. Also, the time is really scarce on my side, so I probably will leave it unfixed. Sorry for inconvenience.
