### ISSUE TITLE
Formatting for autocomplete menu is white

### ISSUE THREAD

**Issue by silver008** [niosus/EasyClangComplete#250]
Hi, I noticed in your screencast showing ECC in action that your autocomplete menu is consistent with your theme (dark colors) and the highlighting is blue. I am using the Monokai theme, which is dark like your screencast. However, my autocomplete menu is white and doesn't highlight as nicely. Is there something I should do to configure this?

**Comment by niosus** [comment]
I guess you're using the color *scheme* which highlights your code as opposed to *theme* that highlights menus and everything else. If your side pane is white, then the theme is default. You can either install some theme (I recommend [Boxy](https://packagecontrol.io/packages/Boxy%20Theme)) or if you are on Sublime dev builds, you can use `Adaptive` theme.

**Comment by silver008** [comment]
got it, thanks.
