### ISSUE TITLE
Autocompletion of #include directives

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#254]
Hi there,

I was just thinking that, a cool feature that seem to be missing from EasyClangComplete, would be to have autocompletion of `#include` directives, based on the include folders enabled for a given file.

I am guessing something similar to the `\input{}` file completion offered by the [LaTeXTools](https://github.com/SublimeText/LaTeXTools/blob/master/latex_input_completions.py) plugin shouldn't would be nice to have, allowing fuzzy matching and whatnot.

**Comment by niosus** [comment]
Yeah it is being already discussed in #231

**Comment by jdumas** [comment]
Oh, my bad then. I searched open issues with "include" in the title. Haven't been thorough enough, sorry.

**Comment by niosus** [comment]
No problem, maybe we should update the name there as the work "include" should probably appear there :)
