### ISSUE TITLE
Info function window only appears sometimes

### ISSUE THREAD

**Issue by FreddieOliveira** [niosus/EasyClangComplete#256]
![bug1](https://cloud.githubusercontent.com/assets/9597536/26020538/f9e8774e-3755-11e7-8a17-e5e422c5e736.jpg)

This info window only pops up sometimes. And it only provides a link to the declaration line, but not to the implementation.

**Comment by niosus** [comment]
That is the intended behavior. We only show the declaration as this is what libclang provides. Also, your file seems to contain compile errors, so the translation unit might be wrong, which might hinder the behavior of the plugin.

Also, if you do think this is an issue, I would ask you to provide more details. When does it not show? Can you nail this down?

**Comment by niosus** [comment]
I will close this for now for the lack of activity. Please reopen if there is any new info.
