### ISSUE TITLE
Not recognizing bool type

### ISSUE THREAD

**Issue by darwinyip** [niosus/EasyClangComplete#257]
ECC highlights all `bool` declarations with "Error: Unknown type name 'bool'".
I have clang 4.0.0 installed in Ubuntu.

I have verified that code compiles under clang.

**Comment by darwinyip** [comment]
This went away after I renamed the extension from `.c` to `.cpp`.

**Comment by diggit** [comment]
What if my sources are in C? Changing extensions is just confusing workaround.

**Comment by niosus** [comment]
Everything should be working with C files as soon as syntax in the bottom right corner shows C.
