### ISSUE TITLE
No completion in if statement

### ISSUE THREAD

**Issue by rdlaner** [niosus/EasyClangComplete#259]
I ran into a strange issue where, within a member function, auto-complete correctly identifies a member variable except when in an "if" statement. See below:

Correct when not using "if" statement:
![screen shot 2017-05-14 at 10 44 19 pm](https://cloud.githubusercontent.com/assets/17415937/26044170/86fb12a2-38f7-11e7-819e-9383ca193159.png)

Failure to auto-complete member variable "m_list" when using "if" statement:
![screen shot 2017-05-14 at 10 44 50 pm](https://cloud.githubusercontent.com/assets/17415937/26044184/9eeda8a2-38f7-11e7-8d03-e418b254a275.png)

Any thoughts on why this is happening?

**Comment by niosus** [comment]
I believe the reason is that the if statement is not valid yet, so the translation unit created from an unsaved file is not really fully valid, so libclang cannot properly create the AST.

**Comment by simia** [comment]
Works perfectly fine here. Maybe configuration issue? (I have autocomplete_all=true and hide_default_completions=true)

**Comment by niosus** [comment]
@simia I think it supports what I said before. It highly depends on the code being completed and if libclang was able to create the correct tree.

**Comment by simia** [comment]
Yes :)

**Comment by niosus** [comment]
Anyway, I think I will close this for now, but we can continue discussion here if needed. @rdlaner maybe try it with `autocomplete_all` setting on as @simia has suggested?

**Comment by rdlaner** [comment]
Thanks for the feedback. I tried it with `autocomplete_all` set to true and it was able to successfully autocomplete while in the "if" statement.
One thing of note, when `autocomplete_all` was false, it didn't matter if the "if" statement was fully completed or only partially completed, it still did not auto complete.

The only other issue I'm having with this is, even though the member variable `m_list` is now autocompleting correctly, it will not autocomplete when I try to dereference the pointer:
![screen shot 2017-05-15 at 9 12 10 am](https://cloud.githubusercontent.com/assets/17415937/26067322/a82d28be-394e-11e7-9959-ceec08ad7eb0.png)

**Comment by niosus** [comment]
Ah, stupid me. The original issue is because the plugin searches for a valid trigger before the cursor and `(` is not one for now. I am unsure whether to consider it a bug or not at this time. I will reopen this will I am better decided. 

Your new issue might be because of template use. If the compiler cannot guess the type used with your list in the current translation unit, it will not autocomplete at all.

**Comment by rdlaner** [comment]
Got it, thanks @niosus!

**Comment by niosus** [comment]
Ok, just adding `"("` to triggers in user settings solves this. I have added this by default to the new version. Just make sure your old settings do not override the default ones. I will close it now.
