### ISSUE TITLE
settings_storage: no view to populate common flags from

### ISSUE THREAD

**Issue by kindow** [niosus/EasyClangComplete#261]
here is the console output while i open sublimetext :
```
DPI scale: 1
startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/boxman/.config/sublime-text-3/Packages
state path: /home/boxman/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/boxman/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.092735
startup time: 0.165788
first paint time: 0.191501
first paint time: 0.218909
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin CTags.ctags
reloading plugin CTags.ctagsplugin
reloading plugin CTags.test_ctags
reloading plugin CTags.test_ctagsplugin
reloading plugin Javatar.Javatar
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-cppcheck.linter
SublimeLinter: cppcheck linter loaded 
reloading plugin SublimeLinter-cpplint.linter
SublimeLinter: cpplint linter loaded 
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-clang.linter
SublimeLinter: clang linter loaded 
plugins loaded
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  autocomplete_all           <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  c_flags                    <-- '['-std=c11']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  clang_binary               <-- 'clang++'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  common_flags               <-- '['-I/usr/include', '-I$project_base_path/src', '-I/usr/lib/clang/$clang_version/include']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  cpp_flags                  <-- '['-std=c++11']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  use_libclang_caching       <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  flags_sources              <-- '[{'file': 'CMakeLists.txt'}, {'file': 'compile_commands.json'}, {'file': '.clang_complete'}]'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  hide_default_completions   <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  include_file_folder        <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  include_file_parent_folder <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  max_cache_age              <-- '00:30:00'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  objective_c_flags          <-- '['-std=c11']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  objective_cpp_flags        <-- '['-std=c++11']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  triggers                   <-- '['.', '->', '::', ' ', '\t', '(', '[']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  use_libclang               <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  verbose                    <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  show_type_info             <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  libclang_path              <-- '<some_path_here>'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  errors_style               <-- 'popups'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  progress_style             <-- 'Moon'
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
SublimeLinter: debug mode: off 
Javatar snippet Class.javatar loaded
Javatar snippet Enumerator.javatar loaded
Javatar snippet Interface.javatar loaded
Javatar package "Java Standard Edition 8" loaded with 4385 classes in 213 packages
reloading settings Packages/User/Javatar.sublime-settings
[Javatar] Use default Java version [JDK1.6.0u45]
reloading settings Packages/User/Javatar.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2017-05-19 13:57:00, next run at 2017-05-19 14:57:00 or after
ERROR:EasyClangComplete.plugin.settings.settings_storage: no view to populate common flags from
SublimeLinter: WARNING: clang deactivated, cannot locate 'clang' 
SublimeLinter: WARNING: cppcheck deactivated, cannot locate 'cppcheck' 
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 3.8.0
reloading settings Packages/User/Javatar.sublime-settings
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
WARNING:EasyClangComplete.plugin.clang.utils: clang could not find 'libclang-3.8.so'
WARNING:EasyClangComplete.plugin.clang.utils: clang could not find 'libclang.so'
INFO:EasyClangComplete.plugin.clang.utils: found libclang library file: '/usr/lib/x86_64-linux-gnu/libclang-3.8.so.1'
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: running command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "/Develop/SDL/sdl_core/src/3rd_party/expat-2.1.0"
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: cmake produced output: 
CMake Warning (dev) at CMakeLists.txt:41 (set):
  Cannot set "EXPAT_INCLUDE_DIRECTORY": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:44 (set):
  Cannot set "EXPAT_LIBS_DIRECTORY": current scope has no parent.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/EasyClangComplete/cmake_builds/1127efa2385dc17c797c93468a8781b8

reloading settings Packages/User/Javatar.sublime-settings
ERROR:EasyClangComplete.plugin.settings.settings_storage: no view to populate common flags from
reloading settings Packages/User/Javatar.sublime-settings
```

**Comment by kindow** [comment]
when i open a c++ source file, there would be more errors

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 279, in on_activated
    self.check_syntax(view)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 206, in check_syntax
    Linter.assign(view, reset=True)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 3.8.0
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: running command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "/Develop/SDL/sdl_core"
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 279, in on_activated
    self.check_syntax(view)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 206, in check_syntax
    Linter.assign(view, reset=True)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 3.8.0
reloading settings Packages/User/Javatar.sublime-settings
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: cmake produced output: 
-- libudev stable: 1
-- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
--  include: /usr/include
-- USB support is enabled
-- Bluetooth support is enabled
USE DHMI_PTU_PARSER
-- Found Sqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Doxygen not found. Documentation will not be generated
-- To enable documentation generation please install doxygen and graphviz packages
-- sudo apt-get install doxygen graphviz
-- To enable processing of MscGen comments please install mscgen
-- sudo apt-get install mscgen
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/EasyClangComplete/cmake_builds/323b0aff2515f2f106aba1b100f7af41

ERROR:concurrent.futures:exception calling callback for <Future at 0x7f3392c99ed0 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/home/boxman/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 367, in load_for_view
    config = ViewConfig(view, settings)
  File "/home/boxman/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 71, in __init__
    self.completer.update(view, settings)
  File "/home/boxman/.config/sublime-text-3/Packages/EasyClangComplete/plugin/completion/lib_complete.py", line 307, in update
    if self.tu.cursor.displayname != view.file_name():
AttributeError: 'NoneType' object has no attribute 'cursor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/boxman/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 254, in config_updated
    log.debug(" updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/home/boxman/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 382, in load_for_view
    e.msg)
AttributeError: 'AttributeError' object has no attribute 'msg'
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
reloading settings Packages/User/Javatar.sublime-settings
reloading settings Packages/User/Javatar.sublime-settings
reloading settings Packages/User/Javatar.sublime-settings
reloading settings Packages/User/Javatar.sublime-settings
reloading settings Packages/User/Javatar.sublime-settings

**Comment by niosus** [comment]
Ok, will have a look into this.

**Comment by niosus** [comment]
Just to make sure, is it upon installation of the plugin? Did you restart sublime text after installing the pluign?

**Comment by kindow** [comment]
hi, niosus

thanks for you answer , to answer your question i do  have restarted sublimetext .

**Comment by niosus** [comment]
Ok, I will try to have a look. Unfortunately, I have really limited amount of time because of work, but I will try.

**Comment by niosus** [comment]
Ok, so first two tracebacks: 
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 279, in on_activated
    self.check_syntax(view)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 206, in check_syntax
    Linter.assign(view, reset=True)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
```
and 
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 279, in on_activated
    self.check_syntax(view)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 206, in check_syntax
    Linter.assign(view, reset=True)
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/home/boxman/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
```
are not from my plugin. So I will ignore those.

As for the original error. Something seems to be wrong with your view. I cannot say for now what exactly, but I will release a new version today with more debug information to be able to find out more precicely what it going on.

**Comment by niosus** [comment]
@kindow if you are still on it, can you repeat what you did before and publish the results here again? I have added some more debug information now, so I might understand slightly more about the issue.

**Comment by niosus** [comment]
I have fixed a bunch of things in last revisions and will for now assume this solved. Please reopen with a new log otherwise.
