### ISSUE TITLE
The path to the flags_sources

### ISSUE THREAD

**Issue by papaDoc** [niosus/EasyClangComplete#262]
Hi,

I want to set the path for finding the compile_command.json and I was wondering if the path can be relative. If so it is relative to what ?

Thanks in advance.

papaDoc

"flags_sources": [
    {"file": "compile_commands.json", "search_in": "<YOUR_PATH>"},
  ],

**Comment by niosus** [comment]
No, it can't be implicitly relative exactly for the reasons of unclarity with respect to what. Feel free to use `~` for home directory or `$project_base_path` for path to current project.
