### ISSUE TITLE
the plugin didn't work 

### ISSUE THREAD

**Issue by yifengding** [niosus/EasyClangComplete#263]
HI,
I'm using mac 10.12.4, and sublime text 3. The EasyClangComplete didn't work after reload the sublime. I reinstalled the plugin, tried many times, still didn't work. This issue quite confused me, hope could get your help.
Thx

**Comment by niosus** [comment]
Hello, thanks for reaching out. Sorry it didn't work for you. I need more info to find out what is going on. Could you open the plugin again, change the `verbose` setting to true, restart sublime text, open any cpp file and try to complete something? Then just copy all the console output from sublime text console here. Thanks!

**Comment by yifengding** [comment]
Sorry, I removed the plugin changed another, which works well.
quite sorry, still thank you a lot

**Comment by niosus** [comment]
Could you tell me to which one you have changed? Just out of curiosity.

**Comment by yifengding** [comment]
clang-complete
