### ISSUE TITLE
complete the optional arguments howto 

### ISSUE THREAD

**Issue by wangjihu** [niosus/EasyClangComplete#264]
how to complete the full arguements , because i use opencv library,there are several arguemts that i want to config  instead of using the default value??? thanks very much..

**Comment by niosus** [comment]
Yep, for now we filter them out. That might not be the best solution. Let's see what I can do about it.

**Comment by niosus** [comment]
I have tried implementing this today, but failed. The optional arguments are not shown in the output from `complete`. I have found [a very old thread](http://clang-developers.42468.n3.nabble.com/libclang-inspecting-function-parameters-with-default-arguments-td4037675.html) that states it is impossible with libclang. I will put this in backlog as I definitely won't have the time now to dig much deeper.
