### ISSUE TITLE
Explicitly specify root of a CMake project

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#266]
Hi,

I was wondering if would be possible to add a configuration option to override or explicitly specify the root of a CMake project with EasyClangComplete. Right now one "annoying" behavior is that it tries to be smart a find the closest `CMakeLists.txt` that contains a `project(foo)` macro. This is fine for small project, but it can be quite cumbersome for larger codebases, which contain several sub-projects as part of a larger build, and where rewriting every individual `CMakeLists.txt` is not an option.

Moreover, there can be [advantages](https://stackoverflow.com/questions/8587224/what-is-the-proper-use-of-the-cmake-project-directive) in defining multiple projects as part of a larger build. Consequently, I think that it would be nice to be able to override/explicitly setup the default root `CMakeLists.txt` to use in a project (plus, if the project is large indeed, it will save time by running `cmake` only on the root folder, and not separately in every individual project).

I suggest having either:
- A setting that can be defined per-project in the `foo.sublime-project` file.
- A magic comment in the `CMakeLists.txt` to allow root override. This one would allow multiple root override, but I don't imagine it would be super useful.

**Comment by niosus** [comment]
Ok, I am still convinced, that it is best to search for a project, but it should be easy to add a custom setting for the path. We have all the infrastructure for this and this change should be relatively easy to add. I will try to do it in the upcoming week.

**Comment by niosus** [comment]
Oh, I am stupid. I have added this functionality long ago.

You can specify `search_in` as part of the cmake flags source like this:

```json
        "flags_sources": [
        {
           "file": "CMakeLists.txt",
           "search_in": "some/folder"
        },
    ],
```

The plugin will only search in that folder then.

**Comment by niosus** [comment]
I will close this for now. Reopen if it doesn't work for you.

**Comment by jdumas** [comment]
Seems to be working indeed thanks!
And sometimes there are situations where changing the subproject CMake scripts is not up to us, so it's good to have this kind of control anyway.
