### ISSUE TITLE
QT integration / unknown type name errors (false positive)

### ISSUE THREAD

**Issue by teamimx** [niosus/EasyClangComplete#267]
I work with a cmake based QT project and use Sublime as IDE (I work on a Mac). Your plugins works like a charm, except for the Qt part, where it does not seem to correctly resolve some of the QT includes (e.g. "unknown type name" error for QToolButton and other widgets). Everything builds  correctly though. Screenie attached below.
<img width="577" alt="easy_clang_autocomplete" src="https://cloud.githubusercontent.com/assets/7009939/26606741/6aad0350-4593-11e7-8e63-0b14a6577e33.png">

**Comment by niosus** [comment]
Thanks for submitting. Are you using ui created in designer? If yes, you will need to change your project settings to be able to find the headers generated from ui files in your build folder. This is probably not really optimal, but solves the trick. You will need to add an entry into the common flags in your project settings that will point to the build folder where your ui generated headers lie.

**Comment by teamimx** [comment]
Yes, the UI was created with designer and extended in code. Let me check that and come back to you on this :)

**Comment by teamimx** [comment]
are you referring to common_flags in "easy_clang_complete.sublime-settings" ?

**Comment by niosus** [comment]
Sorry I wan't clear enough. I am referring to a sublime text project file, e.g. `your_project.sublime-project`. In this file, you can override any setting of ECC plugin. Here is a part of the one I am using for Qt code:

```json
"settings":
	{
		"ecc_common_flags":
		[
			"-I/usr/include",
			"-I/usr/lib/clang/$clang_version/include",
			"-I~/Code/catkin_ws/build/$project_name/src"
		],
	}
```

Here, `"-I~/Code/catkin_ws/build/$project_name/src"` is the build folder where the headers get generated to when I build the code from the terminal. 

So the workflow is then a little bit complicated, but seems to work:
- modify your project file
- build code from the console
- open a cpp file in sublime text, the plugin should work now

**Comment by teamimx** [comment]
Thanks. Funnily enough, it seems to work by just adding a ".clang_complete" file into the build folder with the following content:
`{
  "settings":
  {
   "common_flags" : 
   [
    "-I/usr/include",
    "-I$project_base_path/src",
    "-I/usr/lib/clang/$clang_version/include",
    "-I$project_base_path/Tycoon_autogen/include",
  ],
    "easy_clang_complete_verbose": true
  }
}`

The errors / highlighting is gone...

**Comment by niosus** [comment]
Are you sure it is a `.clang_complete` file? :) Because it can't work like this :)

**Comment by teamimx** [comment]
Yep. Don't ask me why, but it works. the errors come back as soon as I remove the file... :o

**Comment by niosus** [comment]
I am pretty sure it doesn't :) That is even not the format we expect in the `.clang_complete` file. In case it doesn't work, try the trick with project settings. I maybe will add a user interface for setting that up.

**Comment by niosus** [comment]
I will close this issue for now, but I will keep in mind that this process has to be streamlined.
