### ISSUE TITLE
Can't resolve type use "using" directive

### ISSUE THREAD

**Issue by mkubasz** [niosus/EasyClangComplete#281]
I can't find definition of using assigned definition ` namespace sth { using MyClassPtr = std::shared_ptr<MyClass>;}`, when i use it like return type for my method `sth::MyClassPtr`. It show " no type name MyClassPtr in namespace sth". I

**Comment by niosus** [comment]
Thanks for reporting this. Can you give me some minimal example that I could reproduce? Otherwise it is hard for me to give you hints on this.

**Comment by niosus** [comment]
I will close this for the lack of activity. Please reopen if any new infos are available.
