### ISSUE TITLE
Unable to use libclang with Clang 5.0.0

### ISSUE THREAD

**Issue by Kyran-C** [niosus/EasyClangComplete#283]
I built Clang 5.0.0 from source, and using libclang fails with the following error:

``INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 5.0.0
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
CRITICAL:EasyClangComplete.plugin.completion.lib_complete: No cindex module for clang version: 5.0.0
ERROR:EasyClangComplete.plugin.view_config: cannot initialize completer with libclang.
INFO:EasyClangComplete.plugin.view_config: falling back to using clang in a subprocess.``

Win7 64 bit. 
`Clang/bin` is already in my path. I've confirmed that it's actually in that directory and isn't named weirdly. I tried putting `"libclang_path" : "E:/DevEnvironment/Clang/bin"` in my user settings but no luck. I also tried duplicating the existing cindex40.py to cindex50.py on the off chance it would use that, but I get the identical error. 

Everything works fine with libclang disabled.

**Comment by Kyran-C** [comment]
`"libclang_path" : "libclang.dll"` seems to work. It's able to find the directory through my path variable.
I also added an entry for '5.0' into cindex_dict in lib_complete.py, pointing to my duplicated cindex50.py. Not sure if that part was necessary. Everything's working now though.

@niosus I'll leave this issue open for now, in case you want to reference it in a future fix. I'm guessing you'll want to have a separate cindex50 for when 5.0.0 is properly released, instead of pointing it to a copy of cindex40.



Also, yaaaay c++17!
![if constexpr autocomplete](http://imgur.com/ilrPO1r.png)

**Comment by niosus** [comment]
Yeah, it makes sense to leave it open, I agree. Maybe I should just copy cindex40 and make this official. Just for those who like living on the bleeding edge. The default one in the readme will still be clang 4.0 for now.

And wow c++17 looks good!

**Comment by niosus** [comment]
I have included `cindex40.py` as fallback for clang 5.0, so you only need to set libclang path if you have it installed from source. I guess, I will close this for now.
