### ISSUE TITLE
Parsing Doxygen coments removes @param entries

### ISSUE THREAD

**Issue by papadokolos** [niosus/EasyClangComplete#292]
First, as you requst for it:
- Sublime Text version: `3126`
- which system are you on: `Ubuntu 14.04`
----
I was working on some C++ code and found out that my comments are being cut-off in the _Full Doxygen comment_ section of the _type info_ tooltip.

Here is an example:
![image](https://user-images.githubusercontent.com/13286080/28639357-9f1be7f2-7250-11e7-91d4-23488e1404d4.png)
As you can see, the `@param` section is missing.

It seems to me that this type of comments is pretty common, and thus should be parsed correctly. So I took a glance at the code and found that the method `cleanup_comment` is reponsible for the issue. I had a hard time understanding what exactly is going on there, so I've decided to rewrite it myself and propose my implementation here:
```python
import string
import itertools

@staticmethod
def cleanup_comment(raw_comment):
    """Cleanup raw doxygen comment."""

    def is_brief_comment(comment_line):
        # Brief comment is line starting with '@brief' or anything but '@'
        return (comment_line.startswith('@brief') or
                not comment_line.startswith('@'))

    # Split comment into lines
    lines = raw_comment.split('\n')

    # Remove comment prefixes from all lines
    chars_to_strip = '/' + '*' + string.whitespace
    clean_lines = [line.lstrip(chars_to_strip) for line in lines]

    # Remove first and last lines if they are empty
    if not clean_lines[0]:
        del clean_lines[0]
    if not clean_lines[-1]:
        del clean_lines[-1]

    # Exclude the brief comment from full comment if exists
    if is_brief_comment(clean_lines[0]):
        del clean_lines[0]

        # Remove any trailing empty lines
        clean_lines = itertools.dropwhile(
            lambda line: not line, clean_lines)

    # Combine all comment lines to valid HTML representation
    return '<br>'.join(clean_lines)
```

And the result is:
![image](https://user-images.githubusercontent.com/13286080/28639937-ad43120e-7252-11e7-824d-dcbf98fb8f83.png)

I would love to create a pull request for this but genuiney I've never done this before so I have no idea how to do it correctly.

----
PS. This plugin never stops to amaze me! Please know that the work you put on this plugin is very much appreciated :smile: 

**Edit:**
Now that I think about it I have an even better idea for this implementation regarding the brief comment. I'll add it tomorrow after I'll give it a check.

**Comment by niosus** [comment]
Hey @papadokolos thanks for the input. I will try to have a look into the way I am parsing the comments. The main problem was that many people use many different styles, so that might have caused me to converge on a code far from optimal :smile: 

Anyway, if you want to rewrite parts of the code, please, just provide a pull request. This way it is going to be much easier for me to test out the code and merge it in case it works better in all cases. And thanks for the kind words :)
