### ISSUE TITLE
Skip function bodies?

### ISSUE THREAD

**Issue by rwols** [niosus/EasyClangComplete#297]
When creating a translation unit, you can pass the option to skip parsing the function bodies (`TU.PARSE_SKIP_FUNCTION_BODIES`). This greatly improves parsing the file when it first loads. For the sake of completions, parsing function bodies is also not necessary. However, you may get strange warnings about undefined functions even if they're defined. Because of this, if one would implement this feature, it would be incompatible with the inline warnings/errors feature. I would like to implement this but I'd like to hear your opinions about this first.

So, I propose a new setting called `"skip_function_bodies"`. By default it is set to `false`. If it's set to `true`, inline warnings/errors are disabled, but parse time is improved.

**Comment by niosus** [comment]
Thanks for the proposition.

> So, I propose a new setting called "skip_function_bodies". By default it is set to false

This seems valid to me. As for disabling the warnings. Can't we just filter them out? How many of different kinds of warnings are there? I already filter out the warnings related to `#pragma once` for parsing header files, so we could just add some more checks there.

Overall the addition is welcome. It would be best if we just filter out the (potentially?) wrong warnings if the setting is on. If we cannot do this, I don't know what would be a good way. We should inform the user that we disable a setting if we do it automatically.

**Comment by dibalavs** [comment]
Hello. I created PR #325 about goto definition/declaration.

If we skip function bodies, will goto_declaration work to local variables, declared inside function body?

**Comment by niosus** [comment]
@dibalavs I agree. I think it is important to remember that this option exists. Maybe we will use it in case we do something about #124 to make parsing faster. I will close this issue for now as I have no plans implementing it.
