### ISSUE TITLE
Support for Xcode 9

### ISSUE THREAD

**Issue by jjgod** [niosus/EasyClangComplete#301]
Currently we got: Version '9.0' of AppleClang is not supported yet. Please open an issue for it

![screen shot 2017-08-07 at 10 28 50 am](https://user-images.githubusercontent.com/1017/29038114-52ba3198-7b5b-11e7-8646-9554acda70a9.png)

**Comment by rwols** [comment]
As a quick fix, you could do `brew install llvm`. It will install the "linux" clang and EasyClangComplete should pick that up. I have not tested this, so take this with a grain of salt.

**Comment by niosus** [comment]
Thanks for opening an issue. I will look into it soon.

**Comment by niosus** [comment]
@jjgod I can't really test it as I don't have a mac, but could you add this line:
```
'9.0': 4.0'
```
under [this line](https://github.com/niosus/EasyClangComplete/blob/master/plugin/tools.py#L38)? (Also, make sure all lines before the last have a comma in the end of line)

**Comment by jjgod** [comment]
@niosus Thanks! That’s the workaround I have been using and it seems to work fine for my sources (Objective-C++ code).

**Comment by niosus** [comment]
@jjgod cool. Will add it soon.

**Comment by meritozh** [comment]
I think use: (copy from YCM-Generator)

```python
def LoadSystemIncludes():
    regex = re.compile(r'(?:\#include \<...\> search starts here\:)(?P<list>.*?)(?:End of search list)', re.DOTALL)
    process = subprocess.Popen(['clang', '-v', '-E', '-x', 'c++', '-'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    process_out, process_err = process.communicate('')
    output = (process_out + process_err).decode("utf8")

    includes = []
    for p in re.search(regex, output).group('list').split('\n'):
        p = p.strip()
        if len(p) > 0 and p.find('(framework directory)') < 0:
            includes.append('-isystem')
            includes.append(p)
    return includes
```

is  more flexible way to set default CXX flags in **macOS**, so you needn't manually add a map between "linux" clang version and AppleClang version

**Comment by niosus** [comment]
@meritozh thanks for the input, but I feel that we're talking about different things. 
There is no difference between how we process the includes. The difference comes from how to pick the python bingings to libclang. These are quite sensitive to version of underlying llvm clang.
