### ISSUE TITLE
Autocompletion of beginend patterns.

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#304]
Hi,

I very often type stuff like `std::sort(foo.begin(), foo.end())`. The completion triggers when I reach the first dot, i.e. `std::sort(foo.|`. Then i can very conveniently choose the `beginend` patterns, which expands into `$1.begin(), $1.end()`, with both `$1` highlighted.

However, what happens is that I end up with `std::sort(foo.v.begin(), v.end())` instead, with both `v` selected (so I can turn them into `foo`). But then I have to remove the first `foo.`, which is very annoying and I feel that it shouldn't behave like this.

This works fine for autocompletion patterns which use a single selection, only stuff like `beginend` leads to this issue.

Do you observe a similar behavior?

**Comment by rwols** [comment]
> Do you observe a similar behavior?

Yes. What you're seeing is a default snippet that's getting triggered, so it's not really an ECC issue. The default snippets try to be too clever sometimes. I believe [it's this snippet you're talking about](https://github.com/sublimehq/Packages/blob/master/C%2B%2B/Snippets/%241.begin()-%241.end()-(beginend).sublime-snippet)?

**Comment by jdumas** [comment]
Ah yes, I wasn't sure whether it was a ECC issue or not. Is there a way to disable it? I already have `"hide_default_completions": true` in my preferences. Or if you know of a way to fix it? I don't have a lot of experience with Sublime's snippets.

**Comment by rwols** [comment]
I did some digging... [here is the flag for that becomes active](https://github.com/niosus/EasyClangComplete/blob/92334dd2f6a7dd56f773d43e1ad661dea86d1093/plugin/tools.py#L93-L94) when `"hide_default_completions"` is set to `true`. However from [this commit to the unofficial docs](https://github.com/guillermooo/sublime-undocs/pull/190/files) you can see that `sublime.INHIBIT_EXPLICIT_COMPLETIONS` only disables stuff from `.sublime-completions` files. I think this implies that `.sublime-snippet` files still get triggered. I'm starting to think there's no way to disable sublime snippets. That feels like an oversight on Sublime's side.

**Comment by jdumas** [comment]
Aww, that sucks =/
I was able to disable it following [this](https://stackoverflow.com/questions/27995926/how-do-i-disable-snippets-in-sublime-text-3), and setting the snippet to the empty file. But this feels a bit brittle to me.

Anyway, feel free to close the issue now if you want.

**Comment by niosus** [comment]
Thanks @rwols for pitching in :+1: 
Yes, I will close this issue as this is not really related to ECC.

@jdumas I think what you want to do in this case is not use completion from my plugin at all. Do not wait till you reach the end of `foo`, but start typing `begin` right after the opening bracket. The `beginend` snippet will show up and after choosing it, you will be able to type `foo` once in both expansion slots simultaneously. I love sublime just for that. It is the choice of a tool and when to use it that makes it so great.

**Comment by jdumas** [comment]
Ah well, I'm stupid for not having tried what you just suggested @niosus =D. Maybe I'll do that in the future. I love Sublime, but I don't know all the shortcuts/features/best ways to use it yet.
