### ISSUE TITLE
Any way of seeing the exact clang command that is used to get errors?

### ISSUE THREAD

**Issue by merlinthered** [niosus/EasyClangComplete#305]
I am currently fighting with EasyClangComplete on a certain project where it produces nonsenical errors, while a similar project with almost the same settings and flags works flawlessly. Some errors I get are:

* Not being able to find a type name that is defined via a C++11 `using` in a header file in the same folder.
* Not recognizing a type that is defined via `using` literally two lines above the error.
* Not recognizing the `std::get` function.

It looks like these errors are related exclusively to C++11 funtionality. However, the log shows that `-std=c++11` is contained in the clang flags for both the project that is working, and the one that is not. It seems logical that the problem lies with clang, and probably the flags it gets when retrieving the errors. That's why I would like to know if there is a way to see the exact command that EasyClangComplete uses to retrieve errors from clang. Maybe that way I can find out which incorrect settings I am using. If not, maybe you can help me get to the bottom of this issue in some other way.

- Sublime Text version: `3`
- which system are you on: `Ubuntu/Linux`
- clang version: `3.8.0`
- `"use_libclang": true`

**Comment by niosus** [comment]
Hey @merlinthered 
Yeah, I went through this too at my new work now :) This experience is definitely not the best.

I guess, it would be cool if we could show all errors in all files say in the output pane. Currently, there is no such functionality.

What you can do: disable libclang and enable verbose output. You then can see a line starting with `clang` in the console. Just copy this line in your terminal emulator and this will show you all errors. This way, you will be able to trace the root of the problem, i.e. the first error after which the compiler produces garbage error messages.

Sorry for this behavior. I definitely need to address this at some point.

**Comment by merlinthered** [comment]
Thanks, I didn't think that the errors are caused by other errors showing up before.  

I was able to resolve the errors. They were caused because I specified include directories in `ecc_common_flags` for stuff that the compiler would have better found by itself. This caused clang to include some gcc headers which are not compatible with clang, throwing lots of `undeclared identifier` errors.
