### ISSUE TITLE
No completion inside templates?

### ISSUE THREAD

**Issue by merlinthered** [niosus/EasyClangComplete#307]
- Sublime Text version: `3`
- which system are you on: `Linux`

I noticed that autocompletion does not work inside templates. When I have a normal class, autocomplete works fine:

```cpp
class Foo{
public:
    Foo(){
        this->;
    }
private:
    double _baz;
};
```
after writing `this->`, autocomplete is triggered and I see both `_baz` and the implicitly defined `operator=()`.

When I make the class a template, it no longer works:

```cpp
template <typename T>
class Foo{
public:
    Foo(){
        this->;
    }
private:
    double _baz;
};
```
Now, the log reports an empty list of clang completions, and consequently, normal Sublime Text autocompletions are shown.

I suspect this is a problem with clang, as the template is not instantiated yet at that point, and so clang does not know a concrete class it can base its completions on. I am surprised however, that I could not find a lot about this problem on Google. It seems to be a major drawback that more people must have noticed by now. Do you have any insight on this?

**Comment by niosus** [comment]
@merlinthered yep, the completion inside the templates is essentially impossible from within the translation unit. The only time the code for templates is generated is when you instantiate an instance of this class or declare a typedef or mark it used with some clever macro. In this case, libclang does not know which type it should use to generate code and therefore cannot do any completion. This is the limitation of using a single translation unit based completion approach. So I will close this for now.
