### ISSUE TITLE
the "triggers" option are ineffective

### ISSUE THREAD

**Issue by abadcafe** [niosus/EasyClangComplete#31]
my settings:
```
{
	"auto_complete_triggers":
	[
		{
			"characters": ".:>",
			"selector": "source.c - string - comment - constant.numeric"
		},
		{
			"characters": ".:>",
			"selector": "source.c++ - string - comment - constant.numeric"
		}
	],
	"include_dirs" : [],
	"autocomplete_all": true,
	"std_flag" : "-std=gnu11",
}
```

![1cdcd0bf-02eb-49e0-904a-4fdf1006c942](https://cloud.githubusercontent.com/assets/922228/15753384/5093e6cc-2925-11e6-901a-14f728230fde.png)

**Comment by niosus** [comment]
Hey @abadcafe 
This issue exists because of issue #15 
I guess I will need to decouple function `needs_autocomletion` into more functions and return `None` in all cases apart from wrong triggers. Will do on the weekend.

**Comment by niosus** [comment]
Sorry that I didn't use your pull request. I decided to rewrite that part in a better way. Now my plugin will not obscure the completions of sublime unless a part of the trigger is entered. So it will complete "->" and "::", will use default completions for every other situation and will remove all completions whatsoever on ">" or when entering a dot after a number.

Also, I just saw that probably this issue is invalid as you set `autocomplete_all` to `true`. This will force the plugin to try to complete at every possible position, disregarding all the triggers.

**Comment by abadcafe** [comment]
@niosus never mind, is up to you.

**Comment by niosus** [comment]
I don't fully understand what you mean here:
> and set `autocomplete_all` to `true` was not resolve the problem, infact.

This setting cannot resolve the trigger problem as it is there exactly to do the opposite - to autocomplete on every character no matter what triggers are defined.

**Comment by abadcafe** [comment]
@niosus Sorry for my English, I just misunderstand your second post :P .

**Comment by niosus** [comment]
Yeah, no problem at all :) I am just trying to understand the issue and make it go away for you. 

So is there any particular reason why you want to use `autocomplete_all` setting?

**Comment by abadcafe** [comment]
@niosus 

While `autocomplete_all` is true, I can get more exact completions and function arguments. And, `autocomplete_all` is fast enough while deal with linux kernel source. In addition, a C project big than linux kernel is rare.

**Comment by niosus** [comment]
ok, I understand that. So you want `autocomplete_all` but to avoid it generating garbage for invalid triggers, right? I can do that. Probably will land tomorrow.

**Comment by abadcafe** [comment]
@niosus thank you in advance

**Comment by abadcafe** [comment]
@niosus I tried your new version plugin, and reviewed the patch.

Basically, I think use a multiple state function to determine whether need completions, is a better way than before.

But in my option, even `settings.complete_all` set to `true`, the plugin also need check current position, otherwise the plugin will cause sublime text's tedious word completion.

And, I suggest you supply a new option `suppress_word_completion`. In the case of `autocomplete_all = true`, people (like me :p) usually don't like any word completions because the plugin can almost always supply more exact completions.

Even in some corner case, the plugin can not return any completions, for example, included a non-exist header file, it is still better than return word completions because people may perceive the wrong header file error.

**Comment by niosus** [comment]
This sounds like a good idea actually. I will track it in a new issue.
