### ISSUE TITLE
error: libLLVMAArch64AsmParser.so: cannot open shared object file:

### ISSUE THREAD

**Issue by kubaroth** [niosus/EasyClangComplete#310]
I'm having some issues with the with clang/llvm dynamic libraries as they are not installed in the default location. 
What would be the easiest way to test if the plugin works in my environment - ideally from the command line?
Part of the problem may be also related that the location of llvm is different then clang in my case and I don't see in the ECC.settings I can specify the locations independently.

The error I'm getting is the following:
`error: libLLVMAArch64AsmParser.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().`

Wolud specifying explicitly Config.set_library_path() help here? Not sure where to put the line.. :)
Alternatively, do you know if staticly-linked llvm/clang can been used instead?
Thanks!

**Comment by kubaroth** [comment]
I think I got it working by adding env={} with updated LD_LIBRARY_PATH to  run_command() in tools.py.
As to the comand line example, I was able to extract it from the DEBUG log (set in EasyClangComplete.sublime-settings, 'verbose')
Would you accept PR to add the env to the settings files?

**Comment by kubaroth** [comment]
One more thing I've noticed. It looks completions is not triggered by "." character but it works on any other character. Is there a way to force it by calling a plugin command with a shortcut?

**Comment by niosus** [comment]
This is a strange error. I have never seen it before. Which system are you on? There is a setting `libclang_path` which you can specify in case your libclang is in non-standard location. It should work in your case.
