### ISSUE TITLE
[Feature Request] Disable common flags when a flags source is found

### ISSUE THREAD

**Issue by papadokolos** [niosus/EasyClangComplete#311]
### Feature Request:
Currently, this plugin supports default flags:
```javascript
// Specify common flags that will be passed to clang for EVERY build.
"common_flags" : [
...
]
```
While this feature is incredibly usefull when working on standalone, non-project related files; It is redundant and sometimes even harmfull when working on projects with an existing `flags_source` file (such as `compile_commands.json`).

> An example for a collision between `common_flags` and `compile_commangs.json` is where `common_flags` contains an include directory for _llvm's C++ standard library_, whereas the `compile_commands.json` states an include for _GNU's C++ standard library_.

Since the `flags_source` file already contains all the flags I need, the `common_flags` and its friends are no longer needed. So my request is adding this setting:
```javascript
// Whether to use common flags when one of the flags_sources is found.
"use_common_flags_with_flags_source": true
```
This way I can set this setting to `false`, and the default value maintains backward compatibility.

#### My System Specifications
- Sublime Text version: `3126`
- which system are you on: `Ubuntu 14.04 32bit (Virtualbox)`

**Comment by niosus** [comment]
Thanks for the feature proposal. This should be explained better, but you can always set them empty in the project specific settings. I don't want to make a decision on when we do and don't need the common flags.

**Comment by papadokolos** [comment]
Alright. I respect that.

Nevertheless, putting an empty setting in the project file won't do the trick unfortunately, since my use case involves working on non-project-related files **while** working on a project (in the same window).

For example, my project doesn't work with C++ standard library, but I do want to check something in a temporary file which requires C++ standard library. I would rather not to open a new window just for this temporary file.

So I guess my options are:
1. Create a little plugin to toggle `common_flags` on key binding
2. Fork this repository and implement my requested logic there

Perhaps you can think of an easier solution for my problem?
