### ISSUE TITLE
Allow configuring cmake path

### ISSUE THREAD

**Issue by meritozh** [niosus/EasyClangComplete#320]
# Please state the following: #
- Sublime Text version: `Build 3126`
- which system are you on: `macOS 10.12.6`

When I first open one project, ECC use installed `cmake` to generate *compile_commands.json* then cache it. But I upgrade cmake next day, then open this project again, will throw `cmake command can't be found`.

Then reason is, the path of previous version `cmake` is `/usr/local/Cellar/cmake/3.9.1/bin/cmake` if I use homebrew to install it, but after upgrading, true path is `/usr/local/Cellar/cmake/3.9.2/bin/cmake`.

Can we just use `/usr/local/bin/cmake`?

**Comment by niosus** [comment]
I've seen this a couple of times. I will add a way to specify the full cmake command in the settings.

**Comment by niosus** [comment]
After I merge the #347 to master you will be able to specify any cmake location using `"cmake_binary"` in the plugin settings.
