### ISSUE TITLE
hotkey to show info popup window for selected symbol

### ISSUE THREAD

**Issue by dibalavs** [niosus/EasyClangComplete#326]
- Sublime Text version: `3.0`
- which system are you on: `linux`

Sublimetext is great code editor. You can work with it mostly without mouse, with only hotkeys.
But looks like there is no hotkey to show function/variable/macro information popup window  (like on mouse hover).

So the idea is introduce such hotkey.

On some IDEs like VisualStudio it can be done with ctrl+space

**Comment by niosus** [comment]
This is a valid idea. Should be also trivial to implement. I will be quite busy the next two weeks, but will try to find time to do this afterwards. Also, PRs are welcome for this feature. We should just call the same function that we do from `on_hover`.

**Comment by kjteske** [comment]
Created PR for this issue. By default, I'm not setting a hotkey binding, but the PR description documents how to add this.
