### ISSUE TITLE
ability to specify different compiler flags for different directories

### ISSUE THREAD

**Issue by dibalavs** [niosus/EasyClangComplete#327]
in .clang-complete file It is possible to add only global flags. Which will be used to all files in all directories.

It would be good to have some customization for specific directories. because in big project there are different compiler settings can be in different directories.
There are some variants:
1) use separate .clang-complete files for that directories
2) use the same .clang-complete file, but have special  file structure, which allows customization for different directories

**Comment by niosus** [comment]
I guess this one is related mostly to #274 
This functionality is already available: you can use a different `.clang_complete` file per folder. It is searched from the opened file up the directory tree.
