### ISSUE TITLE
'NoneType' object has no attribute 'codeComplete'

### ISSUE THREAD

**Issue by segfault-11** [niosus/EasyClangComplete#337]
- Sublime Text version: `Version 3.0 Build 3143`
- which system are you on: `macOS Sierra version 10.12.6`

ECC works very well on my Ubuntu machine, but no completion shows up on my Mac machine. The problem seems come from `libclang`, but I've no idea how to make it work. Below is the console information. Thanks for your help.

> [ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-7]: Overriding settings by project ones if needed:
> [ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-7]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
> [ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-7]: Reading settings...
> [ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-7]: Settings sucessfully read...
> [ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-7]: Getting version from command: `clang++ -v`
> [ECC:WARNING]:[tools.py]:[_get_apple_clang_version_str]:[Dummy-7]: OSX version 9.0 reported. Reducing it to 4.0.
> [ECC:INFO]:[tools.py]:[_get_apple_clang_version_str]:[Dummy-7]: Found clang version 4.0
> [ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-7]: populating common_flags with current variables.
> [ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-7]: populated '-I$project_base_path/src' to '-I/src'
> [ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-7]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/4.0/include'
> [ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-7]: settings initialized for view: 64
> [ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-38]: submitting job: job: 'update', args: ([<sublime.View object at 0x109340c90>, <EasyClangComplete.plugin.settings.settings_storage.SettingsStorage object at 0x109335990>])
> [ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-38]: running 1 jobs
> [ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-16]: generate new config for path: 64
> [ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-16]: init completer based on libclang
> [ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-16]: using bundled cindex: EasyClangComplete.plugin.clang.cindex40
> [ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-16]: [cmake]:[get]: for file /Users/szhou/PointsFit/converter.cpp
> [ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-16]: [cmake]:[cached]: 'None'
> [ECC:DEBUG]:[tools.py]:[search]:[Thread-16]: searching 'CMakeLists.txt' from '/Users/szhou/PointsFit' to '/'
> [ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-16]: [cmake]:[current]: 'None'
> [ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-16]: [cmake]:[generate new db]
> [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-16]: [db]:[get]: for file /Users/szhou/PointsFit/converter
> [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-16]: [db]:[cached]: 'None'
> [ECC:DEBUG]:[tools.py]:[search]:[Thread-16]: searching 'compile_commands.json' from '/Users/szhou/PointsFit' to '/'
> [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-16]: [db]:[current]: 'None'
> [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-16]: [db]:[load new]
> [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-16]: [db]:[no new]: return None
> [ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-16]: [clang_complete_file]:[get]: for file /Users/szhou/PointsFit/converter.cpp
> [ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-16]: [clang_complete_file]:[cached]: 'None'
> [ECC:DEBUG]:[tools.py]:[search]:[Thread-16]: searching '.clang_complete' from '/Users/szhou/PointsFit' to '/'
> [ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-16]: [clang_complete_file]:[current]: 'None'
> [ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-16]: view is 64
> [ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-16]: translation unit does not exist. Creating.
> [ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-16]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', '-I/usr/include', '-I/src', '-I/usr/lib/clang/4.0/include', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks', '-I/Users/szhou/PointsFit', '-I/Users/szhou']
> [ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-16]: compilation started for view id: 64
> [ECC:ERROR]:[lib_complete.py]:[parse_tu]:[Thread-16]: error while compiling: Error parsing translation unit.
> [ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-16]: compilation done in 0.0023908615112304688 seconds
> [ECC:CRITICAL]:[lib_complete.py]:[update]:[Thread-16]:  cannot create translation unit. Abort.
> [ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-16]: starting timer to remove old configs.
> [ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-16]: [timer]: start for view: 64
> [ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-16]: [timer]: active for views: dict_keys([64])
> [ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-16]: updated config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x109335b10>
> [ECC:DEBUG]:[thread_pool.py]:[__stop_progress_animation]:[Thread-16]: Jobs still running: 0
> [ECC:DEBUG]:[thread_pool.py]:[__stop_progress_animation]:[Thread-16]: Stopping progress animation.
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-7]: on_modified_async view id 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-7]: config exists for path: 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-7]: on_modified_async view id 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-7]: config exists for path: 64
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: on_query_completions view id 64
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: prefix: s, locations: [180]
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: this position has identifier: '(64, 179)'
> [ECC:DEBUG]:[tools.py]:[get_pos_status]:[MainThread]: matched trigger ' '.
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: starting async auto_complete with id: (64, 179)
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: showing default completions
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64
> [ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-7]: on_modified_async view id 64
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-7]: config exists for path: 64
> [ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-40]: submitting job: job: 'complete', args: ([<sublime.View object at 0x108ccc790>, <EasyClangComplete.plugin.tools.ActionRequest object at 0x109393c50>])
> [ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-40]: running 1 jobs
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-14]: config exists for path: 64
> [ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-14]: started code complete for view 64
> [ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-14]: using newer version of clang: 4.0
> [ECC:ERROR]:[lib_complete.py]:[complete]:[Thread-14]: error while completing view /Users/szhou/PointsFit/converter.cpp: 'NoneType' object has no attribute 'codeComplete'
> [ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-14]: code complete done in 0.0001919269561767578 seconds
> [ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-14]: completions: []
> [ECC:DEBUG]:[thread_pool.py]:[__stop_progress_animation]:[Thread-14]: Jobs still running: 0
> [ECC:DEBUG]:[thread_pool.py]:[__stop_progress_animation]:[Thread-14]: Stopping progress animation.
> [ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 64

**Comment by niosus** [comment]
It seems that your config is wrong. The lines from the flags like:
```
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1'
```
suggest that you forgot an include prefix `-I<your_include>`.  Without it libclang does not know what to do with it and fails to parse a translation unit. This is related to #193 I guess. Don't know when I will have the time to add that functionality though...

Please reopen if adding the -I won't fix the issue.

**Comment by segfault-11** [comment]
Adding `-I` solved my problem perfectly, thank you so much.
