### ISSUE TITLE
Settings are outside Packages/User

### ISSUE THREAD

**Issue by detly** [niosus/EasyClangComplete#340]
# Please state the following: #
- Sublime Text version: `3126`
- which system are you on: `Ubuntu 17.04`

Advice from Package Control on [syncing settings](https://packagecontrol.io/docs/syncing) across computers is to sync the `Packages/User` directory, since that's where package settings should be kept. But ECC seems to store settings outside this directory.

```shell
~ ☼ cd ~/.config/sublime-text-3/Packages/
Packages ☼ ls
Base16  C Improved  EasyClangComplete  User
Packages ☼ ls User/*.sublime-settings
User/C Improved.sublime-settings           User/Objective-C.sublime-settings
User/clang_format_custom.sublime-settings  User/Package Control.sublime-settings
User/clang_format.sublime-settings         User/Preferences.sublime-settings
User/Matlab.sublime-settings
```

This makes it harder to sync settings (I sync from the top level directory, but most users will sync from `Packages/User` making it impossible). It also means I don't really know what are user settings and what are plugin files that should be managed by Package Control.

**Comment by niosus** [comment]
This is strange. The user settings should be in User the moment you change them at least once. 
On my machine they are there: 
![screenshot from 2017-10-23 20-57-21](https://user-images.githubusercontent.com/1893598/31924310-1e9cb4e6-b835-11e7-9cb9-0edf67a1f9f5.png)

**Comment by detly** [comment]
How weird — I definitely changed them while I was trying to configure it. I wonder if I somehow saved them in the wrong place?

I'll delete it all and manually restore my ECC settings (there aren't many changed) and report back on whether it happens again.

**Comment by niosus** [comment]
Weird indeed. It should not be possible to save them into the wrong place :)

**Comment by detly** [comment]
Yeah I stuffed this up and somehow saved my settings in the left hand pane (the package settings). 🙄 Not a bug.

**Comment by niosus** [comment]
Really strange. :) How did you manage? I thought sublime text does not allow you to save the settings elsewhere. Anyway, I guess I can close this issue.
