### ISSUE TITLE
CMakeLists.txt with read-only permissions can't be used

### ISSUE THREAD

**Issue by mrockey28** [niosus/EasyClangComplete#341]
- Sublime Text version: `3.0 Build 4134`
- which system are you on: `Ubuntu 14.04.5 LTS 32-bit`

If ECC attempts to use a CMakeLists.txt file that is locked, the following exception occurs:

> exception calling callback for <Future at 0xb5b059ac state=finished raised PermissionError>
> Traceback (most recent call last):
>   File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 308, in config_updated
>     log.debug("updated config: %s", future.result())
>   File "./python3.3/concurrent/futures/_base.py", line 394, in result
>   File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
>   File "./python3.3/concurrent/futures/thread.py", line 54, in run
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 360, in load_for_view
>     config = ViewConfig(view, settings)
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 60, in __init__
>     completer, flags = ViewConfig.__generate_essentials(view, settings)
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 176, in __generate_essentials
>     flags += ViewConfig.__load_source_flags(view, settings, prefixes)
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 221, in __load_source_flags
>     flags = flag_source.get_flags(view.file_name(), search_scope)
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/flags_sources/cmake_file.py", line 75, in get_flags
>     current_cmake_path = self._find_current_in(search_scope, 'project')
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/flags_sources/flags_source.py", line 114, in _find_current_in
>     search_content=search_content).full_path()
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 331, in search
>     found_file = File(path.join(current_folder, file))
>   File "/home/mrockey/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 233, in __init__
>     open(self.__full_path, 'a+').close()
> PermissionError: [Errno 13] Permission denied: '/home/mrockey/X/CMakeLists.txt'

This occurs because this Cmakelists file only has read permissions:
-r--r--r--  1 mrockey mrockey  4386 Oct  5 12:45 CMakeLists.txt
This is because this file is under Perforce version control, which changes all files to read-only until they are checked out.

However, the CMakeList compiler does not need to open the file for writing. The only reason this is done is due to line 233 in plugin/tools.py:
```
         self.__full_path = path.abspath(file_path)
         # initialize the file
         open(self.__full_path, 'a+').close()
```

I have a pull request prepared but not submitted with the following change around this line:
```
        self.__full_path = path.abspath(file_path)
        # initialize the file
        if path.isfile(self.__full_path):
            open(self.__full_path, 'r').close()
        else:
            open(self.__full_path, 'a+').close()
```

Since the only point of opening and then closing the file is to create it if it doesn't exist, this seems like a reasonable change. If agreed to, I will submit the change.

**Comment by niosus** [comment]
Yeah, sure, that sounds reasonable. Thanks for reporting. I will add this change.
