### ISSUE TITLE
suppress_word_completion option

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#35]
@abadcafe has pointed out
> And, I suggest you supply a new option `suppress_word_completion`. In the case of `autocomplete_all = true`, people (like me :p) usually don't like any word completions because the plugin can almost always supply more exact completions.

**Comment by niosus** [comment]
Added `hide_default_completions` with commit 047403ce51cf05aa206d9339eb117b074acb1e00.
Will be available soon in version 1.1.2. Closing for now. Please reopen if something is not working.

**Comment by abadcafe** [comment]
@niosus Thank you for the `hide_default_completions` option, but the `triggers` option still not work while `autocomplete_all` option was `true`.

I built a patch here.
[fix_triggers_option.patch.txt](https://github.com/niosus/EasyClangComplete/files/299407/fix_triggers_option.patch.txt)

**Comment by niosus** [comment]
Yes. Sorry, forgot. Done now. Will be available in the next version soon.
