### ISSUE TITLE
Control error highlight style, and "go-to-next-error" command

### ISSUE THREAD

**Issue by zhiayang** [niosus/EasyClangComplete#354]
# Please do this before submitting: #
- [x] check for already solved issues
- [x] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `3.0, Build 3143`
- System: `macOS 10.13.2`

Not really a bug report insomuch as a feature request;

1. The ability to control error highlights. Right now, errors in the code itself are highlighted in this fugly colour combination that I cannot control:

![image](https://i.imgur.com/OMiXZb8.png)

Some ability to change the styling, such as box outlining (as we have now) or underlining, as well as changing the colour, would be very much appreciated. If I'm misguided and there's a specific tag I need to set in my colour scheme, I'd be glad to do it.

2. The ability to jump to the next error in the file with a keybinding. This should be self-explanatory, and is a feature I'm find myself missing a lot.

**Comment by niosus** [comment]
Yeah, this is boiling in my head for a long time already. I should be able to implement it in a couple of weeks. Sorry for the delay.

**Comment by niosus** [comment]
The error highlighting is now used in a non-filled fashion and uses `invalid.illegal` scope for picking the color. The second request in this feature for navigating to the next error will be addressed when fixing #350

**Comment by zhiayang** [comment]
Alright, that's great, now the only thing left is to add error navigation, and also the #350 thing where you show all the errors.

As it is now this has replaced SublimeClang, which is great news because that thing is old and seems to hang the render/update thread when trying to autocomplete files with a lot of includes. Extremely glad this doesn't happen with ECC!

Great work.
