### ISSUE TITLE
Feature request: mark errors in gutter

### ISSUE THREAD

**Issue by detly** [niosus/EasyClangComplete#356]
- Sublime Text version: `3143`
- which system are you on: `Windows 10/Ubuntu 17.04`

It would be nice to have an option to see errors marked in the gutter. Sometimes I miss them on long/cluttered lines.

**Comment by niosus** [comment]
Yeah, I agree. I guess this fits well with my intention to implement #354 
I will also look at your PR, thanks for it. Sorry for the delay. I should have much more time on my hands in 2-3 weeks.
