### ISSUE TITLE
Please add "C Improved" syntax.

### ISSUE THREAD

**Issue by r44083** [niosus/EasyClangComplete#36]
Hi, a lot of users uses [C Improved](https://packagecontrol.io/packages/C%20Improved) plugin. But EasyClangComplete doesn't support this syntax. I have already tested it - you need just add it to the tools.py (line 103):
```

    syntax_regex = re.compile("\/([^\/]+)\.(?:tmLanguage|sublime-syntax)")

    valid_extensions = [".c", ".cc", ".cpp", ".cxx", ".h", ".hpp", ".hxx"]
    valid_syntax = ["C", "C++", "C Improved"]

```

**Comment by niosus** [comment]
Done. Release should be live in a couple of hours.
