### ISSUE TITLE
Please add EasyClangComplete folder into user temp folder.

### ISSUE THREAD

**Issue by r44083** [niosus/EasyClangComplete#37]
It would be nice if you change EasyClangComplete plugin behavior
from:
    using raw Temp user folder for storing analyzed files
to:
    create EasyClangComplete folder into Temp folder and using EasyClangComplete folder for storing analyzed files.

It increase stability and lets plugin avoid situation when there are some *.c or *.h files into Temp folder.

**Comment by niosus** [comment]
Makes sense. Will do.

**Comment by niosus** [comment]
Done. Will be available in a couple of hours.
