### ISSUE TITLE
Can't use libclang

### ISSUE THREAD

**Issue by schreda** [niosus/EasyClangComplete#373]
I am on a customized system in my company and cannot use libclang, because of libatomic.so.1
I can't find anything regarding to this library on the internet.
The error message is the following:
`[ECC:ERROR]:[lib_complete.py]:[__init__]:[Thread-9]: error: libatomic.so.1: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().`

- Sublime Text version: `3.0, 3143`
- which system are you on: `OpenSUSE11`

How is this library related to libclang?

**Comment by niosus** [comment]
I am sorry to say this, but I have no idea what is going on here. Can you compile something with clang?

**Comment by schreda** [comment]
Bad news...
Clang compiling works fine

**Comment by niosus** [comment]
At least googling seems to tell me it is not strictly libclang related. A lot of people seem to be having it with various systems like heroku or chrome.

**Comment by niosus** [comment]
This might be helpful: https://askubuntu.com/questions/825626/chromium-is-not-working-in-ubuntu-12-04

See the point **2.**

**Comment by niosus** [comment]
As of now, I feel like this is not related to the plugin itself, so I will close this issue. Feel free to reopen if you feel otherwise.

**Comment by schreda** [comment]
Installing another clang version solved the problem!
