### ISSUE TITLE
Support SConstruct file (SCons)

### ISSUE THREAD

**Issue by kblomqvist** [niosus/EasyClangComplete#374]
Like there's support for CMake, I would like to have support for SCons too. I have already prototyped a software to export the compiler, and user defined std, include paths and preprocessor macro definitions from the SConstruct file. Compiler defaults are also exported. 

You can find the prototype here
https://gist.github.com/kblomqvist/d5ebe28d2604420d5d08553b4c575dbf

For example, following flags:

```
{
  "c_flags": [
    "-std=gnu11",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/lib/gcc/arm-none-eabi/4.9.3/include",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/lib/gcc/arm-none-eabi/4.9.3/include-fixed",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/arm-none-eabi/include",
    "-D'__DBL_MIN_EXP__=(-1021)'",

    // ...
 
    "-D'__ULACCUM_FBIT__=32'",
    "-D'__QQ_IBIT__=0'",
    "-D'__ATOMIC_ACQ_REL=4'",
    "-D'__ATOMIC_RELEASE=3'"
  ],
  "cpp_flags": [
    "-std=gnu++14",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/arm-none-eabi/include/c++/4.9.3",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/arm-none-eabi/include/c++/4.9.3/arm-none-eabi",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/arm-none-eabi/include/c++/4.9.3/backward",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/lib/gcc/arm-none-eabi/4.9.3/include",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/lib/gcc/arm-none-eabi/4.9.3/include-fixed",
    "-Ic:/program files (x86)/gnu tools arm embedded/4.9 2014q4/arm-none-eabi/include",
    "-D'__DBL_MIN_EXP__=(-1021)'",

    // ...

    "-D'__QQ_IBIT__=0'",
    "-D'__cpp_init_captures=201304'",
    "-D'__ATOMIC_ACQ_REL=4'",
    "-D'__ATOMIC_RELEASE=3'"
  ],
  "common_flags": [
    "-IC:\\Users\\kblomqvist\\foo",
    "-D'foo=bar'"
  ]
}
```

are generated from the following SConstruct file:

```python
import os

cross = 'arm-none-eabi-'
toolchain = {
    'CC': cross + 'gcc',
    'CXX': cross + 'g++',
    'AR': cross + 'ar',
    'AS': cross + 'gcc',
    'OBJCOPY': cross + 'objcopy',
    'SIZE': cross + 'size',
    'PROGSUFFIX': '.elf',
}

env = Environment(tools=('gcc', 'g++', 'gnulink', 'ar', 'as'), ENV=os.environ)
env.SetOption('warn', 'no-visual-c-missing')
env.Replace(**toolchain)

env.Append(
    CFLAGS='-std=gnu11',
    CPPFLAGS="-std=gnu++14",
    CPPPATH=[Dir('foo')],
    CPPDEFINES=[('foo', 'bar')]
)
```

I know that you have recently been working toward to support default defines and include paths from the used compiler #370. My current prototype uses my own functions to read this info, but can be easily changed to use what's merged to ECC when ready.

Do you think this is something you would like to get into ECC?

**Comment by niosus** [comment]
Hey @kblomqvist 
Thanks for reaching out. 
Let's put it this way. I personally don't even know what SCons is, so I personally would probably avoid creating a complete solution for this. However, once me and @mhoeher merge #372 I would be open to review a PR on this. The main criteria for this PR for me would be that it does not change other major functionality in a significant way, so that I am sure that it does not brake anything. If there is a way to integrate this in a meaningful incapsulated way, I would be happy to see it in, otherwise, it is hard for me to support this change. How does that sound for you? I can notify you once #372 is merged if you are interested.

**Comment by kblomqvist** [comment]
Which ever way you feel comfortable. Ping me when #372 is ready and I create a PR for you to decide. Question. So far I have copy pasted the generated json into user configs, as compile_commands.json doesn't seem to support the same format used in user configs. Do I miss something?

**Comment by mhoeher** [comment]
Hi @kblomqvist,

a `compile_commands.json` file is a JSON file following a specific format as [described here](https://clang.llvm.org/docs/JSONCompilationDatabase.html). It is a standard format used to tell IDEs and other programs how a specific source file can be compiled. Such files usually are produced by build systems like `cmake` (that's also what ECC does: It calls cmake and let it generate such a file).

Your script currently produces a configuration specific to ECC which you have to add to the user or project configuration so it is picked up by ECC.

I am not too familiar with SCons, however, would it be an option to generate a `compile_commands.json` file instead? There are tools like [Build EAR](https://github.com/rizsotto/Bear) which hook into any build system and can generate such a file. The advantages are that such a file also has potentially file-specific flags (which often is the case with more complex projects where without these flags code completion is not delivering accurate results).

**Comment by kblomqvist** [comment]
Hi @mhoeher 

> a `compile_commands.json` file is a JSON file following a specific format as described here. It is a standard format used to tell IDEs and other programs how a specific source file can be compiled.

Thanks for clarifying this. I wasn't aware of it.

> would it be an option to generate a `compile_commands.json` file instead? There are tools like Build EAR which hook into any build system and can generate such a file.

This should be possible and seems like [it has been proposed to be included into SCons](
https://pairlist4.pair.net/pipermail/scons-users/2015-January/003322.html), but was never finalized / reached an agreement. As I dug further, I also found out that [MongoDB has implemented this functionality in their own build scripts](https://github.com/mongodb/mongo/blob/master/site_scons/site_tools/compilation_db.py#L184). Thus I think that this should be either built in to SCons or supported by a tool like Build EAR as hinted by you. Btw. Any idea why compiler default flags are not included into standardized compilation database by CMake?

> Your script currently produces a configuration specific to ECC which you have to add to the user or project configuration so it is picked up by ECC.

Yep. Now when I understand the compilation db thingy, I think that my current implementation should not be added into ECC. Instead I can use it to write options into `.sublime-project` file prefixed by `ecc_` and use that until SCons can support compilation db. Then it can be utilized by ECC. However, first I think I will try to make this to work through Build EAR.

**Comment by mhoeher** [comment]
Hi @kblomqvist,

I think the reason cmake does not include default flags in the compilation DB is, that it usually is not required at all ;-) The question that file answers is basically: *Given a source file, how can I compile it?* The default flags are given kind of implicitly as that file contains the compiler used for each source file. In fact, I think that usually it is a bad idea to set these default flags from the outside when they instead should be set by the compiler itself (as most of these defaults really are toolchain specific and might even vary depending on e.g. configuration options the toolchain has been built with). I guess there are only a few tools (ECC being among them) which can draw benefits from knowing these additional flags (higher quality code completion and more accurate error reporting).

**Comment by niosus** [comment]
So did we reach some conclusion over here? I am confused about the state of this discussion for now.

**Comment by kblomqvist** [comment]
I think we agreed that SCons need to support compilation db before ECC can support it.

**Comment by niosus** [comment]
Ok, then I will close this issue for now.
