### ISSUE TITLE
Auto Complete not working!

### ISSUE THREAD

**Issue by vivekagal1998** [niosus/EasyClangComplete#375]
The auto complete feature of easy-clang is not working...@niosus please help me out...

I am working on Ubuntu 16.04, Sublime Text 3 

![subl](https://user-images.githubusercontent.com/22425848/34341289-d0da7fe2-e9ba-11e7-8178-73c889bf5907.png)

**Comment by niosus** [comment]
What are you trying to achieve here? The plugin will only work in files where the syntax is set to C, C++ or Objective C. In your case you are opening a temporary file and the plugin does not know if it should complete anything in it.

**Comment by niosus** [comment]
I will close this for now. Please reopen if my comment did not help with some more details.
