### ISSUE TITLE
Font size and gutter theme

### ISSUE THREAD

**Issue by BigfootN** [niosus/EasyClangComplete#376]
Hello,

I am having a problem with the font size of the popups, here is a screenshot:

![Imgur](https://i.imgur.com/435wKKK.png)

The font is really too big, and I can't find any settings related to this problem.

Also, I am having a problem with the gutter theme. I correctly set the gutter theme of my choice in my settings but it doesn't seem to load. Here is a screenshot:

![Imgur](https://i.imgur.com/yAK4vrc.png)

The warning icon stays the same whatever the gutter theme I use.

Thank you very much in advance for any help

**Comment by niosus** [comment]
Yeah, the fond size is in works. We will soon use the [markdown popups](https://github.com/facelessuser/sublime-markdown-popups) where the fonts will be handled elsewhere.

As for the icon, are you sure you're not running something like the SublimeLinter? In my experience it can override the icons if it was added after ECC has added its.

**Comment by niosus** [comment]
This is fixed in #386
