### ISSUE TITLE
the c_flags and cpp_flags should be overrided by compile_commands.json

### ISSUE THREAD

**Issue by braindevices** [niosus/EasyClangComplete#378]
When using cmake with `set(CMAKE_CXX_STANDARD 14)` or `set_property(TARGET example PROPERTY CXX_STANDARD 14)`, the compile_commands.json will generate `-std=` option for each target. Thus we need to use that flag instead of the cpp_flag/c_flag in "settings".

`[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-7]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', '-I/usr/include', '-I/tmp/subl_example/src', '-I/usr/lib/clang/4.0.1/include', '-I/tmp/subl_example', '-I/tmp', '-Wall', '-Wextra', '-Og', '-std=gnu++14']
`

Here we can see `'-std=gnu++14'` in the end, but still has the default c++11 at the beginning.

**Comment by niosus** [comment]
Yes, definitely a bug. I've seen it before. Hope to find some time to fix it in the near future.
