### ISSUE TITLE
the clean cmake cache does not work due to singleton failure in mainthread

### ISSUE THREAD

**Issue by braindevices** [niosus/EasyClangComplete#379]
The actual `EasyClangComplete.plugin.flags_sources.cmake_file.CMakeFileCache` is created in sub process. Thus it does not get share into main thread. However the cleanCmakeCommand are run in mainthread. Thus it will always fail due to empty dict.

**Comment by niosus** [comment]
The command should just remove the temp folder with the build files, so it should not be important which thread it is run from. Or do I misunderstand something?

**Comment by braindevices** [comment]
you modify several dict data structure in sub threads, so it should mattered. Since now we only have 1 sub thread, it might not be that critical. But it might in the future. Anyway the singleton does not work as expected due to the re-import stuff. My fix should repair that. And in the future we should be careful about the way we import the modules containing singleton.

**Comment by niosus** [comment]
Hmm, what if we put a singleton in a separate module and will make sure we are not reloading this module? This should fix the issue, right?

**Comment by niosus** [comment]
Oops, closed by mistake.
