### ISSUE TITLE
show only errors instead of all errors and warnings

### ISSUE THREAD

**Issue by braindevices** [niosus/EasyClangComplete#381]
when use libclang it will show all exceptions: warnings and errors. The warnings has severity <=2, the errors are 3. In some projects there are too many warnings and 1 or 2 errors, the current `show all errors` will be flooded by all the warnings.

**Comment by niosus** [comment]
I am hesitant on adding a new setting for this, however, maybe a prefix of error vs warning will suffice as then just typing in "error" in the opened window will be showing errors only. What do you think?

**Comment by braindevices** [comment]
I actually tried the prefix alternative, which is still in the pull request. However, it won't help that much. Please try to imagine  struggling to find 2 errors embedded into hundreds warnnings ... surely I can put some cpp_flags to suppress them but it is annoying. 
I do not understand "adding a new setting". There is no additional setting requires. I just simply add a new command in there, which does not need that much effort. So basically in my pull request, I just use command "show all errors" to show just errors and "show all warns" to show all errs+warns (as the current version). For clang bin completer I just simply add the severity=3 item in each errdict, which is proper since the regex only capture errs. 
If you want I can also spend some time to put a warn regex for it to make them behave same as the libclang completer.

**Comment by niosus** [comment]
Sorry for the delay. Ok, this sounds reasonable. I might change "show all errors" to "navigate errors only" and "show all warns" to "navigate all errors and warnings" or alike.
