### ISSUE TITLE
how to let EasyClangComplete support source type except c++ and objc

### ISSUE THREAD

**Issue by myy1966** [niosus/EasyClangComplete#383]
I want to use EasyClangComplete in cuda, and I add CUDA c++ package to hightlight cuda. When I open cuda source file *.cu, their scope is "source.cuda-c++", so I add "source.cuda-c++" to Preferences.sublime-settings:
```
{
  // DO NOT MODIFY!
  // Your changes will be overwritten upon plugin update.
  // To change the triggers, copy these lines to your user preferences.
  "auto_complete_triggers":
  [
    {
      "selector": "source.c++ - string - comment - constant.numeric",
      "characters": ".>:",
    },
    {
      "selector": "source.c - string - comment - constant.numeric",
      "characters": ".>:",
    },
    {
      "selector": "source.objc++ - string - comment - constant.numeric",
      "characters": ".>: ",
    },
    {
      "selector": "source.objc - string - comment - constant.numeric",
      "characters": ".>: ",
    },
    {
      "selector": "source.cuda-c++ - string - comment - constant.numeric",
      "characters": ".>: ",
    }
  ],
}
```
But that's useless, I still can not use EasyClangComplete in cuda source file, so how can I do to let EasyClangComplete support source type except c++ and objc?

My sublime version is 3 Build 3143
My EasyClangComplete version is 4.30

**Comment by niosus** [comment]
For now the languages that ECC supports are hardcoded. Check it out [here](https://github.com/niosus/EasyClangComplete/blob/master/plugin/tools.py#L487). Just add the cuda syntax so that ECC understands it is actually c++ and submit a PR.

**Comment by myy1966** [comment]
@niosus Thank you!
So is the "Preferences.sublime-settings" a useless file?

**Comment by niosus** [comment]
No, it is not. It is needed to specify any additional characters that should trigger completion.
