### ISSUE TITLE
Support CppProperties.json and c_cpp_properties.json from Microsoft

### ISSUE THREAD

**Issue by mclayton7** [niosus/EasyClangComplete#384]
I'd like to add support for a couple of Microsoft's project specification files (both in a similar ``json`` format). At work, we use [waf](https://github.com/waf-project/waf) to generate ``CppProperties.json`` files for each folder, and I'd like to use EasyClangComplete to parse them and provide auto completion.

I needed ``CppProperties.json`` support, but went ahead and added ``c_cpp_properties.json`` support because of the similarities of files.

- [CppProperties.json](https://blogs.msdn.microsoft.com/vcblog/2017/11/02/customizing-your-environment-with-visual-c-and-open-folder/) is used by Visual Studio as part of its "open folder" concept. It's a pretty simple file that provides include paths and defines.

- [c_cpp_properties.json](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md) is a configuration file commonly generated with Visual Studio Code that's at the root level of a project.

**Comment by niosus** [comment]
Sure, this sounds reasonable. I will have a look at the PR soon. Please make sure the tests don't fail in the meantime.

**Comment by niosus** [comment]
Closing as the functionality has reached master from #385 
Thanks for the contribution!
