### ISSUE TITLE
Incorrect suggestion while accessing vector's functions

### ISSUE THREAD

**Issue by Posto578** [niosus/EasyClangComplete#387]
Apparently plugin can not suggest completions after "." (dot). Everything goes fine If I look for global functions but It can not list class'functions like vector.push_back();
# Please do this before submitting: #
- [x ] check for already solved issues
- [x ] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `3.0`
- which system are you on: `OSX`

# What I need to help you: #
- The best way is to provide a minimal example that illustrates the issue in a small repo on GitHub. This way, I can probably run it on my machine and solve it locally.
- If you can't create it, please provide a full log output from the plugin. Without it I cannot do anything. To capture the log:
    + set `"verbose": true` in plugin settings
    + restart Sublime Text
    + open the file or do the action that causes trouble
    + open console with <kbd>Ctrl</kbd>+<kbd>P</kbd>
    + copy *full* output to a text file and link it to this issue

[log.txt](https://github.com/niosus/EasyClangComplete/files/1636535/log.txt)
![optimisticellipticalarchaeopteryx-size_restricted](https://user-images.githubusercontent.com/35492119/35009237-43607f6c-faff-11e7-9512-57e067cfed79.gif)

**Comment by mclayton7** [comment]
Hi, can you try getting the logfile again? You can actually access the console with <kbd>Ctrl</kbd>+<kbd>`</kbd>. The log should look something like this:
```
DPI scale: 2.5
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/user/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/user/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/user/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0955659
startup time: 0.187566
first paint time: 0.195566
reloading plugin Default.auto_indent_tag
reloading plugin Default.profile
reloading plugin Default.quick_panel
...
reloading plugin EasyClangComplete.EasyClangComplete
plugins loaded
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[MainThread]: on_activated_async view id 25
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 25. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v
...
```

**Comment by mclayton7** [comment]
I'm betting it's messing up because the libc++ headers on OSX aren't in the include path by default. You can try adding the path to them in the EasyClangComplete settings under ``common_flags``.

This might help you find the path: [https://stackoverflow.com/questions/20848341/where-are-libc-headers-located-on-mac-os-x-mavericks](https://stackoverflow.com/questions/20848341/where-are-libc-headers-located-on-mac-os-x-mavericks)

**Comment by Miszo97** [comment]
For everyone who has similar problem. Make sure you know well where libc++ headers on OSX are.
Basically there are should be at 
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`
Keep in mind also that if you want to have **C++14** standard support you have to change standard in settings. 
The following setting should do the work.

@mclayton7 Thanks a lot for clarification. The problem was wrong patch to libs. 👍 

This is a part of my settings which made everything work. :)
```
  "common_flags" : [
    // some example includes
    "-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
    "-I/usr/include",
    "-I$project_base_path/src",
    // this is needed to include the correct headers for clang
    "-I/usr/lib/clang/$clang_version/include",
  ],
  // C specific flags. Prepend common_flags for C files.
  "c_flags" : [ "-std=c14" ],
  // C++ specific flags. Prepend common_flags for C++ files.
  "cpp_flags" : [ "-std=c++14" ],
  // Objective-C specific flags. Prepend common_flags for Objective-C files.
  "objective_c_flags" : [ "-std=c14" ],
  // Objective-C++ specific flags. Prepend common_flags for Objective-C++ files.
  "objective_cpp_flags" : [ "-std=c++14" ],
```

**Comment by niosus** [comment]
Hey guys, glad this got resolved. The front of works is pretty big and I have fewer and fewer time for the plugin unfortunately, but this seems to be related to #274 

At some point there should be a clear tutorial on how to use the plugin.
