### ISSUE TITLE
The "capture log" part of the issue text doesn't have correct key commands

### ISSUE THREAD

**Issue by mclayton7** [niosus/EasyClangComplete#388]
# Please do this before submitting: #
- [x] check for already solved issues
- [x] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `3143`
- which system are you on: `Windows 10`

# What I need to help you: #
- The best way is to provide a minimal example that illustrates the issue in a small repo on GitHub. This way, I can probably run it on my machine and solve it locally.
- If you can't create it, please provide a full log output from the plugin. Without it I cannot do anything. To capture the log:
    + set `"verbose": true` in plugin settings
    + restart Sublime Text
    + open the file or do the action that causes trouble
    + open console with <kbd>Ctrl</kbd>+<kbd>P</kbd>
    + copy *full* output to a text file and link it to this issue

===
I believe the **open console** line above in the help text should be <kbd>Ctrl</kbd>+<kbd>`</kbd> instead of <kbd>Ctrl</kbd>+<kbd>P</kbd>

**Comment by niosus** [comment]
Ooops, you're right. Let me change that.
