### ISSUE TITLE
How to let EasyClangComplete with Chromium

### ISSUE THREAD

**Issue by philong6297** [niosus/EasyClangComplete#392]
Im using Windows and currently working with Chromium. I generated compile_commands.json file with this command:
```cmd
ninja -C out/Default -t compdb cc cxx objc objcxx > out/Default/compile_commands.json
```
And this is my setting:
```json
	"common_flags":[
		//for chromium path
		"-IF:/chromium/src",
		// my clang version 
		"-IC:/Program Files/LLVM/lib/clang/5.0.1/include"
	],
	 // C specific flags. Prepend common_flags for C files.
  "c_flags" : [ "-std=c11" ],
  // C++ specific flags. Prepend common_flags for C++ files.
  "cpp_flags" : [ "-std=c++14" ],
    "flags_sources": [
    {"file": "CMakeLists.txt"},
    {"file": "compile_commands.json"},
    {"file": ".clang_complete"},
//my compile_commands file path
    {"file": "compile_commands.json", "search_in": "F:\\chromium\\src\\out\\Debug"},
  ],
```
But im getting these issues:
![capture](https://user-images.githubusercontent.com/29605147/35179434-c47fb5b6-fdcc-11e7-887d-0b943ee790e3.PNG)

so my question is how can I use this excellent plugin in chromium.

**Comment by mclayton7** [comment]
Hi, I'm not familiar with the chromium setup, but I do notice a few things that you can try to solve the problem:

1. It looks like your ``compile_commands.json`` path is ``out/Default/compile_commands.json``, but you're searching for it in ``F:\\chromium\\src\\out\\Debug``. Does changing the search path to ``F:\\chromium\\src\\out\\Default`` fix it?
2. Does the ``teset_ui.cc`` translation unit exist in the generated ``compile_commands.json``? If it's a new file, you'll have to re-run the generator to update the ``compile_commands.json`` for it to work.
