### ISSUE TITLE
Show class documentation before its definition in tooltip

### ISSUE THREAD

**Issue by papadokolos** [niosus/EasyClangComplete#393]
## Suggestion
When hovering over a class symbol, an informative popup shows the entire class definition. While this is a nice feature, it pushes the class documentation down to the bottom of the tooltip. This usually requires a lot of scrolling, which makes it less nice...

I suggest to re-order the tooltip categories, and to put the class documentation before the class definition.

I believe that in most use cases of this tooltip, the user looks for the class documentation rather than its definition - since the definition is usually large, and is better examined in a big space which requires less scrolling and provides syntax highlighting (like a separate tab, or an output panel).

**Comment by niosus** [comment]
Yep, this was annoying me to and is already fixed in #386 PR. Will land soon. I will keep it open until it hits master.

**Comment by niosus** [comment]
Closed with #386
