### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mjbogusz** [niosus/EasyClangComplete#401]
- Sublime Text version: `3.0, build 3143`
- which system are you on: `Linux x86_64 (Arch Linux)`

There's apparently a leak in ECC, as `plugin_host` can easily eat even over 1GB of RAM and disabling ECC prevents that from happening.
Restarting Sublime obviously helps, but that's a workaround.

It seems to happen when working on a cmake-based project that fail during cmake phase.
Specifically, the project causing problems uses cmake modules/packages not found in default paths - for building I'm manually sourcing the toolchain setup script in terminal but it takes too long to put it into `.profile` or wherever for ECC to use.

Opening even a single file in this project causes `plugin_host` to suddenly jump from ~45 to as high as 462MB (!) droping only by about 20 after closing said file (or even the whole project, assuming there's at least one more Sublime window). Each next opened file from that project - more unfreed RAM.

The (seemingly) most important part from log:
```
[ECC:INFO   ]: cmake produced output: 
-- Detected architecture: amd64, no additional flags
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/EasyClangComplete/cmake_builds/1f45afec840eeea8f826fefbf0c0a45d/CMakeFiles/CMakeOutput.log".

[ECC:ERROR  ]: cmake has finished, but no compilation database.
```

**Comment by niosus** [comment]
Yeah, this is a known issue to me and I have been tracking this for quite a while now.
I don't think it is related to cmake really as I have experienced it with a completely different system setups. 

This plugin ended up using some complex machinery. It is spawning subprocesses and heavily uses ctypes. At this point it is hard for me to assess where the leak is happening. It is probably in the way objects are handles cross-threads or, alternatively, it can be even within the libclang bindings and clang not releasing memory correctly. 

I've spent a considerable amount of time searching for the root cause (and have found plenty) but I have to admit that I have failed for now. I will keep digging this though. If you have a suggestion on where this might happen or on the tools that can be used in python for this purpose, please do not hesitate to post them here.

**Comment by snippins** [comment]
I have similar issue, but in my case cmake build runs fine, everything seems normal and works great. Sadly closings files hardly free any memories.

**Comment by niosus** [comment]
@snippins yeah, you're right. I have removed the mention of cmake from this issue. 
I have tried a bunch of things to track it down like printing the dependency graph or trying to see if the garbage collector is doing its thing. There is a branch `further_memoery_leak_crackdown` that tracks some of these changes. Unfortunately, I did not find what exactly is leaking.

If anyone stumbles upon this who has a magical way of debugging memory leaks related to python and ctypes, I will take all the help that I can. I am no expert in Python and even less so in ctypes, so any help would be appreciated. For now, I am out of ideas. My best guess, for now, is that libclang keeps translation units in memory, but I do not understand exactly why or how that happens.

Also, let me link another issue that I have opened before: #286

**Comment by mjbogusz** [comment]
Maybe it was mentioned somewhere already, but have you tried Valgrind? [This SO answer](https://stackoverflow.com/questions/12666153/how-to-find-leaks-in-python-ctypes-libraries#12666626) has some useful links for setting it up with python.

**Comment by niosus** [comment]
I have tried it really briefly, but as discussed in that SO answer it does produce a lot of false positives. I might give it another try in the future.

**Comment by KingKili** [comment]
Since I leak multiple gigabyte, I tried to the issue down. The only thing I found out that if I set 
> "use_libclang" : false

I go from leaking 200 MB per open file to about 1 MB per open file. @niosus does this information help you by any means? Do you have an suggestion where I should continue to look for the leak?

**Comment by niosus** [comment]
Yeah, when not using libclang there are only calls to clang binary that terminate after every call and no information is kept. When using libclang we interface with it using its python bindings. At this point I am fairly confident there is no leak in the plugin, just that libclang holds on some translation units which are actually quite big.

**Comment by KingKili** [comment]
After trying all possible things trying to find the leak, I share your opinion that the leak is probably not in the plugin. But I would say there is definitely one, presumably in libclang. For example if instantly after the [line](https://github.com/niosus/EasyClangComplete/blob/0d0e4338c31e8fcffd9809cbce9d8a02b0e69fe2/plugin/completion/lib_complete.py#L171) delete the translation unit again, the memory stays allocated until I close Sublime Text. Also, I have never seen the memory consumption fall.
