### ISSUE TITLE
Support Xcode 9.3

### ISSUE THREAD

**Issue by saagarjha** [niosus/EasyClangComplete#405]
# Please do this before submitting: #
- [X] check for already solved issues
- [X] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `Version 3.0, Build 3143`
- which system are you on: `macOS High Sierra 10.13.4 Beta (17E139j)`

New beta of Xcode, new version of LLVM:
<img width="532" alt="screen shot 2018-01-26 at 21 21 32" src="https://user-images.githubusercontent.com/13786931/35469024-d21942c8-02e0-11e8-9f56-8d4e1b6860a7.png">
I'm currently setting it to 4.0 as a workaround (https://github.com/saagarjha/EasyClangComplete/commit/5112c867354a609184c3809f885b903ab61f7902), but I'm not sure what version of clang Xcode is actually based on.

**Comment by niosus** [comment]
Well, that's the thing, nobody knows this anymore :) We can guess, but that's it. If 4.0 works for you I can push a new version with this change. Unfortunately, Apple Clang is going in a different direction from the LLVM Clang.

**Comment by niosus** [comment]
Fixed in the PR referenced above.

**Comment by saagarjha** [comment]
Thanks!
