### ISSUE TITLE
Timer for tooltips seems to not work correctly

### ISSUE THREAD

**Issue by saagarjha** [niosus/EasyClangComplete#412]
# Please do this before submitting: #
- [X] check for already solved issues
- [X] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `Version 3.0 Build 3143`
- which system are you on: `macOS High Sierra 10.13.4 Beta (17E139j)`

The timer for autohiding/autoshowing tooltips doesn't seem to be working correctly since around 5.0. In particular, when hovering over a method definition, the tooltip show up but fails to hide after a delay when the cursor is moved off of the definition. For errors that show up in the sidebar, the tooltip doesn't show up at all until clicked; then it fails to hide unless it loses focus.

**Comment by niosus** [comment]
I'm not really sure what exactly you are talking about. There was never a timer in the first place. Before we had two mechanisms of showing the errors: tooltips that would only show if the cursor is in the line with the error and phantoms that were showing all the time right under the error. There were a lot of issues with the tooltips and I decided to move away from default sublime's ones to use `mdpopups` instead. Also, I have completely removed the phantoms as I do not have enough time unfortunately to support both cases, especially considering that I am not using the phantoms.

There is a command <kdb>Ctrl</kbd>+<kdb>Shift</kbd>+<kdb>e</kbd> to show all errors that are currently active and to navigate to them.

**Comment by niosus** [comment]
I'm not really sure what exactly you are talking about. There was never a timer in the first place. Before we had two mechanisms of showing the errors: tooltips that would only show if the cursor is in the line with the error and phantoms that were showing all the time right under the error. There were a lot of issues with the tooltips and I decided to move away from default sublime's ones to use `mdpopups` instead. Also, I have completely removed the phantoms as I do not have enough time unfortunately to support both cases, especially considering that I am not using the phantoms.

There is a command <kdb>Ctrl</kbd>+<kdb>Shift</kbd>+<kdb>e</kbd> to show all errors that are currently active and to navigate to them.

**Comment by saagarjha** [comment]
The issue is that the tooltips (mdpopup or whatever you're using) don't hide when the cursor is moved away, like Sublime Text's tooltips did. They just stay there until you click something else.

**Comment by niosus** [comment]
Ok, got it. Will see what I can do in the upcoming days.

**Comment by niosus** [comment]
Should be as simple as passing `sublime.HIDE_ON_MOUSE_MOVE_AWAY` in `flags` variable when showing info popups. Will land by the end of the week, I guess.

**Comment by saagarjha** [comment]
Thanks for looking into this!

**Comment by niosus** [comment]
Landed in master and will be released soon.
