### ISSUE TITLE
ECC constantly emits "Your source generated settings define too many std flags" warning

### ISSUE THREAD

**Issue by mhoeher** [niosus/EasyClangComplete#417]
Since the last update, ECC generates the following warning regularly for some files in a project:

```
Your source generated settings define too many std flags:
[(-std=c++98), (-std=gnu99), (-std=c99)]

Please fix your settings.
```

This happens for:

* Files, which do not directly appear in the `compile_commands.json` file and where no fitting single source file can be derived. In this case, ECC merges flags from all over the project.
* Non-C/C++ files.

For the second point, I guess this could be solved by disabling ECC for non-C/C++ files somehow.

For the first point, I am not sure how this could be solved in a good way. Merging all flags of a project only works if the project in itself is set up in a "uniform" way. However, for large CMake projects which potentially include third party sub-modules, this cannot be guaranteed. This is where the different `-std` flags are coming from (in the example given, you can see that the project is a mixed C/C++ one and there is basically no way to "fix" the project settings ;-) ).

As a mitigation, I think that ECC should not show a dialog but use a less intrusive way to report the issue (currently, editing an affected file is quite difficult, as the warning pops up quite regularly).

**Comment by niosus** [comment]
Ok, I got the point. We can for now just log this to the console.

**Comment by haylingsailor** [comment]
I'm getting something very similar, which also started a few days ago. The message i'm getting is:

[ECC:INFO   ]: init completer based on libclang
error: 
Your `lang_flags` settings define too many std flags:
[(-DASIO_STANDALONE), (-DRAPIDJSON_HAS_STDSTRING=1)]

**Comment by niosus** [comment]
@haylingsailor Oh, this is definitely a different bug with the way I detect the std flags. I will open a separate issue for that.

**Comment by haylingsailor** [comment]
Thanks!
