### ISSUE TITLE
Infer compiler flags based on folder hierarchy

### ISSUE THREAD

**Issue by VeaaC** [niosus/EasyClangComplete#423]
When working with header-only (or header-mainly) libraries ECC is (mostly) not working: There are no (or few) CPP files it can derive the flags from.

A strategy I had tried successfully with ClangAutoComplete was to infer the flags from the folder hierarchy:
- Each folder inherits all flags from all files/sub-folders in it
- If a header file is compiled, and no matching CPP found, just take the flags from the closest folder in the path

This worked nicely for many environments/libraries (and even for CPP files, which could drastically shrink the compile flag database: just flags per folder).

Would it be an option to also add this feature to ECC?

**Comment by niosus** [comment]
Making the plugin useful for header only libraries sounds useful.
However, every solution that we can do will be a hack and while it might work for you it will probably not work for other people.

I will think about it and maybe we could extend the way we search for the source files that accompany the headers to accommodate your use case, but it will definitely take some time.

**Comment by VeaaC** [comment]
This is not limited to header-only libraries (it is just most visible there). Man libraries I work with have the following pattern:
- A.cpp + A.h
- B.h + B.inl
- C.h

Some files do not have a CPP, usually: templates, PODs (getter/setter inline), definitions/constants.

Obviously finding out the correct compile flags is really hard in this situation (basically you would need to find one CPP file that includes (transitively) the header file you want to compile).
However, offering some approximation as a fallback would improve this already drastically.

Basing the compiler flags on the folder hierarchy (basically inferring them from the first CPP it shares a parent with) was the easiest thing I could think of.
Other possibilities: Compilation output includes usually dependencies (A.cpp also needs B.h + C.h) for incremental builds.

**Comment by merlinthered** [comment]
The problem with templates is that they cannot be compiled before they are instantiated. Instantiation usually doesn't happen in the header file that defines the template. This makes it impossible for clang to generate completions. It cannot guess which type you are going to instantiate the template with, and the template's behavior might change completely depending on that type. Guessing compiler flags won't help this issue. Having completions for non-template code in headers would be nice though.

**Comment by niosus** [comment]
I guess in any real project there is at least some system on where to search the cpp file with respect to the header file. For that you can already use a setting provided by plugin. Check out relevant setting here:
https://github.com/niosus/EasyClangComplete/blob/947cc3180bde15cd8114f5090e72027360a48b92/EasyClangComplete.sublime-settings#L121-L155

I feel that this can solve most of the issues in most project. I am hesitant to implement a new strategy that will be custom for this plugin. It is really hard to make people aware of obscure features and this code already struggles with being way to complex to get started with to my taste.
