### ISSUE TITLE
Multiple definitions in different files cause the definition to show up as Not defined

### ISSUE THREAD

**Issue by TediumRemedy** [niosus/EasyClangComplete#424]
Sublime text 3
MacOS 10.13.2

Hello,
When a project contains multiple header files, that contain the same (macro) definition, the EasyClangComplete says that these macros are undefined. A sample Makefile-based project (it is autogenerated using an embedded project configuration tool, called STM32CubeMX) can be found here:

https://github.com/TediumRemedy/SonarTest

In this project,  in main.c the EasyClangComplete marks macro definition FLASH_LATENCY_2 (and many others) as undefined - even though FLASH_LATENCY_2 is defined in header files
Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_system.h

and in

Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_flash.h

**The Drivers/STM32F1xx_HAL_Driver/Inc/ is specified in .clang_complete, as well as all other subdirectories, that contain .h files. The .clang_complete is located in the sublime text's project root directory**

Here's what I get:
<img width="949" alt="screen shot 2018-02-05 at 9 51 59 pm" src="https://user-images.githubusercontent.com/5770542/35825546-e2a4f476-0abe-11e8-9928-69223c26c68d.png">

Is there anything that can be done to make EasyClangComplete correctly process multiple definitions of a macro in different files? Like, provide a dropdown list of suggestions, or at least pick the first (or the last) macro definition found and ignore all the following ones?

Thanks!

**Comment by niosus** [comment]
I am confused here. If I understand correctly you have a redefinition of a macros in multiple files that are all included into another file? Then clang has no way to find out which of those you mean when you type the name of this macros. It then has nothing to do with the plugin itself.

Or did I misunderstand the issue?

**Comment by TediumRemedy** [comment]
@niosus 
the headers that redefine a macro are not necessarily all included. They are just present in the directories, that are listed in  **.clang_complete** file.
This seems to be enough for the plugin (or clang?) to get confused.
Unfortunately, I am not exactly sure how clang works when parsing the header files.

If you could open https://github.com/TediumRemedy/SonarTest with the Sublime Text, you would see the problem: there are a lot of "undefined" errors by the ECC, even though they are defined in various header files, whose directories are listed in .clang_complete.

I am using this command to find out in what files the macro is defined (all the header files are located in "Drivers" in my SonarTest project:
`grep -r Drivers -e "FLASH_LATENCY_2"`

========
Also, just wondering, what if the same macro is redefined in the same file, is there any way to make clang return a completion choice, suggesting all the redefinitions? ECC then could show these options in a drop down menu or something?

**Comment by niosus** [comment]
Ok, let me have a look at this and come back to you. Just having all of the files with the same macros in the include search path should not be the issue. However, If you define multiple macro in a single file with the same name this is a c++ error and therefore the plugin cannot function properly as the code does not compile.

**Comment by TediumRemedy** [comment]
@nisous
if a macro is defined multiple times, the code should compile (if this is just a macro, it can be redefined, unlike a function/variable, that must be defined only once). Try this code, for example:

```
#define DEFINITION 1234
#define DEFINITION 2345

int main() {
    printf("%d", DEFINITION);
    return 0;
}
```

It would compile, but the EasyCLangCompletion wouldn't work properly...

**Comment by TediumRemedy** [comment]
@niosus 
Macros can be redefined multiple times, I think you meant variables/functions that cause compiler errors?

```
#define A 123
#define A 234
printf("%d", A);
```

**Comment by TediumRemedy** [comment]
If necessary, I can also submit a log, if that helps to understand what is going on?

**Comment by niosus** [comment]
Ok, right, of course it doesn't cause the code to fail, I used completely wrong wording for this. The preprocessor has some rules dealing with the redefined macros. Citing the [gcc online docs](https://gcc.gnu.org/onlinedocs/cpp/Undefining-and-Redefining-Macros.html):

> If a macro is redefined with a definition that is not effectively the same as the old one, the preprocessor issues a warning and changes the macro to use the new definition. If the new definition is effectively the same, the redefinition is silently ignored. This allows, for instance, two different headers to define a common macro. The preprocessor will only complain if the definitions do not match. 

So, for example this code:
```
#define BLAH 10
#define BLAH 20
```
Causes a warning that the macros is redefined. This should not cause a failure by itself. This plugin should behave exactly like your compiler given all the compiler flags are set correctly. 

Looking at your project, it seems that it is a configuration issue. What are you building your project with? If you can generate a compilation database with `cmake` or `bear make` do that as it will guarantee the correct include folders. I see that in your code it cannot find some macroses and types like `uint32_t` which is an indicator that some include file is missing or the compiler is confused. You might want to use `use_target_compiler_built_in_flags` set to true and setting `target_cpp_compiler` to the one you are using.

Unfortunately, I cannot dig deeper inside of this problem. You have a quite specific setup and at this point there is not much I can help you with, so I am afraid I will have to ask you to figure out what went wrong on your own. Feel free to post what was wrong here if you do find how to make it work.
