### ISSUE TITLE
Generate completion database remotely but autocomplete locally

### ISSUE THREAD

**Issue by merisanualex** [niosus/EasyClangComplete#427]
I have a very specific working environment, which is to edit files locally and have sublime rsync them to a remote server where it is possible to build the application (on the local machine it is not possible due to lots and lots of dependencies I cannot install).
Would it be possible to have the plugin run clang over ssh to generate the completion database and autocomplete on the local machine ? Or would it be too complicated ?

**Comment by niosus** [comment]
I would imagine the runtime of this will be awful. 
Probably it will be a huge pain to adapt libclang for that if at all possible, so using clang binary sounds like the only option and it doesn't sound easy either.

So for now I would say, that I am skeptical as to how useful it might be even if possible.

**Comment by merisanualex** [comment]
Was worth a shot.. thank you for your answer !

**Comment by niosus** [comment]
Ok, I will throw this to a backlog and if ever there is time, maybe we will return to this. :)
