### ISSUE TITLE
Does not work out of the box

### ISSUE THREAD

**Issue by c0nd3v** [niosus/EasyClangComplete#428]
I'm on windows, installed clang 5.0.1, installed easyclangcomplete and it was unable to find libclang. I spent time messing with all of the settings and got it to partially work, but lets say I did:

std::vector<int> hello;
hello.    <-------------- NO AUTOCOMPLETE

Thank you.

**Comment by niosus** [comment]
Please follow the guide when creating issues. I cannot guess what the problem is, but I can read the log.
