### ISSUE TITLE
Correctly show type info without saving

### ISSUE THREAD

**Issue by DoktorStein** [niosus/EasyClangComplete#429]
**EasyClangComplete** appears to display type information only after saving the file. It would be very useful if it could display type information in real time, like Intellisense of Visual Studio Code does.

**Comment by niosus** [comment]
I don't fully understand what you mean by "the way Intellisense of Visual Studio Code works". As far as I know, VSC still does not have clang based completion for C++ code. 

The way, this plugin works is it tries to build a translation unit using libclang. Before we have a translation unit, there is nothing we can do better than suggesting completions based on the contents of the file (not semantics of the language).

Could you clarify what exactly you expect the plugin do?
