### ISSUE TITLE
macOS unittests hang when using "UnitTesting: Test Current Package" 

### ISSUE THREAD

**Issue by kjteske** [niosus/EasyClangComplete#431]
# System info: #
- Sublime Text version: `3.0, build 3143`
- Which system are you on: `macOS High Sierra 10.13.3`

# What happens:  #
If I have a single test file open, e.g. test_error_vis.py, and run the "UnitTesting: Test Current File" command, everything runs just fine for that file.
But if I use the "UnitTesting: Test Current Package" command, then tests hang in an infinite loop in `GuiTestWrapper.set_up_view()`. `self.view.isLoading()` returns `True` forever.
I'm not sure why "Test Current File" would work, but not "Test Current Package". A few weeks ago, this reproduced locally, but not in the Travis CI. Now, I've seen a  failure in Travis CI "Timeout: Sublime Text is not responding" at https://travis-ci.org/niosus/EasyClangComplete/jobs/340200817 that may or may not be related to this.

I can't view the console log, because the Sublime UI hangs entirely.

I remember this working fine ~6 months ago, but this has been broken for at least the last 3 weeks.

**Comment by niosus** [comment]
Its the same here. I had it for some time looong time ago, see SublimeText/UnitTesting#45 

I believe we should report it there. The workaround that works for me is not to call "Test Current Package" but rather just call "UnitTesting" and then input the name of the package when the prompt appears. This way it works. 

I will close this as I don't believe it is related to this plugin.
