### ISSUE TITLE
Enable plugin for custom syntaxes

### ISSUE THREAD

**Issue by YeshaMaggi** [niosus/EasyClangComplete#432]
Took me awhile to trace ECC not working to a conflict with my custom syntax.
There have been some past similar issues [#36](https://github.com/niosus/EasyClangComplete/issues/36), [#43](https://github.com/niosus/EasyClangComplete/issues/43), [#302](https://github.com/niosus/EasyClangComplete/issues/302).

I was wondering if there could be a setting "valid_syntax", or perhaps more appropriately "c_syntax", "cpp_sytax", etc. That way this could be user defined, not fixed individually by you per request.

I was looking through the code, interested in adding this feature myself, until I found the dilemma. ECC checks for valid syntax BEFORE loading the settings (and probably many other functions). Is this something that could be worked around? Is it worth the efficiency of ECC loading settings to run this check while working with undesired syntaxes?

I solved my immediate issue by renaming my custom syntax, but let me know if this could be implemented.

**Comment by niosus** [comment]
This sounds reasonable to me. I will have a look and get back to you after that.
