### ISSUE TITLE
file encoding is gbk not work

### ISSUE THREAD

**Issue by sduwww** [niosus/EasyClangComplete#436]
# Please do this before submitting: #
- Check for already solved issues
- Try restarting Sublime Text
- Remove this header and fill info below the line

# Create minimal example if you can #
If you can create a minimal example and link it here.
- Ideally it should compile on Linux
- It must work if I build it from the terminal

# Copy the log #
To capture the log:
- Set `"verbose": true` in plugin settings
- Restart Sublime Text
- Open the file or do the action that causes trouble
- Open console with <kbd>Ctrl</kbd>+<kbd>`</kbd>
- Copy *full* output to a text file and link it to this issue
- Or copy it below under `<LOG GOES HERE>`
-
--------------------------------------------------------

# System info: #
- Sublime Text version: `<here>`
- Which system are you on: `<here>`

# What happens:  #
Describe your issue here.

<details>
<summary>Log that illustrates the issue: </summary>
```
<LOG GOES HERE>
```
</details>

**Comment by sduwww** [comment]
st3 3156, win7, set verbose true, ctrl +’ output is “UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0xd6 in position 96: invalid continuation byte”

**Comment by niosus** [comment]
Please make sure to follow the guide provided in issue template. Read it carefully, please. Please resubmit the issue with needed information and following the issue template.
