### ISSUE TITLE
Add support for clang-6

### ISSUE THREAD

**Issue by papadokolos** [niosus/EasyClangComplete#446]
Hello! :smile: 

First, I would like to thank you (again) for your amazing plugin. It works very nicely :+1: 

Recently there has been released a new version of clang, clang 6! From initial insception, it seems like this plugin uses a dedicated `cindex.py` file for each clang's version. So, would it be possible to add support for the new version of clang?

Thank you very much for your hard work,
it makes mine much easier :stuck_out_tongue_winking_eye:

**Comment by niosus** [comment]
Should already work out of the box (although a bit hackily implemented). Definer here: https://github.com/niosus/EasyClangComplete/blob/fec98b15dbdd6b1518c9da193cb6ba9af111a9d5/plugin/completion/lib_complete.py#L37

Does it not work for you?

**Comment by papadokolos** [comment]
You're right, it does work :laughing: 
I should have just checked it instead of "scanning" the source code.
Thanks!
