### ISSUE TITLE
EasyClangComplete can't work.

### ISSUE THREAD

**Issue by yhzhm** [niosus/EasyClangComplete#448]
# Create minimal example if you can #
```
#include <iostream>
#include <string>
using namespace std;
int main()
{
	string s;
	cin >> s;
	cout << s;
	return 0;
}
```

# Copy the log #
`DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/tools/Sublime Text Build 3143 x64/sublime_text.exe
working dir: /C/tools/Sublime Text Build 3143 x64
packages path: /C/tools/Sublime Text Build 3143 x64/Data/Packages
state path: /C/tools/Sublime Text Build 3143 x64/Data/Local
zip path: /C/tools/Sublime Text Build 3143 x64/Packages
zip path: /C/tools/Sublime Text Build 3143 x64/Data/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.104645
startup time: 0.160644
first paint time: 0.163644
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin SublimeAStyleFormatter.AStyleFormat
plugins loaded
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[MainThread]: on_activated_async view id 25
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 25. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[MainThread]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[MainThread]: settings initialized for view: 25
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-4]: generate new config for path: 25
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-4]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-4]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-4]: platform: ('64bit', 'WindowsPE')
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-4]: python version: 3.3.6
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-4]: we are on 'Windows'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-4]: user provided libclang_path: “C:\Program Files\LLVM\bin\libclang.dll
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-4]: searching for: 'libclang.dll'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-4]: libclang search output = 'C:\Program Files\LLVM\bin\'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-4]: real output: C:\Program Files\LLVM\bin\
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-4]: architecture: ('64bit', 'WindowsPE')
[ECC:INFO]:[utils.py]:[find_libclang_dir]:[Thread-4]: found libclang library file: 'C:\Program Files\LLVM\bin\libclang.dll'
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-9]: view file_name is None
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-4]: [cmake]:[get]: for file E:\Practice\test.cpp
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-4]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-4]: searching 'CMakeLists.txt' from 'E:\Practice' to 'E:\\Practice'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-4]: found 'CMakeLists.txt' file: E:\Practice\CMakeLists.txt
[ECC:DEBUG]:[tools.py]:[contains]:[Thread-4]: found needed line: 'project(Practice)
'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-4]: [cmake]:[current]: 'E:\Practice\CMakeLists.txt'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-4]: [cmake]:[generate new db]
[ECC:DEBUG]:[cmake_file.py]:[__compile_cmake]:[Thread-4]: Folder c:\users\admini~1\appdata\local\temp\EasyClangComplete\cmake_builds\267bcbb15ed11ede809051777840abbd exists.
[ECC:DEBUG]:[cmake_file.py]:[__compile_cmake]:[Thread-4]: prefix paths: []
[ECC:DEBUG]:[cmake_file.py]:[__compile_cmake]:[Thread-4]: merged paths: 
[ECC:DEBUG]:[cmake_file.py]:[__compile_cmake]:[Thread-4]: CMAKE_PREFIX_PATH: 
[ECC:DEBUG]:[cmake_file.py]:[__compile_cmake]:[Thread-4]:  running command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "E:\Practice"
exception calling callback for <Future at 0x3ac1f28 state=finished raised UnicodeDecodeError>
Traceback (most recent call last):
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\tools.py", line 680, in run_command
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command 'cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "E:\Practice"' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 385, in config_updated
    log.debug("updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 462, in load_for_view
    config = ViewConfig(view, settings)
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 68, in __init__
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 183, in __generate_essentials
    source_flags = ViewConfig.__load_source_flags(view, settings, prefixes)
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 294, in __load_source_flags
    flags = flag_source.get_flags(view.file_name(), search_scope)
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\flags_sources\cmake_file.py", line 114, in get_flags
    target_compilers=self.__target_compilers)
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\flags_sources\cmake_file.py", line 211, in __compile_cmake
    command=cmake_cmd, cwd=tempdir, env=my_env)
  File "C:\tools\Sublime Text Build 3143 x64\Data\Packages\EasyClangComplete\plugin\tools.py", line 683, in run_command
    output_text = e.output.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 8: invalid start byte
Package Control: Skipping automatic upgrade, last run at 2018-04-02 08:15:30, next run at 2018-04-02 09:15:30 or after
`

# Fill the gaps below this line and remove all text above it #
--------------------------------------------------------------

# System info: #
- Sublime Text version: `<3143>`
- Which system are you on: `<x86_64-pc-windows-msvc>`
- Clang version: `<clang version 6.0.0 (tags/RELEASE_600/final)>`

# What happens:  #
EasyClangComplete can't work.

<details>
<summary> 
`{
  "common_flags" : [
    "-Ie:\\Practice",
    "-IC:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\lib",
    "-IC:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\x86_64-w64-mingw32\\lib",
    "-IC:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\include",
    "-IC:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\x86_64-w64-mingw32\\include",
    "-IC:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\lib\\gcc\\x86_64-w64-mingw32\\4.9.2\\include",
    "-IC:\\Program Files (x86)\\Dev-Cpp\\MinGW64\\lib\\gcc\\x86_64-w64-mingw32\\4.9.2\\include\\c++",
  ],
  "c_flags" : [ "-std=c11" ],
  "cpp_flags" : [ "-std=c++11" ],
  "objective_c_flags" : [ "-std=c11" ],
  "objective_cpp_flags" : [ "-std=c++11" ],
  "flags_sources": [
    {"file": "CMakeLists.txt"},
    {"file": "compile_commands.json"},
    {"file": "CppProperties.json"},
    {"file": "c_cpp_properties.json"},
    {"file": ".clang_complete"},
  ],
  "show_errors": true,
  "gutter_style": "color",
  "triggers" : [ ".", "->", "::", " ", "	", "(", "[" ],
  "use_libclang" : true,
  "verbose" : true,
  "include_file_folder" : true,
  "include_file_parent_folder" : true,
  "clang_binary" : "clang++",
  "cmake_binary" : "cmake",
  "autocomplete_all" : false,
  "hide_default_completions": false,
  "max_cache_age": "00:30:00",
  "show_type_info": true,
  "show_type_body" : true,
  "libclang_path": "“C:\\Program Files\\LLVM\\bin\\libclang.dll",
  "progress_style": "Moon",
  "use_libclang_caching": true,
  "header_to_source_mapping": [
    "./",
    "../src/",
    "../source/",
  ],
  "use_target_compiler_built_in_flags": true,
  "target_c_compiler": null,
  "target_cpp_compiler": null,
  "target_objective_c_compiler": null,
  "target_objective_cpp_compiler": null,
}
`
</summary>
  
```
<LOG GOES HERE>
```

</details>

**Comment by niosus** [comment]
Please, take the time To properly format your log. Use fenced code blocks in Markdown with 3 backslashes.

**Comment by niosus** [comment]
I will close this issue for now for reasons stated in the [Readme]( https://github.com/niosus/EasyClangComplete/blob/master/README.md#follow-issue-template). Please reopen with proper formatting.
