### ISSUE TITLE
Incorrect parsing of methods with default parameters

### ISSUE THREAD

**Issue by Xecutor** [niosus/EasyClangComplete#45]
For example, selecting method 'substr' of std::string gives this completion:
`s.substr({#size_type _Off#})`

**Comment by niosus** [comment]
Yep, have seen this on newer clang versions. Actually, it should just remove those parameters. Are you using libclang or binary way to complete?

**Comment by Xecutor** [comment]
Binary. For function `void fff(int x=0, int y=1)` it generates `[#void#]fff({#<#int x#>{#, <#int y#>#}#})` completion information.

**Comment by r44083** [comment]
+1,
I also noticed such behavior with ``` [#void#]fff({#<#int x#>{#, <#int y#>#}#}) ```

**Comment by niosus** [comment]
ok, thanks! I will look into it. I remember fixing it, though :)

**Comment by niosus** [comment]
Should be fix now. Reopen if needed.
