### ISSUE TITLE
Autocomplete on windows+cmake+mingw does not work, possibly because generator is not applied

### ISSUE THREAD

**Issue by abhijat** [niosus/EasyClangComplete#468]
# System info: #
- Sublime Text version: 3.1.1 (build 3176)
- Which system are you on: Microsoft Windows 10
- Clang version: 6.0.0

# What happens:  #
Autocomplete does not work, minimal example can be seen here https://github.com/abhijat/easyclangcomplete-error

This should run on linux as per issue submission guidelines, however the problem is only seen on windows.

This is a cmake based project on windows, with the MinGW compiler toolchain. When working with the same setup on Linux (with gnu gcc instead of mingw) the plugin works fine. 

However on windows when I looked at the logs, cmake was trying to use the Visual Studio generator and was failing because it could not be found.

To fix this I added the following flags in the plugin settings as below (full settings file is also attached):

```
{
    "verbose": true,
    "flags_sources": [
        {
            "file": "CMakeLists.txt",
            "flags": [
                "-G\"MinGW Makefiles\"",
                "-DCMAKE_C_COMPILER=gcc",
                "-DCMAKE_CXX_COMPILER=g++",
            ],
        },
        {"file": "compile_commands.json"},
        {"file": "CppProperties.json"},
        {"file": "c_cpp_properties.json"},
        {"file": ".clang_complete"},
    ],
}
```

After this I get an error in the log as below:
```
CMake Error: Could not create named generator "MinGW Makefiles"
```

However, in the subsequent list of available generators, MinGW Makefiles is listed. Also, I can use cmake on the same project with the following command successfully:

```
c:\code\cpp\a\build>cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G "MinGW Makefiles" ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/code/cpp/a/build
```

The cmake exe is the same one being used by the plugin internally. 

I suspect this problem is due to the way the string `-G "MinGW Makefiles"` is passed to cmake, is the space messing up the command? 

I checked the old issues to see if there was a simple fix for this, I was not able to find one however. 

It may also be that I have not set the flags_sources bit correctly, apologies if that is the case. I was trying to go by the example settings but may have messed something up there. 

If there is another place within the settings which is more suited to set these sort of globally applicable cmake flags, please do let me know.

The full log of the plugin is at https://gist.github.com/abhijat/9ca5af38369c139cc529b6210e3bb982
and also attached as text below:

[errlog.txt](https://github.com/niosus/EasyClangComplete/files/2020248/errlog.txt)

The plugin settings (file renamed to txt to be able to upload) are :
[EasyClangComplete.sublime-settings.txt](https://github.com/niosus/EasyClangComplete/files/2020249/EasyClangComplete.sublime-settings.txt)

Thanks

**Comment by abhijat** [comment]
Update:

I got the cmake generator to work by splitting the -G argument in two. It was:

```
{
    "verbose": true,
    "flags_sources": [
        {
            "file": "CMakeLists.txt",
            "flags": [
                "-G\"MinGW Makefiles\"",
                "-DCMAKE_C_COMPILER=gcc",
                "-DCMAKE_CXX_COMPILER=g++",
            ],
        },
        {"file": "compile_commands.json"},
        {"file": "CppProperties.json"},
        {"file": "c_cpp_properties.json"},
        {"file": ".clang_complete"},
    ],
}
```


I changed it to:

```
{
    "verbose": true,
    "flags_sources": [
        {
            "file": "CMakeLists.txt",
            "flags": [
                "-G",
               "MinGW Makefiles",
                "-DCMAKE_C_COMPILER=gcc",
                "-DCMAKE_CXX_COMPILER=g++",
            ],
        },
        {"file": "compile_commands.json"},
        {"file": "CppProperties.json"},
        {"file": "c_cpp_properties.json"},
        {"file": ".clang_complete"},
    ],
}
```

So now the cmake command runs fine, and also produces a compile_commands.json file. But autocomplete still does not work. 

It does not find the standard header files like iostream any more. 

Here is the compile_commands.json that was produced by the cmake run internally by the plugin:

```
[
{
  "directory": "C:/Users/abhijat/AppData/Local/Temp/EasyClangComplete/cmake_builds/0cebe5e209f5a691fc5fa2cd26eb65ae",
  "command": "C:\\MinGW\\bin\\g++.exe      -std=gnu++14 -o CMakeFiles\\a.dir\\main.cpp.obj -c C:\\code\\cpp\\a\\main.cpp",
  "file": "C:/code/cpp/a/main.cpp"
}
]
```

I'm not sure how I can make ECC look at the correct include paths? Btw compilation from command line (cmake followed by make) still works. 

Latest log is attached.

[errlog2.txt](https://github.com/niosus/EasyClangComplete/files/2020290/errlog2.txt)

**Comment by abhijat** [comment]
In common flags I have added the MinGW include paths manually. Now the error messages have gone away but I still do not get any autocomplete.

Now the new settings look line this:

```
{
    "target_c_compiler": "gcc",
    "target_cpp_compiler": "g++",
    "flags_sources": [
        {
            "file": "CMakeLists.txt",
            "flags": ["-G", "MinGW Makefiles", ],
        },
        {"file": "compile_commands.json"},
        {"file": "CppProperties.json"},
        {"file": "c_cpp_properties.json"},
        {"file": ".clang_complete"},
    ],
    "common_flags" : [
        "c:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../include/c++/7.3.0",
        "c:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../include/c++/7.3.0/x86_64-w64-mingw32",
        "c:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../include/c++/7.3.0/backward",
        "c:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/include",
        "c:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/include-fixed",
        "c:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/include",
    ],
}
```

But still if I define a string and then do a '.' after that variable no completions are suggested.

**Comment by niosus** [comment]
Hey @abhijat thanks for reporting this. I believe it is important to discuss things like this. Unfortunately, I cannot help you here much as I know nearly nothing about the MinGW setup. This issue was partially raised in #175 

I guess I will keep this issue open for more discussions and hopefully at some point include the resolution of this issue into documentation when closing #274

**Comment by niosus** [comment]
As another option, try looking at setting `use_target_compiler_built_in_flags` and set it to false. That might help.

**Comment by abhijat** [comment]
Thanks, I'll try setting this flag as soon as I can and see if it works.

**Comment by abhijat** [comment]
So this one was completely my fault for not reading the examples you've given in plugin settings. 

If you see the common_flags I have defined above I just listed a bunch of include paths but did not give the '-I' flag before any of them like you mentioned in the examples. 

Once I prefixed the paths with -I everything including autocomplete started working perfectly. Current config looks like below:

```
{
    "target_c_compiler": "gcc",
    "target_cpp_compiler": "g++",
    "flags_sources": [
        {
            "file": "CMakeLists.txt",
            "flags": ["-G", "MinGW Makefiles", ],
        },
        {"file": "compile_commands.json"},
        {"file": "CppProperties.json"},
        {"file": "c_cpp_properties.json"},
        {"file": ".clang_complete"},
    ],
    "common_flags" : [
        "-Ic:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../include/c++/7.3.0",
        "-Ic:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../include/c++/7.3.0/x86_64-w64-mingw32",
        "-Ic:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../include/c++/7.3.0/backward",
        "-Ic:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/include",
        "-Ic:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/include-fixed",
        "-Ic:/mingw/lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/include",
    ],
}
```

Autocomplete working perfectly as seen below:

![image](https://user-images.githubusercontent.com/462313/40646192-1e6f0b88-6346-11e8-8cba-83796ac8d14b.png)

Thanks again, for the great work on this plugin.

**Comment by niosus** [comment]
Great! Happy it worked out for you.
