### ISSUE TITLE
Adding file exceptions

### ISSUE THREAD

**Issue by JPenuchot** [niosus/EasyClangComplete#471]
CUDA files aren't well supported yet ECC displays errors in them. I first thought it would be good to add an exception for `.cu` files to avoid that, but then I thought maybe it would be a better idea to just add a parameter that supports regex/glob expressions to avoid some files like so :

```json
{
  "file_exceptions" : [ "*.cu", "*.hcu",
  "you_might_just_want_some_files_not_to_be_autocompleted_for_some_reason.cpp" ]
}
```

Also adding a kind of `.eccignore` file could be useful.

However it sounds like a rather obvious feature to me now that I think of it, maybe I missed a feature that does it already ?

**Comment by niosus** [comment]
I will close this issue. Instead, the same functionality will be reached by a combination of #491 and #334 where the syntaxes become user-configurable and there is going to be a glob "ignore" list setting which will control which files we don't want to touch.
