### ISSUE TITLE
cindex module for libclang version 7 missing

### ISSUE THREAD

**Issue by SirFerdek** [niosus/EasyClangComplete#473]
# System info: #
- Sublime Text version: `3176 linux x64 channel: stable`
- Which system are you on: `Ubuntu Linux`
- Clang version: `7.0.0`

# What happens:  #
Plugin does not contain cindex module from libclang version 7.0.0 (under development). Dunno what might be frequency of updates to it, but I wonder if it could be possible, as a solution, to use system installed cindex module instead of copying it to repo? Maybe some config switch to try my luck?

<details>
<summary>Log that illustrates the issue: </summary>
  
```
...
plugins loaded
[ECC:INFO   ]: Getting version from command: `clang++-7 -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 7.0.0
```

</details>

**Comment by niosus** [comment]
@SirFerdek I guess I could add an option to use the last available cindex, but we use a modified version of it and I don't think it is feasible to use the system one. I will keep this issue open until I add the missing cindex.
