### ISSUE TITLE
How to remove warnings and errors

### ISSUE THREAD

**Issue by ZackC** [niosus/EasyClangComplete#476]
# System info: #
- Sublime Text version: Version 3.1.1
- Which system are you on: Mac OS
- Clang version: Apple LLVM version 9.1.0

How can I remove the warnings and errors that I do not need to correct?

I'm trying to write a clang static analyzer check so I am running easy clang complete on the latest version of llvm and clang. I have easy clang complete set to the right files but no includes. The warning and errors that are generated for the provided checker SimpleSteamChecker.cpp.  This might be due to an incorrect configuration. I'd like to be able to remove those errors, along with any other similar errors/warnings that I know are not important for my situation - creating experimental static analyses checks. If you have any recommendations on how to correctly configure easy clang complete for llvm, then I would be grateful. But I'd also like to know the answer to the question above.

Sorry if this was mentioned somewhere else. I didn't find it after a limited search.

**Comment by niosus** [comment]
Currently there is no mechanism to ignore warnings and errors. We could theoretically implement something like this but based on some regex on what to ignore. That being said, I would assume that LLVM database should be correctly parsed by the plugin and you are right, it is most likely a configuration issue.

**Comment by ZackC** [comment]
Ok. Thanks for the response!

**Comment by mjendruk** [comment]
If you want to ignore certain types of warnings you could add the appropriate compiler flags in `cpp_flags`, for example `-Wno-unused-parameter`, but I guess you are rather looking to suppress specific instances.

**Comment by niosus** [comment]
I don't think I want to go down the path of implementing filters for warnings in the plugin. I can see how it can quickly become ugly and it is hard to find the time to properly support the plugin as it is unfortunately. So to reduce the scope of my attention, I will close this issue. Sorry about that.
