### ISSUE TITLE
ecc_target_cpp_compiler picks up __cplusplus (which causes other issues)

### ISSUE THREAD

**Issue by leoetlino** [niosus/EasyClangComplete#477]
# System info: #
- Sublime Text version: 3126
- Which system are you on: Linux (Debian sid)
- Clang version: 6.0

# What happens: #

It seems that whenever the `ecc_target_cpp_compiler` config option is used, the `__cplusplus` define is also picked up from the specified compiler default flags. The problem is that it overrides the correct define which should be set according to the `-std=` flag.

This means that if the target compiler defaults to C++14 for example, the define will be set to 201402l even though -std=c++17 is explicitly set in the flags, and there is no way to fix this other than by adding a flag: `-D__cplusplus=201703l`

And then when C++17 library features like std::scoped_lock are used, strange errors will be shown because these features are gated behind `__cplusplus` value checks.

An easy solution would be to just ignore `__cplusplus` from the target compiler, but I'm not sure what would be the best way to fix this (which is why I'm opening an issue instead of a PR).

Thanks for your time!

**Comment by niosus** [comment]
Hey, thanks for reporting. To be honest this setting causes a number of bugs and I do not really have the time to work on this now. This plugin was thought of as a relatively simple tool while using the target compiler flags is already a pretty advanced feature. I personally don't use this feature in my day-to-day programming.

**Comment by leoetlino** [comment]
Hmm, I understand. Would you be fine with a patch that just unsets __cplusplus? Everything seems to work perfectly after overriding that define manually :)

Or if you think the user should be responsible for setting the define to the required value (because it's an advanced feature anyway), I'm fine with that too.

**Comment by niosus** [comment]
I think I would be for leaving it be as it might be more confusing to other people if we remove this in case they expect __cplusplus to be set automatically. I guess this issue would stay as documentation for this. I hope it sounds fine to you.
