### ISSUE TITLE
Too many std flags with -std and -stdlib

### ISSUE THREAD

**Issue by nsubiron** [niosus/EasyClangComplete#479]
# System info: #
- Sublime Text version: `3175`
- Which system are you on: `Ubuntu 16.04`
- Clang version: `5.0`

# What happens:  #
I'm compiling the code with libc++ and c++14 (perfectly valid  combination).

I generate a `compile_commands.json` with CMake.

```
Your source generated settings define too many std flags:
[(-std=c++14), (-stdlib=libc++)]

Please fix your settings.
```

**Comment by niosus** [comment]
Thanks for posting it. This is due to a stupid check we make for finding `-std` flag. 
The relevant code is here:
https://github.com/niosus/EasyClangComplete/blob/a19ecddb27fbaea38e9669a0bb251c2e7649be2f/plugin/view_config.py#L207-L212

It should be fixed by just searching for `-std=` instead.

**Comment by niosus** [comment]
Glad to help. I will try to merge it soon.
