### ISSUE TITLE
How to disable printing all stuff into the sublime text console and disable code linting?

### ISSUE THREAD

**Issue by r44083** [niosus/EasyClangComplete#48]
During EasyClangComplete plugin working, it prints different info into the console like this:

![](https://habrastorage.org/files/deb/7f8/dae/deb7f8dae78a4654b03ef57437b02402.png)

These info is unused majority of time and just spam into the console.
How I can disable it?

Also, is there a way how to disable static code linting (analyzing) in EasyClangComplete? (I use another Clang code analyzer for this and I don't want to load CPU for analyzing code with EasyClangComplete)

**Comment by niosus** [comment]
I should point it out in readme better, I guess.
- To disable spam in console set `"verbose": false`
- To disable linting set `"errors_on_save": false`

**Comment by niosus** [comment]
Oh, have just seen that some of them are warnings. I should check that.

**Comment by niosus** [comment]
Do you still have this behavior?

**Comment by niosus** [comment]
Should be fixed now. Reopen if needed.

**Comment by niosus** [comment]
The tests fail when I try to show a window with a question to the user. The issue will remain open until I understand what is going on.

**Comment by niosus** [comment]
Fixed the tests. Closing again. Stable version should be 1.2.1

**Comment by r44083** [comment]
I noticed that all these stuff still printing to the sublime text console. In settings I set verbose false, but it is not change such behavior.

![](https://habrastorage.org/files/3bd/65b/a4a/3bd65ba4a87f4d05825ed32e28ebd388.png)
