### ISSUE TITLE
show_type_info doesn`t  work

### ISSUE THREAD

**Issue by svischuk** [niosus/EasyClangComplete#481]
# System info: #
- Sublime Text version: `3.1.1`
- Which system are you on: `Windows 10 64bit`
- Clang version: `6.0.1 32bit`

# What happens:  # 
Error Unfortunately, there is no way to show type info
if you are not using libclang.
Please use libclang or set "show_type_info" to false.
If you *are* using libclang and still see this, open an issue.

 [log.txt](https://github.com/niosus/EasyClangComplete/files/2246625/log.txt)

**Comment by niosus** [comment]
Hey @svischuk sorry for the delay, I was away from the internet for a week. How did you install libclang on your system? Is there a reason to use a 32 bit version?

**Comment by svischuk** [comment]
I found the solution, I installed 64bit clang. Now it works fine.Good luck.

2018-08-06 14:35 GMT+03:00 Igor Bogoslavskyi <notifications@github.com>:
