### ISSUE TITLE
Missing feature: Autocompletion of enum member names

### ISSUE THREAD

**Issue by lulle2007200** [niosus/EasyClangComplete#484]
I've noticed that enum members won't get autocompleted.
E.g.:
   typedef enum boolean {true=1, false=0}boolean;
   
   boolean x = fal //no autocompletion here

**Comment by niosus** [comment]
This is not the use case I have been targeting. I tend to use `enum class` and I recommend to use it too (some [reasons](https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum)):
```c++
enum class A { val1, val2 };

int main() {
  auto sample = A::val1;
  return 0;
}
```
In this case the code gets completed after `::`. In your case if you type `boolean::` you will also get completions.

**Comment by asheeshr** [comment]
I have the same question. Is there any way to get enum completions to work in plain C and not C++?

**Comment by asheeshr** [comment]
Any thoughts on this issue? Could we re-open it?

When working with plain C, enum completions would be useful to have functional. @niosus

**Comment by niosus** [comment]
@asheeshr sorry for a late response. I believe you can use the `::` notation, right? 

In any case, feel free to have a look at the code that filters completions and create a PR with the functionality you are missing.

**Comment by lulle2007200** [comment]
Enum classes and the :: notation for enums are not a thing in plain C tho. If you *really* need enum completions, give the LSP plugin with Clangd a try.
I will look into this once i've finally finshed my other PR.
