### ISSUE TITLE
Error hinting improvement

### ISSUE THREAD

**Issue by schreda** [niosus/EasyClangComplete#489]
Hi.

I love the linting feature of ECC. Unfortunately it doesn't mark any characters in the view, when the whole line is affected (missing semicolon for examnple)
I disabled the gutter symbols, so there is no error hinting for this kind of error.

regards.

**Comment by niosus** [comment]
It highlights the end of the line when there is a semicolon missing for me. Can you show a screenshot or a short video of what you are experiencing?

**Comment by schreda** [comment]
It looks like, that it works now. I'll close this issue and will provide a video, if there is such a behavior again!

**Comment by niosus** [comment]
Glad it works for you.
