### ISSUE TITLE
Highlight custom types

### ISSUE THREAD

**Issue by schreda** [niosus/EasyClangComplete#496]
This should be a feature request/suggestion.
The only thing i am missing in writing Code in ST3 are the syntax highlighted user types (typedefs).

**Comment by niosus** [comment]
Unfortunately highlighting is done before the plugin has any say in it and I would not expect that it is at all possible. Highlighting has to be really-really fast whenever the buffer is loaded. Knowing that something is a type needs compilation information and is very slow in comparison. So I think this is not possible.
