### ISSUE TITLE
Runs on files and syntaxes it should not, ignores settings

### ISSUE THREAD

**Issue by kgizdov** [niosus/EasyClangComplete#501]
# System info: #
- Sublime Text version: `3176`
- Which system are you on: `ArchLinux x86_64, GCC 8.2.1`
- Clang version: `6.0.1`

# What happens:  #
`EasyClangComplete` seems to ignore the syntax definitions of files and tries to run/recognise the language in files that it should not. For example, instead of only running in `C++` files, it runs on every click inside a `*.py` file, clearly labelled as `Python` syntax by SublimeText. Not only does this completely pollutes the logs, but also results in a significant performance hit.

![ECC Error on Python](https://user-images.githubusercontent.com/3164953/45950020-441ab700-bffe-11e8-936a-69829f79f672.png)

# Settings: #
```json
{
    "common_flags" : [
        "-I/usr/include",
        "-I/usr/include/root",
        "-I$project_base_path/src",
        "-I$project_base_path/common/include",
        "-I/usr/lib/clang/$clang_version/include",
    ],

    "lang_flags": {
        "C": ["-std=c17"],
        "CPP": ["-std=c++17"],
        "OBJECTIVE_C": ["-std=c17"],
        "OBJECTIVE_CPP": ["-std=c++17"],
    },

    "verbose" : true
}
```

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[MainThread]: Cannot recognize language from syntax: 'Python'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Plain Text (Log)'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Plain Text (Log)'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Plain Text (Log)'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Plain Text (Log)'
[ECC:ERROR]:[tools.py]:[get_view_lang]:[Dummy-11]: Cannot recognize language from syntax: 'Plain Text (Log)'
```

</details>

[full.log](https://github.com/niosus/EasyClangComplete/files/2410600/subl_ecc.log)

**Comment by niosus** [comment]
Ok, I see the point with the log. I will move the message to `DEBUG`. But it should not make any performance hit as the function is async anyway.

**Comment by kgizdov** [comment]
I thought the whole point of:
```json
"valid_lang_syntaxes": {
    "C":              ["C", "C Improved", "C99"],
    "CPP":            ["C++", "C++11"],
    "OBJECTIVE_C":    ["Objective-C"],
    "OBJECTIVE_CPP":  ["Objective-C++"]
}
```
is to not run on any view that is already not in the list. Maybe it's not possible, but I was surprised that you have to check the view on every click (possibly more often, haven't dug up the code). Can you cache the responses for different views and only execute the check on new ones? Only run on ones that have passed?

I mentioned performance hit, as `ECC` was the only update since a long holiday and now SublimeText seems slower, but it might be something else.

**Comment by niosus** [comment]
Yeah, the most of the functionality does not run. It just needs to load the settings for the view in order to make sure it ignores the proper syntaxes. It is a cheap operation, but it needs to be done when the view is opened. We cannot really ignore this, as people wanted to have all the settings being available as peoject settings. For this, we need to load them every time for every view. I will remove the annoying error message though.

**Comment by kgizdov** [comment]
> We cannot really ignore this, as people wanted to have all the settings being available as peoject settings. For this, we need to load them every time for every view.

Why is it necessary to load the check and settings multiple times on an already opened view that doesn't match? For me this check runs without changing view all the time as I type, move cursor, click, etc.

**Comment by niosus** [comment]
Yeah, this might be not optimal for now. It is probably a good idea to store the valid syntax in some cache. I just need to figure out where it makes sense to put it and how to handle settings reload.

**Comment by niosus** [comment]
I decided not to implement the new proposed cache as the current solution actually runs in approx. 0.0007 seconds on my old laptop. More details in the PR referenced above.
