### ISSUE TITLE
Autocompletion doesn't work as expected

### ISSUE THREAD

**Issue by schreda** [niosus/EasyClangComplete#506]
So there is following code:

```
#define TEST_DEF __attribute__((__packed__))

typedef struct TEST_DEF {
    int a;
} a_t;

int main(void) {
    a_t aa = { .a = 2 };
}
```

If i want to use ECC outside the scope of the struct, i can't write TEST_DEF using the auto completion feature

Log: [https://pastebin.com/D2NaD9ue](https://pastebin.com/D2NaD9ue)

- Sublime Text version: 3176
- Which system are you on: suse 11
- Clang version: 5.0.0

**Comment by niosus** [comment]
I don't really understand the issue here? What is the expected behavior? Which one are you actually getting?

**Comment by schreda** [comment]
I would like to use autocompletion for "TEST_DEF". But it doesn't suggest any types outside of the structs scope

**Comment by niosus** [comment]
You mean, like, in `main` function for example?

**Comment by schreda** [comment]
No. Exactly at this point:

`typedef struct >> TEST_DEF << {`

**Comment by niosus** [comment]
Ok, I see the issue, but I don't think there is anything I can do here. It is either sublime text, that is not triggering there at all or clang that provides no completions at that point. So I guess, I will close this one.
