### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'error_vis'

### ISSUE THREAD

**Issue by simonhaenisch** [niosus/EasyClangComplete#51]
With the latest version I don't get any completions anymore on Windows (not libclang). I get this in console:

```
Traceback (most recent call last):
  File "<ST3-Path>\sublime_plugin.py", line 231, in run_callback
    expr()
  File "<ST3-Path>\sublime_plugin.py", line 314, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "<ST3-Packages-Path>\EasyClangComplete\EasyClangComplete.py", line 118, in on_selection_modified
    completer.error_vis.show_popup_if_needed(view, row)
AttributeError: 'NoneType' object has no attribute 'error_vis'
```

And a few similar ones:

```
(...) EasyClangComplete.py", line 129, in on_modified_async
    completer.error_vis.clear(view)
AttributeError: 'NoneType' object has no attribute 'error_vis'
```

```
(...) EasyClangComplete.py", line 94, in on_activated_async
    if completer.exists_for_view(view.buffer_id()):
AttributeError: 'NoneType' object has no attribute 'exists_for_view'
```

```
(...) EasyClangComplete.py", line 175, in on_query_completions
    if completer.async_completions_ready:
AttributeError: 'NoneType' object has no attribute 'async_completions_ready'
```

**Comment by niosus** [comment]
oh. Have you tried to restart sublime text? It all works for me on both linux and windows. Also all the tests pass on all systems. Seems it is some configuration issue on your side.

**Comment by niosus** [comment]
Also, check out if you are actually using completion with clang binary. The plugin will now be able to find libclang. But is still unable to use it on Windows unfortunately.

**Comment by niosus** [comment]
Any news on this?

**Comment by simonhaenisch** [comment]
Maybe I didn't restart Sublime, I don't remember. I had the package disabled for a while and now enabled it again and it works. `use_libclang` was already set to `false`, so that wasn't the problem.

You may want to add a note to restart ST in the message text that shows after the update?

**Comment by niosus** [comment]
That is a good idea. But I'd rather find a cause. I have experienced that sometime there are no completions after some modifications to the plugin, but I am still not sure when. 

Anyway, `AttributeError: 'NoneType' object has no attribute 'error_vis'` is still there, but this is a minor issue and I will fix it soon. It should not affect anything.

Closing this issue for now.
