### ISSUE TITLE
Unnecessary ECC errors! 

### ISSUE THREAD

**Issue by Kartik-715** [niosus/EasyClangComplete#511]
# System info: #
- Sublime Text version: 3.1.1 Build 3176
- Which system are you on: macOS Mojave 10.14
- Clang version: Apple LLVM version 10.0.0 (clang-1000.11.45.2)

# What happens: #
I'm Having unnecessary Errors shown in ECC! Seems like the latest update didn't fix it! 
Attaching the photos to show the unnecessary errors and also attaching the log file!

![screenshot 2018-10-04 at 00 27 03](https://user-images.githubusercontent.com/31189137/46432755-a432fb00-c76c-11e8-8178-a78ec945d695.png)

![screenshot 2018-10-04 at 00 27 43](https://user-images.githubusercontent.com/31189137/46432768-abf29f80-c76c-11e8-92ab-76f3c720b537.png)
![screenshot 2018-10-04 at 00 27 29](https://user-images.githubusercontent.com/31189137/46432779-b4e37100-c76c-11e8-904e-e09a9a1908bd.png)

[log.txt](https://github.com/niosus/EasyClangComplete/files/2443403/log.txt)

**Comment by niosus** [comment]
Judging from the log the plugin has found libclang as expected and the issues are probably configuration ones. I don't think I can provide any help here unfortunately. Again, the best way to use the plugin to ensure correct configuration is by utilizing a cmake build system.

**Comment by Kartik-715** [comment]
> Judging from the log the plugin has found libclang as expected and the issues are probably configuration ones. I don't think I can provide any help here unfortunately. Again, the best way to use the plugin to ensure correct configuration is by utilizing a cmake build system.

I have no idea why has it stopped working suddenly! Can you please suggest anything? I don't use cmake!

**Comment by Kartik-715** [comment]
Sorry for wasting your time! I recently had installed macOS Mojave and there was no /usr/include directory so it was creating a problem :) Figured it out :)

**Comment by niosus** [comment]
Glad that it works now. :)
