### ISSUE TITLE
consider refactoring actions

### ISSUE THREAD

**Issue by maddanio** [niosus/EasyClangComplete#515]
clang now has a refactoring action. since ecc is already having clang parse the code, wouldnt it make sense to also access this from ecc? here is a link to the documentation:
https://clang.llvm.org/docs/RefactoringEngine.html

**Comment by niosus** [comment]
This is generally a nice idea. But I see a couple of issues with it as of now:
- it should be available from python bindings or has to be implemented there and contributed to LLVM. I did not check thoroughly, but it seems that this functionality is not exposed.
- I wonder how useful can it potentially be. To me this functionality would be quite confusing from a user perspective without building a full AST of the whole project (i.e. full index). If we don't build this index, the renaming tool will be constrained to a single translation unit, which basically consists of a source files and its includes. Let's consider a case, where I am including a library into my source file, i.e. I have an `#include <some_lib.h>` statement for the library, but the implementation is in `some_lib.cpp`. If I now decide to refactor code using clang it will rename stuff in my file, in a header file but will not touch the source file as it is in a different translation unit. 

Overall, I've been working in Sublime Text on projects of various size for quite a while now and I never really lacked a tool for renaming, making use of sublime's "search all" functionality with consequent naming patterns. But feel free to change my mind on that :) Not that I have a very strong opinion about it. How do you expect to use this functionality should we actually implement it?

**Comment by maddanio** [comment]
Ok. Yeah, this whole project thing seems to be still untackled by clangd and clang-rename. Hmm, basiclly this whole-project index would consist of single TU indices linked via common symbols, right? So all that is really missing (given all related TUs have been indexed) are these links right. Dunno if this is the right place to discuss this, but i feel an open source approach to whole-project indexing is what is missing, as only big commercial IDEs seem to offer this now.

**Comment by maddanio** [comment]
I mean, this is how the linker does it, right? Before linking there is no "whole project", so i would think do as the linker does...

**Comment by niosus** [comment]
Yep, you're right. But this is definitely out of the scope of this project. I don't even think going for a PR and trying to merge it is feasible as this is a *ton* of work and this functionality will be extremely hard to nail down and I really don't want to push half-baked solutions to the repo...

**Comment by maddanio** [comment]
hmm, i am not so sure if it isnt possible to make headway here in small steps. give me some time to dig into ecc's sources?

**Comment by niosus** [comment]
Sure. If you are up for it, I don't want to discourage you! :smiley: 
I think the best way would be to keep discussing it before you put significant effort into coding a PR. Does it sound good to you?

**Comment by maddanio** [comment]
exactly. I do enjoy ecc a lot, so i would really like to progress this. and i do think i am up to it. but it is something to be done carefully.
so starting to dig, i guess this would only make sense for the cindex path. there i am currently seeing the tu is always handled in isolation per view, and also not cached. so to make a step there would need to be a global tu "repository" for the project, probably cached on disk.

**Comment by maddanio** [comment]
i am not too firm in sublime plugin development. for experimentation: where could i attach a per-project repo? is there any way to store stuff for the current project?

**Comment by niosus** [comment]
I agree, using libclang (cindex) is the prefered way. We do keep some of the TUs in memory, but they are never cached to disk, you are right here.

What exactly do you mean by a "per-project repo"? Also, if you need some simple example, Sublime Text provides them: https://www.sublimetext.com/docs/3/api_reference.html#example_plugins

**Comment by maddanio** [comment]
cool. how do i enable debug logging? :)

**Comment by niosus** [comment]
That sounds like a good idea. :) I will probably close this issue for now. Let's reopen it with a concrete proposition later.

**Comment by maddanio** [comment]
ok. can i still use this to keep the discussion going?
after playing with the index i have a few first findings:
- number of symbols is usually huge, due to all the includes
- one problem is that a node does not reference its declaration (while a declaratio does reference its implementation) which forces quite extensive indexing. it may be interesting to limit to project-local files though
- still even traversing the ast takes much longer than parsing in python, so i would propose a compiled extension. i would like to do this using boost python. i will go ahead and check how fast something in c/c++ would be
- i need a few use-cases to look at to steer research. i think i would go with "find usage" and "rename symbol" for now. oh, and "go to declaration", which does not really work in ecc right now (i.e. one will not be led to a method declaration from the implementation)

**Comment by maddanio** [comment]
and of course this would require index caching, as indexing a largish project can quickly turn into an hour of work.
