### ISSUE TITLE
Error with settings on a fresh install of the plugin

### ISSUE THREAD

**Issue by ChristopheClaustre** [niosus/EasyClangComplete#516]
# System info: #
- Sublime Text version: `3.1.1, Build 3176`
- Which system are you on: `Windows 10`
- Clang version: `8.0.0 (trunk)`

# What happens:  #
Ecc plugin don't want to work without restarting ST3 at least one time after installing it.
I reinstalled several times ecc plugin and clang to test.
Each time path to clang was in my PATH environment variable.

If I restart the plugin, those problems don't occur anymore.

<details>
<summary>Error I obtain when I install ecc plugin: </summary>

![capture](https://user-images.githubusercontent.com/11921745/46939480-afd4ca80-d066-11e8-82e0-cc8e2d5fc938.PNG)

</details>
<details>
<summary>Two examples of errors I can obtain when I give focus to another view just after installing the plugin: </summary>

![capture2](https://user-images.githubusercontent.com/11921745/46939481-b06d6100-d066-11e8-9122-6020da710aee.PNG)

</details>

**Comment by niosus** [comment]
Yeah, known issue, but there is not much I can do. It is a very extensively discussed topic on sublime text forums but there is still no solution, as far as I know. So reloading sublime text is currently the only easy solution.
