### ISSUE TITLE
Support Clang 8.0

### ISSUE THREAD

**Issue by ChristopheClaustre** [niosus/EasyClangComplete#517]
# System info: #
- Sublime Text version: `3.1.1, Build 3176`
- Which system are you on: `Windows 10`
- Clang version: `8.0.0 (trunk)`

# What happens:  #
Apparently ECC doesn't support Clang version 8.0.0 ?

<details>
<summary>Error I can obtain when I give focus to another view: </summary>

```
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 8.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:ERROR  ]: cmake has finished, but no compilation database.
```

</details>

**Comment by niosus** [comment]
As far as I know, clang 8.0.0 is not stable yet, right?

Anyway, it probably will work, could you check if the PR referenced above works for you?

**Comment by niosus** [comment]
Strange, clang download page only shows clang 7.0 to me :laughing:

**Comment by mclayton7** [comment]
For what it's worth, I'm only seeing 7.0.0 as the latest LLVM/clang release on http://releases.llvm.org/download.html

**Comment by niosus** [comment]
Ok, good to know :) I will merge the PR then if it doesn't hurt.
