### ISSUE TITLE
Modifying the autocompletion for template arguments

### ISSUE THREAD

**Issue by dv1** [niosus/EasyClangComplete#518]
I have been trying to perform a slight modification to the way EasyClangComplete autocompletes template arguments. If I for example type `std::vector` and select "vector" in the autocompletion list, EasyClangComplete turns this into `std::vector<typename _Tp>`. I'd like to have `std::vector < typename _Tp >` instead (so, just a few more spaces). I tried to find out where I can modify this, but had no luck so far. Can you point out where I can configure this? This does not seem to be a simple snippet, but something done by clang.

**Comment by niosus** [comment]
If you like, you can add spaces here: https://github.com/niosus/EasyClangComplete/blob/1c9b2667ada40221bf3318d6acf0884b3dc6118b/plugin/completion/lib_complete.py#L459-L461 

But mind, that I will not be merging this change into the plugin as a believer in the Google Style Guide for C++, which explicitly forbids this kind of spaces:

> 
```c++
// No spaces inside the angle brackets (< and >), before
// <, or between >( in a cast
std::vector<string> x;
y = static_cast<char*>(x);
```
Taken from here:
https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace
