### ISSUE TITLE
Add qt configuration steps to the documentation

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#520]
There are additional steps to correctly configure the plugin with qt projects as we need to search for headers in the generated folders.

**Comment by mclayton7** [comment]
@niosus I use Qt pretty extensively so let me know if there's any way I can help with this. I'm assuming you're wanting documentation for adding the ``.moc`` generated files from the build tree?

**Comment by niosus** [comment]
I don't think there is any help needed. I just added the issue to not forget to do it now that the documentation stub is in place. I think I will do it some time this week.

**Comment by niosus** [comment]
The preliminary version available here: https://niosus.github.io/EasyClangComplete/configs/#qt-configuration

@mclayton7 if you can add smth to it, feel free to add a PR with your additions to this section of the docs: https://github.com/niosus/EasyClangComplete/blob/master/docs/configs.md#configurations-that-require-manual-actions
