### ISSUE TITLE
Cannot handle line breaks in compilation database cmd field 

### ISSUE THREAD

**Issue by sprainbrains** [niosus/EasyClangComplete#524]
I got this error in Sub:

```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.
ERROR:concurrent.futures:exception calling callback for <Future at 0x2c27ed95da0 state=finished raised ValueError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 410, in config_updated
    log.debug("updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 464, in load_for_view
    config = ViewConfig(view, settings)
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 69, in __init__
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 184, in __generate_essentials
    source_flags = ViewConfig.__load_source_flags(view, settings, prefixes)
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 297, in __load_source_flags
    flags = flag_source.get_flags(view.file_name(), search_scope)
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\flags_sources\compilation_db.py", line 89, in get_flags
    db = self._parse_database(current_db_file)
  File "C:\Users\nikolay\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\flags_sources\compilation_db.py", line 126, in _parse_database
    data = json.load(data_file)
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Invalid control character at: line 4 column 67 (char 113)
```

OS: Windows 10 1809
Python 3.7.1
Sublime Build 3176

Of course, ECC doesn't work.

**Comment by niosus** [comment]
Hmm, does your `compile_commands.json` file contain any non-utf chars?

**Comment by sprainbrains** [comment]
> 
> 
> Hmm, does your `compile_commands.json` file contain any non-utf chars?

**compile_commands.json** contains:
```
[
{
  "directory": "C:/ProjectsJOB/CmakeTest",
  "command": "C:\\PROGRA~2\\MICROS~2.0\\VC\\bin\\amd64\\cl.exe @<<
 /nologo /TP -DQT_CORE_LIB -IC:\\ProjectsJOB\\CmakeTest -IC:\\ProjectsJOB\\CmakeTest\\CmakeTest2_autogen\\include -IF:\\Qt\\5.8\\msvc2015_64\\include -IF:\\Qt\\5.8\\msvc2015_64\\include\\QtCore -IF:\\Qt\\5.8\\msvc2015_64\\.\\mkspecs\\win32-msvc2015  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /FoCMakeFiles\\CmakeTest2.dir\\main.cpp.obj /FdCMakeFiles\\CmakeTest2.dir\\ /FS -c C:\\ProjectsJOB\\CmakeTest\\main.cpp
<<",
  "file": "C:/ProjectsJOB/CmakeTest/main.cpp"
},
{
  "directory": "C:/ProjectsJOB/CmakeTest",
  "command": "C:\\PROGRA~2\\MICROS~2.0\\VC\\bin\\amd64\\cl.exe @<<
 /nologo /TP -DQT_CORE_LIB -IC:\\ProjectsJOB\\CmakeTest -IC:\\ProjectsJOB\\CmakeTest\\CmakeTest2_autogen\\include -IF:\\Qt\\5.8\\msvc2015_64\\include -IF:\\Qt\\5.8\\msvc2015_64\\include\\QtCore -IF:\\Qt\\5.8\\msvc2015_64\\.\\mkspecs\\win32-msvc2015  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /FoCMakeFiles\\CmakeTest2.dir\\CmakeTest2_autogen\\mocs_compilation.cpp.obj /FdCMakeFiles\\CmakeTest2.dir\\ /FS -c C:\\ProjectsJOB\\CmakeTest\\CmakeTest2_autogen\\mocs_compilation.cpp
<<",
  "file": "C:/ProjectsJOB/CmakeTest/CmakeTest2_autogen/mocs_compilation.cpp"
}
```
]

**Comment by niosus** [comment]
Ok, I can reproduce it on my local python. It seems that there is an issue with this file from `json` point of view. I have reduced it to the following file:
```json
[{ 
"command": "C:\\a" 
}]
```
Here it doesn't like the `\\` symbol. You are on Windows, I assume?

**Comment by sprainbrains** [comment]
> Here it doesn't like the `\\` symbol. You are on Windows, I assume?
Yep. For this situation i using Windows.

And other question: What about parse of **.clang_complete** file in Windows with Windows path? It also doesn't work for me.

**Comment by niosus** [comment]
That is extremely weird. We test it in the unit tests on Windows too. Please open a new issue for parsing `.clang_complete` file. 

As for the issue at hand, this should not happen and I have to look why this happens. Just to be sure, you generate the `compile_commands.json` file on Windows and use it in Sublime Text also on Windows?

**Comment by niosus** [comment]
Ok, I've found the issue. We must escape the backslashes properly: `\\` -> `\\\\`. If we replace all of these in the initial file we can load it. I will try to find the time to fix the issue this week.

**Comment by sprainbrains** [comment]
> That is extremely weird. We test it in the unit tests on Windows too. Please open a new issue for parsing `.clang_complete` file.

ok. I will try to generate new file. Do you can write example how it will look in Windows system? Path to folders, for example?

> As for the issue at hand, this should not happen and I have to look why this happens. Just to be sure, you generate the `compile_commands.json` file on Windows and use it in Sublime Text also on Windows?
Yes. Only Windows and Sublime. I generated sub project file from cmake -G option with "Nmake Makefiles"

**Comment by niosus** [comment]
Sorry, I am again clueless. If I set some string to the text of your file and then try to load it with `json.loads(...)` then I get the same error as you do (if I don't use raw strings explicitly). But if I load this file from disk and use `json.load(...)` I cannot reproduce it. :confused:

**Comment by niosus** [comment]
I've tried loading your original file from windows and it seems that json doesn't like the linebreaks, which are indeed invalid in json. There seems to be nothing to fix in the plugin itself here...

**Comment by sprainbrains** [comment]
After last updates;
Output:
`
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 611, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\Nikolai\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 288, in on_activated_async
    function=EasyClangComplete.view_config_manager.load_for_view,
AttributeError: 'NoneType' object has no attribute 'load_for_view'
`

I prepared my a simple cmake project.
A generated sub.project through cmake -G "Sublime Text 2 - NMake Makefiles"
[cmake_files_windows.zip](https://github.com/niosus/EasyClangComplete/files/2614530/cmake_files_windows.zip)

**Comment by niosus** [comment]
If I open your compilation database even the text editors highlight errors in it, so the json is malformed. Why don't you just use cmake here? Also, why not just using `-DCMAKE_EXPORT_COMPILE_COMMANDS`?

**Comment by sprainbrains** [comment]
> 
> 
> If I open your compilation database even the text editors highlight errors in it, so the json is malformed. Why don't you just use cmake here? Also, why not just using `-DCMAKE_EXPORT_COMPILE_COMMANDS`?

I'm using cmake! I generated new project with compilation database with `cmake -G "NMake Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` and it generated such a compile_database file for me. 
I used VS 2015 x64 console.

**Comment by sprainbrains** [comment]
I think that the main problem is the "Line break character" in a command line. Cmake in VS automatically generated it.

**Comment by sprainbrains** [comment]
> 
> 
> Ok, I see. We'll have to figure out how to fix the json file then. It's weird to me that we actually need to to this, to be honest. Why does it produce a json file that does not correspond to json specs in the first place is a mystery to me.

Me too(
Can you show me correct .json database file based on my example?

**Comment by niosus** [comment]
This is a valid representation with returns removed. I have also removed the weird symbols that from my experience don't belong into the compilation command: 
```json
[
{
  "directory": "C:/ProjectsJOB/CmakeTest",
  "command": "C:\\PROGRA~2\\MICROS~2.0\\VC\\bin\\amd64\\cl.exe /nologo /TP -DQT_CORE_LIB -IC:\\ProjectsJOB\\CmakeTest -IC:\\ProjectsJOB\\CmakeTest\\CmakeTest2_autogen\\include -IF:\\Qt\\5.8\\msvc2015_64\\include -IF:\\Qt\\5.8\\msvc2015_64\\include\\QtCore -IF:\\Qt\\5.8\\msvc2015_64\\.\\mkspecs\\win32-msvc2015  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /FoCMakeFiles\\CmakeTest2.dir\\main.cpp.obj /FdCMakeFiles\\CmakeTest2.dir\\ /FS -c C:\\ProjectsJOB\\CmakeTest\\main.cpp",
  "file": "C:/ProjectsJOB/CmakeTest/main.cpp"
},
{
  "directory": "C:/ProjectsJOB/CmakeTest",
  "command": "C:\\PROGRA~2\\MICROS~2.0\\VC\\bin\\amd64\\cl.exe /nologo /TP -DQT_CORE_LIB -IC:\\ProjectsJOB\\CmakeTest -IC:\\ProjectsJOB\\CmakeTest\\CmakeTest2_autogen\\include -IF:\\Qt\\5.8\\msvc2015_64\\include -IF:\\Qt\\5.8\\msvc2015_64\\include\\QtCore -IF:\\Qt\\5.8\\msvc2015_64\\.\\mkspecs\\win32-msvc2015  /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /FoCMakeFiles\\CmakeTest2.dir\\CmakeTest2_autogen\\mocs_compilation.cpp.obj /FdCMakeFiles\\CmakeTest2.dir\\ /FS -c C:\\ProjectsJOB\\CmakeTest\\CmakeTest2_autogen\\mocs_compilation.cpp",
  "file": "C:/ProjectsJOB/CmakeTest/CmakeTest2_autogen/mocs_compilation.cpp"
}
]
```

**Comment by niosus** [comment]
Sorry, I'm not using anything. I just have removed the weird symbols manually. Sorry for the confusion. I won't be able to assist you in finding the reason why VS generates a wrongly formatted json file as I don't even have a proper dev environment on windows. Sorry for that :disappointed:

**Comment by sprainbrains** [comment]
> Sorry for that

No problem. I understand.
I will try to solve it in Windows.

**Comment by sprainbrains** [comment]
I'm generated compilate_database through Qt Creator and it worked fine. But with cmake a got same error, unfortunately.
