### ISSUE TITLE
EasyClangComplete is not working

### ISSUE THREAD

**Issue by NgoKiet02** [niosus/EasyClangComplete#525]
Hello, I just used the plugin and I'm not good at English. I read and follow your instructions but EasyClangComple does not completion. Here are some pics:
![image](https://user-images.githubusercontent.com/44579553/47659910-84a2bd00-dbc8-11e8-9b3a-a1bd67a7ad4e.png)
![image](https://user-images.githubusercontent.com/44579553/47659931-8ff5e880-dbc8-11e8-8fe6-fec415231493.png)
Can you solve and answer me pls?

**Comment by niosus** [comment]
You can try to follow the tutorial here: https://niosus.github.io/EasyClangComplete/settings/#common_flags for how to set up the plugin with MinGW. Otherwise, please open a new issue following the issue template **exactly**. Otherwise I don't have enough information to help.
