### ISSUE TITLE
EasyClangComplete not showing up in Package Control

### ISSUE THREAD

**Issue by neet-h-patel** [niosus/EasyClangComplete#531]
# System info: #
- Sublime Text version: `3.1.1`
- Which system are you on: `OSX Mojave`
- Clang version: `10.0.0`

# What happens:  #
EasyClangComplete doesn't show up in Package Control's Install list. I wanted to reinstall this package
but for some reason it is not showing up. Restarted sublime, even reinstalled it three times (twice with brew cask install and once with direct download) but still no luck.

<details>
<summary>Sorry no logs since I removed all trace of ST3 during re-install.</summary>
  
```
<LOG GOES HERE>
```

</details>

**Comment by niosus** [comment]
Thanks! This is because I updated the link to the package in this PR: https://github.com/wbond/package_control_channel/pull/7323

I hope it gets reverted soon.

**Comment by neet-h-patel** [comment]
Works now ! Thank you so much. Btw, the new documentation is very good!

**Comment by niosus** [comment]
@neet-h-patel thanks for pointing out that smth was wrong. I completely missed it. 

I am glad you like the docs. Feel free to point out if there are any issues with them still.
