### ISSUE TITLE
Not accepting CMakeLists.txt with "project (Name)" instead of "project(Name)"

### ISSUE THREAD

**Issue by dvs23** [niosus/EasyClangComplete#533]
Hey! 

I just wasted about an hour after upgrading from 4.3.0 to 5.3.2, because my headers suddenly were no longer recognized. Finally I found out the only problem was:

[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: searching 'CMakeLists.txt' from '<some path>' to '/'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: found 'CMakeLists.txt' file: <some path>/CMakeLists.txt
[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: skipping file '<EasyClangComplete.plugin.tools.File object at 0x7fed882ec8d0>'. 
[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: no line starts with: 'project('

My second line was "project (Name)", not "project(Name)"...

After removing the space, everything works, so not a big deal - but I don't think searching for a CMakeLists.txt should fail because of such a tiny issue.

Great plugin nevertheless, I'm a happy user for a long time now :)

Thanks in advance
dvs23

**Comment by niosus** [comment]
I thought I fixed it in #96 but did not. I will look into that. Hope that's not a critical issue for you now.

**Comment by dvs23** [comment]
Oh it's no longer a problem since I simply deleted the space :) It just took some time to find it and maybe someone else is experiencing a similar issue.
Thanks for your time!

**Comment by niosus** [comment]
Closed in the commit above.
