### ISSUE TITLE
auto-completion not working

### ISSUE THREAD

**Issue by safield** [niosus/EasyClangComplete#540]
I am using EasyClangComplete plugin, and it does not seem to be doing anything.

I am using the Android ndk version 18b which is bundled with clang, and am developing on Windows. My clang compiler is not located in any default location on Windows. But since the docs say nothing about pointing to your clang location, I will assume it figures this out somehow.

My project is using Cmake, and a CMakeLists.txt is located in the project root. So after extensively reading the docs, its seems like I am set. Things should be working out of the box....which is not the case.

Have I potentially misinterpreted the instructions?

**Comment by niosus** [comment]
From the way you describe it you should be set. However, please, please, please follow the issue template. I will close this issue, but feel free to reopen it following the template. Without all the info provided there I definitely cannot help in any way.

**Comment by safield** [comment]
I have updated the initial post the best I could.

**Comment by niosus** [comment]
I'm sorry it's not good enough. You did not enable the `verbose` mode. I suggest you reopen a new issue and read *carefully* the issue template.

**Comment by safield** [comment]
I somehow forgot to flip the setting to true. I will open a new issue.

**Comment by niosus** [comment]
No worries. I just really want to make the issues helpful and it takes so much time to always ask for the same information over and over. Thanks for understanding.
