### ISSUE TITLE
Change the color of warnings

### ISSUE THREAD

**Issue by gri1n** [niosus/EasyClangComplete#542]
# System info: #
- Sublime Text version: `3.1.1 build 3176`
- Which system are you on: `Ubuntu 18.04.1 LTS`
- Clang version: `6.0.0-1ubuntu2`

# What happens:  #
Is it possible to change the colour that warnings are highlighted to differentiate them from errors?

**Comment by niosus** [comment]
Yeah, that makes sense. I think there is a way, but will need to check. I will look into this.

**Comment by gri1n** [comment]
Thanks, I only just noticed your reply. I have another question that I'm not sure is worth adding as an issue. Is it possible to limit the size of the completion popup? I noticed popup_maximum_width and popup_maximum_height in the settings but they don't appear to have any affect on the completion popup only the show type info and type body popups.

**Comment by niosus** [comment]
No, I don't think we have any influence on the completion popup from within the plugin.

**Comment by niosus** [comment]
I've started looking into this issue but still am kinda confused. I have never worked with color schemes in sublime text and it seems harder than I expected. 

Basically, we want to add the error regions in this part of plugin: 
https://github.com/niosus/EasyClangComplete/blob/1292434ff8bc47bd24dd578271fe144140d43926/plugin/error_vis/popup_error_vis.py#L112-L117

We will need to separate this into two calls to only add warnings and only add errors by controlling the `scope` parameter in `add_regions` function. That part is easy to do. The hard thing is how to use custom colors for those scopes and which scopes to use. For now I can't figure out the intended way to do this.
