### ISSUE TITLE
Help with "C Improved" please

### ISSUE THREAD

**Issue by adrenalith** [niosus/EasyClangComplete#543]
So plugin works perfectly when I'm using standard c++ syntax. What I'm trying to do is to switch to ["C Improved"](https://packagecontrol.io/packages/C%20Improved) and be able to work with autocomplete as if in c++ mode ( e.g. plugin doesn't know "using", and basically interprets everything as pure c ) How to make it work?

**Comment by niosus** [comment]
You should just move the `C Improved` setting into the `C++` entry in this setting:
https://github.com/niosus/EasyClangComplete/blob/3cb33e0224451d671011b8847c0dd6dc347f440e/EasyClangComplete.sublime-settings#L71-L76

Feel free to reopen if this doesn't work for you.
