### ISSUE TITLE
Have the possibility to switch between "\" and "/" in the new include autocompletion feature

### ISSUE THREAD

**Issue by ChristopheClaustre** [niosus/EasyClangComplete#560]
Hi niosus,

I am here to complain about the new include autocompletion features because I like to complain.
It would be cool to have the possibility to switch between `"\"` and `"/"`.

On windows, if I have a header in a folder "foo", by default your autocompletion feature will propose "foo\header.h" which will compile only on windows 👎. Can you add a settings to convert those path to unix style ? or just do it by default on windows ?

Thanks for the help.

**Comment by niosus** [comment]
Hey @ChristopheClaustre thanks for complaining :)

What is your setup? I never thought about it. Are the include paths always assumed to be unix style? Will the unix style paths compile on windows? If yes, I am happy to add the conversion (or to review a PR about it).

**Comment by ChristopheClaustre** [comment]
I am working on a windows 10 on a project for windows but which must be able to compile on unix systems.

Yes, the unix style paths will compile on windows !

In fact, before I was using VS and the autocompletion system integrated (intellisense) has a settings to switch from windows style to unix style path to support multi-platform projects.

**Comment by niosus** [comment]
Ok, cool. I will add the conversion soon. Should be easy.

**Comment by ChristopheClaustre** [comment]
I must precise that unix style path will compile on windows with msbuilds and gcc I don't know for others like clang or mingw. Maybe put a setting ?

**Comment by lulle2007200** [comment]
I should default to '/' as it compiles on all compilers on both windows and linux platform(as far as im aware)

**Comment by ChristopheClaustre** [comment]
Thanks for this update @niosus ;)
It works perfectly !

**Comment by niosus** [comment]
Glad that it works! :smile:
