### ISSUE TITLE
ECC throws weird errors for std function

### ISSUE THREAD

**Issue by lulle2007200** [niosus/EasyClangComplete#561]
ECC generates inconsistent Errors/Warnings.

```
#include <tuple>
#include <vector>
using namespace std;
int main(int argc, char *argv[]){
   vector< tuple<int,int,float> > E;
    E.push_back(make_tuple(0,1,0.5));
    E.push_back(make_tuple(0,2,0.5));
    E.push_back(make_tuple(1,3,0.3));
    E.push_back(make_tuple(1,4,0.3));
    E.push_back(make_tuple(1,5,0.4));
    E.push_back(make_tuple(2,4,0.5));
    E.push_back(make_tuple(2,5,0.5));
    E.push_back(make_tuple(3,0,1.0));
    E.push_back(make_tuple(4,6,0.5));
    E.push_back(make_tuple(4,7,0.5));
    E.push_back(make_tuple(5,6,0.25));
    E.push_back(make_tuple(5,7,0.25));
    E.push_back(make_tuple(5,8,0.25));
    E.push_back(make_tuple(5,9,0.25));
    E.push_back(make_tuple(6,0,1.0));
    E.push_back(make_tuple(7,0,1.0));
    E.push_back(make_tuple(8,0,1.0));
    E.push_back(make_tuple(9,0,1.0));

    return(0);
}
```

generates the error "no matching function call for "make_tuple" " for the first few times, the function gets called, but not for all (see picture: https://pasteboard.co/HVNUmnW.png). The number of errors is inconsistent too.

ECC finds the headers.

I'll add further information and log later today.

**Comment by lulle2007200** [comment]
A little late, but whatever.
Clang version: 8.0.0 built from latest source
Windows version: Windows 10 pro 1809

Windows 10 SDK 17763 currently installed to the usual location (%programfiles(x86)%\windows kits).
Same problem with Windows 10 SDK 16299.

ECC appears to get the correct include paths from clang and seems to find the headers.

Here the log: pastebin.com/ULckjjr2

**Comment by niosus** [comment]
This looks like a configuration issue to me. Can you also show your settings?

**Comment by lulle2007200** [comment]
It was indeed a configuration issue. I didn't set the c++ standard to c++17 properly and didnt notice it, even after looking at the user settings a billion times. Sorry for stealing your time, keep up the great work.

**Comment by niosus** [comment]
Glad that you've figured this out :)
