### ISSUE TITLE
ECC hangs Sublime Text UI during some operations

### ISSUE THREAD

**Issue by detly** [niosus/EasyClangComplete#562]
(I apologise in advance because this might be a bit more vague than I or you would usually like to see in a report. It's very hard to come up with an example for this straight off, but I'll post some follow up comments when I can reduce the problem a bit.)

# System info: #

- Sublime Text version: `3.1.1 3176`
- Which system are you on: `Ubuntu 18.04.1`
- Clang version: `6.0.0`

# What happens:  #

During some operations of ECC, the Sublime Text UI becomes unresponsive. When these operations are done, all the queued up UI stuff suddenly gets processed. For example, I can do <kbd>ctrl</kbd>+<kbd>pgdn</kbd> a bunch of times, nothing happens, and then suddenly ST cycles through the open files all at once. Same with keyboard mashing — nothing for seconds, then it all comes out.

The pause seems to happen while ECC is showing its progress indicator. It starts after this line in the log:

    [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-6]: [db]:[load new]

...and end when this line appears:

    [ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-6]: [db]: put into cache: '/tmp/EasyClangComplete/cmake_builds/af178d7f22de1e74be5079eed0d45a8c/compile_commands.json'

The issue is complicated by the fact that I'm working on an embedded project using Espressif's [ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/) system. For "real" compilation it involves an Xtensa-based toolchain, but since the build system is in CMake ECC can use it fine. So creating a reproducible example will take a lot of work (which you might have preferred I do before filing an issue, but I figured there's a chance the above information *might* be enough for you to identify a problem?).

I also need to make sure the log doesn't leak any confidential information, and I will post it soon.

**Comment by niosus** [comment]
Ok, I see the reasoning. The only thing that can happen here would be that the worked thread of sublime text gets clogged. When designing the flags sources part I was assuming that it does not take much time which is clearly not the case when running cmake. This might be an indicator that we need to run the command from another thread releasing the worker thread in the meantime. However, this is not trivial to do as some design modifications might be needed for that.
