### ISSUE TITLE
False positives all over project for SFML

### ISSUE THREAD

**Issue by hugfactory** [niosus/EasyClangComplete#565]
# System info: #
- Sublime Text version: 3.1.1
- Which system are you on: Windows 10 LTSB
- Clang version: 7.0.0

# What happens:  #
The plugin throws up all over itself when trying to find some classes and reports false issues all over the place from both custom code and library files.

See image here: https://imgur.com/dEeftG2

Log:

Package Control: Skipping automatic upgrade, last run at 2019-01-16 20:30:02, next run at 2019-01-16 21:30:02 or after
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.

**Comment by dannftk** [comment]
To make it work on Windows with 'cmake' you are supposed to choose one out of the list of cmake's generators that support clang compile database. On Windows 'cmake' does not have a generator by default unlike to linux where 'cmake' has 'Unix Makefiles" by default. There are 'MinGW Makefiles", 'Ninja" those can produce clang compile database. For example, 'Visual Studio'-related generators are not able to do that
Firstly, you need to call cmake with -G option followed by one of the generators offered by me or those supporting generation clang's compile database. For that, learn how to specify flags and transfer them to 'cmake' in ECC

**Comment by niosus** [comment]
Thanks @dannftk 
I should probably add this to the docs.
