### ISSUE TITLE
Header file issue

### ISSUE THREAD

**Issue by ReallyComeOn** [niosus/EasyClangComplete#568]
# System info: #
- Sublime Text version: 3.1.1, Build 3176
- Which system are you on: x86_64-solus-linux
- Clang version: 7.0.0

# What happens:  #
Not sure if this issue is with clang it-self or ECC (please forgive me)
When including:
      
    #include <gtk/gtk.h>

I of course added this to the common_flags.     

    "-I/usr/include/gtk-3.0/",

The header file is found, but for some reason ECC is unable to find any of gtk's types or identifiers.
PS.  "use_libclang" : false, doesn't fix it and logs are not helping.

Example: 

    GtkWidget* window; // shows ECC: Error 'unknown typename'
    window = gtk_window_new (1); // shows ECC: Error 'use of undeclared identifier'

**Comment by niosus** [comment]
I would still ask you to provide the log as at this point I can only guess what can cause the issues. I would expect it to be some kind of configuration issue.

**Comment by rcisterna** [comment]
I have a similar issue here, but I'm working with Arduino code (don't know if that matters). For 'log' you mean the output in the ST console when ```verbose = true```?

**Comment by niosus** [comment]
Sorry for the delay. New job takes lots of time. As for now, I don't really understand what is going on. Can you provide some sample code that I can try to reproduce this on?
