### ISSUE TITLE
Feature request: Copy code from pop up windows

### ISSUE THREAD

**Issue by sopgenorth** [niosus/EasyClangComplete#577]
One useful feature that would be useful to me, is allowing you to copy from the ECC: Info window that pops up for variable/function/type definitions. 

Of course, the current pop up window allows you to easily open the source file to copy the needed things from, but it'd be nice for it to be available right through the pop-up window. 

All in all though, ECC is the killer feature I've been wanting for Sublime! Great work.

**Comment by niosus** [comment]
Hey, sorry for the delay. Unfortunately, I cannot do this as I just rely on [mdpopups](https://github.com/facelessuser/sublime-markdown-popups) and it does not support this just yet. Feel free to open an issue there, I guess. I would love to have that feature, but don't know how complicated this can be to implement.
