### ISSUE TITLE
Adding CUDA support

### ISSUE THREAD

**Issue by JPenuchot** [niosus/EasyClangComplete#578]
CUDA is supported by clang, so it might be easier than it looks. The master branch is currently broken but once everything is back to normal I'll try to get my hands into it.

**Comment by niosus** [comment]
Why do you say, master is broken? I just built `dev` branch and it builds as expected.

**Comment by JPenuchot** [comment]
Sorry I think that's just the build system that's broken ([as you said in my pull request](https://github.com/niosus/EasyClangComplete/pull/576#issuecomment-478215879))
