### ISSUE TITLE
Is this pluggin supportting msys2 clang on win10??

### ISSUE THREAD

**Issue by danyuhao** [niosus/EasyClangComplete#59]
If supportted， which paths should I config for clang，  and where？
I installed clang and gcc in msys2(@ c:/msys64) like this:
```
jie@surface MSYS ~
$ which clang
/usr/bin/clang
jie@surface MSYS ~
$ which gcc
/usr/bin/gcc

```
Any suggestions??

**Comment by danyuhao** [comment]
If support， which paths should I config for clang，  and where？
I installed clang and gcc in msys2(@ c:/msys64) like this:
```
jie@surface MSYS ~
$ which clang
/usr/bin/clang
jie@surface MSYS ~
$ which gcc
/usr/bin/gcc

```

**Comment by niosus** [comment]
Hello! Thanks for the interest in the plugin. However, I don't work in Windows even remotely often, so I'm not the best source to ask about it. Sorry for that. I guess when you install something like msys64 you would need to configure proper bindings to windows power shell or cmd. But I may be wrong about this. 

Sorry again for not being able to help on this. However, if you do find a way - please let me know, I will add it to the readme.

**Comment by niosus** [comment]
I am going to close this issue for now, but I urge to report back if you still will make it work. Sorry for inconvenience.
