### ISSUE TITLE
Deprecation of `project_base_path`

### ISSUE THREAD

**Issue by mjendruk** [niosus/EasyClangComplete#592]
Hi! I have a question regarding the deprecation of `project_base_path`. In the release notes for `6.0.0` you say that they will be removed because `project_path` does the same. I don't think they actually do.

So far I have used `project_base_path` like this:

`.sublime-project` file in `D:\sublime\`
```
{
  "folders":
  [
    {
      "name": "R181",
      "path": "D:\\build\\R181\\"
    }
  ],
  "settings":
  {
    "ecc_common_flags":
    [
      "-I$project_base_path\\external\\inc",
      "-I$project_base_path",
    ]
  }
}
```

In this case `project_base_path` was replaced with `D:\build\R181\`. `project_path` however is `D:\sublime\`. Am I missing something?

**Comment by niosus** [comment]
Oh, you are right! I only looked at projects that have path set to `"."`, which led to this misconception of mine. I will not deprecate it and will tell this to the users in the next release. Thanks!

**Comment by niosus** [comment]
Closing as the notification will appear in the version currently being released.
