### ISSUE TITLE
Finding .clang_complete - add support for TreeSearchScope setting

### ISSUE THREAD

**Issue by FHTheron** [niosus/EasyClangComplete#598]
# System info: #
- Sublime Text version: `3-dev, build 3208`
- Which system are you on: `Ubuntu 18.10`
- Clang version: `7.0.0`

# What happens:  #
Searching for `.clang_complete` defaults to the directory of the file up to the first folder of the project. When the project file itself is located higher up and the first folder is below the `.clang_complete` file, it won't be found.

# Feature request:  #
While `project.settings.ecc_flags_sources.search_in` can take a list, it only searches in those specific directories. I would like to be able to specify a `search_from` and `search_to` directory that results in a TreeSearchScope. I can then specify the starting directory to be that of the file and the top most directory to be my project file directory.

This would need new keys or just new value types and wildcards in `ecc_flags_sources`. If there are any preferences or other ideas, please comment. I'd be happy to create a PR if the idea is acceptable.

# Settings Examples:  #
```
"ecc_flags_sources": [
  {
    "file": ".clang_complete",
    "search_in": [
      "~/my_fallback_file/",
      {
        "from": "$file_folder",
        "to": "$project_path" // Where .sublime-project is, not first folder
      },
      // or
      {
        "from": "$file_folder",
        "to": "/" // If we just want to go up to the drive/root
      },
    ]
  },
]
```
```
"ecc_flags_sources": [
  {
    "file": ".clang_complete",
    "search_in": [
      "~/my_fallback_file/",
      // Make ... imply "from/.../to"
      "$file_folder/.../$project_path",
      // or
      "$file_folder/.../", // up to root
    ],
  },
]
```

```
"ecc_flags_sources": [
  {
    "file": ".clang_complete",
    // New key, implies from file directory up to X
    "search_to": "$project_path"
  },
],
```

**Comment by niosus** [comment]
I might be wrong and will need to check, but I guess if you don't use the 'search_in' you will get exactly the behavior you are describing. By default the files are searched from file up the tree. I guess I need to update the docs if this works for you.

**Comment by FHTheron** [comment]
The default searches from the file up to the first project folder, which in my case is not a parent folder of the file I'm editing.

For example:
```
/path/my.sublime-project
/path/testing/.clang_complete
/path/testing/my/src/a/something.c
/path/testing/my/src/b/editthis.c
```

And /path/my.sublime-project would contain:
```
{
  "folders":
  [
    {
      "path": "/path/testing/my/src/a"
    },
    {
      "path": "/path/testing/my/src/b"
    }
  ]
}
```

Using the defaults, it searches from `/path/testing/my/src/b` to `/path/testing/my/src/a`.

**Comment by FHTheron** [comment]
A much simpler alternative would be to just have an option to search all the way up. Even with unreasonably complex and deeply nested code layouts, searching back up to root should be fast.

**Comment by niosus** [comment]
Actually this should already be the case. At least that is what I remember implementing. I can see one issue however as I don't know if I can handle multiple project folders... I will have a look in the coming days.

**Comment by FHTheron** [comment]
For what it's worth, making the change below gives me the behaviour I want, but definitely changes the expansion of `project_base_path` ( #592 ).

```
diff --git a/plugin/settings/settings_storage.py b/plugin/settings/settings_storage.py
index 8f6d77c..a6b8c22 100644
--- a/plugin/settings/settings_storage.py
+++ b/plugin/settings/settings_storage.py
@@ -300,7 +300,7 @@ class SettingsStorage:
         self._wildcard_values.update(variables)
 
         self._wildcard_values[Wildcards.PROJECT_PATH] = \
-            variables.get("folder", "").replace("\\", "\\\\")
+            variables.get("project_path", "").replace("\\", "\\\\")
 
         self._wildcard_values[Wildcards.PROJECT_NAME] = \
             variables.get("project_base_name", "")
```
