### ISSUE TITLE
Could there be an example on how to use CppProperties.json files

### ISSUE THREAD

**Issue by Niruz** [niosus/EasyClangComplete#599]
# System info: #
- Sublime Text version: `3.2.1`
- Which system are you on: `Windows 10`
- Clang version: `8.0.0`

# What happens:  #
I am very new to Sublime and so I have probably made a ton of mistakes, but the guide mentions that CppProperties files can be used but I'm not sure how to set it up correctly, and I found https://github.com/niosus/EasyClangComplete/issues/433 but I wasn't sure how they got it working. If I understand it correctly I need a sublime project file which looks like this

<details>
{
	"folders":
	[
		{
			"path": "test"
		}
	],
	"settings": {
        "easy_clang_complete_verbose": true,
        "ecc_use_libclang": true,
    },
}
</details>

and then I need a CppProperties.json ( https://devblogs.microsoft.com/cppblog/bring-your-c-codebase-to-visual-studio-with-open-folder/ ) that currenty looks like this

<details>
{
"configurations": [
{
"name": "Test",
"includePath": [ "Z:\\test\\dependencies\\include" ],
"defines": [ "_DEBUG" ],
"compilerSwitches": "/std:c++14",
"intelliSenseMode": "msvc-x64",
"forcedInclude": [],
"undefines": []
}
]
}
</details>

And then finally in Sublime I need to configure ECC which looks like this:

<details>
{
  "common_flags" : [
    "-I/usr/include",
    "-I$project_path/test/code",
    "-I/C:/Program Files/LLVM/lib/clang/8.0.0/include",
  ],

  "triggers" : [ ".", "->", "::", " ", "  ", "(", "[" ],

  "ignore_list": [
    "Z:/build/*",
    "Z:/test/misc/*",
    "Z:/test/data/*",
  ],

  "hide_default_completions": true,
  "show_type_info": true,
  "progress_style": "ColorSublime",
  "use_libclang_caching": true,

}
</details>

Do I still need a compile_commands.json file for it to work properly? I am currently using MSVC and running cl through a batch file, so if it's even possible to generate one on windows without CMake which I'm currently not using. Again, I have probably made a ton of mistakes but since ECC supports CppProperties files I was wondering if there's anywhere I could be pointed at to set it up correctly?

**Comment by niosus** [comment]
Ok, it seems there is a lot of questions in your post. 

First of all, the project settings should be completely enough. The settings to put there are exactly the same as the ones in User settings, just with an `ecc_` prefix. You don't generally need the User settings if you have project settings. 

Second, you should generally have a *single* flags source. So if you use `CppProperties.json` that is the only file you should use. However, I have never worked with those and we should ask @mclayton7 as it wsas his implementation. It seems you don't have either CMake or `compile_commands.json`, so you are stuck with manually specifying folders for searching includes. If you don't have a preference, I would just specify them as `ecc_common_flags` in your project settings. 

Overall, with your setup you will have to understand what you are doing and where all your includes lie. Unfortunately, I am not an expert in Windows and cannot provide much help here. :disappointed: 

As a side note, please use the fenced code block in markdown when pasting code on GitHub.

**Comment by Niruz** [comment]
Thanks for the reply! I realise this isn't technically an ECC issue so I appreciate any help I can get.

Okay, I removed all the user settings for ECC and changed my sublimeproject.sublime-project file to look like this:


	"folders":
	[
		{
			"path": "test"
		}
	],
	"settings": {
        "easy_clang_complete_verbose": true,
        "ecc_use_libclang": true,
		"ecc_common_flags" : [
			// some example includes
			"-I/Z:/test/code",
			// this is needed to include the correct headers for clang
			"-I/C:/Program Files/LLVM/lib/clang/8.0.0/include",
		  ],

	  "ecc_triggers" : [ ".", "->", "::", " ", "  ", "(", "[" ],

	  "ecc_hide_default_completions": true,

	  "ecc_show_type_info": true,

	  "ecc_progress_style": "ColorSublime",

	  "ecc_use_libclang_caching": true,
    },
	



And this file is located at Z:\ and all of my .h and .cpp files are located under Z:/test/code. If I understood correctly I can remove the CppProperties.json file and just specify where all header files are with the ecc_common_flags in the sublime project file? Do I need to put this project file in the same directory as my c++ files? I can see that ECC is running since it is visible at the bottom of sublime but nothing happens when I type. If this plugin works with me just saying where all the headers are that I want to include that would be fantastic :) 

Again, sorry to be a bother but I just can't quite get this working, which is probably my fault since I recently switched to using sublime.

**Comment by niosus** [comment]
>  If this plugin works with me just saying where all the headers are that I want to include that would be fantastic

It should work this way, yes. And yes, you can probably remove the `CppProperties.json`. Straightaway, I can see at least one issue with your current config - there is no need in `/` in your `-I` flags. For example, `"-I/Z:/test/code"` becomes `"-IZ:/test/code"`. You also don't need to duplicate most of the settings as they will be inherited from base settings. I will close this issue, but feel free to continue the discussion here.

**Comment by Niruz** [comment]
It is a bit strange, when I hover over variables I can see the "ECC info" box with descriptions so something is clearly working, I have tried a few things but I can't quite seem to get it working unfortunately. Anyways thanks for the help.
