### ISSUE TITLE
libclang based autocomplete and linting not working on Ubuntu 16.04 with clang 3.8

### ISSUE THREAD

**Issue by 0xdeadbeaf** [niosus/EasyClangComplete#60]
Hi,

i am currently using the plugin on Ubuntu 14.04 LTS, today i installed it on another Ubuntu 16.04 LTS system.
At the new system the autocompletion isn't working properly (especially std library).
`std::` sometimes gives no autocompletion. After waiting, drinking tee and hitting ctrl+s a few times it auto-completes...?

This never gives autocompletion:
```
std::vector<int> testVec;
testVec. 
```
Unfortunately, linting aka "errors_on_save" isn't working at all.

I didn't made changes in configuration files.

When i set `"use_libclang" : false` the behavior is as expected, autocompletion works and "errors_on_save" is working, too.

The configurations between the two systems are exactly the same. The only difference is Ubuntu 14.04 with clang 3.4 and Ubuntu 16.04 with clang 3.8. 

Although `"use_libclang" : false` works, i would like to use `"use_libclang" : true`. 
If you need more information, please tell me where to look and what to add.

**Comment by niosus** [comment]
I am planning to update my system to Ubuntu 16.04 during the next week or so, so I will be able to test it out. It is quite a pain to have everything done right with the clang bindings for all the different versions. Let's see what I got wrong with the `cindex38.py` file. I bet the problem is there.

**Comment by niosus** [comment]
Ok, this is strange. I have updated my laptop to 16.04 today and have just tried the plugin with the default clang installed through `apt-get`. Completion works as expected out of the box.

**Comment by 0xdeadbeaf** [comment]
I freshly installed a new laptop today with Ubuntu 16.04 LTS and have nearly the same issues as posted before. 
Auto-complete is now working fine with `"use_libclang" : true` but there is no linting after saving at all. After changing `"use_libclang" : false` my code is being linted after save.

`dpkg -s clang` yields:
```
Package: clang
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 28
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: llvm-defaults (0.33ubuntu3.1)
Version: 1:3.8-33ubuntu3.1
```

`clang --version`:
```
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I would like to help you to locate the issues... but i don't know what informations to provide. Can you tell me?

Exactly what i did after the fresh installation of Ubuntu 16.04:
## Base Install
```
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt update
sudo apt install sublime-text-installer
```

Set User-Settings to:
```
{
	"auto_complete_triggers":
	[
		{
			"characters": ".:>",
			"selector": "source.c++ - string - comment - constant.numeric"
		}
	],
	"font_size": 10,
	"ignored_packages":
	[
		"Vintage"
	]
}
```

Set User-Keybindings to:
```
[
	{ "keys": ["ctrl+7"],       "command": "toggle_comment", "args": { "block": false } },
	{ "keys": ["ctrl+shift+7"], "command": "toggle_comment", "args": { "block": true } },
	{ "keys": ["ctrl+space"],   "command": "auto_complete" },
	{ "keys": ["keypad_enter"], "command": "find_next", "context": [{"key": "panel", "operand": "find"}, {"key": "panel_has_focus"}]},
]
```

## Default editor
* Get application name:
`ls /usr/share/applications | grep -i subl`

* Add MimeType to found *.desktop:
```
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
```

* Replace gedit with the found name in the file:
`subl /usr/share/applications/defaults.list`


## C++ auto-complete and code linting
* In Sublime View -> Show Console type:
```
import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by) 
```
* Press CTRL + Shift + P
* Type `install`
* Press Enter
* Type `EasyClangComplete`
* Press Enter
* Then in terminal `sudo apt install clang`
* Reboot computer

**Comment by niosus** [comment]
Thanks for all the info. Sorry for delays in communication. Untill like 10th of September there is going to be a really busy time for me at work, so there will be even more delays. Sorry for that.

@0xdeadbeaf you can activate debug logging by using `verbose` set to `true` in the plugin settings. However, it won't help much as there is apparently a bug in the file `cindex38.py`

I was actually wrong, the completions do behave as you told. There are completions after `std::` but there is no correct completion for, say, a vector variable. Custom user types complete as expected. Error showing doesn't work either.

I have an example project [here](https://github.com/niosus/test-complete-plugin) where I hopefully can test what happens better. Please follow instuctions there and open as issue in that project. As soon as we find what is wrong there I will be able to move it here. 

It seems that there is something wrong with the python bindings for clang 3.8 as they don't work for any of the systems.

**Comment by niosus** [comment]
I am sorry, but I cannot seem to find what is wrong with the bindings on clang 3.8.

As a workaround for now, I suggest to install an older version alongside whichever clang you need otherwise. For example:
```
sudo apt-get install clang-3.5
```
Then specify to use this binary in settings of the plugin: `"clang_binary" : "clang++-3.5",` and this setup works for me on Ubuntu 16.04 with clang 3.8.

**Comment by samvasko** [comment]
I think it is also broken on macOS with:,
```
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by niosus** [comment]
@samvasko thanks. This is I guess known of. See issue #47 
I have just had an important deadline at work, so should have slightly more time to find out what is wrong with `cindex38.py` file.

**Comment by niosus** [comment]
There seemed to be an issue with an include. It was always generating an error: `'stdarg.h' file not found", 'col': '11', 'file': '/usr/include/wchar.h` 

So for those on Ubuntu 16.04, please add this to your plugin settings:
```json
"include_dirs" : [
                        ... some includes ...
                        "/usr/lib/clang/3.8/include"
                        ]
```

I should probably think of adding this automatically knowing the clang version one is using, system they are running on and the path it should be not too hard.

This still doesn't resolve Apple issues though.
