### ISSUE TITLE
ecc annotations sometimes stop updating

### ISSUE THREAD

**Issue by maddanio** [niosus/EasyClangComplete#602]
sometimes the annotations (i.e. red frames, error flags, pop-ups) somehow get stuck. i.e. they dont update anymore. also pop ups at this point do not happen anymore. the project is very large, so i do not have a reproducible example but a log:
[ecc.log](https://github.com/niosus/EasyClangComplete/files/3158156/ecc.log)

**Comment by niosus** [comment]
It might be because they are updated after the information is provided by the translation unit. That is - if the build takes a long time, it might take time to update. It is hard for me to say more on this without seeing the project.

**Comment by maddanio** [comment]
Yeah, I am aware. Not sure I can get something reproducible. Thing is on these files it really never gets it. It basically dies. Like a race that’s never won
