### ISSUE TITLE
ECC fails to work with Conan

### ISSUE THREAD

**Issue by akowalew** [niosus/EasyClangComplete#604]
I would like to use Conan with my projects. Unfortunately, I could not get ECC to work with it. Conan is producing CMake scripts inside the build directory, which are not copied by ECC to its compilation database (and are therefore not found when needed to include).

Paste from ECC log:
```
CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    /tmp/EasyClangComplete/cmake_builds/7cce2e2e739500d4b51379640204c963/conanbuildinfo.cmake


CMake Error at CMakeLists.txt:9 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".


-- Configuring incomplete, errors occurred!
```

The way I'm using Conan is pretty similar to recommended by its developers. I have in my top-level CMakeLists.txt following lines:
```CMake
# Conan setup
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

Is there any way to instruct ECC to either include original build dir (where my workspace is) in CMake commands, or just to copy some files (here `conanbuildinfo.cmake`) to its compilation database?

# System info: #
- Sublime Text version: 3.2.1 3207
- System: Ubuntu 18.04 LTS
- Clang version: 6.0.0-1ubuntu2

**Comment by niosus** [comment]
I don't know if this will work for you, but you can maybe do the same trick I did to make it work for catkin: https://niosus.github.io/EasyClangComplete/configs/#catkin-configuration

The idea there is that we can set the `CMAKE_PREFIX_PATH` to whatever we want before calling cmake command. I did not work with Conan but I assume you can get it to work in this way. Also, you can pass any flags to cmake command: https://niosus.github.io/EasyClangComplete/settings/#cmake-specific-options

Please give it a try and if it works - I will add it to the docs. If it does not, I will have a look at this at some point. Generally I would like to make it possible to use ECC with Conan-enabled projects. But I cannot promise a timeframe for this at this point.

**Comment by akowalew** [comment]
Thank you for that! I've added project build path to `ecc_flags_sources` and finally got it to work. Worth to mention about one modification in CMakeLists I had to add:
```CMake
# Conan setup
find_file(CONANBUILDINFO_FILE conanbuildinfo.cmake)
include(${CONANBUILDINFO_FILE})
conan_basic_setup()
```

This way CMake will search first for Conan configuration file in prefix paths. Now everything is OK and compilation database is generated. ;)

**Comment by niosus** [comment]
Thanks for this. I will close this issue for now, but might add this to the docs in the future.
