### ISSUE TITLE
clang -v invoked for any file type

### ISSUE THREAD

**Issue by 07151129** [niosus/EasyClangComplete#608]
# System info: #
- Sublime Text version: `3.2.1 3207`
- Which system are you on: `OS X 10.14.2`
- Clang version: `5.0`

# What happens:  #
Whenever a file is being opened that is not currently open in any tab, ECC invokes `$clang_binary -v` even if the file is not recognised by sublime syntax definition as C-like source. Is there a way to prevent ECC from doing that? Spawning a process has overhead that gets especially noticeable if multiple files are being opened at the same time.

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-3]: no settings for view 981. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-3]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-3]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-3]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-3]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-3]: Getting version from command: `/opt/llvm/bin/cc -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-3]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-3]: Populated '$project_base_path/src' to '/Users/...'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-3]: Populated '~/some_folder/*' to '/Users/User/some_folder/*'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-3]: Populated '$project_path/some/project/path/*' to '/some/project/path/*'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-3]: settings initialized for view: 981
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-3]: ECC does nothing for language syntax: 'Plain text'
```

</details>

**Comment by niosus** [comment]
That is a good point. :) I have been thinking about it some time ago, but there was some reason behind it. I will have a look at it and hopefully remove this.

**Comment by niosus** [comment]
Ok, so the issue is that this is done to check that users can specify custom syntax for which the plugin can run. For that we unfortunately need to load the settings for the view first. This might not be an optimal decision, but the alternative from my perspective is to just have a hard-coded list of languages, but then people will always complain that their syntax definition is not supported. The question here, I guess, is would you still notice the gap in performance on file open without the `verbose` flag? :wink:

**Comment by 07151129** [comment]
> For that we unfortunately need to load the settings for the view first.

Isn't the plugin already doing that, since it's using the correct $clang_binary value in `get_clang_version_str`?

> The question here, I guess, is would you still notice the gap in performance on file open without the verbose flag? 

Does ECC block sublime's main thread when invoking clang? The performance impact is noticeable with or without the verbose logging, but without profiling I don't know whether it can be safely attributed to ECC.
