### ISSUE TITLE
C and C++ should have separate settings for std_flag

### ISSUE THREAD

**Issue by Spudd86** [niosus/EasyClangComplete#61]
I write code in both C and C++ and since I use C99 and C11 features parsing the C as C++ will not have the same meaning since C99 and C11 are not subsets of C++ version. As long as you only use one language per project you _could_ set it in the project settings, but sometimes I have mixed language projects.

Basically I want to be able to have it parse C as C and C++ as C++ without needing to configure anything, it should just look at the file extension.

**Comment by niosus** [comment]
Ok, so would you be happy if there was another setting for `std_flag` for C? That is easy to add.

**Comment by niosus** [comment]
The only thing is that for now I don't care about extensions much. I just take the language that sublime text has guessed (bottom right corner).

**Comment by Spudd86** [comment]
The label from sublime text works just fine for me, I only care that it's parsing my C code as C.

So yea a second `std_flag` for C and picking the correct one to use based on what language Sublime Text thinks the file is would make me happy.

**Comment by niosus** [comment]
Ok, will do then.

**Comment by niosus** [comment]
Sorry for a big delay. This change should be live soon.
