### ISSUE TITLE
Support AppleClang 11

### ISSUE THREAD

**Issue by notbaab** [niosus/EasyClangComplete#611]
Console output. 

```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
error: Version '11.0' of AppleClang is not supported yet. Please open an issue for it
```

I'm just doing what the plugin tells me to do.

**Comment by niosus** [comment]
Noted. Will take care of this in a couple of days.

**Comment by FichteFoll** [comment]
Due to issues being created at both ST-specific repos, I suggest to add some indicator that this is dialog is created by the EasyClangComplete package.

**Comment by niosus** [comment]
@FichteFoll ooops. Sorry about that. Will fix the issue and add the appropriate notice ASAP.
