### ISSUE TITLE
Querying g++ default flags uses wrong options

### ISSUE THREAD

**Issue by merlinthered** [niosus/EasyClangComplete#614]
# System info: #
- Sublime Text version: `3.2.1`
- Which system are you on: `CentOS Linux 7`
- Clang version: `5.0.2b`

# What happens:  #
I have a project with an exotic build system that uses compilers from custom locations. For this reason I suspect I have to use the `target_compilers` to get ECC to find the standard library headers. I put the following into my project settings file:

```
"ecc_target_compilers": {
	"C": "/path/to/custom/gcc",
	"CPP": "/path/to/custom/g++",
	"OBJECTIVE_C": null,
	"OBJECTIVE_CPP": null
}
```
If I look into the log, I see that ECC tries to query the default flags of g++ using the wrong options:

```
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-8]: Getting default flags for ('/path/to/custom/g++', None, 'CPP')
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-8]: Querying compiler for defaults
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-8]: command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-8]: command output: 
g++: error: language CPP not recognized
g++: error: language CPP not recognized

[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-8]: command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-8]: command output: 
Using built-in specs.
COLLECT_GCC=/path/to/custom/g++
g++: error: unrecognized command line option ‘-Wp’; did you mean ‘-W’?
Target: x86_64-pc-linux-gnu
Configured with: /home/test/gcc/gcc-7.1.0/configure --enable-threads --enable-shared --enable-languages=c,c++,fortran --prefix=/usr/local/hudson/workspace/gnu_build_lin64_glibc2.10/linux-x86_64-2.10.1/gnu7.1.0
Thread model: posix
gcc version 7.1.0 (GCC) 
```

It seems that ECC is passing `-x CPP` to `g++` instead of `-x c++`. It also seems like it uses the `-Wp` option in a wrong way. In `compiler_builtins.py` line [194](https://github.com/niosus/EasyClangComplete/blob/0d0e4338c31e8fcffd9809cbce9d8a02b0e69fe2/plugin/utils/compiler_builtins.py#L194) the args are specified as: `['-Wp','-v','-E','-']`, but args passed to `-Wp` should be placed in a comma-separated list directly after `-Wp`, without spaces.
 
As a result, it seems like no target compiler options are found.

**Comment by 07151129** [comment]
My understanding is that -Wp affects nothing, because it passes an empty list of preprocessor options:

```
$ cc -Wp -v -E -xc -

clang version 5.0.0 (tags/RELEASE_500/final)
...
warning: unknown warning option '-Wp' [-Wunknown-warning-option]
```

On the other hand, for gcc this is an error:

```
$ gcc -Wp -v -E -xc -

gcc: error: unrecognized command line option '-Wp'; did you mean '-W'?
```

For your purpose you could specify -isysroot or -I flag(s) for your target in the project settings instead of relying on compiler to report the correct paths.

**Comment by niosus** [comment]
However, I agree, that if we provide an option to generate relevant flags from the compiler that feature should actually work :) I will have a look as soon as I find the time.

**Comment by niosus** [comment]
@merlinthered this week I will have time to look at it, but I switched to a Mac and don't have a linux machine handy. 

> args passed to -Wp should be placed in a comma-separated list directly after -Wp, without spaces

Could you maybe fix it and create a PR for this? I would then merge it quickly.
