### ISSUE TITLE
Some primitive types and keywords are not appear in completion list

### ISSUE THREAD

**Issue by hadisfr** [niosus/EasyClangComplete#618]
# System info: #
- Sublime Text version: `3.2.1`
- Which system are you on: `macOS 10.14`
- Clang version: `Apple LLVM version 10.0.1 (clang-1001.0.46.4)` (result of `clang++ --version`)

# What happens:  #
Some primitive types and keywords are not appear in completion list; e.g. `return`, `true`, `long`, etc.

![image](https://user-images.githubusercontent.com/24562441/61167406-e424db00-a553-11e9-9473-aeebe1209d46.png)

<details>
<summary>a small code example: </summary>
  
```cpp
#include <iostream>

using namespace std;

bool my_function();

int main(int argc, char const *argv[])
{
    bool res = my_function();
    return 0;
}

bool my_function() {
    return true;
}

```

</details>

[log.txt](https://github.com/niosus/EasyClangComplete/files/3388483/log.txt)

**P.S.**: It seems that I was using the plug-in with `"use_libclang": false`. When I switched back to the default `"use_libclang": true`, the problem seems to be solved.

**Comment by niosus** [comment]
At this point we only target using libclang. So I will close this issue as you say that it works when using libclang.
