### ISSUE TITLE
plugin_host has exited unexpectedly

### ISSUE THREAD

**Issue by noelfarrugia09** [niosus/EasyClangComplete#622]
# System info: #
- Sublime Text version: `3207`
- Which system are you on: `macOS Mojave`
- Clang version: `Apple LLVM version 10.0.1 (clang-1001.0.46.4)`

# What happens:  #
This happens in a random fashion so I don't have a way to give an example that always reproduces the issue. But what happens is that sometimes when I am typing a function's name a Sublime popup shows stating that the plugin_host has exited unexpectedly. What I'm noticing is that when I set "use_libclang" to false the crash no longer happens.
I know it's not a lot to go on but feel free to tell me what steps/log I can take to help you figure out what's going on.

The Log output is attached.
[ecc.txt](https://github.com/niosus/EasyClangComplete/files/3452163/ecc.txt)

**Comment by niosus** [comment]
Thanks for reporting. When not using libclang a completely different method of completion is used. I see some weird errors in the log. Can you provide your settings? If there would be a way for me to reproduce this it would be really cool!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by noelfarrugia09** [comment]
My settings are all default. I finally managed to reproduce this! The problem is when using the C++17 Structured binding declaration. The below is an example that will produce the crash:

```
#include <utility>

std::pair<int, int>
MyFunction()
{
  return std::make_pair(10, 10);
}

int main(int argc, char const *argv[])
{
  auto [a, b] = M
  return 0;
}
```

as soon as I type the M after auto [a,b] the plugin crashes. I tried to update the settings to set the language to c++17 as shown below but the crash is still occurring:

```
{
    "lang_flags": {
    "C": ["-std=c11"],
    "CPP": ["-std=c++17"],
    "OBJECTIVE_C": ["-std=c11"],
    "OBJECTIVE_CPP": ["-std=c++11"],
  },
}
```

Hope this helps!

**Comment by niosus** [comment]
Unfortunately I cannot reproduce this on macOS 10.14.6... Everything works as expected. It shows an error if I have `c++11` as standard and works when I have `c++17`.

**Comment by noelfarrugia09** [comment]
Thank you for taking the time to check this issue.
