### ISSUE TITLE
Feature for configuration of error highlighting

### ISSUE THREAD

**Issue by oakmountainapps** [niosus/EasyClangComplete#634]
# System info: #
- Sublime Text version: `3`
- Which system are you on: `Windows/Linux`
- Clang version: `7`

# What happens:  #
I was planning to implement a configuration options which selects how EasyClangComplete will highlight errors in the code. Something like Anaconda has:

    /*
        If 'outline' (default), anaconda will outline error lines.
        If 'fill', anaconda will fill the lines.
        If 'solid_underline', anaconda will draw a solid underline below regions.
        If 'stippled_underline', anaconda will draw a stippled underline below regions.
        If 'squiggly_underline', anaconda will draw a squiggly underline below regions.
        If 'none', anaconda will not draw anything on error lines.
    */
    "anaconda_linter_mark_style": "outline",

This configuration would then be read in popup_err_vis.py:show_errors() and flags to view.add_regions() would then be set accordingly. I myself is interested in the 'none' options since I don't want anything drawn in the code. Is this something that you would be interested in me uploading as PR?

<details>
<summary>Log that illustrates the issue: </summary>
N/A
</details>

**Comment by niosus** [comment]
Sounds good to me. Just add the `linter_mark_style` to the settings then 👍
