### ISSUE TITLE
clang_flags in sublime-project not used

### ISSUE THREAD

**Issue by merlinthered** [niosus/EasyClangComplete#64]
When I set `use_project_specific_settings` to `true`, all the clang flags I specify in my project are used, but none of the ones in the global settings. This is ok.

When I set `use_project_specific_settings` to `false`, only the clang flags from the global settings are used, and the ones in the project file are ignored. This is not how it's advertised in the README, and it's also not how it should work. In general, you want some flags you always use, and some that are project specific. When building, you want to use all of them at once. Otherwise you have to repeat the global settings in each and every project.

My User settings file only defines `"verbose" : true` to discover which clang flags are used. All other settings are default. I'm on Linux.

**Comment by merlinthered** [comment]
I just discovered that apparently the clang flags which are printed in the debug log are not even all used. 

For example, I have a c++ file where I include a certain header in a nonstandard location. I add the location to `clang_flags` in my project settings. I set `use_project_specific_settings` to `true`. The debug log shows that the path is in fact added to the clang flags used in `lib_complete`. However, I still get an error vis on the line where I include the header, stating that the file could not be found.

When I manually call clang++ on the command line for that source file, using that same include path, I don't get this error. If I omit the include path, the same error appears. 

Did you maybe forget to pass the clang flags to libclang somewhere? When I search for clang_flags in your source files I only find occurrences in `bin_complete`, but not in `lib_complete`. In fact, when I set `use_libclang` to `false`, the error disappears.

**Comment by niosus** [comment]
Sorry for the delay. This is quite a busy time for me. 

I understand the issue. Currently if you have any project specific settings ALL other settings are ignored. If you don't use project specific setting they will ALWAYS be ignored. Sorry if that was not clear from documentation.

I guess this behavior is indeed suboptimal. Alternatively, I could just merge all flags together. However, this is not a simple decision to make, I guess. It will take some time to do as now it is a really busy time at work + I am struggling to make clang 3.8 work as expected on Ubuntu 16.04 and Windows. Sorry for that.

**Comment by rchl** [comment]
Always merging might not be always correct either. I can imagine that in some cases one might want to completely override user settings with project ones.

**Comment by niosus** [comment]
@rchl cases like what? 

We can ensure, that the priority of the project-specific settings is always higher than that of other ones. This way the only settings that will be still there are possibly some common include directories and they don't break things generally.

Alternatively, we could add an element to json project settings file under our tag that will handle the behavior.

**Comment by rchl** [comment]
I was specifically thinking about the clang-cl case. It doesn't accept `-std=c++11` flag (I assume it's the default). But that could in theory be handled different - by having clang-cl specific `std_flag_cpp`/`std_flag_c` options. Not sure what is better.

**Comment by merlinthered** [comment]
What about this: Have a place to specify flags in the global settings just like we have now, but in the project specific settings, we introduce two variables: `clang_flags`, and `clang_flags_extra`. `clang_flags` overwrites the global `clang_flags` (if it is defined in the project), while `clang_flags_extra` is appended to whatever `clang_flags` resolves to, no matter if there is a project specific definition or not. This would also allow us to get rid of `use_project_specific_settings` in an elegant way.

**Comment by niosus** [comment]
Ah, @rchl so you refer to the case where there is no setting in project specific settings to override the default one, but the picked binary doesn't accept the flags, I see. I don't think I like the idea of having a clang-cl specific setting, because it is Windows only, but everyone will have to see it, and this is usually confusing.

@merlinthered this sounds ok to me at the first glance, but will give it more thoughts once I get my hands to actually implement this. Thanks for an idea.

**Comment by rchl** [comment]
As a side note, I think it wouldn't hurt to let *any* setting be overridden by project specific settings.
For example I have to point to different clang-binary path on different systems (as that binary is in a checkout which is in different directories).

**Comment by niosus** [comment]
@rchl this is actually a good idea and a better way to go.

From the next version on I will deprecate the setting `use_project_specific_settings` and the needed functionality will be achieved by adding a `settings` tag and overriding settings there. These settings will ALWAYS override the ones defined in the user preferences. Use it like this in file `*.sublime-project`:
```json
{
	"settings":
	{
			"use_libclang": true,
                        "verbose": true
	}
}
```

So what do you think?
