### ISSUE TITLE
Disable popups when hovering over text

### ISSUE THREAD

**Issue by jack1223233244** [niosus/EasyClangComplete#646]
I have defined constant char strings in a class and now when I hover over these strings I get this huge popup with the body of the entire class inside the popup. It is incredibly annoying when trying to edit the contents of the strings. Is it possible to do something about this? Or can I somehow disable the popups from ECC? Much appreciate the help!

**Comment by niosus** [comment]
Sure. You can disable showing the full class for example. Just look through the settings.

**Comment by jack1223233244** [comment]
> Sure. You can disable showing the full class for example. Just look through the settings.

Didn't know that plugins had their own settings you could tweak. Thanks very much for the help :)

**Comment by niosus** [comment]
Sure, I will close this issue for now, but feel free to reopen it if something is still missing.
