### ISSUE TITLE
Navigate to next error

### ISSUE THREAD

**Issue by zhiayang** [niosus/EasyClangComplete#650]
### feature request

Not sure what happened to the second half of #350, but there's still no command to navigate to the next error and the issue was closed.

Given that there's already a way to get all the errors in a file, it might be plausibly not-that-difficult to get the next error whose location is after the current position?

I'm not well-versed in python, but if you tell me where to look to get started I might be able to get a PR together.

**Comment by niosus** [comment]
If you show all errors you can easily navigate between them. Is this enough for you or would you still want a button to navigate to the next error?

**Comment by zhiayang** [comment]
There's still some inconveniences using the show-all-errors list:

1. changing the selection doesn't "live update" the text view, I actually have to press enter to move the cursor to the error. Would be nice if it scrolled the screen (without physically changing the cursor position?).

2. The list doesn't have any awareness of the cursor position in the file, so the selected error is always the first item. The main use-case is that I'm fixing errors from top-to-bottom --- in this scenario, i'd have to repeatedly down-arrow my way to the next error (I don't save the file immediately, since it takes a while to update).

I think for me the key feature is goto *next* error.

**Comment by niosus** [comment]
Well, while I understand what you want I am hesitant to spend time on this as I doubt this will actually add much value. In C++ most errors after the first one are garbage anyway, so ideally, you should rebuild the file after fixing the first one.

**Comment by zhiayang** [comment]
Hmm, that isn't always the case, but I can understand your hesitation? Does ECC currently have a command to just jump to the first error then?

**Comment by niosus** [comment]
I believe the top-most entry when showing all errors is the first one.
