### ISSUE TITLE
Option to change the commands that is used to get default definitions

### ISSUE THREAD

**Issue by lulle2007200** [niosus/EasyClangComplete#651]
# System info: #
- Sublime Text version: `Build 3211`
- Which system are you on: `Windows 10`
- Clang version: `Clang 9.0.0`

It would be nice to be able to change the commands that are used to get the default definitions and includes. Especially for cross platform development that would be useful. When targeting - lets say - arm and developing for a stm32 device, i obviously dont want the Windows SDK/C library headers in my includes. Same situation with default definitions. 

Being able to add additional options like "--target=arm-none-eabi -mcpu=cortex-m4 --sysroot=path/to/arm-none-eabi" etc. to the commands that are used to retrive the defaults would be a really nice feature.

If that's already a thing or there's other issues about this - i am sorry.

**Comment by niosus** [comment]
What would happen if you just append the proposed lines to the `target_compilers` setting?

**Comment by lulle2007200** [comment]
Just tried that, doesn't seem to work. 
I added `"clang --sysroot=\"c:\\program files\\gcc\\arm-none-eabi\""` to the C target compiler option (tried with normal slashes aswell).
ECC fails with `[ECC:WARNING]: No output from cmd to get default flags: ['clang --sysroot="c:\\program files\\gcc\\arm-none-eabi"', '-x', 'c', '-std=c11', '-c', 'ECC_temp_file.cpp', '-dM', '-v', '-E']`

For now i just disabled default includes and definitions entirely and added the right include directories with `isystem` flags in common_flags.

**Comment by niosus** [comment]
Ok, I see the issue. We could probably add a new subsetting under the `target_compilers` setting to allow for flags there. I will try to have a look. If you want to try your hand in this - fell free to throw a PR at me.

**Comment by lulle2007200** [comment]
Sent PR
