### ISSUE TITLE
Can't find system framework headers on macOS

### ISSUE THREAD

**Issue by tomeksowi** [niosus/EasyClangComplete#653]
# System info: #
- Sublime Text version: `3.2.2, Build 3211`
- Which system are you on: `macOS 10.15.1`
- Clang version: `Apple clang version 11.0.0 (clang-1100.0.33.12)`

# What happens:  #
EasyClangComplete doesn't find default framework headers, e.g. Cocoa.

A `cocoa_simple.m` file that illustrates the issue:
```Objective-C
#import <Cocoa/Cocoa.h>

int main()
{
	@autoreleasepool {
		NSApplication* app = [NSApplication sharedApplication];
		return app ? 0 : 1;
	}	
}
```

Compiling it from command line with `clang cocoa_simple.m -framework Cocoa` works fine but in Sublime EasyClangComplete fails with `'Cocoa/Cocoa.h' file not found` and in consequence `use of undeclared identifier NSApplication`.

The source file is in the Sublime project, I don't use CMake. My user settings for EasyClangComplete are:

```JSON
{
"common_flags" : [
	"-I/usr/include",
	"-I$project_path",
	"-I/usr/lib/clang/$clang_version/include",
	"-I$file_path",

	// Stuff added by me
	"-framework Cocoa",
	// This is where Cocoa.h resides on my system
	"-I/Library/Frameworks/Cocoa.framework/Versions/A/Headers",
],

"lang_flags": {
	"C": ["-std=c11"],
	"CPP": ["-std=c++17"],
	"OBJECTIVE_C": ["-std=c11", "-ObjC"],
	"OBJECTIVE_CPP": ["-std=c++17", "-ObjC++"],
},

"verbose" : true,
"clang_binary" : "clang",
}
```

As mentioned in the comment, `Cocoa.h` resides in `/Library/Frameworks/Cocoa.framework/Versions/A/Headers` on my system. However, it's not enclosed in a `Cocoa` directory as specified in the `#import` statement -- this seems to be normal on a Mac, I can't find any symlink location that would have the header path enclosed in a directory named after the framework.
<details>
<summary>Log that illustrates the issue: </summary>

[EasyClangComplete.log](https://github.com/niosus/EasyClangComplete/files/3923787/EasyClangComplete.log)

</details>

Could be related to #626 and #652.

**Comment by niosus** [comment]
Thanks for reporting! Could you verify if #652 affects you? Does it work for you with that fix?

**Comment by tomeksowi** [comment]
It's better after applying the fix for #652. However, there are still problems with some headers, e.g.
```obj-c
@import Metal;  // OK, I see most symbols are indexed
@import QuartzCore.CAMetalLayer;  // ECC Error: could not build module 'QuartzCore'
#import <QuartzCore/CAMetalLayer.h>  // Equivalent of the above in the old syntax, fails with the same error
```
I experience the same problem with `@import AppKit`. I'm not how they are different from `@import Metal` which works. Of course, I added `-fmodules` in ECC settings.

Another thing (perhaps to be raised separately) is the size of the ECC Info tooltip. It tries to fit the original header in the Body section, which may result in the tooltip width exploding past screen bounds as most Apple's headers don't line-break doc comments assuming the reader has word wrap. I of course have `"word_wrap": true` in my user settings.

**Comment by saagarjha** [comment]
I have

```json
"popup_maximum_width": 500,
"popup_maximum_height": 500,
```

in my configuration to deal with the latter issue. But back on topic, can you just not import those headers at all? I was having some issues with modules, but for me it largely went away if I had them off. Are you seeing them in both cases?

**Comment by tomeksowi** [comment]
@saagarjha, I was unaware of "popup_maximum_*". Decreasing it worked, thank you.

As for the main issue, `CAMetalLayer` is a necessary link between Cocoa and Metal. I can't eschew it, unfortunately.

As for turning off modules and replacing `@import` with regular `#import <header>`, ECC does parse `CAMetalLayer` correctly. However, it slows down the compilation noticeably so I'd rather not do it.

**Comment by niosus** [comment]
Unfortunately, beyond fixing the above issues I don't know how I could help. I am by far not an expert in Objective C and the whole Objective C implementation was a contribution. :man_shrugging: 

Sorry about that
