### ISSUE TITLE
Support for Xcode builds

### ISSUE THREAD

**Issue by guinzoo** [niosus/EasyClangComplete#654]
# System Info:
Sublime Text version: 3.2.2, Build 3211
Which system are you on: macOS 10.14.6
Clang version: Apple clang version 11.0.0 (clang-1100.0.33.16)

# What happens:

I generate _compile_commands.json_ using xcodebuild and [xcpretty](https://github.com/xcpretty/xcpretty) and have found some errors in generating compile flags.

First, in generated _compile_commands.json_ input file argument is not the last, so method _filter_bad_arguments_ does not exclude it.

Second, _SEPARABLE_PREFIXES_ in _flags.py_ lacks _"-index-store-path"_ and _"--serialize-diagnostics"_ (with 2 dashes) and _"-fmodules-cache-path"_ have to be only in _PREFIXES_WITH_PATHS_.

Also it will be great if there will be a command to generate _compile_commands.json_ from xcode projects. It needs to run just 2 commands:
```
xcodebuild clean -project "{path-to-.xcodeproj}" -scheme "{name-of-scheme}"
xcodebuild -project "{path-to-.xcodeproj}" -scheme "{name-of-scheme}" | xcpretty -r json-compilation-database -o compile_commands.json
```

**Comment by niosus** [comment]
I don't currently have a mac to test these things. If you are willing to put some time into that, I would be happy to look at a PR that implements this. :wink:

**Comment by guinzoo** [comment]
I've created [pull request](https://github.com/niosus/EasyClangComplete/pull/656). Seems it has some errors in python2.7, but I don't have much experience with python. Later I will try to create a command to generate db from xcode.

**Comment by guinzoo** [comment]
Can be related to #653
I use such settings and everything works fine:
```
"use_libclang" : true,
"use_default_includes": false,
"use_default_definitions": false,
```

**Comment by niosus** [comment]
As described in the PR, I guess I will have to close this issue as I won't be able to support it even once its merged and I guess it is possible to perform these actions outside of the plugin and to use the resulting compilation database with ECC afterwards.
