### ISSUE TITLE
Error highlight is now white instead of red

### ISSUE THREAD

**Issue by chalizardmisadon** [niosus/EasyClangComplete#661]
As of the new commit, error outline / highlight is now in white instead of red. Can you add an option to either:
- allow the user to specify the specific error highlight color?
- or just link the error highlight color to "misspelling" color in ColorScheme-Default/*.sublime-color-scheme

Regardless, thank you for this plugins. Really helps me out in my day to day work.

**Comment by niosus** [comment]
Oops, this is definitely not intended. I thought if I provide an unknown syntax it will just show png as is and those are colored by default. I will look into that. Thanks for the idea with `misspelling`.

**Comment by niosus** [comment]
Are you by any change using a light scheme? I just looked into it and I still see the errors as black in light schemes, but as red in dark schemes.

**Comment by chalizardmisadon** [comment]
I am currently using Monokai.sublime-color-scheme. The quick fix I have is to add the color scheme for the scope "undefined" within "rules" inside Monokai.sublime-color-scheme
~~~json
{
    "name": "Monokai",
    "author": "Sublime HQ Pty Ltd, Wimer Hazenberg",
    "variables":
    {
        "black": "hsl(0, 0%, 0%)",
        ...
        "purple": "hsl(261, 100%, 75%)",
        "red": "hsl(0, 93%, 59%)",
        "red2": "hsl(338, 95%, 56%)",
        "white": "hsl(0, 0%, 97%)",
        ...
    },
    "globals":
    {
        "foreground": "var(white3)",
        ...
        "tags_options": "stippled_underline",
    },
    "rules":
    [
        {
            "name": "ECC Undefined",
            "scope": "undefined",
            "background": "var(red2)"
        },
        {
            "name": "Comment",
            "scope": "comment",
            "foreground": "var(yellow5)"
        },
        {
            "name": "String",
            "scope": "string",
            "foreground": "var(yellow)"
        },
       ...
    ]
}
~~~

**Comment by chalizardmisadon** [comment]
I added the quick fix based on the example:
https://www.sublimetext.com/docs/3/color_schemes.html#scope_rules

**Comment by Lancelot-0** [comment]
The issue commes with the change at *line 27* of `plugin/error_vis/popup_error_vis.py `
`    _ERROR_SCOPE = "undefined"`, and undefined is not always a scope depending of color schemes, while `"invalid.illegal"` was a valid entry

**Comment by niosus** [comment]
I've looked a bit closer into the issue and that got me even more confused. On my system, I see the color perfectly fine in all the dark themes. 
![image](https://user-images.githubusercontent.com/1893598/74761093-b89d6800-527b-11ea-8648-fad86ef9b24c.png)

Surprizingly, light themes show me just black outlines. All of them. 

The `undefined` scope was chosen on purpose. The docs say, that the icon will be tinted with the color assigned to scope and I wanted to avoid it by providing already colored icons and no tint. This seems to not really work as expected.

The problem with tints is that there is no way to control that and there are no scopes like `meta.error` and `meta.warning` or smth. So I would need to hack around this, which I really wanted to avoid.
