### ISSUE TITLE
Error highlighting is off by one line.

### ISSUE THREAD

**Issue by asheeshr** [niosus/EasyClangComplete#675]
![ecc_error_wrong_line](https://user-images.githubusercontent.com/1908945/76663311-f88ffc00-6556-11ea-81d1-856931df8b86.gif)

--------------------------------------------------------------

# System info: #
- Sublime Text version: `ST3 Build 3211`
- Which system are you on: `Ubuntu 16.04`
- Clang version: `3.8.0-2ubuntu4`

# What happens:  #
Error highlighting is off by one line.

[sublime.log](https://github.com/niosus/EasyClangComplete/files/4331874/sublime.log)

**Comment by niosus** [comment]
Yep, I'm already on it. Will release the fix later today.

**Comment by niosus** [comment]
Fixed in #674 and will be release in about half an hour.
