### ISSUE TITLE
Files of form `/User/smth` are parsed as flag which breaks compilation

### ISSUE THREAD

**Issue by firesense** [niosus/EasyClangComplete#677]
# System info: #
- Sublime Text version: `3.2.2, Build 3211`
- Which system are you on: `macOS Catalina 10.15.3`
- Clang version: `11`

# What happens:  #
After installing (updating) EasyClangComplete v.6.2.6 to v.6.2.7, the EasyClangComplete package stopped working and gives the following error:

[ECC: WARNING]: OSX version 11.0 reported. Reducing it to 7.0.
[ECC: INFO]: Found clang version 7.0
[ECC: INFO]: init completer based on libclang
[ECC: ERROR]: error while compiling: Error parsing translation unit.
[ECC: CRITICAL]: cannot create translation unit. Abort.

It does not works neither with std nor with Qt5

With EasyClangComplete v.6.2.6 everything worked perfectly!
My CMakeLists.txt file is attached:
[CMakeLists.txt](https://github.com/niosus/EasyClangComplete/files/4334117/CMakeLists.txt)

<details>
<summary>Log that illustrates the issue: </summary>
  
[log.txt](https://github.com/niosus/EasyClangComplete/files/4334115/log.txt)

</details>

**Comment by niosus** [comment]
I think I see the issue...
```
'/U', 'sers/dsso/Dropbox/Public/develop/macOS/qt-projects/tester-qt5-NURBS_curves/src/mainwindow.cpp'
```
Somehow this flag was separated instead of being ignored. I will see what I can do about this.

**Comment by niosus** [comment]
Should be fixed in v.6.2.8, which is going to be available in about half an hour or so.
