### ISSUE TITLE
Crash when editing codes

### ISSUE THREAD

**Issue by hliu1020** [niosus/EasyClangComplete#680]
# System info: #
- Sublime Text version: `3.2.2, Build 3211`
- Which system are you on: `macOS Catalina`
- Clang version: `Apple clang version 11.0.0 (clang-1100.0.33.8)`

# What happens:  #
The plugin crashed when editing code. It always happens if editing some codes at the same time when the `moon` progressing icon appears (it seems the plugin is busily handling last edited code)

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:DEBUG]:[subl_bridge.py]:[get_pos_status]:[MainThread]: matched trigger '::'.
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: this position has identifier: '(80, 61003)'
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: starting async auto_complete with id: (80, 61003)
[ECC:DEBUG]:[singleton_thread_pool.py]:[new_job]:[MainThread]: Cannot cancel job: 'job: 'complete''
[ECC:DEBUG]:[singleton_thread_pool.py]:[new_job]:[MainThread]: Canceled job: 'job: 'complete''
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: hiding default completions
[ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-6]: on_modified_async view id 80
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-6]: config exists for view: 80
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-6]: config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x10cc3fe10>
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-6]: config exists for view: 80
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-6]: config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x10cc3fe10>
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

</details>

**Comment by niosus** [comment]
Thanks for reporting. This is very strange. Is it a new behavior or did it also happen before? Also, please provide a full log do that I could have some more information on this.

**Comment by hliu1020** [comment]
It also happened before time to time, especially when editing during the progress of the plugin busy handling for last edited code (the `moon` progressing icon is running). I think maybe my modifying conflicts with something. I attach all the verbose logs before crash-restarting and hope it helps

.   
[st3_crash.log](https://github.com/niosus/EasyClangComplete/files/4347777/st3_crash.log)

**Comment by niosus** [comment]
It should not be the case as everything is handled in an asynchronous manner and I tried to make sure that we never access `libclang` concurrently, which could cause the failure. I will try to have a deeper look into this.

**Comment by niosus** [comment]
Looking at your log it doesn't seem to happen all the time. Does it only happen on a specific project? Is there a small test project where you could reproduce this? Does it only happen on a MacOS? Is there a specific action that you do that causes it or does it just happen in different places in the code randomly when you edit the code?

**Comment by brupelo** [comment]
I've started to use the package few minutes ago and I've also experienced this crash, ie:

![showcase](https://bit.ly/2XJsVOz)

Unfortunately I haven't been able to reproduce it consistently (just couple of times and I'm not sure what was the reason of the crash), my specs below:

```
clang version 10.0.0 - Target: x86_64-pc-windows-msvc
OS: windows7
ST: 3211
EasyClang: 6.4.2
```

Also... one question, although I'd probably open a different issue for this one... but, what does this mean?

```
Traceback (most recent call last):
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 688, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "D:\sources\personal\sublimetext3\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 563, in on_query_completions
    if not SublBridge.has_valid_syntax(view, settings):
  File "D:\sources\personal\sublimetext3\Data\Packages\EasyClangComplete\plugin\utils\subl\subl_bridge.py", line 198, in has_valid_syntax
    lang_tag, lang = SublBridge.get_view_lang(view, settings_storage)
  File "D:\sources\personal\sublimetext3\Data\Packages\EasyClangComplete\plugin\utils\subl\subl_bridge.py", line 160, in get_view_lang
    for lang_tag, syntaxes in settings_storage.valid_lang_syntaxes.items():
AttributeError: 'SettingsStorage' object has no attribute 'valid_lang_syntaxes'
```

Hopefully you can advice here... i've just opened a sublimetext clean, added a folder, created a dummy main.cpp, save the sublime project and this happens... I'd expect it to give no errors even if i haven't configured, anything, right?

I recall I'd tried this package couple of years ago and at that time it was pretty unstable... I'll give it a shot again as I'd love to use to start using it so i can stay away from QtCreator+Vs hehe.

Also... is there any way to disable easyclang without uninstalling it?

Tyvm!

**Comment by niosus** [comment]
Hey @brupelo thanks for the info. So the trace with the settings storage looks like an artifact after an update. It should not happen after a restart.

The plugin should work out of the box on your setup, you're right. Can you please enable `verbose` and upload a screenshot if it crashes on you again here? This is weird and usually has something to do with how we interface with libclang.

> is there any way to disable easyclang without uninstalling it?

You can disable any plugin in sublime text, just type "disable" into the command pane. Also, there is `ignore_list` setting in ECC that you can use to not run ECC on specific folders or files. Hope that suits you.

**Comment by brupelo** [comment]
Hey @niosus , thanks for the fast response, sure thing... I realize now my previous report wasn't very helpful to you but I didn't know better at that time... so hopefully next time I'll be able to provide a better issue with more insightful info, from now on I'll have the verbose enabled but just to confirm... If I've understood correctly I should edit my .sublime-project with something like this:

```
{
    "settings": {
        "verbose": true
    },
    "folders":
    [
        {
            "path": "example0"
        },
        {
            "path": "example1"
        },
    ]
}
```
and restart SublimeText, right? At that point theorically the debug info I'll get will be more helpful to you to narrow it down...

Btw, I'll be reading the manual more carefully but fast question, in theory I should also get autocompletion from the folders added to my sublime-project, right? (in the above example would be `example0` and `example1` folders

> You can disable any plugin in sublime text, just type "disable" into the command pane. Also, there is ignore_list setting in ECC that you can use to not run ECC on specific folders or files. Hope that suits you.

Ah cool, yeah, I guess that will do it for me... I mean, ideally I'd have the plugin enabled all the time... but I guess with large projects the clang parsing will be quite cpu intensive and i wouldn't like it to slow me down when coding in another languages!=c++

**Comment by niosus** [comment]
@brupelo you need to prefix the ECC-related settings with `ecc_` if you are specifying them in the project-specific settings, so `verbose` would be `ecc_verbose`.

> I should also get autocompletion from the folders added to my sublime-project, right?

Generally no. The folders are just for sublime to manage the files and folders in the sidebar and internal index. ECC does not care about those. The project is just needed to get the proper settings to each view (file). ECC only cares about either CMake/Bazel or a place where you manually specify the flags, like the settings of the plugin or a file like `.clang_complete`. Please do read https://niosus.github.io/EasyClangComplete/configs/

> with large projects the clang parsing will be quite cpu intensive 

No it should not be in general as ECC does not build a full index of the project. It treats each file on its own. I use the plugin in my daily work and have been using it without issues in quite big projects, where compilation databases (single json file) were hundreds of megabytes.

> i wouldn't like it to slow me down when coding in another languages!=c++

This should not happen anyway. It should only trigger on c-family languages, which is decided by the syntax that sublime gives a file (shown in the bottom right corner)

**Comment by hliu1020** [comment]
Sorry for my later response. I think it happens often but not every time when editing code during ECC index rebuilding (when the moon icon appears after editing). 
Because I am developing Linux application at macos  so I have a Linux Ubuntu docker mapping the project directory to the container. Each time I build I will run "make" ("cmake" before that) in the Linux docker container. I don't know  whether the ECC crashing has something to do with my docker-building way. 
And I don't modify the default configuration of ECC much and the problem seems less happen when I build a macos-based cpp project. 
Sorry for my poor English and I'm expressing the problem as clearly as I can. Thanks for your patience @niosus , I think ECC is very convenient for me and hope the can help.

**Comment by niosus** [comment]
Oh, this is a complex setup. It might have something to do with which libclang library we get bound to, but this is a wild guess. I would need a reproducible example to understand this. Sorry that it is not the answer you were hoping for...
