### ISSUE TITLE
ECC dosent work when including hpp files.

### ISSUE THREAD

**Issue by Glymse** [niosus/EasyClangComplete#683]
Hi, so im trying to get ECC to work, and it kinda is,
but when i include header files with #include the program stops working, im using windows 10 with mingw and LLVM. (Im sorry if this is a configuration issue, but im relatively new to sublime)

**System**
Sublime: 3.2.2
OS: Windows 10
Clang: 9.0.0

**Examples:** 
Without header:
![image](https://user-images.githubusercontent.com/31343658/77452822-b12b2a80-6df6-11ea-9180-9b7a7cf3d326.png)

With header:
![image](https://user-images.githubusercontent.com/31343658/77452901-ca33db80-6df6-11ea-9706-41f832d952cd.png)

- - -

**Project settings:**
 ` {

    "settings": {
    "libclang_path": "C:\\Program Files\\LLVM\\lib",
    "ecc_verbose": true,
    "ecc_use_libclang": true ,
    "ecc_show_type_info": false,

    },

	"folders":
	[

        {
            "path": "src/..",
            "file_exclude_patterns": ["*.sublime-project", "*.o"],
            "follow_symlinks": true,
        }
	],
	"build_systems":
    [
        {
            "name": "Build Debug",
            "working_dir": "${project_path}",
            "cmd": "g++ -c src/*.cpp -std=c++14 -Wall -m64 -g -I include && g++ *.o -o bin/debug/main && start bin/debug/main",
            "selector": "source.c++",
            "shell": true
        },
        {
            "name": "Build Release",
            "working_dir": "${project_path}",
            "cmd": "g++ -c src/*.cpp -std=c++14 -m64 -O3 -I include && g++ *.o -o bin/release/main -s -mwindows && start/release/main",
            "selector": "source.c++",
            "shell": true
        },
        {
            "name": "Output Assebler Code",
            "working_dir": "${project_path}",
            "cmd": "g++ -S src/${file_base_name}.cpp -std=c++14 -m64 -g -I include -o asm/${file_base_name}.asm",
            "selector": "source.c++",
            "shell": true
        }

    ]

}`

- - - 
**ECC settings:**

![image](https://user-images.githubusercontent.com/31343658/77478862-fa8f7000-6e1e-11ea-992a-03f7e8457b62.png)

- - -
**Log:**
``
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[MainThread]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-5]: no settings for view 33. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: show_type_info             <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: use_libclang               <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Settings sucessfully read...
[ECC:INFO]:[clang_utils.py]:[get_clang_version_str]:[Dummy-5]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-5]: Populating common_flags with current variables.
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated '$project_path/include' to '['D:\\Programmering\\C++\\Sublime\\First\\include']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated '~/some_folder/*' to '['C:\\Users\\jonas\\some_folder\\*']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated '/some/absolute/file.ext' to '['\\some\\absolute\\file.ext']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated '$project_path/some/project/path/*' to '['D:\\Programmering\\C++\\Sublime\\First\\some\\project\\path\\*']'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-5]: settings initialized for view: 33
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-5]: on_activated_async view id 33
[ECC:DEBUG]:[view_config_manager.py]:[load_for_view]:[Thread-9]: Generate new config for path: 33
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-9]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-9]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Platform: Windows, ('32bit', 'WindowsPE')
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Python version: 3.3.6
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: User provided libclang_path: 'C:\Program Files\LLVM\liblibclang.lib'
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Searching for: 'libclang.dll'
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Generating search folder
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Libclang search output = 'C:\Program Files\LLVM\bin\clang'
[ECC:DEBUG]:[clang_utils.py]:[dir_from_output]:[Thread-9]: Real output: C:\Program Files\LLVM\bin\clang
[ECC:DEBUG]:[clang_utils.py]:[dir_from_output]:[Thread-9]: Architecture: ('32bit', 'WindowsPE')
[ECC:DEBUG]:[clang_utils.py]:[dir_from_output]:[Thread-9]: Folder to search: C:\Program Files\LLVM\bin\clang\..
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Checking path: C:\Program Files\LLVM\bin\libclang.dll
[ECC:INFO]:[clang_utils.py]:[find_libclang]:[Thread-9]: Found libclang library file: 'C:\Program Files\LLVM\bin\libclang.dll'
[ECC:ERROR]:[lib_complete.py]:[__init__]:[Thread-9]: error: [WinError 193] %1 er ikke et gyldigt Win32-program. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-9]: cannot initialize completer with libclang.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-9]: falling back to using clang in a subprocess.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-9]: init completer based on clang from cmd
[ECC:DEBUG]:[file.py]:[get_temp_dir]:[Thread-9]: Folder c:\users\jonas\appdata\local\temp\EasyClangComplete exists.
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-9]: Generating default flags from file 'ECC_temp_file.cpp' in folder 'c:\users\jonas\appdata\local\temp\EasyClangComplete'
[ECC:DEBUG]:[compiler_builtins.py]:[__generate_flags]:[Thread-9]: Generating new default flags with cmd: '['C:\\Program Files\\LLVM\\bin\\clang++', '-x', 'c++', '-std=c++17', '-c', 'ECC_temp_file.cpp', '-dM', '-v', '-E']'
[ECC:DEBUG]:[compiler_builtins.py]:[get_defines]:[Thread-9]: Got defines: ['-D_CPPRTTI=1', '-D_CPPUNWIND=1', '-D_HAS_CHAR16_T_LANGUAGE_SUPPORT=1', '-D_INTEGRAL_MAX_BITS=64', '-D_MSC_BUILD=1', '-D_MSC_EXTENSIONS=1', '-D_MSC_FULL_VER=191100000', '-D_MSC_VER=1911', '-D_MSVC_LANG=201703L', '-D_M_AMD64=100', '-D_M_X64=100', '-D_NATIVE_NULLPTR_SUPPORTED=1', '-D_NATIVE_WCHAR_T_DEFINED=1', '-D_RVALUE_REFERENCES_SUPPORTED=1', '-D_RVALUE_REFERENCES_V2_SUPPORTED=1', '-D_WCHAR_T_DEFINED=1', '-D_WIN32=1', '-D_WIN64=1', '-D__ATOMIC_ACQUIRE=2', '-D__ATOMIC_ACQ_REL=4', '-D__ATOMIC_CONSUME=1', '-D__ATOMIC_RELAXED=0', '-D__ATOMIC_RELEASE=3', '-D__ATOMIC_SEQ_CST=5', '-D__BIGGEST_ALIGNMENT__=16', '-D__BOOL_DEFINED=1', '-D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__', '-D__CHAR16_TYPE__=unsigned short', '-D__CHAR32_TYPE__=unsigned int', '-D__CHAR_BIT__=8', '-D__CLANG_ATOMIC_BOOL_LOCK_FREE=2', '-D__CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2', '-D__CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2', '-D__CLANG_ATOMIC_CHAR_LOCK_FREE=2', '-D__CLANG_ATOMIC_INT_LOCK_FREE=2', '-D__CLANG_ATOMIC_LLONG_LOCK_FREE=2', '-D__CLANG_ATOMIC_LONG_LOCK_FREE=2', '-D__CLANG_ATOMIC_POINTER_LOCK_FREE=2', '-D__CLANG_ATOMIC_SHORT_LOCK_FREE=2', '-D__CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2', '-D__CONSTANT_CFSTRINGS__=1', '-D__DBL_DECIMAL_DIG__=17', '-D__DBL_DENORM_MIN__=4.9406564584124654e-324', '-D__DBL_DIG__=15', '-D__DBL_EPSILON__=2.2204460492503131e-16', '-D__DBL_HAS_DENORM__=1', '-D__DBL_HAS_INFINITY__=1', '-D__DBL_HAS_QUIET_NAN__=1', '-D__DBL_MANT_DIG__=53', '-D__DBL_MAX_10_EXP__=308', '-D__DBL_MAX_EXP__=1024', '-D__DBL_MAX__=1.7976931348623157e+308', '-D__DBL_MIN_10_EXP__=(-307)', '-D__DBL_MIN_EXP__=(-1021)', '-D__DBL_MIN__=2.2250738585072014e-308', '-D__DECIMAL_DIG__=__LDBL_DECIMAL_DIG__', '-D__DEPRECATED=1', '-D__FINITE_MATH_ONLY__=0', '-D__FLT_DECIMAL_DIG__=9', '-D__FLT_DENORM_MIN__=1.40129846e-45F', '-D__FLT_DIG__=6', '-D__FLT_EPSILON__=1.19209290e-7F', '-D__FLT_EVAL_METHOD__=0', '-D__FLT_HAS_DENORM__=1', '-D__FLT_HAS_INFINITY__=1', '-D__FLT_HAS_QUIET_NAN__=1', '-D__FLT_MANT_DIG__=24', '-D__FLT_MAX_10_EXP__=38', '-D__FLT_MAX_EXP__=128', '-D__FLT_MAX__=3.40282347e+38F', '-D__FLT_MIN_10_EXP__=(-37)', '-D__FLT_MIN_EXP__=(-125)', '-D__FLT_MIN__=1.17549435e-38F', '-D__FLT_RADIX__=2', '-D__FXSR__=1', '-D__GCC_ASM_FLAG_OUTPUTS__=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1', '-D__INT16_C_SUFFIX__', '-D__INT16_FMTd__="hd"', '-D__INT16_FMTi__="hi"', '-D__INT16_MAX__=32767', '-D__INT16_TYPE__=short', '-D__INT32_C_SUFFIX__', '-D__INT32_FMTd__="d"', '-D__INT32_FMTi__="i"', '-D__INT32_MAX__=2147483647', '-D__INT32_TYPE__=int', '-D__INT64_C_SUFFIX__=LL', '-D__INT64_FMTd__="lld"', '-D__INT64_FMTi__="lli"', '-D__INT64_MAX__=9223372036854775807LL', '-D__INT64_TYPE__=long long int', '-D__INT8_C_SUFFIX__', '-D__INT8_FMTd__="hhd"', '-D__INT8_FMTi__="hhi"', '-D__INT8_MAX__=127', '-D__INT8_TYPE__=signed char', '-D__INTMAX_C_SUFFIX__=LL', '-D__INTMAX_FMTd__="lld"', '-D__INTMAX_FMTi__="lli"', '-D__INTMAX_MAX__=9223372036854775807LL', '-D__INTMAX_TYPE__=long long int', '-D__INTMAX_WIDTH__=64', '-D__INTPTR_FMTd__="lld"', '-D__INTPTR_FMTi__="lli"', '-D__INTPTR_MAX__=9223372036854775807LL', '-D__INTPTR_TYPE__=long long int', '-D__INTPTR_WIDTH__=64', '-D__INT_FAST16_FMTd__="hd"', '-D__INT_FAST16_FMTi__="hi"', '-D__INT_FAST16_MAX__=32767', '-D__INT_FAST16_TYPE__=short', '-D__INT_FAST32_FMTd__="d"', '-D__INT_FAST32_FMTi__="i"', '-D__INT_FAST32_MAX__=2147483647', '-D__INT_FAST32_TYPE__=int', '-D__INT_FAST64_FMTd__="lld"', '-D__INT_FAST64_FMTi__="lli"', '-D__INT_FAST64_MAX__=9223372036854775807LL', '-D__INT_FAST64_TYPE__=long long int', '-D__INT_FAST8_FMTd__="hhd"', '-D__INT_FAST8_FMTi__="hhi"', '-D__INT_FAST8_MAX__=127', '-D__INT_FAST8_TYPE__=signed char', '-D__INT_LEAST16_FMTd__="hd"', '-D__INT_LEAST16_FMTi__="hi"', '-D__INT_LEAST16_MAX__=32767', '-D__INT_LEAST16_TYPE__=short', '-D__INT_LEAST32_FMTd__="d"', '-D__INT_LEAST32_FMTi__="i"', '-D__INT_LEAST32_MAX__=2147483647', '-D__INT_LEAST32_TYPE__=int', '-D__INT_LEAST64_FMTd__="lld"', '-D__INT_LEAST64_FMTi__="lli"', '-D__INT_LEAST64_MAX__=9223372036854775807LL', '-D__INT_LEAST64_TYPE__=long long int', '-D__INT_LEAST8_FMTd__="hhd"', '-D__INT_LEAST8_FMTi__="hhi"', '-D__INT_LEAST8_MAX__=127', '-D__INT_LEAST8_TYPE__=signed char', '-D__INT_MAX__=2147483647', '-D__LDBL_DECIMAL_DIG__=17', '-D__LDBL_DENORM_MIN__=4.9406564584124654e-324L', '-D__LDBL_DIG__=15', '-D__LDBL_EPSILON__=2.2204460492503131e-16L', '-D__LDBL_HAS_DENORM__=1', '-D__LDBL_HAS_INFINITY__=1', '-D__LDBL_HAS_QUIET_NAN__=1', '-D__LDBL_MANT_DIG__=53', '-D__LDBL_MAX_10_EXP__=308', '-D__LDBL_MAX_EXP__=1024', '-D__LDBL_MAX__=1.7976931348623157e+308L', '-D__LDBL_MIN_10_EXP__=(-307)', '-D__LDBL_MIN_EXP__=(-1021)', '-D__LDBL_MIN__=2.2250738585072014e-308L', '-D__LITTLE_ENDIAN__=1', '-D__LONG_LONG_MAX__=9223372036854775807LL', '-D__LONG_MAX__=2147483647L', '-D__MMX__=1', '-D__NO_INLINE__=1', '-D__NO_MATH_INLINES=1', '-D__OBJC_BOOL_IS_BOOL=0', '-D__OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3', '-D__OPENCL_MEMORY_SCOPE_DEVICE=2', '-D__OPENCL_MEMORY_SCOPE_SUB_GROUP=4', '-D__OPENCL_MEMORY_SCOPE_WORK_GROUP=1', '-D__OPENCL_MEMORY_SCOPE_WORK_ITEM=0', '-D__ORDER_BIG_ENDIAN__=4321', '-D__ORDER_LITTLE_ENDIAN__=1234', '-D__ORDER_PDP_ENDIAN__=3412', '-D__PIC__=2', '-D__POINTER_WIDTH__=64', '-D__PRAGMA_REDEFINE_EXTNAME=1', '-D__PTRDIFF_FMTd__="lld"', '-D__PTRDIFF_FMTi__="lli"', '-D__PTRDIFF_MAX__=9223372036854775807LL', '-D__PTRDIFF_TYPE__=long long int', '-D__PTRDIFF_WIDTH__=64', '-D__REGISTER_PREFIX__', '-D__SCHAR_MAX__=127', '-D__SEG_FS=1', '-D__SEG_GS=1', '-D__SHRT_MAX__=32767', '-D__SIG_ATOMIC_MAX__=2147483647', '-D__SIG_ATOMIC_WIDTH__=32', '-D__SIZEOF_DOUBLE__=8', '-D__SIZEOF_FLOAT__=4', '-D__SIZEOF_INT128__=16', '-D__SIZEOF_INT__=4', '-D__SIZEOF_LONG_DOUBLE__=8', '-D__SIZEOF_LONG_LONG__=8', '-D__SIZEOF_LONG__=4', '-D__SIZEOF_POINTER__=8', '-D__SIZEOF_PTRDIFF_T__=8', '-D__SIZEOF_SHORT__=2', '-D__SIZEOF_SIZE_T__=8', '-D__SIZEOF_WCHAR_T__=2', '-D__SIZEOF_WINT_T__=2', '-D__SIZE_FMTX__="llX"', '-D__SIZE_FMTo__="llo"', '-D__SIZE_FMTu__="llu"', '-D__SIZE_FMTx__="llx"', '-D__SIZE_MAX__=18446744073709551615ULL', '-D__SIZE_TYPE__=long long unsigned int', '-D__SIZE_WIDTH__=64', '-D__SSE2_MATH__=1', '-D__SSE2__=1', '-D__SSE_MATH__=1', '-D__SSE__=1', '-D__STDCPP_DEFAULT_NEW_ALIGNMENT__=16ULL', '-D__STDC_HOSTED__=1', '-D__STDC_UTF_16__=1', '-D__STDC_UTF_32__=1', '-D__UINT16_C_SUFFIX__', '-D__UINT16_FMTX__="hX"', '-D__UINT16_FMTo__="ho"', '-D__UINT16_FMTu__="hu"', '-D__UINT16_FMTx__="hx"', '-D__UINT16_MAX__=65535', '-D__UINT16_TYPE__=unsigned short', '-D__UINT32_C_SUFFIX__=U', '-D__UINT32_FMTX__="X"', '-D__UINT32_FMTo__="o"', '-D__UINT32_FMTu__="u"', '-D__UINT32_FMTx__="x"', '-D__UINT32_MAX__=4294967295U', '-D__UINT32_TYPE__=unsigned int', '-D__UINT64_C_SUFFIX__=ULL', '-D__UINT64_FMTX__="llX"', '-D__UINT64_FMTo__="llo"', '-D__UINT64_FMTu__="llu"', '-D__UINT64_FMTx__="llx"', '-D__UINT64_MAX__=18446744073709551615ULL', '-D__UINT64_TYPE__=long long unsigned int', '-D__UINT8_C_SUFFIX__', '-D__UINT8_FMTX__="hhX"', '-D__UINT8_FMTo__="hho"', '-D__UINT8_FMTu__="hhu"', '-D__UINT8_FMTx__="hhx"', '-D__UINT8_MAX__=255', '-D__UINT8_TYPE__=unsigned char', '-D__UINTMAX_C_SUFFIX__=ULL', '-D__UINTMAX_FMTX__="llX"', '-D__UINTMAX_FMTo__="llo"', '-D__UINTMAX_FMTu__="llu"', '-D__UINTMAX_FMTx__="llx"', '-D__UINTMAX_MAX__=18446744073709551615ULL', '-D__UINTMAX_TYPE__=long long unsigned int', '-D__UINTMAX_WIDTH__=64', '-D__UINTPTR_FMTX__="llX"', '-D__UINTPTR_FMTo__="llo"', '-D__UINTPTR_FMTu__="llu"', '-D__UINTPTR_FMTx__="llx"', '-D__UINTPTR_MAX__=18446744073709551615ULL', '-D__UINTPTR_TYPE__=long long unsigned int', '-D__UINTPTR_WIDTH__=64', '-D__UINT_FAST16_FMTX__="hX"', '-D__UINT_FAST16_FMTo__="ho"', '-D__UINT_FAST16_FMTu__="hu"', '-D__UINT_FAST16_FMTx__="hx"', '-D__UINT_FAST16_MAX__=65535', '-D__UINT_FAST16_TYPE__=unsigned short', '-D__UINT_FAST32_FMTX__="X"', '-D__UINT_FAST32_FMTo__="o"', '-D__UINT_FAST32_FMTu__="u"', '-D__UINT_FAST32_FMTx__="x"', '-D__UINT_FAST32_MAX__=4294967295U', '-D__UINT_FAST32_TYPE__=unsigned int', '-D__UINT_FAST64_FMTX__="llX"', '-D__UINT_FAST64_FMTo__="llo"', '-D__UINT_FAST64_FMTu__="llu"', '-D__UINT_FAST64_FMTx__="llx"', '-D__UINT_FAST64_MAX__=18446744073709551615ULL', '-D__UINT_FAST64_TYPE__=long long unsigned int', '-D__UINT_FAST8_FMTX__="hhX"', '-D__UINT_FAST8_FMTo__="hho"', '-D__UINT_FAST8_FMTu__="hhu"', '-D__UINT_FAST8_FMTx__="hhx"', '-D__UINT_FAST8_MAX__=255', '-D__UINT_FAST8_TYPE__=unsigned char', '-D__UINT_LEAST16_FMTX__="hX"', '-D__UINT_LEAST16_FMTo__="ho"', '-D__UINT_LEAST16_FMTu__="hu"', '-D__UINT_LEAST16_FMTx__="hx"', '-D__UINT_LEAST16_MAX__=65535', '-D__UINT_LEAST16_TYPE__=unsigned short', '-D__UINT_LEAST32_FMTX__="X"', '-D__UINT_LEAST32_FMTo__="o"', '-D__UINT_LEAST32_FMTu__="u"', '-D__UINT_LEAST32_FMTx__="x"', '-D__UINT_LEAST32_MAX__=4294967295U', '-D__UINT_LEAST32_TYPE__=unsigned int', '-D__UINT_LEAST64_FMTX__="llX"', '-D__UINT_LEAST64_FMTo__="llo"', '-D__UINT_LEAST64_FMTu__="llu"', '-D__UINT_LEAST64_FMTx__="llx"', '-D__UINT_LEAST64_MAX__=18446744073709551615ULL', '-D__UINT_LEAST64_TYPE__=long long unsigned int', '-D__UINT_LEAST8_FMTX__="hhX"', '-D__UINT_LEAST8_FMTo__="hho"', '-D__UINT_LEAST8_FMTu__="hhu"', '-D__UINT_LEAST8_FMTx__="hhx"', '-D__UINT_LEAST8_MAX__=255', '-D__UINT_LEAST8_TYPE__=unsigned char', '-D__USER_LABEL_PREFIX__', '-D__VERSION__="Clang 9.0.0 (tags/RELEASE_900/final)"', '-D__WCHAR_MAX__=65535', '-D__WCHAR_TYPE__=unsigned short', '-D__WCHAR_UNSIGNED__=1', '-D__WCHAR_WIDTH__=16', '-D__WINT_MAX__=65535', '-D__WINT_TYPE__=unsigned short', '-D__WINT_UNSIGNED__=1', '-D__WINT_WIDTH__=16', '-D__amd64=1', '-D__amd64__=1', '-D__clang__=1', '-D__clang_major__=9', '-D__clang_minor__=0', '-D__clang_patchlevel__=0', '-D__clang_version__="9.0.0 (tags/RELEASE_900/final)"', '-D__code_model_small_=1', '-D__cplusplus=201703L', '-D__cpp_aggregate_bases=201603L', '-D__cpp_aggregate_nsdmi=201304L', '-D__cpp_alias_templates=200704L', '-D__cpp_aligned_new=201606L', '-D__cpp_attributes=200809L', '-D__cpp_binary_literals=201304L', '-D__cpp_capture_star_this=201603L', '-D__cpp_constexpr=201603L', '-D__cpp_decltype=200707L', '-D__cpp_decltype_auto=201304L', '-D__cpp_deduction_guides=201703L', '-D__cpp_delegating_constructors=200604L', '-D__cpp_digit_separators=201309L', '-D__cpp_enumerator_attributes=201411L', '-D__cpp_exceptions=199711L', '-D__cpp_fold_expressions=201603L', '-D__cpp_generic_lambdas=201304L', '-D__cpp_guaranteed_copy_elision=201606L', '-D__cpp_hex_float=201603L', '-D__cpp_if_constexpr=201606L', '-D__cpp_impl_destroying_delete=201806L', '-D__cpp_inheriting_constructors=201511L', '-D__cpp_init_captures=201304L', '-D__cpp_initializer_lists=200806L', '-D__cpp_inline_variables=201606L', '-D__cpp_lambdas=200907L', '-D__cpp_namespace_attributes=201411L', '-D__cpp_nested_namespace_definitions=201411L', '-D__cpp_noexcept_function_type=201510L', '-D__cpp_nontype_template_args=201411L', '-D__cpp_nontype_template_parameter_auto=201606L', '-D__cpp_nsdmi=200809L', '-D__cpp_range_based_for=201603L', '-D__cpp_raw_strings=200710L', '-D__cpp_ref_qualifiers=200710L', '-D__cpp_return_type_deduction=201304L', '-D__cpp_rtti=199711L', '-D__cpp_rvalue_references=200610L', '-D__cpp_static_assert=201411L', '-D__cpp_structured_bindings=201606L', '-D__cpp_template_auto=201606L', '-D__cpp_threadsafe_static_init=200806L', '-D__cpp_unicode_characters=200704L', '-D__cpp_unicode_literals=200710L', '-D__cpp_user_defined_literals=200809L', '-D__cpp_variable_templates=201304L', '-D__cpp_variadic_templates=200704L', '-D__cpp_variadic_using=201611L', '-D__k8=1', '-D__k8__=1', '-D__llvm__=1', '-D__pic__=2', '-D__seg_fs=__attribute__((address_space(257)))', '-D__seg_gs=__attribute__((address_space(256)))', '-D__tune_k8__=1', '-D__x86_64=1', '-D__x86_64__=1']
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-9]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-9]: Tokenizing: ['-x', 'c++', '-std=c++17', '-IC:\\Program Files\\LLVM\\lib\\clang\\9.0.0\\include']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Source
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-9]: [cmake]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-9]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-9]: Searching 'CMakeLists.txt' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-9]: No CMakeLists.txt file with 'project' in it found.
[ECC:DEBUG]:[file.py]:[search]:[Thread-9]: Searching 'compile_commands.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-9]: [CppProperties]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-9]: [CppProperties]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-9]: Searching 'CppProperties.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-9]: [c_cpp_properties]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-9]: [c_cpp_properties]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-9]: Searching 'c_cpp_properties.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-9]: [clang_complete_file]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-9]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-9]: Searching '.clang_complete' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Merge
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-9]: lang flags: [(-x c++), (-std=c++17), (-IC:\Program Files\LLVM\lib\clang\9.0.0\include)]
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Appending and filtering flags with ignore patterns: ['some_flag_pattern*', '-W_other_pattern_$project_path*']
[ECC:DEBUG]:[file.py]:[get_temp_dir]:[Thread-9]: Folder c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89 exists.
[ECC:DEBUG]:[bin_complete.py]:[run_clang_command]:[Thread-9]: clang command: 
'clang++' '-c' '-fsyntax-only' '-x' 'c++' '-std=c++17' '-I' 'C:\Program Files\LLVM\lib\clang\9.0.0\include' '-I' 'D:\Programmering\C++\Sublime\First\include' '-I' 'C:\Program Files\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++' '-I' 'C:\Program Files\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\backward' '-I' 'C:C:\Program Files\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\bits' 'c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89\main.cpp'
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-9]: Command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-9]: Command output: 
In file included from c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89\main.cpp:1:

C:\Program Files\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\iostream:38:10: fatal error: 'bits/c++config.h' file not found

#include <bits/c++config.h>

         ^~~~~~~~~~~~~~~~~~

1 error generated.

[ECC:DEBUG]:[bin_complete.py]:[update]:[Thread-9]: rebuilding done in 0.1386280059814453 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: Generating error regions for view 33
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-9]: Showing error regions: []
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-9]: Showing warning regions: []
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-9]: updated config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x042A08B0>
[ECC:DEBUG]:[view_config_manager.py]:[__remove_old_configs]:[Thread-4]: Skip young config: Age 3.153017044067383 < 1800. View: 33.

``

**Comment by niosus** [comment]
Please reformat the issue in the format requested in here: https://github.com/niosus/EasyClangComplete/blob/master/.github/ISSUE_TEMPLATE.md

When this is done - feel free to reopen. Issues are an important source of information for the users. This is why I really want to keep them formatted in a proper way.
