### ISSUE TITLE
How can I know which header files was absent in my project? 

### ISSUE THREAD

**Issue by abadcafe** [niosus/EasyClangComplete#686]
If some header files missing in ".clang_complete", the plugin maybe give wrong completions.

How can I know which header files was absent in my project without cmake or something similar? Because my project just has a simple Makefile.

Are there some shortcuts or commands can help? thanks.

**Comment by niosus** [comment]
Not that I know of. Basically, if you use files like `.clang_complete` you are basically saying that you know what you're doing and know the exact configuration of your project. If you don't want to care, I would say that using CMake or Bazel would be preferable as they both allow to generate a compilation database that can be used by the plugin. I will close this, as this is slightly tangential to the functionality of the plugin.
