### ISSUE TITLE
Compatibility with clang-cl

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#69]
> clang-cl is an alternative command-line interface to Clang driver, designed for compatibility with the Visual C++ compiler, cl.exe.
http://clang.llvm.org/docs/UsersManual.html#clang-cl

There is a couple of problems that prevent it from working. I'll add references below.

**Comment by niosus** [comment]
Are you sure using `clang-cl` is needed? I think I read somewhere that `clang` is smart enough to pick it my itself? Am I wrong?

**Comment by rchl** [comment]
> : clang c:\test.cc /O2
> clang.exe: error: no such file or directory: '/O2'

It works with clang-cl.
So given that command line interfaces are not compatible, I don't see how it could just work automatically.

Besides, I work with chromium where `clang-cl` binary is downloaded automatically but there is no `clang.exe`.

**Comment by niosus** [comment]
At this point, it seems that you have implemented all parts of this issue, so I will close this one too.

Thanks a lot for the contributions :+1:
