### ISSUE TITLE
Getting function pointer arguments

### ISSUE THREAD

**Issue by septag** [niosus/EasyClangComplete#698]
- Sublime Text version: 3.2.2 (3211)
- Which system are you on: windows 
- Clang version: clang-cl 10.0.0 (modified compile_commands.json)

Hi,

First of all, thanks for your great plugin.
I was wondering, if it's possible to have intellisense for function pointers ? 
I have a lot of functions that reside inside structs as function pointers (interface structs)

```c
typedef struct my_api {
    void (*foo)(int arg);
};

my_api api;
api.foo(1);
```

but code complete only suggest the name and not the actual arguments.

**Comment by niosus** [comment]
I believe there is nothing on my side I can do. I will check if I'm not clearing any output of libclang, but if it does not provide this, I will not be able to add this, sorry.

**Comment by septag** [comment]
alright. thanks
