### ISSUE TITLE
Wrong default autocomplete item

### ISSUE THREAD

**Issue by dzpt** [niosus/EasyClangComplete#699]
The autocompletion popup doesn't start from beginning item
<img width="415" alt="Screen Shot 2020-04-30 at 20 58 15" src="https://user-images.githubusercontent.com/5781080/80719568-de6da580-8b25-11ea-80d9-6c5859870e8a.png">

It's supposed to be like this.
<img width="409" alt="Screen Shot 2020-04-30 at 21 03 01" src="https://user-images.githubusercontent.com/5781080/80719690-0957f980-8b26-11ea-8350-b383191cc17d.png">

On Mac, all in latest version

**Comment by niosus** [comment]
Hey @dzpt if you are referring to the order of the currently highlighted entry, there is little I can do on my side, sublime does its magic there on its own as far as I know. You could try to disable the default completions leaving only ECC ones if those are available in the settings of the plugin.
I will close this issue as it seems like it's not on my side.
