### ISSUE TITLE
ignore_list argument does not work

### ISSUE THREAD

**Issue by gavriil07** [niosus/EasyClangComplete#701]
# System info: #
- Sublime Text version: `3211`
- Which system are you on: `Ubuntu 20.04`
- Clang version: `10.0.0-4ubuntu1`

# What happens:  #
ignore_list argument does not seem to have any effect.

<details>
<summary>Details</summary>
  

![Tooltip_001](https://user-images.githubusercontent.com/28069262/80869044-c1acab80-8ca6-11ea-9275-fd6a46de7460.png)

![Selection_002](https://user-images.githubusercontent.com/28069262/80869057-d5581200-8ca6-11ea-9c7b-fa217f858873.png)

</details>

**Comment by niosus** [comment]
I'm sorry if this was not clear in the documentation. It has unfortunately nothing to do with the issues you are experiencing.  Your errors come from the fact that the file you have opened has includes that don't exist and it is a compilation error as it should be. The setting you are referring to is there to not trigger the plugin if you open a file that matches the pattern. In this case, ECC will not try to do anything for any file in `/usr/*`. I will close this issue for now as there seems to be nothing on my side to do about it, but feel free to reopen if you disagree.
