### ISSUE TITLE
The requested operation cannot be performed on a file with a user-mapped section open.

### ISSUE THREAD

**Issue by KirillGrigoriev** [niosus/EasyClangComplete#708]
# System info: #
- Sublime Text version: `3.2.2 Build 3211`
- Which system are you on: `Microsoft Windows 10 `
- Clang version: `10.0.0`

# What happens:  #
Can't save a file, drops error message: "The requested operation cannot be performed on a file with a user-mapped section open.". After Sublime restart I able to save unsaved file, but after source and header change and save, sometimes problem happen again, I'm not sure how reproduce problem at 100%. Seems like only header (.h) files used in parsed sources affected. I save files with "Save All" bind, source and header may be saved at the same time. I think, It can be important, because ECC parse files at save.

# Log: #
https://gist.github.com/KirillGrigoriev/32b18456761130441b7ac579a353f1f5

**Comment by niosus** [comment]
I've seen this happen before on Windows and it means that the file is being used by different processes. Maybe the file is still in use by libclang and when you try to save it you encounter a lock. I am not really sure I can do anything about this on my side. At least for now I have no good idea what to do about it. Sorry about that.
