### ISSUE TITLE
How to run this plugin?

### ISSUE THREAD

**Issue by Firanolfind** [niosus/EasyClangComplete#709]
Hi,
I went through _Simple start in just 3 steps!_ for **Easy**ClangComplete, gone through half of a links in docs, and I still didn't get how it works. I got CMakeLists.txt and ".sublime-project". Should I configure sublime-project file? Are there any example of .sublime-project setup?
Docs are not straightforward on this, imo.

Thank you!

**Comment by AdityaGupta150** [comment]
For me, it was (on Linux)
1. Install clang
2. Clone this repo (or download the zip, and extract it to 'EasyClangComplete')
3. Move/Copy the EasyClangComplete directory to ~/.config/sublime-text-3/Packages

**Comment by niosus** [comment]
@Firanolfind you should set up absolutely nothing if you have a `CMakeLists.txt` file. The plugin should be working out of the box. If it does not, please open a different issue with the logs of what is happening. Sorry about this experience. 

I will close this issue, but feel free to open a new one if something is still not working.

**Comment by Firanolfind** [comment]
Hi @niosus , I have no idea how but it suddenly started working! I am sorry for this issue, I was really frustrated at the beginning.
Thank you for this tool!

**Comment by niosus** [comment]
Great that it works for you!
