### ISSUE TITLE
[clang-cl] "-x c++" argument not supported

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#71]
This plugin forces flag `-x c++` when executing clang binary. This is not supported by clang-cl and throws error.

Blocks #69

**Comment by niosus** [comment]
Hmm, this one is slightly harder. This flag is only needed when we are using c++ so the way it is hardcoded now is bad anyways. Probably we will only need to add this flag if the file is a c++ file (then again, how to decide if .h file is c++ or just plain c) and only if we are not using clang-cl. Do you maybe have thoughts on this?

**Comment by rchl** [comment]
init_flags could be a map that has 'clang++' and 'clang-cl' keys that map to different default flags.
The key to use could be deciphered from the path to the clang binary like so: `os.path.splitext(os.path.basename(binary_path))[0]`

Maybe it would also be worth adding error handling so that, by default, if key is not known, we would use 'clang++' by default.

**Comment by rchl** [comment]
cpplint (google's linter for C/C++ code) just has a simple regex check:
```
_SEARCH_C_FILE = re.compile(r'\b(?:LINT_C_FILE|'
                            r'vim?:\s*.*(\s*|:)filetype=c(\s*|:|$))')
```
Not very robust.
Files I use have such header which I think is fairly standard too:
`// -*- Mode: c++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-`
So we could use those hints at least, but otherwise it would probably be non-trivial to guess language. Unless clang has some way to do it itself.

**Comment by niosus** [comment]
I'm pretty sure I read somewhere that clang considers everything c unless told otherwise. I will try to find exact reference tomorrow.

**Comment by rchl** [comment]
I've created a pull request with suggested solution. It doesn't handle part about detecting c/c++ code but that is IMO a separate issue anyway.

We can discuss design, style and the overall solution. You said you'd rather not have another abstraction but I felt it's the best way to handle that problem.

**Comment by niosus** [comment]
Great! Thank you so much! I will look at it and merge it soon.

**Comment by niosus** [comment]
I have merged the pull request as it looks all good to me. I will test the things a bit before pushing them to package control. I am closing this issue for now. Will reopen if anything doesn't work as expected.
