### ISSUE TITLE
ECC:Info Box extends beyond screen

### ISSUE THREAD

**Issue by adi-g15** [niosus/EasyClangComplete#710]
--------------------------------------------------------------
# System info: #
- Sublime Text version: `Build 3211`
- Which system are you on: `Linux Mint 19.3 Cinnamon`
- Clang version: `6.0.0-1ubuntu2`

# What happens:  #
When hovering over some STL container use in code, in some cases, the ECC:Info Box content is not readable, due to the box extending beyond.
To Reproduce Problem - Hover over `std::find(...)`, or the `.begin()` iterators [Additionally, ECC:Info box is very useful, and in most cases like custom functions, and `std::vector` work fine]

Attaching a picture of screen (since, when PrtScr button is clicked, the box hides, no problem though)
![IMG_20200524_172150_LL](https://user-images.githubusercontent.com/37269665/82835178-c8e46500-9eb2-11ea-91b0-33bdccb7da0b.jpg)

**Additionally**, the screen resolution i am using is 1366x768 (16:9) . Thanks

**Comment by niosus** [comment]
Yep, this is unfortunately expected and there is not much I can do about this. I'd say this is something that has to be fixed on the side of the library I use for popups: https://github.com/facelessuser/sublime-markdown-popups
