### ISSUE TITLE
Handle links to remote folders in pop-ups

### ISSUE THREAD

**Issue by imran27** [niosus/EasyClangComplete#715]
I am using this plugin just for getting completion & hover documentation and to open them up by clicking the link in the hover popup.

In case of network location, \\\abc123\... it opens into a:bc123\\...

Unfortunately I cannot post screenshots

Info:
Sublime Text 3.2.2, Build 3211
Current version this plugin as of this comment + clang + cmake locally in path.
Remote folders where code is stored have their own local versions of build tools on the server

**Comment by niosus** [comment]
I am happy to accept a PR for this, but this is very far from my current usecase so I probably won't have the time to work on this.
