### ISSUE TITLE
Console is intrusive

### ISSUE THREAD

**Issue by gavriil07** [niosus/EasyClangComplete#720]
Sublime 3.2.2, Windows 10

On every single focus inside a file editor this console appears, how can I turn it off?

![fsa](https://user-images.githubusercontent.com/28069262/97803799-68710500-1c54-11eb-96e5-fe68bf87b9ba.PNG)

**Comment by niosus** [comment]
This means that this part of your build fails. I've been thinking about this feature for some time and decided to make the console pop up in this case. If the build fails it means ECC will not work as expected. I don't really like the idea of making it less intrusive as it will then just show random errors in this case, which, to me, is even more confusing. What do you think would be a good behavior here?

**Comment by fake-name** [comment]
I'm getting this continuously as well.

In my case, I'm working on a source tree that depends on packages that are not present on the machine running sublime, so there's no way for me to make the build *not* fail. 

There really needs to be some way to say "Yes, I know this won't fully build on this machine, don't tell me".
