### ISSUE TITLE
Show all links from sublime index in popup

### ISSUE THREAD

**Issue by asheeshr** [niosus/EasyClangComplete#721]
# System info: #
- Sublime Text version: `3211`
- Which system are you on: `Ubuntu 16`
- Clang version: `3.8`

# What happens:  #
ECC has a setting to override the default popup. I can currently trigger the ECC popup via keypress (I already have this through a keybinding for `ecc_show_popup_info`).  I would also like to be able to access the default popup with the full list of definitions/references on hover (and not the ECC popup) as the list in the ECC popup is usually incomplete. Is there a way to accomplish that?

Setting `show_type_info` to false seems to disable the ECC popup altogether.

**Comment by niosus** [comment]
Hey @asheeshr 

This is currently not possible. When you say that the ECC one is incomplete, what are you missing? I made sure I show all the information that comes from clang _and_ the one that comes from the sublime index.

If you feel that things are still missing, I am happy to review a PR on this, but I probably won't have the time to implement this.

**Comment by asheeshr** [comment]
The ECC popup only seems to have the first few references for a particular symbol whereas the Sublime popup shows the full list of references. For example, for a function, I only get the reference to the definition in the ECC popup whereas the sublime popup shows references to all the calls to that function as well. This is useful to have to look for other uses of a particular function call when working with medium to large codebases as one example.

**Comment by niosus** [comment]
Hmm. What I do is I load all the additional suggestions from sublime index. So the information should be identical. Maybe I'm not loading all of it. I will have a look.
