### ISSUE TITLE
[clang-cl] Errors in view not highlighted due to different error formatting

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#73]
For compatibility with cl.exe, it returns errors in this format:
  `c:\temp\EasyClangComplete\base64.cc(14,3):  error: use of undeclared identifier 'Xstd'`
rather than:
  `/temp/EasyClangComplete\base64.cc:14:3:  error: use of undeclared identifier 'Xstd'`

So the regexes in error_vis.py don't match.

We should discuss how to handle that cleanly. Also having in mind #71.

It would be best if all "clang variation" specific behavior would be encapsulated in its own class.

Blocks #69

**Comment by niosus** [comment]
Yes, definitely. Let's discuss it a bit in issue #69 if we actually need to use `clang-cl`. Otherwise this is a valid point and I will look into it.

**Comment by rchl** [comment]
Another option is to force clang-compatible diagnostics with http://clang.llvm.org/docs/UsersManual.html#cmdoption-fdiagnostics-format

**Comment by niosus** [comment]
This sounds much better than introducing another level of abstraction

**Comment by rchl** [comment]
To be frank, clang-cl doesn't support that command actually. :/
I haven't checked that until now.

**Comment by rchl** [comment]
The regexp could just be extended to cater for both syntaxes I guess. The differences are probably only in line/column information:

```
% clang test.cpp
test.cpp:3:7: error: expected expression
  i+++;
      ^
1 error generated.
% clang-cl test.cpp
test.cpp(3,7) :  error: expected expression
  i+++;
      ^
```
