### ISSUE TITLE
How can configure in MinGW32？

### ISSUE THREAD

**Issue by WaZC-Git** [niosus/EasyClangComplete#738]
How can I configure with mingw32 them，
(Sorry, I can't discern the document)
Thank you

**Comment by niosus** [comment]
Sorry, please take time to format the issue well, stating what you tried and what you did not. I am a single person who is not getting payed to do this. Please show _some_ respect to this work in the form of at least spending the time to ask the question well. There is an issue template for a reason. I will close this issue, but please feel free to open a new one with more information.
