### ISSUE TITLE
Proper way to pass cmake flags to use ninja?

### ISSUE THREAD

**Issue by esteimle** [niosus/EasyClangComplete#740]
I was trying to get EasyClangComplete to work with my android ndk project (cross compiled on windows).  My first step was I need to pass the -G Ninja parameter to cmake but I don't think I have it right.  This is what I did in my .sublime-project file below. It does not seem to be picking up the option though as it throws a bunch of popups and then shows me a window at the bottom of Sublime with the same cmake output I get if I don't specify the -G option.  What did I miss?

```
{
	"folders":
	[
		{
			"path": "."
		}
	],

	"ecc_flags_sources":
	[
	    {
	        "file": "CMakeLists.txt",
	        "flags":
	        [
	            "-G Ninja .."
	        ]
	    }
	],

	"settings":
    {
       "easy_clang_complete_verbose": true, 
       "ecc_use_libclang": true,
       "ecc_libclang_path": "C:\\Users\\myusername\\AppData\\Local\\Android\\sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android28-clang++.cmd",
    }
```

**Comment by niosus** [comment]
@esteimle what you are doing looks correct. Please try to close the file, call `ECC: Clean CMake cache` command and try again. Otherwise, please provide the things I ask for in the template to a new issue here. Without seeing an error and the log from the plugin there is little I can do.
