### ISSUE TITLE
relative paths not loading correctly from .clang_complete after update to v. 1.3.0

### ISSUE THREAD

**Issue by kpskp77** [niosus/EasyClangComplete#75]
In previous version 1.2.5, every thing works fine. I'm using clang 3.8.1 on windows 10, and setting the include dirs via file .clang_complete. However, it's not working when the plugin upgrades to version 1.3.0 (user-provided headers can't be found, std headers still can be found). I restart sublime text many times, it doesn't help. I notice that new version bring cmake support. I'm not using cmake right now, but cmake binary does reside in my PATH environment. Do I need modifications to my user settings file?

**Comment by niosus** [comment]
Sorry for the inconvenience @kpskp77 

Can you please set the setting: `"verbose": true` in the plugin settings and copy the sublime text console output here? 

Just set this setting, close sublime text, open it again, open some simple c++ file and try to complete something. Then copy all the output here please. Thanks a lot!

Knowing it I will be able to see what causes the bug. Again, sorry for the inconvenience. It is always hard to be sure that a big upgrade goes smoothly.

**Comment by niosus** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SprSHGhZ&#x2F;583-make-sure-to-track-issue"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Make sure to track issue</a>

**Comment by kpskp77** [comment]
>DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang command: 
clang++ -c -fsyntax-only -x c++ -fdiagnostics-format=clang -std=c++14 c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp -I "C:\usr\include" -I "D:\sublime-text-project\demo\src" -I "C:\workspace\demo_c++\src" -I "D:\sublime-text-project\demo\src" -I "D:\sublime-text-project\demo" -I "D:\sublime-text-project\demo\.clang_complete\include"
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process finished with code: 1
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process output: 
c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp:6:10: fatal error: 'my_type_traits.h' file not found
>
#include "my_type_traits.h"
                ^
1 error generated.
>
>
DEBUG:EasyClangComplete.plugin.completion.bin_complete: rebuilding done in 0.2968888282775879 seconds
DEBUG:EasyClangComplete.plugin.error_vis: generating error regions for view 28
DEBUG:EasyClangComplete.plugin.error_vis: removing old error regions
DEBUG:root: adding error {'row': '6', 'file': 'c:\\users\\carousel\\appdata\\local\\temp\\EasyClangComplete\\main.cpp', 'col': '10', 'error': "'my_type_traits.h' file not found"}
DEBUG:EasyClangComplete.plugin.error_vis: 1 error regions ready
DEBUG:EasyClangComplete.plugin.error_vis: showing error regions: [(90, 92)]

I'm not sure if I have copied the right message.

**Comment by niosus** [comment]
But you do see the highlighted error in your code, right? Because it cannot find the file `my_type_traits.h`. Where is this file situated?

**Comment by kpskp77** [comment]
Yeah, I see the highlighted error.  The `my_type_traits.h` is in the dir `./include`, and I put it in the .clang_complete file as `-I./include`. And both dir `include` and file .clang_complete are in the root of project path

**Comment by niosus** [comment]
Ok, then I need a bigger log. Please:
- Close sublime text
- open sublime text
- open cpp file
- write something there with a place you expect it to complete
- copy the FULL log from the sublime text console here (from the start)

I need to see how things are initialized.
Thanks!

**Comment by niosus** [comment]
ah, wait. This line looks wrong:
>  -I "D:\sublime-text-project\demo.clang_complete\include"

Can you change your .clang_complete line `-I./include` to `-Iinclude`?

**Comment by kpskp77** [comment]
>DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 5
Package Control: Skipping automatic upgrade, last run at 2016-08-31 18:09:14, next run at 2016-08-31 19:09:14 or after
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.base_complete: flags handler not initialized. Do it.
DEBUG:EasyClangComplete.EasyClangComplete:init completer for view id: 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.flags_manager: expanded CMAKE_PREFIX_PATHs: ['C:\\Users\\Carousel/relative/path', '/absolute/path']
DEBUG:EasyClangComplete.plugin.plugin_settings: populating include dirs with current variables:
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_name = demo_c++
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_folder = D:\sublime-text-project\demo
DEBUG:EasyClangComplete.plugin.plugin_settings: file_parent_folder = D:\sublime-text-project\demo
DEBUG:EasyClangComplete.plugin.plugin_settings: include_dirs = ['C:\\usr\\include', 'D:\\sublime-text-project\\demo\\src', 'C:\\workspace\\demo_c++\\src', 'D:\\sublime-text-project\\demo\\src', 'D:\\sublime-text-project\\demo']
DEBUG:EasyClangComplete.plugin.completion.bin_complete: flags_manager loaded
DEBUG:EasyClangComplete.plugin.completion.flags_manager: cmake file not loaded yet. Searching for one...
DEBUG:EasyClangComplete.plugin.tools: searching 'CMakeLists.txt' from 'D:\sublime-text-project\demo\src' to 'D:\sublime-text-project\demo'
DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete not loaded. Searching for one...
DEBUG:EasyClangComplete.plugin.tools: searching '.clang_complete' from 'D:\sublime-text-project\demo\src' to 'D:\sublime-text-project\demo'
DEBUG:EasyClangComplete.plugin.tools: found '.clang_complete' file: D:\sublime-text-project\demo\.clang_complete
DEBUG:EasyClangComplete.plugin.tools: last mod: 0, actual mod: 1472639746.0107934
DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete modified. Load new flags.
DEBUG:EasyClangComplete.plugin.completion.flags_manager: all lines: ['-Iinclude']
DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete contains flags: {'-I "D:\\sublime-text-project\\demo\\.clang_complete\\include"'}
DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang flags are: ['-I "C:\\usr\\include"', '-I "D:\\sublime-text-project\\demo\\src"', '-I "C:\\workspace\\demo_c++\\src"', '-I "D:\\sublime-text-project\\demo\\src"', '-I "D:\\sublime-text-project\\demo"', '-I "D:\\sublime-text-project\\demo\\.clang_complete\\include"']
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: no completions needed
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: wrong trigger 't:'.
DEBUG:EasyClangComplete.plugin.tools: wrong trigger fired
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: matched trigger '::'.
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 299
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang command: 
clang++ -c -fsyntax-only -x c++ -fdiagnostics-format=clang -std=c++14 -Xclang -code-completion-at=c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp:17:19 c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp -I "C:\usr\include" -I "D:\sublime-text-project\demo\src" -I "C:\workspace\demo_c++\src" -I "D:\sublime-text-project\demo\src" -I "D:\sublime-text-project\demo" -I "D:\sublime-text-project\demo\\.clang_complete\include"
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process finished with code: 1
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process output: 
c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp:6:10: fatal error: 'my_type_traits.h' file not found
>
#include "my_type_traits.h"
                ^
>
1 error generated.


Still the same for that line after I changed to `-Iinclude`

**Comment by niosus** [comment]
Ok, I see the error. It's here:
> DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete contains flags: {'-I "D:\sublime-text-project\demo\.clang_complete\include"'}

I will try to fix it later today. It shoudn't take too much time. Hopefully I will release a fix till tomorrow. Thanks for the info!

**Comment by kpskp77** [comment]
It seems markdown escape reduce the number of the backslashes, the actual original message is
>DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete contains flags: {'-I "D:\\\\sublime-text-project\\\\demo\\\\.clang_complete\\\\include"'}

Hope it doesn't make big difference to your diagnostic.

**Comment by niosus** [comment]
Can you include it as code then? Just to be sure.

**Comment by kpskp77** [comment]
Yes, my compiler works fine.

**Comment by niosus** [comment]
No, sorry, I was not clear enough. I meant here in the messages include it as code and not as citation. 

Like this: 
``` 
Your log goes here 
```

It guarantees the formatting stays intact.

**Comment by kpskp77** [comment]
Sorry, my bad...
```
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 5
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.base_complete: flags handler not initialized. Do it.
DEBUG:EasyClangComplete.EasyClangComplete:init completer for view id: 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.flags_manager: expanded CMAKE_PREFIX_PATHs: ['C:\\Users\\Carousel/relative/path', '/absolute/path']
DEBUG:EasyClangComplete.plugin.plugin_settings: populating include dirs with current variables:
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_name = demo_c++
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_folder = D:\sublime-text-project\demo
DEBUG:EasyClangComplete.plugin.plugin_settings: file_parent_folder = D:\sublime-text-project\demo
DEBUG:EasyClangComplete.plugin.plugin_settings: include_dirs = ['C:\\usr\\include', 'D:\\sublime-text-project\\demo\\src', 'C:\\workspace\\demo_c++\\src', 'D:\\sublime-text-project\\demo\\src', 'D:\\sublime-text-project\\demo']
DEBUG:EasyClangComplete.plugin.completion.bin_complete: flags_manager loaded
DEBUG:EasyClangComplete.plugin.completion.flags_manager: cmake file not loaded yet. Searching for one...
DEBUG:EasyClangComplete.plugin.tools: searching 'CMakeLists.txt' from 'D:\sublime-text-project\demo\src' to 'D:\sublime-text-project\demo'
DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete not loaded. Searching for one...
DEBUG:EasyClangComplete.plugin.tools: searching '.clang_complete' from 'D:\sublime-text-project\demo\src' to 'D:\sublime-text-project\demo'
DEBUG:EasyClangComplete.plugin.tools: found '.clang_complete' file: D:\sublime-text-project\demo\.clang_complete
DEBUG:EasyClangComplete.plugin.tools: last mod: 0, actual mod: 1472639746.0107934
DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete modified. Load new flags.
DEBUG:EasyClangComplete.plugin.completion.flags_manager: all lines: ['-Iinclude']
DEBUG:EasyClangComplete.plugin.completion.flags_manager: .clang_complete contains flags: {'-I "D:\\sublime-text-project\\demo\\.clang_complete\\include"'}
DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang flags are: ['-I "C:\\usr\\include"', '-I "D:\\sublime-text-project\\demo\\src"', '-I "C:\\workspace\\demo_c++\\src"', '-I "D:\\sublime-text-project\\demo\\src"', '-I "D:\\sublime-text-project\\demo"', '-I "D:\\sublime-text-project\\demo\\.clang_complete\\include"']
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: no completions needed
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: wrong trigger 't:'.
DEBUG:EasyClangComplete.plugin.tools: wrong trigger fired
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 28
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: matched trigger '::'.
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 296
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang command: 
clang++ -c -fsyntax-only -x c++ -fdiagnostics-format=clang -std=c++14 -Xclang -code-completion-at=c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp:17:19 c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp -I "C:\usr\include" -I "D:\sublime-text-project\demo\src" -I "C:\workspace\demo_c++\src" -I "D:\sublime-text-project\demo\src" -I "D:\sublime-text-project\demo" -I "D:\sublime-text-project\demo\.clang_complete\include"
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process finished with code: 1
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process output: 
c:\users\carousel\appdata\local\temp\EasyClangComplete\main.cpp:6:10: fatal error: 'my_type_traits.h' file not found

#include "my_type_traits.h"

         ^

1 error generated.
```

**Comment by niosus** [comment]
No problem. :)

I've looked through the code during lunch from my phone. I'm pretty sure I see where the big is. Thanks for reporting. Will fix it as soon as I get back to my machine.

**Comment by niosus** [comment]
The change should be live in version 1.3.1. It should be up soon.

**Comment by kpskp77** [comment]
It works now. The plugin is amazing, great job!

**Comment by niosus** [comment]
I'm really happy to hear it! :)
