### ISSUE TITLE
Files with same name share error messages

### ISSUE THREAD

**Issue by ellipticaldoor** [niosus/EasyClangComplete#755]
Basically if you have a file called `foo.hpp` in `src/foo.hpp` and other one in `src/test/foo.hpp` then, if for example `src/test/foo.hpp`has an error message then this one will appear also in `src/foo.hpp`

**Comment by niosus** [comment]
@ellipticaldoor oh wow, thanks for reporting this. This is extremely weird. I mean I constantly test on tiles like `test.cpp` which are all over the place and have never observed the behavior. I would still ask you to update the description respecting the issue template. I will close the issue for now as it does not contain enough information for me to go on but please reopen it once you have updated the issue following the template, the most important part being the log.

**Comment by ellipticaldoor** [comment]
I reinstalled and I stopped having the error. Maybe it was something with a cache somewhere... but it seems like it stopped.

If I manage to reproduce this again I will post it
