### ISSUE TITLE
Headers are not auto-completed in Sublime Text 4

### ISSUE THREAD

**Issue by dannftk** [niosus/EasyClangComplete#756]
# System info: #
- Sublime Text version: 4113
- Which system are you on: gentoo linux, 5.10.52, x86_64
- Clang version: 12.0.0

# What happens:
It seems nothing happens when I like to complete headers using `autocomplete_include` feature. When it is set in `true` and I start typing `#include "` EasyClangComplete suggests nothing, and just gives the output:

```
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-10]: config exists for view: 61
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-10]: config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x7f498c033410>
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-10]: config exists for view: 61
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-10]: config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x7f498c033410>
```

Does the plugin support ST4 comprehensively? In case it does what might be wrong with my settings that prevents the plugin from offering me headers?

**Comment by niosus** [comment]
Hey @dannftk sorry for the delay. As you closed the issue, I understand that it has fixed itself? :wink:

**Comment by dannftk** [comment]
Hi. Yes, it has. Thank you
