### ISSUE TITLE
Using defintions declared on the CMakeLists.txt from windows gives "Error: Expected expression"

### ISSUE THREAD

**Issue by ellipticaldoor** [niosus/EasyClangComplete#759]
So on latest windows if you define something in your `CMakeLists.txt` like this

``` cmake
add_compile_definitions(
  ENVIRONMENT="development"
)
```

And then in a source file you try to use this variable like this

``` c++
if (ENVIRONMENT == "development") {
  ...
}
```

Then you will get the error `Error: Expected expression`

This error only appears on EasyClangComplete, the file compiles just fine. Also this error doesn't appears on mac, with the same code.

**Comment by niosus** [comment]
@ellipticaldoor please follow the template when creating the issue. Here I don't have enough information to understand what is going on. Please reopen with the required information.

**Comment by ellipticaldoor** [comment]
Sorry for filling the template. In the end I managed to get the error rid by doing this:

```
#ifndef STRINGIFY
#define STRING_CV(X) #X
#define STRINGIFY(X) STRING_CV(X)
#endif

if (STRINGIFY(ENVIRONMENT) == "development")
  ...
}

```
