### ISSUE TITLE
Trigger completion with keyboard shortcut

### ISSUE THREAD

**Issue by kkaefer** [niosus/EasyClangComplete#77]
Is there a way to manually trigger a completion with a keyboard shortcut, rather than having to type one of the completion characters?

**Comment by niosus** [comment]
This relates to #62 
Unfortunately clang completions are intended to be used with a trigger. For now I don't think there is a quick way to overcome this, but I will focus on this as soon as there is more time and more crucial bugs are fixed. Also, feel free to implement it and open a pull request :smile: 

For more info on the issue: Check out [this StackOverflow answer](http://stackoverflow.com/questions/15875800/why-isnt-libclang-returning-meaningful-completion-results/15878799#15878799)
