### ISSUE TITLE
precompiled headers?

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#79]
Guys, I've been thinking of it for quite a while. Currently, there are two ways of using the plugin:
- libclang
- parsing output from clang binary

`libclang` should be faster as it internally manages all the work with precompiled headers. The problem with it is that it does not reliably work for Windows or latest osx (at least we haven't solved this yet #4 #47 ). 

So I thought of actually doing the same by emitting the precompiled headers on the first build of the file and then using these to speed up completion based on parsing the output from the clang binary. I feel there is going to be some problems on the way and we need to have a nice way to manage (and remove) the precompiled headers, but generally it seems beneficial for the whole system. 

What do you think guys?

**Comment by rchl** [comment]
At least the Windows libclang problem might be fixed soon. I think I've figured out what is the problem. See https://forum.sublimetext.com/t/ctypes-from-sublime-text-3-python-broken-on-windows/21490/32
If sublime developers integrate that patch, it might work as well as on other platforms.

**Comment by niosus** [comment]
Yes @rchl I've seen that! And it looks really promising! Thanks you for your awesome work and help. 
But even if the sublime devs actually patch their python we will still need the latest version of sublime text for running the plugin, which is slightly suboptimal. :)

**Comment by rchl** [comment]
I'm not very familiar with how precompiled headers are used, but I thought that precompiled headers are typically created manually by developer and then compiler is made aware of them using special compilation flag. As in, developer creates a list of headers to precompile and then compiler compiles those, before compiling main code (source files).

If my understanding is right then I have some concerns about trying to use that.
 - Will it really saves a lot of time? This package just needs to compile one source files + all linked headers so it wouldn't probably speed up things for the *first* compilation of the file.
 - When using previously compiled headers, how would you know that those previously compiled headers, should be used for next source file that is to be compiled? It might be completely different source file including completely different header files.
 - Or are you just thinking of saving precompiled headers per-path? So file foo.cc would have its own cached precompiled headers and file bar.cc would have its own?
 - How would you handle invalidating precompiled headers when any of the header files changes? Would you trow away all caches or...?

**Comment by niosus** [comment]
I am still not sure IF I want to do it, let alone HOW :) 

This is needed only if we fail to make libclang method work reliably.

Basically, if I would eventually do it, I would try to reproduce the behavior of libclang, i.e. a precompiled header is generated upon file save to allow for faster building of a particular file being built. Every single file will then have its own precompiled header. It is an open question where to store them and for how long. I guess that is approximately how libclang works under the hood.

I know there is one Atom package that generates the precompiled headers upon user query, but that goes against my philosophy. I would rather do it automatically.

**Comment by rchl** [comment]
That sounds doable then.

While I believe we can make libclang work reliably, I'm more of a Windows guy and I currently I'm more interested in using clang-cl as that is compatible with the project I'm working on. So I would appreciate any speedup. :)

It would be ideal if libclang could work in clang-cl compatibility mode, but I'm not sure if that's possible.

**Comment by rchl** [comment]
I've looked at the source and there seems to be undocumented switch `--clang-driver=cl` that does the trick of running libclang in `cl` mode.

So in fact maybe it's not worth fixing this. :)

**Comment by niosus** [comment]
This flag looks neat :) could you try this out and tell me if it works? 

In case it doesn't I'm happy to either fix it for clang-cl or to receive a pull request from you

**Comment by rchl** [comment]
It does work. It makes libclang accept Windows style compile flags at least.
Before testing more I'd like to wait for llvm 4.0 release.

**Comment by niosus** [comment]
Sure! Sounds good to me.
