### ISSUE TITLE
test_vector.cpp test failing on Windows with (clang 3.9)

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#88]
`test_complete_vector()` test is disabled for Windows. When enabled, it fails for me because libclang can't find code for standard libraries:

```
DEBUG:root: adding error {'row': '10', 'file': 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\include\\\\crtdefs.h', 'col': '10', 'error': "'corecrt.h' file not found"}
```

I found out that this is because of a silly bug in clang driver that was already fixed by https://github.com/llvm-mirror/clang/commit/394ca50fa91a04fb3df27b9352b10ba23ad5d003
This fix is not yet in 3.9 so should be in 4.0.

With this fix clang automatically finds that header. We can keep this bug open to enable the test when new llvm is released.

**Comment by niosus** [comment]
Yeah, that was the reason to disable it. Actually, I think it was working well with clang 3.8. I had to explicitly disable it after some time. Before an update to Appveyor everything was passing as expected.

Keeping this bug open seems to be appropriate.

**Comment by niosus** [comment]
Ok, so clang is out. Now the only missing part is Appveyor. It uses clang 3.9. We'll need to update the tests once they start using 4.0.

**Comment by niosus** [comment]
Ok, so Appveyor started using clang 4.0 as of today, but the builds hang. Described in #230 

We should fix this once the other issue is away.

**Comment by niosus** [comment]
That issue is fixed, but clang still cannot find the headers on my machine. Can anyone else test it?
