### ISSUE TITLE
Completions don't show up in some situations

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#89]
With a code like:
```
#include <vector>
int main(int argc, char const *argv[]) {
  std::vector<int> vec;
  vec.
}
```
1. Place cursor after `vec.` and type another dot - `.`
2. Press backspace twice to delete both dots
3. Type one dot.

At 1 it's expected that no clang completions are shown.
At 3 it's expected that clang completions are shown but they are not.

This happens because when completions are empty we don't reset `async_completions_ready` to False. That results in empty completions being used on next `on_query_completions` request.
The fix is not as easy as resetting that member, as tests rely on it, even for empty completions.

I think it would be best to redesign completions handling to fix this and couple other problems.

**Comment by niosus** [comment]
This happens here too, good catch. The completions handling was done somewhere in the start, so it may be useful to rewrite it in a better way. Do you have any suggestion in mind?

**Comment by rchl** [comment]
One improvement I'm thinking of (and experimenting with in a local branch) is to track the last completion request so that we can drop all results for requests that were triggered before it. Each request would hold its completion results that would be easily accessible from `on_query_completions`.

(While at that I'm trying to make it more clear which code is run in a completion thread and trying to make tests use the same code patch (using threads) but with blocking main thread. So it is turning out to be a slightly bigger change.)

**Comment by niosus** [comment]
When I was initially experimenting with more threads I found out that libclang is intended to be used from single thread only and there is an assert for that inside of the library, so we have to be cautious not to use it from multiple threads at once.

**Comment by rchl** [comment]
Sure. I wouldn't use more threads. Just wrap existing one with some custom class and keep using existing synchronization that you've added lately.
