### ISSUE TITLE
std flag gets appended multiple times when using clang binary

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#9]
as described. After some time of usage `std=c++11` flag gets appended multiple times, e.g. 
`clang++ -cc1 -fsyntax-only -x c++ -std=c++11 -std=c++11 -std=c++11 -code-completion-at ...`

**Comment by niosus** [comment]
@simonhaenisch I will track this issue here, separately.

**Comment by simonhaenisch** [comment]
I think it has something to do with switching files, projects or directories and trying to complete new variables that fail, but I couldn't really reproduce it reliably.
