### ISSUE TITLE
Subprocess methods should be called with array of strings, not a string

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#91]
In various places of the code the strings passed to the clang binary are passed as one string. This makes it hard to specify paths in custom `clang_flags` or other preferences that are for specifying clang arguments.

For example if you want to specify path with spaces in `clang_binary` pref you have to quote the whole string. Path like `"c:\\Program Files\\LLVM\\bin\\clang-cl"` will cause error in clang due to space in the path.
Or if you specify `["-imsvcC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE"]` argument in `clang_flags` then it will trigger error in clang because all `clang_flags` arguments are converted into one string and then the space in the path will cause problems. So values like that require awkward escaping which shouldn't be needed.

But in any case, the plugin should internally handle arguments as an array of strings throughout the code when calling subprocess methods. And the preferences that are for specifying command line arguments ((`std_flag_c`, `std_flag_cpp`) should take arrays not strings . Support for strings could be kept for legacy reasons but it will complicate the code a bit.

**Comment by niosus** [comment]
Hey, sorry for the delay. I'm afraid I still do not understand fully what you mean. Can you provide an example when an array would work better then just passing a big string?

**Comment by rchl** [comment]
Basically spaces in arguments passed to clang cause problems. User specifies `clang_flags` like so in the project file:

```
"clang_flags": [
  "-imsvcC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE",
]
```
As the plugins flattens all argument into a string, clang will think that the argument ends at the first space that it finds so it will just parse it as 3 different arguments and fail.
It can be worked around by quoting the arguments like so:
`"\"-imsvcC:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE\"",`
but that shouldn't be needed.

When arguments are treated as a list of strings then python knows the boundaries of each argument and passes them onto the binary in a way that won't cause problems like that.

**Comment by niosus** [comment]
Ah, right. I handle it by having parentheses around the flags from `.clang_complete`. I think I also need to handle ones added by user.

**Comment by rchl** [comment]
Well, the proper solution would be to handle arguments as an array of strings from start to finish (from plugin preferences to the subprocess call).

Only in case where the input is initially just one string (.clang_complete file?) you might need to do some magic. But I think even in that case you shouldn't need to do anything if you pass it onto compiler as one string because those commands are supposed to just work. But maybe when you mix it with default plugin arguments then the problems arise...

I just had a brief look at what you do in the FlagsManager and it seems that you are filtering arguments to just a couple of types (-I, -D, and some other). Why not just pass everywhere from the .clang_complete command? If the commands were created for the same compiler then passing all should work just fine. But that might be a separate discussion.

Also about this:
```
separate_includes (bool): if True "-I/blah" turns to "-I '/blah'"
```
I think the reason you have to do it is exactly because you are just passing a string. If you would parse those into an array of arguments then original format `-I/blah` should work just fine.

**Comment by niosus** [comment]
yes, totally. What you say is absolutely correct. I never though of passing an array, that is a really good point :) This is what happens when I don't know the API well enough.

**Comment by niosus** [comment]
Ok, I have removed the need to separate includes. The code is now cleaner and better. Thanks for the hint. Didn't know I could pass a list :) This change will be live later today.

**Comment by niosus** [comment]
As for:
> Why not just pass everywhere from the .clang_complete command? If the commands were created for the same compiler then passing all should work just fine. But that might be a separate discussion.

Indeed, it is a separate discussion and I think it has smth to do with #104 
Let's move this discussion there or to a new issue if needed.

**Comment by niosus** [comment]
Oh damn, It does not work on Windows as expected... I have reverted back for now as there were other changes I needed to push.

**Comment by niosus** [comment]
See build: https://ci.appveyor.com/project/niosus/easyclangcomplete/build/1.0.352

**Comment by rchl** [comment]
I can have a look if you don't have easy way to check that yourself.

**Comment by niosus** [comment]
I think it will be fine, just yesterday night didn't have the will power to fire up windows to find what the heck is happening. If I fail, I will point to the branch that has the changes here.
