### ISSUE TITLE
It stop working on macOS Sierra

### ISSUE THREAD

**Issue by david9991** [niosus/EasyClangComplete#92]
I have upgraded both Sublime Text 3 to build 3126 and EasyClangComplete to 1.4.0, auto completion stop working without any compile errors. Only these log generated while inputing and deleting the '.' (dot) following a object. e.g.

> std::vector<std::string> a;
> a.

While I input and delete the 'dot' behind a, nothing but these logs was outputted. What debug message should output while it doing the auto complete?

> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 29
> DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 29
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.plugin.error_vis: no error regions for row: 28
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 29
> DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 29
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.plugin.error_vis: no error regions for row: 28
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 29
> DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 29
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.plugin.error_vis: no error regions for row: 28
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 29
> DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 29
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.plugin.error_vis: no error regions for row: 28
> DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++11`
> DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 29
> DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 29

**Comment by david9991** [comment]
And when I switch forces to the source code window, this message displayed, does it mean there is another completer running conflict to the EasyClangComplete or EasyClangComplete was initialed and no need to init again?

> DEBUG:EasyClangComplete.plugin.completion.base_complete: view 67, already has a completer

**Comment by niosus** [comment]
Try to restart sublime text and if the error persist please copy the full log from the moment you started sublime text to the moment when you see the behavior. 

The things you say in second comment is not an error and is ok.

**Comment by david9991** [comment]
[log.txt](https://github.com/niosus/EasyClangComplete/files/523290/log.txt)

**Comment by david9991** [comment]
More investigation, on_query_completions() was not called if I type '.' that was set in settings' Trigger option. So I tried to select the Show Completion in Menu manually, the completion window appears correctly. I found the only place you check the Trigger option is in get_position_status() that will be called by on_query_completions() that won't be called automatically in my here, except I set auto_complete_selector and auto_complete_triggers in project setting file. Something wrong I did?

**Comment by david9991** [comment]
Copy Preferences.sublime-settings files that in package to User settings folder works for me.

**Comment by niosus** [comment]
I see. I do some magic with the triggers, so probably something is wrong with that. I am still at the conference in Korea, but I will probably be able to have a look next weekend. Sorry for the delay :)

**Comment by david9991** [comment]
Duplicated with #98

**Comment by niosus** [comment]
So, @david9991 is this bug the same as #98? Can I close either of them?

**Comment by david9991** [comment]
Yes, you can close this one.
