### ISSUE TITLE
libclang crashes with clang version 3.7.x

### ISSUE THREAD

**Issue by tastytea** [niosus/EasyClangComplete#95]
Every time I save or type a trigger, the  plugin_host exits unexpectedly and I get the terminal output:
```
libclang: crash detected in code completion
exec: No such file or directory
```

Console output
```
startup, version: 3126 linux x64 channel: stable
[…]
reloading plugin EasyClangComplete.EasyClangComplete
[…]
INFO:EasyClangComplete.EasyClangComplete: init completer based on libclang
INFO:EasyClangComplete.plugin.completion.base_complete: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.completion.base_complete: Found clang version: 3.7
INFO:EasyClangComplete.clang.utils: we are on 'Linux'
INFO:EasyClangComplete.clang.utils: searching for: 'libclang.so'
INFO:EasyClangComplete.clang.utils: libclang search output = '/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../lib64/libclang.so'
INFO:EasyClangComplete.clang.utils: found libclang dir: '/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../lib64'
INFO:EasyClangComplete.clang.utils: found library file: 'libclang.so'
[…]
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
Unable to find cancel_build command: exec
```

### Workarounds
* `exec` is a shell built-in command here, so I symlinked exec to /bin/bash. Now the plugin_host doesn't crash anymore, but the libclang error persists.
* If I set `"use_libclang"` to `false`, it works fine.

**Comment by niosus** [comment]
This seems system specific. Please provide details about your system.

**Comment by tastytea** [comment]
sublime: 3126
OS: Linux 4.4.21, Gentoo

`clang --version`:
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-pc-linux-gnu
Thread model: posix

Do you need more details?

**Comment by niosus** [comment]
This looks like an issue of having a wrong `libclang`. Are you sure you have only one on your system and it corresponds to the clang version you have installed? If yes, can you try clang version 3.8 - there I am sure everything works. 

Also, could you enable `verbose: true` in the settings of the plugin and upload full log file here? Maybe there is something useful there.

**Comment by tastytea** [comment]
I am sure I have only one libclang and it is the right one.
`/usr/lib64/libclang.so` is a symlink to `libclang.so.3.7`.
I will try with clang-3.8 later.
Here is the verbose log: [verbose_console_output.txt](https://github.com/niosus/EasyClangComplete/files/545910/verbose_console_output.txt)

**Comment by tastytea** [comment]
Works with clang 3.8.1.

**Comment by niosus** [comment]
Ok, I will close this issue for now.
