### ISSUE TITLE
CMake "project" detection should be case insensitive

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#96]
When this plugin tries to detect a `project` command inside a CMakeLists.txt, the search is case-sensitive, while CMake's syntax isn't. It is perfectly valid to write `Project(foo)` or `PROJECT(foo)` (even if the latter is ugly), but right now `EasyClangComplete` doesn't detect it.

**Comment by niosus** [comment]
You are totally right. I have fixed it in the local build already and will push it over the weekend probably.
